// Generated by scripts/emit-contract-tests.mjs from packages/catalog/apis.json and the thirteen packages/catalog/apis/*.json
// engine files, with every engine module bound and probed as this file was generated. Do not edit by hand —
// run `npm run contract-tests`. The build fails if this file and its sources disagree, so an edit here is
// lost rather than merely wrong.
//
// What is held, per engine:
//
//   1. The registered table. runtime.bound() must equal the keys baked below exactly — every route the
//      engine registers, and no other — and every registered key must be one the catalog marks built. A
//      built route the engine does not register is not a failure here: the thirteen engines are built one
//      route at a time, and some built routes are served outside packages/engines for now (apps/api,
//      apps/passport and apps/assistant-api). The registered/absent partition is what is pinned, exactly.
//   2. Withdrawn and proposed routes are registered nowhere. A call to a withdrawn route answers nothing:
//      404 no-route, from the runtime rather than an engine — the contract's "410 route-withdrawn" is the
//      binder refusing to register one, not an answer to a request, and nothing here pretends a caller gets
//      a 410. A call to a proposed route is answered by the development mock, which is what a route no
//      engine has built gets; no engine answers it.
//   3. Refusal wiring, on live routes: a caller the route does not name, a purpose it does not serve, a
//      required field not sent, a field sent in the wrong shape and a money or dispatch write without its
//      idempotency key are each called and answered with the catalog's status and sentence. Every
//      expectation below was proven against the runtime while this file was generated.
//
// This file sits beside the engines because it binds all of them. Nothing here is a real service.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { MEMORY, createClock, createRuntime, type EngineModule, type RouteKey, type Runtime } from './runtime/index.ts';
import { engine as access } from './access/engine.ts';
import { engine as care } from './care/engine.ts';
import { engine as clinical } from './clinical/engine.ts';
import { engine as core } from './core/engine.ts';
import { engine as devices } from './devices/engine.ts';
import { engine as medicines } from './medicines/engine.ts';
import { engine as money } from './money/engine.ts';
import { engine as movement } from './movement/engine.ts';
import { engine as record } from './record/engine.ts';
import { engine as safety } from './safety/engine.ts';
import { engine as trust } from './trust/engine.ts';

const MORNING = '2026-09-15T09:00:00+02:00';
const NO_ROUTE_MESSAGE = 'No route in the contract answers that method and path.';
const ENGINES: Record<string, EngineModule> = { access, care, clinical, core, devices, medicines, money, movement, record, safety, trust };

const REGISTERED: Record<string, string[]> = {
 access: [
  'GET /v1/access/bookings/{bookingRef}@1',
  'GET /v1/access/households@1',
  'GET /v1/access/settings@2',
  'GET /v1/access/sponsors@1',
  'GET /v1/access/visit-threads/{bookingRef}@1',
  'POST /v1/access/bill-splits/{splitRef}/accept@1',
  'POST /v1/access/bill-splits@2',
  'POST /v1/access/bookings/{bookingRef}/cancel@1',
  'POST /v1/access/bookings@2',
  'POST /v1/access/conversations/{conversationRef}/handover@2',
  'POST /v1/access/household-memberships@1',
  'POST /v1/access/households@1',
  'POST /v1/access/setting-changes@1',
  'POST /v1/access/setting-reviews@2',
  'POST /v1/access/sponsors/{sponsorshipRef}/answer@1',
  'POST /v1/access/sponsors@2',
  'POST /v1/access/visit-threads/{bookingRef}/messages@1',
 ],
 care: [
  'GET /v1/care/circuits@1',
  'GET /v1/care/locum-shifts@1',
  'GET /v1/care/services@1',
  'GET /v1/care/settings@2',
  'GET /v1/care/shifts@1',
  'POST /v1/care/offers/{offerRef}/accept@1',
  'POST /v1/care/offers/{offerRef}/decline@1',
  'POST /v1/care/offers@2',
  'POST /v1/care/setting-changes@1',
  'POST /v1/care/setting-reviews@2',
  'POST /v1/care/sync-batches@2',
  'POST /v1/care/visits/{appointmentRef}/capture@1',
  'POST /v1/care/visits/{appointmentRef}/checklist@1',
  'POST /v1/care/visits/{appointmentRef}/complete@2',
  'POST /v1/care/visits/{appointmentRef}/handover@2',
  'POST /v1/care/visits/{appointmentRef}/start@1',
 ],
 clinical: [
  'GET /v1/clinical/review-confirmers@2',
  'GET /v1/clinical/reviews@2',
  'GET /v1/clinical/settings@2',
  'POST /v1/clinical/consultations@2',
  'POST /v1/clinical/guidance@1',
  'POST /v1/clinical/proms@2',
  'POST /v1/clinical/results/{resultRef}/acknowledge@1',
  'POST /v1/clinical/reviews/{reviewRef}/sign@2',
  'POST /v1/clinical/setting-changes@1',
  'POST /v1/clinical/setting-reviews@2',
  'POST /v1/clinical/triage@3',
 ],
 core: [
  'GET /v1/core/audit-exports@1',
  'GET /v1/core/loops@2',
  'GET /v1/core/protocols/{protocolVersionId}@1',
  'GET /v1/core/settings@1',
  'POST /v1/core/alerts@2',
  'POST /v1/core/events@1',
  'POST /v1/core/loops/{loopRef}/acknowledge@3',
  'POST /v1/core/loops/{loopRef}/close@2',
  'POST /v1/core/loops/{loopRef}/escalate@3',
  'POST /v1/core/loops@1',
  'POST /v1/core/permission-checks@1',
  'POST /v1/core/protocols/{protocolId}/ratify@1',
  'POST /v1/core/setting-changes@1',
 ],
 devices: [
  'GET /v1/devices/registry/{deviceRef}/health@2',
  'GET /v1/devices/settings@1',
  'POST /v1/devices/kits/{kitRef}/loss@2',
  'POST /v1/devices/kits/{kitRef}/return@2',
  'POST /v1/devices/kits@2',
  'POST /v1/devices/readings/{readingRef}/observation@1',
  'POST /v1/devices/readings@2',
  'POST /v1/devices/registry/{deviceRef}/recall@2',
  'POST /v1/devices/registry@2',
  'POST /v1/devices/setting-changes@2',
  'POST /v1/devices/wearable-links/{linkRef}/withdraw@1',
  'POST /v1/devices/wearable-links@2',
 ],
 medicines: [
  'GET /v1/medicines/formulary@2',
  'GET /v1/medicines/orders@2',
  'GET /v1/medicines/settings@2',
  'POST /v1/medicines/collection-authorisations@1',
  'POST /v1/medicines/collections/{collectionRef}/handover@2',
  'POST /v1/medicines/collections@2',
  'POST /v1/medicines/interaction-checks@2',
  'POST /v1/medicines/lab-orders/{labOrderRef}/close@1',
  'POST /v1/medicines/lab-orders@2',
  'POST /v1/medicines/lab-results@1',
  'POST /v1/medicines/prescriptions/{prescriptionRef}/dispense@2',
  'POST /v1/medicines/prescriptions/{prescriptionRef}/verify@2',
  'POST /v1/medicines/prescriptions@2',
  'POST /v1/medicines/setting-changes@1',
  'POST /v1/medicines/setting-reviews@2',
 ],
 money: [
  'GET /v1/money/claims@1',
  'GET /v1/money/group-memberships@1',
  'GET /v1/money/groups/{groupRef}@1',
  'GET /v1/money/held-cash-payments@1',
  'GET /v1/money/payouts@1',
  'GET /v1/money/plan-subscriptions/{subscriptionRef}@1',
  'GET /v1/money/settings@1',
  'POST /v1/money/claims/{claimRef}/consent@1',
  'POST /v1/money/claims/{claimRef}/submit@1',
  'POST /v1/money/claims@3',
  'POST /v1/money/gifts@1',
  'POST /v1/money/group-memberships/{membershipRef}/accept@1',
  'POST /v1/money/group-memberships/{membershipRef}/leave@1',
  'POST /v1/money/group-memberships@1',
  'POST /v1/money/group-payments@1',
  'POST /v1/money/groups@2',
  'POST /v1/money/market-orders@1',
  'POST /v1/money/payments/{paymentRef}/cash-code@2',
  'POST /v1/money/payments/{paymentRef}/release@2',
  'POST /v1/money/payments@1',
  'POST /v1/money/payments@2',
  'POST /v1/money/plan-subscriptions/{subscriptionRef}/accept@1',
  'POST /v1/money/plan-subscriptions@1',
  'POST /v1/money/setting-changes@1',
  'POST /v1/money/voucher-redemptions@1',
  'POST /v1/money/vouchers@2',
 ],
 movement: [
  'GET /v1/movement/admissions/{admissionRef}@2',
  'GET /v1/movement/facilities@2',
  'GET /v1/movement/settings@1',
  'GET /v1/movement/trips/{tripRef}/position@1',
  'POST /v1/movement/admissions/{admissionRef}/arrival@2',
  'POST /v1/movement/admissions/{admissionRef}/decision@2',
  'POST /v1/movement/admissions/{admissionRef}/handover@2',
  'POST /v1/movement/admissions/{admissionRef}/more-information@1',
  'POST /v1/movement/admissions/{admissionRef}/packet@2',
  'POST /v1/movement/admissions@2',
  'POST /v1/movement/ems-requests@1',
  'POST /v1/movement/responder-heartbeats@2',
  'POST /v1/movement/setting-changes@1',
  'POST /v1/movement/trips/{tripRef}/accept@2',
  'POST /v1/movement/trips/{tripRef}/decline@1',
  'POST /v1/movement/trips/{tripRef}/handover@2',
  'POST /v1/movement/trips@2',
 ],
 record: [
  'GET /v1/record/settings@1',
  'POST /v1/record/setting-changes@1',
 ],
 safety: [
  'GET /v1/safety/checkins@1',
  'GET /v1/safety/desk-queue@1',
  'GET /v1/safety/next-of-kin@1',
  'GET /v1/safety/panics/{panicRef}/position@1',
  'GET /v1/safety/safeguarding-reports@1',
  'GET /v1/safety/sentinel-baselines@1',
  'GET /v1/safety/settings@4',
  'GET /v1/safety/sos/{sosRef}/area@1',
  'GET /v1/safety/sos@1',
  'POST /v1/safety/checkins/{checkinRef}/close@2',
  'POST /v1/safety/checkins/{checkinRef}/extend@2',
  'POST /v1/safety/checkins/{checkinRef}/safe@1',
  'POST /v1/safety/next-of-kin/{nominationRef}/alert@2',
  'POST /v1/safety/next-of-kin/{nominationRef}/withdraw@1',
  'POST /v1/safety/next-of-kin@2',
  'POST /v1/safety/overdue-checkins/{checkinRef}/close@1',
  'POST /v1/safety/overdue-checkins/{checkinRef}/pick-up@1',
  'POST /v1/safety/panics/{panicRef}/pick-up@1',
  'POST /v1/safety/panics/{panicRef}/resolve@1',
  'POST /v1/safety/panics@1',
  'POST /v1/safety/safeguarding-reports@2',
  'POST /v1/safety/sentinel-deviations@2',
  'POST /v1/safety/setting-changes@2',
  'POST /v1/safety/setting-reviews@2',
  'POST /v1/safety/sos/{sosRef}/stand-down@1',
  'POST /v1/safety/sos@2',
 ],
 trust: [
  'GET /v1/trust/complaint-notices@1',
  'GET /v1/trust/complaints/{complaintRef}@1',
  'GET /v1/trust/complaints@1',
  'GET /v1/trust/parties/{partyId}/badge@1',
  'GET /v1/trust/parties/{partyId}/gates@1',
  'GET /v1/trust/settings@1',
  'GET /v1/trust/shift-starts@1',
  'POST /v1/trust/complaints/{complaintRef}/decide@1',
  'POST /v1/trust/complaints@2',
  'POST /v1/trust/door-codes@1',
  'POST /v1/trust/door-verifications/{appointmentRef}/answer@1',
  'POST /v1/trust/door-verifications@2',
  'POST /v1/trust/setting-changes@2',
  'POST /v1/trust/shift-starts@2',
 ],
};

const BUILT: Record<string, string[]> = {
 access: [
  'GET /v1/access/access-log-integrity@1',
  'GET /v1/access/access-log@1',
  'GET /v1/access/account-data@1',
  'GET /v1/access/audit-chain@1',
  'GET /v1/access/bookings/{bookingRef}@1',
  'GET /v1/access/consent-contract@1',
  'GET /v1/access/consents@1',
  'GET /v1/access/correction-requests@1',
  'GET /v1/access/doors@1',
  'GET /v1/access/health@1',
  'GET /v1/access/households@1',
  'GET /v1/access/rate-limits@1',
  'GET /v1/access/second-factors@1',
  'GET /v1/access/sessions@1',
  'GET /v1/access/settings@2',
  'GET /v1/access/sponsors@1',
  'GET /v1/access/subject-requests@1',
  'GET /v1/access/verification-status@1',
  'GET /v1/access/visit-threads/{bookingRef}@1',
  'POST /v1/access/account-exports@1',
  'POST /v1/access/account-names@1',
  'POST /v1/access/bill-splits/{splitRef}/accept@1',
  'POST /v1/access/bill-splits@2',
  'POST /v1/access/bookings/{bookingRef}/cancel@1',
  'POST /v1/access/bookings@2',
  'POST /v1/access/consents/{purposeId}/withdraw@1',
  'POST /v1/access/consents@1',
  'POST /v1/access/conversations/{conversationRef}/handover@2',
  'POST /v1/access/correction-requests@1',
  'POST /v1/access/erasure-cancellations@1',
  'POST /v1/access/erasure-requests@1',
  'POST /v1/access/household-memberships@1',
  'POST /v1/access/households@1',
  'POST /v1/access/second-factor-confirmations@1',
  'POST /v1/access/second-factor-removals@1',
  'POST /v1/access/second-factors@1',
  'POST /v1/access/setting-changes@1',
  'POST /v1/access/setting-reviews@2',
  'POST /v1/access/sign-ins/{challengeId}/verify@1',
  'POST /v1/access/sign-ins/{challengeToken}/second-factor@1',
  'POST /v1/access/sign-ins@1',
  'POST /v1/access/sign-outs@1',
  'POST /v1/access/sponsors/{sponsorshipRef}/answer@1',
  'POST /v1/access/sponsors@2',
  'POST /v1/access/subject-requests/{requestId}/respond@1',
  'POST /v1/access/visit-threads/{bookingRef}/messages@1',
  'POST /v1/access/witness-statements@1',
 ],
 assistant: [
  'GET /health@1',
  'GET /v1/status@1',
  'POST /turn@1',
  'POST /v1/handover/prepare@3',
  'POST /v1/handover/submit@3',
  'POST /v1/knowledge/search@2',
  'POST /v1/listen@3',
  'POST /v1/speak@3',
  'POST /v1/triage/answer@3',
  'POST /v1/triage/start@3',
  'POST /v1/turn@1',
  'POST /v1/vitals@3',
 ],
 care: [
  'GET /v1/care/circuits@1',
  'GET /v1/care/locum-shifts@1',
  'GET /v1/care/services@1',
  'GET /v1/care/settings@2',
  'GET /v1/care/shifts@1',
  'POST /v1/care/offers/{offerRef}/accept@1',
  'POST /v1/care/offers/{offerRef}/decline@1',
  'POST /v1/care/offers@2',
  'POST /v1/care/setting-changes@1',
  'POST /v1/care/setting-reviews@2',
  'POST /v1/care/sync-batches@2',
  'POST /v1/care/visits/{appointmentRef}/capture@1',
  'POST /v1/care/visits/{appointmentRef}/checklist@1',
  'POST /v1/care/visits/{appointmentRef}/complete@2',
  'POST /v1/care/visits/{appointmentRef}/handover@2',
  'POST /v1/care/visits/{appointmentRef}/start@1',
 ],
 clinical: [
  'GET /v1/clinical/review-confirmers@2',
  'GET /v1/clinical/reviews@2',
  'GET /v1/clinical/settings@2',
  'POST /v1/clinical/consultations@2',
  'POST /v1/clinical/guidance@1',
  'POST /v1/clinical/proms@2',
  'POST /v1/clinical/results/{resultRef}/acknowledge@1',
  'POST /v1/clinical/reviews/{reviewRef}/sign@2',
  'POST /v1/clinical/setting-changes@1',
  'POST /v1/clinical/setting-reviews@2',
  'POST /v1/clinical/triage@3',
 ],
 core: [
  'GET /v1/core/audit-exports@1',
  'GET /v1/core/loops@2',
  'GET /v1/core/protocols/{protocolVersionId}@1',
  'GET /v1/core/settings@1',
  'POST /v1/core/alerts@2',
  'POST /v1/core/events@1',
  'POST /v1/core/loops/{loopRef}/acknowledge@3',
  'POST /v1/core/loops/{loopRef}/close@2',
  'POST /v1/core/loops/{loopRef}/escalate@3',
  'POST /v1/core/loops@1',
  'POST /v1/core/permission-checks@1',
  'POST /v1/core/protocols/{protocolId}/ratify@1',
  'POST /v1/core/setting-changes@1',
 ],
 devices: [
  'GET /v1/devices/registry/{deviceRef}/health@2',
  'GET /v1/devices/settings@1',
  'POST /v1/devices/kits/{kitRef}/loss@2',
  'POST /v1/devices/kits/{kitRef}/return@2',
  'POST /v1/devices/kits@2',
  'POST /v1/devices/readings/{readingRef}/observation@1',
  'POST /v1/devices/readings@2',
  'POST /v1/devices/registry/{deviceRef}/recall@2',
  'POST /v1/devices/registry@2',
  'POST /v1/devices/setting-changes@2',
  'POST /v1/devices/wearable-links/{linkRef}/withdraw@1',
  'POST /v1/devices/wearable-links@2',
 ],
 medicines: [
  'GET /v1/medicines/formulary@2',
  'GET /v1/medicines/orders@2',
  'GET /v1/medicines/settings@2',
  'POST /v1/medicines/collection-authorisations@1',
  'POST /v1/medicines/collections/{collectionRef}/handover@2',
  'POST /v1/medicines/collections@2',
  'POST /v1/medicines/interaction-checks@2',
  'POST /v1/medicines/lab-orders/{labOrderRef}/close@1',
  'POST /v1/medicines/lab-orders@2',
  'POST /v1/medicines/lab-results@1',
  'POST /v1/medicines/prescriptions/{prescriptionRef}/dispense@2',
  'POST /v1/medicines/prescriptions/{prescriptionRef}/verify@2',
  'POST /v1/medicines/prescriptions@2',
  'POST /v1/medicines/setting-changes@1',
  'POST /v1/medicines/setting-reviews@2',
 ],
 money: [
  'GET /v1/money/claims@1',
  'GET /v1/money/group-memberships@1',
  'GET /v1/money/groups/{groupRef}@1',
  'GET /v1/money/held-cash-payments@1',
  'GET /v1/money/payouts@1',
  'GET /v1/money/plan-subscriptions/{subscriptionRef}@1',
  'GET /v1/money/settings@1',
  'POST /v1/money/claims/{claimRef}/consent@1',
  'POST /v1/money/claims/{claimRef}/submit@1',
  'POST /v1/money/claims@3',
  'POST /v1/money/gifts@1',
  'POST /v1/money/group-memberships/{membershipRef}/accept@1',
  'POST /v1/money/group-memberships/{membershipRef}/leave@1',
  'POST /v1/money/group-memberships@1',
  'POST /v1/money/group-payments@1',
  'POST /v1/money/groups@2',
  'POST /v1/money/market-orders@1',
  'POST /v1/money/payments/{paymentRef}/cash-code@2',
  'POST /v1/money/payments/{paymentRef}/release@2',
  'POST /v1/money/payments@1',
  'POST /v1/money/payments@2',
  'POST /v1/money/plan-subscriptions/{subscriptionRef}/accept@1',
  'POST /v1/money/plan-subscriptions@1',
  'POST /v1/money/setting-changes@1',
  'POST /v1/money/voucher-redemptions@1',
  'POST /v1/money/vouchers@2',
 ],
 movement: [
  'GET /v1/movement/admissions/{admissionRef}@2',
  'GET /v1/movement/facilities@2',
  'GET /v1/movement/settings@1',
  'GET /v1/movement/trips/{tripRef}/position@1',
  'POST /v1/movement/admissions/{admissionRef}/arrival@2',
  'POST /v1/movement/admissions/{admissionRef}/decision@2',
  'POST /v1/movement/admissions/{admissionRef}/handover@2',
  'POST /v1/movement/admissions/{admissionRef}/more-information@1',
  'POST /v1/movement/admissions/{admissionRef}/packet@2',
  'POST /v1/movement/admissions@2',
  'POST /v1/movement/ems-requests@1',
  'POST /v1/movement/responder-heartbeats@2',
  'POST /v1/movement/setting-changes@1',
  'POST /v1/movement/trips/{tripRef}/accept@2',
  'POST /v1/movement/trips/{tripRef}/decline@1',
  'POST /v1/movement/trips/{tripRef}/handover@2',
  'POST /v1/movement/trips@2',
 ],
 record: [
  'GET /audit/mine@1',
  'GET /fhir/{resourceType}/{id}@1',
  'GET /fhir/{resourceType}@1',
  'GET /summary/emergency@1',
  'GET /v1/record/encounter-statuses/{encounterRef}@1',
  'GET /v1/record/hl7v2-quarantine@1',
  'GET /v1/record/settings@1',
  'POST /breakglass@1',
  'POST /consent/grant@1',
  'POST /consent/revoke@1',
  'POST /export@2',
  'POST /fhir/{resourceType}@1',
  'POST /hl7v2/inbound@1',
  'POST /share/link@2',
  'POST /v1/record/consent-checks@1',
  'POST /v1/record/dev-subjects@1',
  'POST /v1/record/patient-identifiers@1',
  'POST /v1/record/session-ends@1',
  'POST /v1/record/setting-changes@1',
  'POST /v1/record/share-link-opens@1',
  'POST /v1/record/share-link-revocations@1',
 ],
 safety: [
  'GET /v1/safety/checkins@1',
  'GET /v1/safety/desk-queue@1',
  'GET /v1/safety/incident-kinds@1',
  'GET /v1/safety/incidents@1',
  'GET /v1/safety/next-of-kin@1',
  'GET /v1/safety/panics/{panicRef}/position@1',
  'GET /v1/safety/safeguarding-reports@1',
  'GET /v1/safety/sentinel-baselines@1',
  'GET /v1/safety/settings@4',
  'GET /v1/safety/sos/{sosRef}/area@1',
  'GET /v1/safety/sos@1',
  'POST /v1/safety/checkins/{checkinRef}/close@2',
  'POST /v1/safety/checkins/{checkinRef}/extend@2',
  'POST /v1/safety/checkins/{checkinRef}/safe@1',
  'POST /v1/safety/incidents/{incidentId}/close@1',
  'POST /v1/safety/incidents/{incidentId}/contain@1',
  'POST /v1/safety/incidents/{incidentId}/notified@1',
  'POST /v1/safety/next-of-kin/{nominationRef}/alert@2',
  'POST /v1/safety/next-of-kin/{nominationRef}/withdraw@1',
  'POST /v1/safety/next-of-kin@2',
  'POST /v1/safety/overdue-checkins/{checkinRef}/close@1',
  'POST /v1/safety/overdue-checkins/{checkinRef}/pick-up@1',
  'POST /v1/safety/panics/{panicRef}/pick-up@1',
  'POST /v1/safety/panics/{panicRef}/resolve@1',
  'POST /v1/safety/panics@1',
  'POST /v1/safety/safeguarding-reports@2',
  'POST /v1/safety/sentinel-deviations@2',
  'POST /v1/safety/setting-changes@2',
  'POST /v1/safety/setting-reviews@2',
  'POST /v1/safety/sos/{sosRef}/stand-down@1',
  'POST /v1/safety/sos@2',
 ],
 trust: [
  'GET /v1/trust/complaint-notices@1',
  'GET /v1/trust/complaints/{complaintRef}@1',
  'GET /v1/trust/complaints@1',
  'GET /v1/trust/parties/{id}@1',
  'GET /v1/trust/parties/{partyId}/badge@1',
  'GET /v1/trust/parties/{partyId}/gates@1',
  'GET /v1/trust/settings@1',
  'GET /v1/trust/shift-starts@1',
  'GET /v1/trust/standing@1',
  'POST /v1/trust/complaints/{complaintRef}/decide@1',
  'POST /v1/trust/complaints@2',
  'POST /v1/trust/door-codes@1',
  'POST /v1/trust/door-verifications/{appointmentRef}/answer@1',
  'POST /v1/trust/door-verifications@2',
  'POST /v1/trust/evidence/{evidenceId}/decide@1',
  'POST /v1/trust/evidence/{evidenceId}/open@1',
  'POST /v1/trust/evidence/{evidenceId}/second@1',
  'POST /v1/trust/evidence@1',
  'POST /v1/trust/identity-callbacks@1',
  'POST /v1/trust/parties/{partyId}/restore@1',
  'POST /v1/trust/parties/{partyId}/suspend@1',
  'POST /v1/trust/parties@1',
  'POST /v1/trust/setting-changes@2',
  'POST /v1/trust/shift-starts@2',
 ],
};

const WITHDRAWN: Record<string, string[]> = {
 access: [
  'GET /v1/access/settings@1',
  'POST /v1/access/bill-splits@1',
  'POST /v1/access/bookings@1',
  'POST /v1/access/conversations/{conversationRef}/handover@1',
  'POST /v1/access/setting-reviews@1',
  'POST /v1/access/sponsors@1',
 ],
 assistant: [
  'POST /v1/handover/prepare@1',
  'POST /v1/handover/prepare@2',
  'POST /v1/handover/submit@1',
  'POST /v1/handover/submit@2',
  'POST /v1/knowledge/search@1',
  'POST /v1/listen@1',
  'POST /v1/listen@2',
  'POST /v1/speak@1',
  'POST /v1/speak@2',
  'POST /v1/triage/answer@1',
  'POST /v1/triage/answer@2',
  'POST /v1/triage/start@1',
  'POST /v1/triage/start@2',
  'POST /v1/vitals@1',
  'POST /v1/vitals@2',
 ],
 care: [
  'GET /v1/care/settings@1',
  'POST /v1/care/offers@1',
  'POST /v1/care/setting-reviews@1',
  'POST /v1/care/sync-batches@1',
  'POST /v1/care/visits/{appointmentRef}/complete@1',
  'POST /v1/care/visits/{appointmentRef}/handover@1',
 ],
 clinical: [
  'GET /v1/clinical/review-confirmers@1',
  'GET /v1/clinical/reviews@1',
  'GET /v1/clinical/settings@1',
  'POST /v1/clinical/consultations@1',
  'POST /v1/clinical/proms@1',
  'POST /v1/clinical/reviews/{reviewRef}/sign@1',
  'POST /v1/clinical/setting-reviews@1',
  'POST /v1/clinical/triage@1',
  'POST /v1/clinical/triage@2',
 ],
 core: [
  'GET /v1/core/loops@1',
  'POST /v1/core/alerts@1',
  'POST /v1/core/loops/{loopRef}/acknowledge@1',
  'POST /v1/core/loops/{loopRef}/acknowledge@2',
  'POST /v1/core/loops/{loopRef}/close@1',
  'POST /v1/core/loops/{loopRef}/escalate@1',
  'POST /v1/core/loops/{loopRef}/escalate@2',
 ],
 devices: [
  'GET /v1/devices/registry/{deviceRef}/health@1',
  'POST /v1/devices/kits/{kitRef}/loss@1',
  'POST /v1/devices/kits/{kitRef}/return@1',
  'POST /v1/devices/kits@1',
  'POST /v1/devices/readings@1',
  'POST /v1/devices/registry/{deviceRef}/recall@1',
  'POST /v1/devices/registry@1',
  'POST /v1/devices/setting-changes@1',
  'POST /v1/devices/wearable-links@1',
 ],
 medicines: [
  'GET /v1/medicines/formulary@1',
  'GET /v1/medicines/orders@1',
  'GET /v1/medicines/settings@1',
  'POST /v1/medicines/collections/{collectionRef}/handover@1',
  'POST /v1/medicines/collections@1',
  'POST /v1/medicines/interaction-checks@1',
  'POST /v1/medicines/lab-orders@1',
  'POST /v1/medicines/prescriptions/{prescriptionRef}/dispense@1',
  'POST /v1/medicines/prescriptions/{prescriptionRef}/verify@1',
  'POST /v1/medicines/prescriptions@1',
  'POST /v1/medicines/setting-reviews@1',
 ],
 money: [
  'POST /v1/money/claims@1',
  'POST /v1/money/claims@2',
  'POST /v1/money/groups@1',
  'POST /v1/money/payments/{paymentRef}/cash-code@1',
  'POST /v1/money/payments/{paymentRef}/release@1',
  'POST /v1/money/vouchers@1',
 ],
 movement: [
  'GET /v1/movement/admissions/{admissionRef}@1',
  'GET /v1/movement/facilities@1',
  'POST /v1/movement/admissions/{admissionRef}/arrival@1',
  'POST /v1/movement/admissions/{admissionRef}/decision@1',
  'POST /v1/movement/admissions/{admissionRef}/handover@1',
  'POST /v1/movement/admissions/{admissionRef}/packet@1',
  'POST /v1/movement/admissions@1',
  'POST /v1/movement/responder-heartbeats@1',
  'POST /v1/movement/trips/{tripRef}/accept@1',
  'POST /v1/movement/trips/{tripRef}/handover@1',
  'POST /v1/movement/trips@1',
 ],
 record: [
  'POST /export@1',
  'POST /share/link@1',
 ],
 safety: [
  'GET /v1/safety/settings@1',
  'GET /v1/safety/settings@2',
  'GET /v1/safety/settings@3',
  'POST /v1/safety/checkins/{checkinRef}/close@1',
  'POST /v1/safety/checkins/{checkinRef}/extend@1',
  'POST /v1/safety/checkins@1',
  'POST /v1/safety/incidents@1',
  'POST /v1/safety/incidents@2',
  'POST /v1/safety/next-of-kin/{nominationRef}/alert@1',
  'POST /v1/safety/next-of-kin@1',
  'POST /v1/safety/safeguarding-reports@1',
  'POST /v1/safety/sentinel-deviations@1',
  'POST /v1/safety/setting-changes@1',
  'POST /v1/safety/setting-reviews@1',
  'POST /v1/safety/sos@1',
 ],
 trust: [
  'POST /v1/trust/complaints@1',
  'POST /v1/trust/door-verifications@1',
  'POST /v1/trust/setting-changes@1',
  'POST /v1/trust/shift-starts@1',
 ],
};

const PROPOSED: Record<string, string[]> = {
 access: [
  'POST /v1/access/conversations/{conversationRef}/messages@1',
  'POST /v1/access/tools/{tool}@1',
 ],
 money: [
  'POST /v1/money/wallets@1',
 ],
 safety: [
  'POST /v1/safety/incidents@3',
 ],
};

const PROBES: { engine: string; key: string; role: string; purpose: string; fields: Record<string, unknown>; expect: { status: number; error: string; message: string } }[] = [
 { engine: 'access', key: 'GET /v1/access/bookings/{bookingRef}@1', role: 'nobody-synthetic-0', purpose: 'subject-access', fields: {}, expect: { status: 403, error: 'caller-not-allowed', message: 'This route does not take calls from your role.' } },
 { engine: 'access', key: 'GET /v1/access/bookings/{bookingRef}@1', role: 'patient', purpose: 'purpose-not-served-synthetic', fields: {}, expect: { status: 403, error: 'purpose-not-allowed', message: 'This route does not serve the purpose you gave.' } },
 { engine: 'access', key: 'POST /v1/access/bookings/{bookingRef}/cancel@1', role: 'patient', purpose: 'dispatch', fields: {}, expect: { status: 400, error: 'idempotency-key-required', message: 'A money or dispatch write needs an idempotency key.' } },
 { engine: 'access', key: 'GET /v1/access/bookings/{bookingRef}@1', role: 'patient', purpose: 'subject-access', fields: {}, expect: { status: 400, error: 'required-field-missing', message: 'A field this route needs was not sent.' } },
 { engine: 'access', key: 'GET /v1/access/bookings/{bookingRef}@1', role: 'patient', purpose: 'subject-access', fields: { bookingRef: 123 }, expect: { status: 400, error: 'field-of-the-wrong-type', message: 'A field this route needs was sent in the wrong shape.' } },
 { engine: 'care', key: 'GET /v1/care/circuits@1', role: 'nobody-synthetic-0', purpose: 'dispatch', fields: {}, expect: { status: 403, error: 'caller-not-allowed', message: 'This route does not take calls from your role.' } },
 { engine: 'care', key: 'GET /v1/care/circuits@1', role: 'nurse', purpose: 'purpose-not-served-synthetic', fields: {}, expect: { status: 403, error: 'purpose-not-allowed', message: 'This route does not serve the purpose you gave.' } },
 { engine: 'care', key: 'POST /v1/care/offers/{offerRef}/accept@1', role: 'nurse', purpose: 'dispatch', fields: {}, expect: { status: 400, error: 'idempotency-key-required', message: 'A money or dispatch write needs an idempotency key.' } },
 { engine: 'care', key: 'POST /v1/care/offers/{offerRef}/accept@1', role: 'nurse', purpose: 'dispatch', fields: { idempotencyKey: 'contract-compliance-1' }, expect: { status: 400, error: 'required-field-missing', message: 'A field this route needs was not sent.' } },
 { engine: 'care', key: 'POST /v1/care/offers/{offerRef}/accept@1', role: 'nurse', purpose: 'dispatch', fields: { idempotencyKey: 'synthetic-compliance', offerRef: 123 }, expect: { status: 400, error: 'field-of-the-wrong-type', message: 'A field this route needs was sent in the wrong shape.' } },
 { engine: 'clinical', key: 'GET /v1/clinical/review-confirmers@2', role: 'nobody-synthetic-0', purpose: 'audit', fields: {}, expect: { status: 403, error: 'caller-not-allowed', message: 'This route does not take calls from your role.' } },
 { engine: 'clinical', key: 'GET /v1/clinical/review-confirmers@2', role: 'engine:access', purpose: 'purpose-not-served-synthetic', fields: {}, expect: { status: 403, error: 'purpose-not-allowed', message: 'This route does not serve the purpose you gave.' } },
 { engine: 'clinical', key: 'POST /v1/clinical/consultations@2', role: 'doctor', purpose: 'treatment', fields: {}, expect: { status: 400, error: 'required-field-missing', message: 'A field this route needs was not sent.' } },
 { engine: 'clinical', key: 'POST /v1/clinical/consultations@2', role: 'doctor', purpose: 'treatment', fields: { encounterRef: 'synthetic-compliance', consultationEntryRef: 'synthetic-compliance', sectionsWritten: [], subjectRef: 123 }, expect: { status: 400, error: 'field-of-the-wrong-type', message: 'A field this route needs was sent in the wrong shape.' } },
 { engine: 'core', key: 'GET /v1/core/audit-exports@1', role: 'nobody-synthetic-0', purpose: 'audit', fields: {}, expect: { status: 403, error: 'caller-not-allowed', message: 'This route does not take calls from your role.' } },
 { engine: 'core', key: 'GET /v1/core/audit-exports@1', role: 'operator', purpose: 'purpose-not-served-synthetic', fields: {}, expect: { status: 403, error: 'purpose-not-allowed', message: 'This route does not serve the purpose you gave.' } },
 { engine: 'core', key: 'POST /v1/core/loops/{loopRef}/acknowledge@3', role: 'nurse', purpose: 'treatment', fields: {}, expect: { status: 400, error: 'idempotency-key-required', message: 'A money or dispatch write needs an idempotency key.' } },
 { engine: 'core', key: 'GET /v1/core/audit-exports@1', role: 'operator', purpose: 'audit', fields: {}, expect: { status: 400, error: 'required-field-missing', message: 'A field this route needs was not sent.' } },
 { engine: 'core', key: 'GET /v1/core/audit-exports@1', role: 'operator', purpose: 'audit', fields: { to: '2026-09-15', from: 123 }, expect: { status: 400, error: 'field-of-the-wrong-type', message: 'A field this route needs was sent in the wrong shape.' } },
 { engine: 'devices', key: 'GET /v1/devices/registry/{deviceRef}/health@2', role: 'nobody-synthetic-0', purpose: 'treatment', fields: {}, expect: { status: 403, error: 'caller-not-allowed', message: 'This route does not take calls from your role.' } },
 { engine: 'devices', key: 'GET /v1/devices/registry/{deviceRef}/health@2', role: 'nurse', purpose: 'purpose-not-served-synthetic', fields: {}, expect: { status: 403, error: 'purpose-not-allowed', message: 'This route does not serve the purpose you gave.' } },
 { engine: 'devices', key: 'GET /v1/devices/registry/{deviceRef}/health@2', role: 'nurse', purpose: 'treatment', fields: {}, expect: { status: 400, error: 'required-field-missing', message: 'A field this route needs was not sent.' } },
 { engine: 'devices', key: 'GET /v1/devices/registry/{deviceRef}/health@2', role: 'nurse', purpose: 'treatment', fields: { deviceRef: 123 }, expect: { status: 400, error: 'field-of-the-wrong-type', message: 'A field this route needs was sent in the wrong shape.' } },
 { engine: 'medicines', key: 'GET /v1/medicines/formulary@2', role: 'nobody-synthetic-0', purpose: 'dispensing', fields: {}, expect: { status: 403, error: 'caller-not-allowed', message: 'This route does not take calls from your role.' } },
 { engine: 'medicines', key: 'GET /v1/medicines/formulary@2', role: 'doctor', purpose: 'purpose-not-served-synthetic', fields: {}, expect: { status: 403, error: 'purpose-not-allowed', message: 'This route does not serve the purpose you gave.' } },
 { engine: 'medicines', key: 'GET /v1/medicines/formulary@2', role: 'doctor', purpose: 'dispensing', fields: {}, expect: { status: 400, error: 'required-field-missing', message: 'A field this route needs was not sent.' } },
 { engine: 'medicines', key: 'GET /v1/medicines/formulary@2', role: 'doctor', purpose: 'dispensing', fields: { query: 123 }, expect: { status: 400, error: 'field-of-the-wrong-type', message: 'A field this route needs was sent in the wrong shape.' } },
 { engine: 'money', key: 'GET /v1/money/claims@1', role: 'nobody-synthetic-0', purpose: 'billing', fields: {}, expect: { status: 403, error: 'caller-not-allowed', message: 'This route does not take calls from your role.' } },
 { engine: 'money', key: 'GET /v1/money/claims@1', role: 'patient', purpose: 'purpose-not-served-synthetic', fields: {}, expect: { status: 403, error: 'purpose-not-allowed', message: 'This route does not serve the purpose you gave.' } },
 { engine: 'money', key: 'POST /v1/money/claims/{claimRef}/consent@1', role: 'patient', purpose: 'billing', fields: {}, expect: { status: 400, error: 'idempotency-key-required', message: 'A money or dispatch write needs an idempotency key.' } },
 { engine: 'money', key: 'GET /v1/money/groups/{groupRef}@1', role: 'sponsor', purpose: 'billing', fields: {}, expect: { status: 400, error: 'required-field-missing', message: 'A field this route needs was not sent.' } },
 { engine: 'money', key: 'GET /v1/money/groups/{groupRef}@1', role: 'sponsor', purpose: 'billing', fields: { groupRef: 123 }, expect: { status: 400, error: 'field-of-the-wrong-type', message: 'A field this route needs was sent in the wrong shape.' } },
 { engine: 'movement', key: 'GET /v1/movement/admissions/{admissionRef}@2', role: 'nobody-synthetic-0', purpose: 'dispatch', fields: {}, expect: { status: 403, error: 'caller-not-allowed', message: 'This route does not take calls from your role.' } },
 { engine: 'movement', key: 'GET /v1/movement/admissions/{admissionRef}@2', role: 'patient', purpose: 'purpose-not-served-synthetic', fields: {}, expect: { status: 403, error: 'purpose-not-allowed', message: 'This route does not serve the purpose you gave.' } },
 { engine: 'movement', key: 'POST /v1/movement/admissions/{admissionRef}/decision@2', role: 'ops-desk', purpose: 'dispatch', fields: {}, expect: { status: 400, error: 'idempotency-key-required', message: 'A money or dispatch write needs an idempotency key.' } },
 { engine: 'movement', key: 'GET /v1/movement/admissions/{admissionRef}@2', role: 'patient', purpose: 'dispatch', fields: {}, expect: { status: 400, error: 'required-field-missing', message: 'A field this route needs was not sent.' } },
 { engine: 'movement', key: 'GET /v1/movement/admissions/{admissionRef}@2', role: 'patient', purpose: 'dispatch', fields: { admissionRef: 123 }, expect: { status: 400, error: 'field-of-the-wrong-type', message: 'A field this route needs was sent in the wrong shape.' } },
 { engine: 'record', key: 'GET /v1/record/settings@1', role: 'nobody-synthetic-0', purpose: 'audit', fields: {}, expect: { status: 403, error: 'caller-not-allowed', message: 'This route does not take calls from your role.' } },
 { engine: 'record', key: 'GET /v1/record/settings@1', role: 'admin', purpose: 'purpose-not-served-synthetic', fields: {}, expect: { status: 403, error: 'purpose-not-allowed', message: 'This route does not serve the purpose you gave.' } },
 { engine: 'record', key: 'POST /v1/record/setting-changes@1', role: 'admin', purpose: 'audit', fields: {}, expect: { status: 400, error: 'required-field-missing', message: 'A field this route needs was not sent.' } },
 { engine: 'record', key: 'POST /v1/record/setting-changes@1', role: 'admin', purpose: 'audit', fields: { idempotencyKey: 'synthetic-compliance', expectedVersion: 1, setting: 123 }, expect: { status: 400, error: 'field-of-the-wrong-type', message: 'A field this route needs was sent in the wrong shape.' } },
 { engine: 'safety', key: 'GET /v1/safety/checkins@1', role: 'nobody-synthetic-0', purpose: 'dispatch', fields: {}, expect: { status: 403, error: 'caller-not-allowed', message: 'This route does not take calls from your role.' } },
 { engine: 'safety', key: 'GET /v1/safety/checkins@1', role: 'nurse', purpose: 'purpose-not-served-synthetic', fields: {}, expect: { status: 403, error: 'purpose-not-allowed', message: 'This route does not serve the purpose you gave.' } },
 { engine: 'safety', key: 'POST /v1/safety/checkins/{checkinRef}/close@2', role: 'nurse', purpose: 'dispatch', fields: {}, expect: { status: 400, error: 'idempotency-key-required', message: 'A money or dispatch write needs an idempotency key.' } },
 { engine: 'safety', key: 'GET /v1/safety/checkins@1', role: 'nurse', purpose: 'dispatch', fields: {}, expect: { status: 400, error: 'required-field-missing', message: 'A field this route needs was not sent.' } },
 { engine: 'safety', key: 'GET /v1/safety/checkins@1', role: 'nurse', purpose: 'dispatch', fields: { appointmentRef: 123 }, expect: { status: 400, error: 'field-of-the-wrong-type', message: 'A field this route needs was sent in the wrong shape.' } },
 { engine: 'trust', key: 'GET /v1/trust/complaint-notices@1', role: 'nobody-synthetic-0', purpose: 'vetting', fields: {}, expect: { status: 403, error: 'caller-not-allowed', message: 'This route does not take calls from your role.' } },
 { engine: 'trust', key: 'GET /v1/trust/complaint-notices@1', role: 'nurse', purpose: 'purpose-not-served-synthetic', fields: {}, expect: { status: 403, error: 'purpose-not-allowed', message: 'This route does not serve the purpose you gave.' } },
 { engine: 'trust', key: 'GET /v1/trust/complaints/{complaintRef}@1', role: 'admin', purpose: 'vetting', fields: {}, expect: { status: 400, error: 'required-field-missing', message: 'A field this route needs was not sent.' } },
 { engine: 'trust', key: 'GET /v1/trust/complaints/{complaintRef}@1', role: 'admin', purpose: 'vetting', fields: { complaintRef: 123 }, expect: { status: 400, error: 'field-of-the-wrong-type', message: 'A field this route needs was sent in the wrong shape.' } },
];

const world = (engine: string): Runtime => createRuntime({ env: { MYTHUSO_ENGINES: 'synthetic-data-only' }, engines: [ENGINES[engine]!], dataDirectory: MEMORY, clock: createClock(MORNING) });
type Call = { role: string; purpose: string; fields: Record<string, unknown> };
const callWith = (runtime: Runtime, key: string, input: Call) => runtime.call(key as RouteKey, { ...input, ref: 'subject-synthetic-compliance' });

test('access: the registered table is exactly the one this file was generated with', () => {
 const runtime = world('access');
 const bound = runtime.bound().sort();
 assert.deepEqual(bound, REGISTERED['access'], 'the registered table');
 for (const key of bound) assert.ok((BUILT['access'] ?? []).includes(key), `${key} is registered, and the catalog does not mark it built and live`);
 runtime.close();
});

test('access: a withdrawn route is registered nowhere, and the runtime answers none of them', () => {
 const runtime = world('access');
 for (const key of WITHDRAWN['access']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is withdrawn and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [404, 'no-route', NO_ROUTE_MESSAGE, 'runtime'], key);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('access: a proposed route is registered nowhere, and the mock answers it — no engine has built it', () => {
 const runtime = world('access');
 for (const key of PROPOSED['access']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is proposed and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.equal(answer.answeredBy, 'mock', `${key} is answered by ${answer.answeredBy}`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('access: the binder refuses as the catalog declares, on the routes access has built', () => {
 const runtime = world('access');
 for (const probe of PROBES.filter((entry) => entry.engine === 'access')) {
  const answer = callWith(runtime, probe.key, { role: probe.role, purpose: probe.purpose, fields: probe.fields });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [probe.expect.status, probe.expect.error, probe.expect.message, 'engine'], `${probe.key} (${probe.expect.error})`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('care: the registered table is exactly the one this file was generated with', () => {
 const runtime = world('care');
 const bound = runtime.bound().sort();
 assert.deepEqual(bound, REGISTERED['care'], 'the registered table');
 for (const key of bound) assert.ok((BUILT['care'] ?? []).includes(key), `${key} is registered, and the catalog does not mark it built and live`);
 runtime.close();
});

test('care: a withdrawn route is registered nowhere, and the runtime answers none of them', () => {
 const runtime = world('care');
 for (const key of WITHDRAWN['care']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is withdrawn and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [404, 'no-route', NO_ROUTE_MESSAGE, 'runtime'], key);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('care: the binder refuses as the catalog declares, on the routes care has built', () => {
 const runtime = world('care');
 for (const probe of PROBES.filter((entry) => entry.engine === 'care')) {
  const answer = callWith(runtime, probe.key, { role: probe.role, purpose: probe.purpose, fields: probe.fields });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [probe.expect.status, probe.expect.error, probe.expect.message, 'engine'], `${probe.key} (${probe.expect.error})`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('clinical: the registered table is exactly the one this file was generated with', () => {
 const runtime = world('clinical');
 const bound = runtime.bound().sort();
 assert.deepEqual(bound, REGISTERED['clinical'], 'the registered table');
 for (const key of bound) assert.ok((BUILT['clinical'] ?? []).includes(key), `${key} is registered, and the catalog does not mark it built and live`);
 runtime.close();
});

test('clinical: a withdrawn route is registered nowhere, and the runtime answers none of them', () => {
 const runtime = world('clinical');
 for (const key of WITHDRAWN['clinical']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is withdrawn and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [404, 'no-route', NO_ROUTE_MESSAGE, 'runtime'], key);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('clinical: the binder refuses as the catalog declares, on the routes clinical has built', () => {
 const runtime = world('clinical');
 for (const probe of PROBES.filter((entry) => entry.engine === 'clinical')) {
  const answer = callWith(runtime, probe.key, { role: probe.role, purpose: probe.purpose, fields: probe.fields });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [probe.expect.status, probe.expect.error, probe.expect.message, 'engine'], `${probe.key} (${probe.expect.error})`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('core: the registered table is exactly the one this file was generated with', () => {
 const runtime = world('core');
 const bound = runtime.bound().sort();
 assert.deepEqual(bound, REGISTERED['core'], 'the registered table');
 for (const key of bound) assert.ok((BUILT['core'] ?? []).includes(key), `${key} is registered, and the catalog does not mark it built and live`);
 runtime.close();
});

test('core: a withdrawn route is registered nowhere, and the runtime answers none of them', () => {
 const runtime = world('core');
 for (const key of WITHDRAWN['core']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is withdrawn and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [404, 'no-route', NO_ROUTE_MESSAGE, 'runtime'], key);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('core: the binder refuses as the catalog declares, on the routes core has built', () => {
 const runtime = world('core');
 for (const probe of PROBES.filter((entry) => entry.engine === 'core')) {
  const answer = callWith(runtime, probe.key, { role: probe.role, purpose: probe.purpose, fields: probe.fields });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [probe.expect.status, probe.expect.error, probe.expect.message, 'engine'], `${probe.key} (${probe.expect.error})`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('devices: the registered table is exactly the one this file was generated with', () => {
 const runtime = world('devices');
 const bound = runtime.bound().sort();
 assert.deepEqual(bound, REGISTERED['devices'], 'the registered table');
 for (const key of bound) assert.ok((BUILT['devices'] ?? []).includes(key), `${key} is registered, and the catalog does not mark it built and live`);
 runtime.close();
});

test('devices: a withdrawn route is registered nowhere, and the runtime answers none of them', () => {
 const runtime = world('devices');
 for (const key of WITHDRAWN['devices']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is withdrawn and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [404, 'no-route', NO_ROUTE_MESSAGE, 'runtime'], key);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('devices: the binder refuses as the catalog declares, on the routes devices has built', () => {
 const runtime = world('devices');
 for (const probe of PROBES.filter((entry) => entry.engine === 'devices')) {
  const answer = callWith(runtime, probe.key, { role: probe.role, purpose: probe.purpose, fields: probe.fields });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [probe.expect.status, probe.expect.error, probe.expect.message, 'engine'], `${probe.key} (${probe.expect.error})`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('medicines: the registered table is exactly the one this file was generated with', () => {
 const runtime = world('medicines');
 const bound = runtime.bound().sort();
 assert.deepEqual(bound, REGISTERED['medicines'], 'the registered table');
 for (const key of bound) assert.ok((BUILT['medicines'] ?? []).includes(key), `${key} is registered, and the catalog does not mark it built and live`);
 runtime.close();
});

test('medicines: a withdrawn route is registered nowhere, and the runtime answers none of them', () => {
 const runtime = world('medicines');
 for (const key of WITHDRAWN['medicines']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is withdrawn and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [404, 'no-route', NO_ROUTE_MESSAGE, 'runtime'], key);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('medicines: the binder refuses as the catalog declares, on the routes medicines has built', () => {
 const runtime = world('medicines');
 for (const probe of PROBES.filter((entry) => entry.engine === 'medicines')) {
  const answer = callWith(runtime, probe.key, { role: probe.role, purpose: probe.purpose, fields: probe.fields });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [probe.expect.status, probe.expect.error, probe.expect.message, 'engine'], `${probe.key} (${probe.expect.error})`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('money: the registered table is exactly the one this file was generated with', () => {
 const runtime = world('money');
 const bound = runtime.bound().sort();
 assert.deepEqual(bound, REGISTERED['money'], 'the registered table');
 for (const key of bound) assert.ok((BUILT['money'] ?? []).includes(key), `${key} is registered, and the catalog does not mark it built and live`);
 runtime.close();
});

test('money: a withdrawn route is registered nowhere, and the runtime answers none of them', () => {
 const runtime = world('money');
 for (const key of WITHDRAWN['money']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is withdrawn and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [404, 'no-route', NO_ROUTE_MESSAGE, 'runtime'], key);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('money: a proposed route is registered nowhere, and the mock answers it — no engine has built it', () => {
 const runtime = world('money');
 for (const key of PROPOSED['money']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is proposed and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.equal(answer.answeredBy, 'mock', `${key} is answered by ${answer.answeredBy}`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('money: the binder refuses as the catalog declares, on the routes money has built', () => {
 const runtime = world('money');
 for (const probe of PROBES.filter((entry) => entry.engine === 'money')) {
  const answer = callWith(runtime, probe.key, { role: probe.role, purpose: probe.purpose, fields: probe.fields });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [probe.expect.status, probe.expect.error, probe.expect.message, 'engine'], `${probe.key} (${probe.expect.error})`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('movement: the registered table is exactly the one this file was generated with', () => {
 const runtime = world('movement');
 const bound = runtime.bound().sort();
 assert.deepEqual(bound, REGISTERED['movement'], 'the registered table');
 for (const key of bound) assert.ok((BUILT['movement'] ?? []).includes(key), `${key} is registered, and the catalog does not mark it built and live`);
 runtime.close();
});

test('movement: a withdrawn route is registered nowhere, and the runtime answers none of them', () => {
 const runtime = world('movement');
 for (const key of WITHDRAWN['movement']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is withdrawn and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [404, 'no-route', NO_ROUTE_MESSAGE, 'runtime'], key);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('movement: the binder refuses as the catalog declares, on the routes movement has built', () => {
 const runtime = world('movement');
 for (const probe of PROBES.filter((entry) => entry.engine === 'movement')) {
  const answer = callWith(runtime, probe.key, { role: probe.role, purpose: probe.purpose, fields: probe.fields });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [probe.expect.status, probe.expect.error, probe.expect.message, 'engine'], `${probe.key} (${probe.expect.error})`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('record: the registered table is exactly the one this file was generated with', () => {
 const runtime = world('record');
 const bound = runtime.bound().sort();
 assert.deepEqual(bound, REGISTERED['record'], 'the registered table');
 for (const key of bound) assert.ok((BUILT['record'] ?? []).includes(key), `${key} is registered, and the catalog does not mark it built and live`);
 runtime.close();
});

test('record: a withdrawn route is registered nowhere, and the runtime answers none of them', () => {
 const runtime = world('record');
 for (const key of WITHDRAWN['record']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is withdrawn and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [404, 'no-route', NO_ROUTE_MESSAGE, 'runtime'], key);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('record: the binder refuses as the catalog declares, on the routes record has built', () => {
 const runtime = world('record');
 for (const probe of PROBES.filter((entry) => entry.engine === 'record')) {
  const answer = callWith(runtime, probe.key, { role: probe.role, purpose: probe.purpose, fields: probe.fields });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [probe.expect.status, probe.expect.error, probe.expect.message, 'engine'], `${probe.key} (${probe.expect.error})`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('safety: the registered table is exactly the one this file was generated with', () => {
 const runtime = world('safety');
 const bound = runtime.bound().sort();
 assert.deepEqual(bound, REGISTERED['safety'], 'the registered table');
 for (const key of bound) assert.ok((BUILT['safety'] ?? []).includes(key), `${key} is registered, and the catalog does not mark it built and live`);
 runtime.close();
});

test('safety: a withdrawn route is registered nowhere, and the runtime answers none of them', () => {
 const runtime = world('safety');
 for (const key of WITHDRAWN['safety']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is withdrawn and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [404, 'no-route', NO_ROUTE_MESSAGE, 'runtime'], key);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('safety: a proposed route is registered nowhere, and the mock answers it — no engine has built it', () => {
 const runtime = world('safety');
 for (const key of PROPOSED['safety']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is proposed and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.equal(answer.answeredBy, 'mock', `${key} is answered by ${answer.answeredBy}`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('safety: the binder refuses as the catalog declares, on the routes safety has built', () => {
 const runtime = world('safety');
 for (const probe of PROBES.filter((entry) => entry.engine === 'safety')) {
  const answer = callWith(runtime, probe.key, { role: probe.role, purpose: probe.purpose, fields: probe.fields });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [probe.expect.status, probe.expect.error, probe.expect.message, 'engine'], `${probe.key} (${probe.expect.error})`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('trust: the registered table is exactly the one this file was generated with', () => {
 const runtime = world('trust');
 const bound = runtime.bound().sort();
 assert.deepEqual(bound, REGISTERED['trust'], 'the registered table');
 for (const key of bound) assert.ok((BUILT['trust'] ?? []).includes(key), `${key} is registered, and the catalog does not mark it built and live`);
 runtime.close();
});

test('trust: a withdrawn route is registered nowhere, and the runtime answers none of them', () => {
 const runtime = world('trust');
 for (const key of WITHDRAWN['trust']!) {
  assert.ok(!runtime.bound().includes(key as RouteKey), `${key} is withdrawn and must not be registered`);
  const answer = callWith(runtime, key, { role: 'nobody-synthetic-0', purpose: 'purpose-not-served-synthetic', fields: {} });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [404, 'no-route', NO_ROUTE_MESSAGE, 'runtime'], key);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});

test('trust: the binder refuses as the catalog declares, on the routes trust has built', () => {
 const runtime = world('trust');
 for (const probe of PROBES.filter((entry) => entry.engine === 'trust')) {
  const answer = callWith(runtime, probe.key, { role: probe.role, purpose: probe.purpose, fields: probe.fields });
  assert.deepEqual([answer.status, answer.body['error'], answer.body['message'], answer.answeredBy], [probe.expect.status, probe.expect.error, probe.expect.message, 'engine'], `${probe.key} (${probe.expect.error})`);
 }
 assert.deepEqual(runtime.faults(), []);
 runtime.close();
});
