/* Booking a visit and the thread about it, written out for two native apps by a machine.

   packages/catalog/booking.json holds the words of the person step, the review, the three booking
   states and the visit thread. The web and packages/engines read it; iOS and Android cannot read JSON
   at runtime, so this writes BookingData.swift and BookingData.kt and scripts/check-boundaries.mjs
   compares both with what this would write on every build.

   WHAT IS RESOLVED HERE RATHER THAN COPIED. A refusal a route answers with is the route's sentence, in
   packages/catalog/apis/access.json; booking.json names it by route and id, and this looks it up — so a
   phone renders the route's own words, and a refusal booking.json names that the route does not
   declare stops the build instead of compiling an empty string. The badge a nurse must hold is the
   verified tier's name and sentence in packages/catalog/trust.json. The emergency numbers in the
   thread's "nobody watches" sentence are packages/catalog/sos.json's. None of the three is typed twice.

   WHAT IS NOT EMITTED. Prices, durations and the cancellation window. Each native app already reads
   services and the window from its own generated or catalogued source, and a second copy here would be
   a price that can disagree with the one on the service row.

   Escaping: Swift needs its quotes escaped; Kotlin needs backslash, quote and dollar, because a lone $
   starts a template. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/catalog/booking.json';

const swift = value => `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const kotlin = value => `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const optSwift = value => (value === null || value === undefined ? 'nil' : swift(value));
const optKotlin = value => (value === null || value === undefined ? 'null' : kotlin(value));

const banner = () => [
 `Generated by scripts/emit-booking.mjs from ${SOURCE}, with refusals from packages/catalog/apis/access.json,`,
 'the badge from packages/catalog/trust.json and the emergency numbers from packages/catalog/sos.json.',
 'Do not edit by hand — run `npm run booking`. The build fails if this file and its sources disagree,',
 'so an edit here is lost rather than merely wrong.',
 '',
 'Nothing here books anybody. The booking and messaging capabilities are simulated, and every screen that',
 'reads this says so from the capabilities contract.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function resolveBooking(root = '') {
 const read = file => JSON.parse(readFileSync(root + file, 'utf8'));
 const contract = read(SOURCE);
 const access = read('packages/catalog/apis/access.json');
 const trust = read('packages/catalog/trust.json');
 const sos = read('packages/catalog/sos.json');

 const tier = trust.tiers.find(t => t.id === contract.person.badge.tier);
 if (!tier) throw new Error(`${SOURCE} names the badge tier "${contract.person.badge.tier}", which packages/catalog/trust.json does not have.`);
 const number = id => {
  const found = sos.emergency.numbers.find(n => n.id === id);
  if (!found) throw new Error(`packages/catalog/sos.json has no emergency number "${id}".`);
  return found.number;
 };
 const say = text => text.replace(/\{(ambulance|mobile)\}/g, (_, id) => number(id));
 const routeRefusals = contract.routeRefusals.map(({ route, id }) => {
  const declared = access.routes.find(r => `${r.method} ${r.path}@${r.version}` === route);
  if (!declared) throw new Error(`${SOURCE} names a refusal of ${route}, which packages/catalog/apis/access.json does not declare.`);
  const refusal = declared.refusals.find(r => r.id === id);
  if (!refusal) throw new Error(`${SOURCE} names the refusal "${id}" of ${route}, which the route does not declare.`);
  return { id, route, status: refusal.status, sentence: refusal.statement };
 });
 const refusals = [...contract.refusals.map(r => ({ id: r.id, route: null, status: null, sentence: r.sentence })), ...routeRefusals];
 return { contract, tier, say, refusals };
}

export function emitBooking(root = '') {
 const { contract, tier, say, refusals } = resolveBooking(root);
 const { person, time, review, thread } = contract;

 const swiftFile = `${banner()}

import Foundation

enum BookingData {
    static let publishes: [String] = [${contract.publishes.map(swift).join(', ')}]

    enum Person {
        static let stepLabel = ${swift(person.stepLabel)}
        static let heading = ${swift(person.heading)}
        static let lead = ${swift(person.lead)}
        static let options: [BookingPersonOption] = [
${person.options.map(o => `            .init(id: ${swift(o.id)}, name: ${swift(o.name)}, detail: ${swift(o.detail)})`).join(',\n')}
        ]
        /// The take-visit gate decides whether a badge is current; the words are trust.json's verified tier.
        static let badgeCapability = ${swift(person.badge.decidedBy)}
        static let badgeName = ${swift(tier.name)}
        static let badgeSentence = ${swift(tier.sentence)}
        static let worksIn = ${swift(person.worksIn)}
        static let namedHeading = ${swift(person.namedHeading)}
        static let notOfferedHeading = ${swift(person.notOfferedHeading)}
        static let noPrevious = ${swift(person.noPrevious)}
        static let previousNotOffered = ${swift(person.previousNotOffered)}
        static let asapNeedsNearest = ${swift(person.asapNeedsNearest)}
        static let continuity = ${swift(person.continuity)}
    }

    enum Time {
        static let fewerHours = ${swift(time.fewerHours)}
        static let noHoursLeft = ${swift(time.noHoursLeft)}
    }

    enum Review {
        static let nurseLabel = ${swift(review.nurseLabel)}
        static let nearestValue = ${swift(review.nearestValue)}
        static let priceLabel = ${swift(review.priceLabel)}
        static let cancellingLabel = ${swift(review.cancellingLabel)}
    }

    static let states: [BookingStateWords] = [
${contract.states.map(s => `        .init(id: ${swift(s.id)}, name: ${swift(s.name)}, patientWords: ${swift(s.patientWords)}, event: ${swift(s.event)})`).join(',\n')}
    ]
    static let transitions: [BookingTransition] = [
${contract.transitions.map(t => `        .init(from: ${optSwift(t.from)}, to: ${swift(t.to)})`).join(',\n')}
    ]
    static let statusHeading = ${swift(contract.statusHeading)}
    enum StatusWords {
        static let reached = ${swift(contract.statusWords.reached)}
        static let current = ${swift(contract.statusWords.current)}
        static let waiting = ${swift(contract.statusWords.waiting)}
    }
    static let acceptedBy = ${swift(contract.acceptedBy)}
    static let asapStaysRequested = ${swift(contract.asapStaysRequested)}

    /// booking.json's own refusals, then the routes' refusals it names, each in the route's words.
    static let refusals: [BookingRefusal] = [
${refusals.map(r => `        .init(id: ${swift(r.id)}, route: ${optSwift(r.route)}, status: ${r.status ?? 'nil'}, sentence: ${swift(r.sentence)})`).join(',\n')}
    ]

    enum Thread {
        static let title = ${swift(thread.title)}
        static let openLabel = ${swift(thread.openLabel)}
        static let lead = ${swift(thread.lead)}
        static let notARecord = ${swift(thread.notARecord)}
        static let nobodyWatches = ${swift(say(thread.nobodyWatches))}
        static let inputLabel = ${swift(thread.inputLabel)}
        static let sendLabel = ${swift(thread.sendLabel)}
        static let maxCharacters = ${thread.maxCharacters}
        static let empty = ${swift(thread.empty)}
        static let kept = ${swift(thread.kept)}
        static let you = ${swift(thread.you)}
        static let closedBecause: [BookingThreadClosed] = [
${thread.closedBecause.map(c => `            .init(id: ${swift(c.id)}, sentence: ${swift(c.sentence)})`).join(',\n')}
        ]
    }
}
`;

 const kotlinFile = `${banner()}

package za.co.mythuso.model

object BookingData {
    val publishes = listOf(${contract.publishes.map(kotlin).join(', ')})

    object Person {
        const val stepLabel = ${kotlin(person.stepLabel)}
        const val heading = ${kotlin(person.heading)}
        const val lead = ${kotlin(person.lead)}
        val options = listOf(
${person.options.map(o => `            BookingPersonOption(${kotlin(o.id)}, ${kotlin(o.name)}, ${kotlin(o.detail)})`).join(',\n')}
        )
        /** The take-visit gate decides whether a badge is current; the words are trust.json's verified tier. */
        const val badgeCapability = ${kotlin(person.badge.decidedBy)}
        const val badgeName = ${kotlin(tier.name)}
        const val badgeSentence = ${kotlin(tier.sentence)}
        const val worksIn = ${kotlin(person.worksIn)}
        const val namedHeading = ${kotlin(person.namedHeading)}
        const val notOfferedHeading = ${kotlin(person.notOfferedHeading)}
        const val noPrevious = ${kotlin(person.noPrevious)}
        const val previousNotOffered = ${kotlin(person.previousNotOffered)}
        const val asapNeedsNearest = ${kotlin(person.asapNeedsNearest)}
        const val continuity = ${kotlin(person.continuity)}
    }

    object Time {
        const val fewerHours = ${kotlin(time.fewerHours)}
        const val noHoursLeft = ${kotlin(time.noHoursLeft)}
    }

    object Review {
        const val nurseLabel = ${kotlin(review.nurseLabel)}
        const val nearestValue = ${kotlin(review.nearestValue)}
        const val priceLabel = ${kotlin(review.priceLabel)}
        const val cancellingLabel = ${kotlin(review.cancellingLabel)}
    }

    val states = listOf(
${contract.states.map(s => `        BookingStateWords(${kotlin(s.id)}, ${kotlin(s.name)}, ${kotlin(s.patientWords)}, ${kotlin(s.event)})`).join(',\n')}
    )
    val transitions = listOf(
${contract.transitions.map(t => `        BookingTransition(${optKotlin(t.from)}, ${kotlin(t.to)})`).join(',\n')}
    )
    const val statusHeading = ${kotlin(contract.statusHeading)}
    object StatusWords {
        const val reached = ${kotlin(contract.statusWords.reached)}
        const val current = ${kotlin(contract.statusWords.current)}
        const val waiting = ${kotlin(contract.statusWords.waiting)}
    }
    const val acceptedBy = ${kotlin(contract.acceptedBy)}
    const val asapStaysRequested = ${kotlin(contract.asapStaysRequested)}

    /** booking.json's own refusals, then the routes' refusals it names, each in the route's words. */
    val refusals = listOf(
${refusals.map(r => `        BookingRefusal(${kotlin(r.id)}, ${optKotlin(r.route)}, ${r.status ?? 'null'}, ${kotlin(r.sentence)})`).join(',\n')}
    )

    object Thread {
        const val title = ${kotlin(thread.title)}
        const val openLabel = ${kotlin(thread.openLabel)}
        const val lead = ${kotlin(thread.lead)}
        const val notARecord = ${kotlin(thread.notARecord)}
        const val nobodyWatches = ${kotlin(say(thread.nobodyWatches))}
        const val inputLabel = ${kotlin(thread.inputLabel)}
        const val sendLabel = ${kotlin(thread.sendLabel)}
        const val maxCharacters = ${thread.maxCharacters}
        const val empty = ${kotlin(thread.empty)}
        const val kept = ${kotlin(thread.kept)}
        const val you = ${kotlin(thread.you)}
        val closedBecause = listOf(
${thread.closedBecause.map(c => `            BookingThreadClosed(${kotlin(c.id)}, ${kotlin(c.sentence)})`).join(',\n')}
        )
    }
}
`;

 return {
  swift: { path: 'apps/ios/MyThuso/Models/BookingData.swift', content: swiftFile },
  kotlin: { path: 'apps/android/app/src/main/java/za/co/mythuso/model/BookingData.kt', content: kotlinFile }
 };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 const { swift: s, kotlin: k } = emitBooking();
 writeFileSync(s.path, s.content);
 writeFileSync(k.path, k.content);
 console.log(`wrote ${s.path}\nwrote ${k.path}`);
}
