/* One palette, written out three times, by a machine.

   The design language is described once in packages/design-tokens/tokens.json. Until now that file
   was a reference nobody read: the same eighteen colours were re-typed as CSS custom properties, as
   SwiftUI Color(red:green:blue:) and as Compose Color(0xFF…), and nothing checked that the three
   agreed. A palette drifting apart is not a clinical-safety problem the way a reference range is,
   but it is the seam nobody was watching, and a hand-converted colour channel is exactly the kind
   of thing a reviewer's eye slides over.

   Generating the native files does not make the apps less native. What comes out is SwiftUI source
   and Compose source, compiled into the binaries, parsing nothing at runtime — the same code
   somebody would have typed, minus the arithmetic.

   scripts/check-boundaries.mjs imports emitTokens() and compares what it returns against what is on
   disk, so a stale generated file and a hand-edited one both fail the build. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/design-tokens/tokens.json';

const kebab = name => name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
const pascal = name => name[0].toUpperCase() + name.slice(1);
const channel = (hex, index) => (parseInt(hex.slice(1 + index * 2, 3 + index * 2), 16) / 255).toFixed(3);

/* Two Compose names cannot be taken as they stand. `Body` reads as a layout slot rather than a text
   colour, and `Surface` is a material3 composable this package star-imports everywhere. Both were
   already renamed by hand in Theme.kt; the rename simply moved here. */
const composeNames = { body: 'BodyText', surface: 'SurfaceWhite' };

/* Two shadow names are load-bearing: styles.css says var(--shadow) and var(--shadow-raised) in
   rules this generator does not own. */
const cssShadowNames = { card: '--shadow', raised: '--shadow-raised' };

const banner = extension => {
 const lines = [
  `Generated by scripts/emit-tokens.mjs from ${SOURCE}.`,
  'Do not edit by hand — run `npm run tokens`. The build fails if this file and the token source',
  'disagree, so an edit here is lost rather than merely wrong.'
 ];
 if (extension === 'css') return `/* ${lines.join('\n   ')} */\n`;
 return lines.map(line => `// ${line}`).join('\n') + '\n';
};

export function emitTokens(root = '') {
 const tokens = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const colours = Object.entries(tokens.color);
 /* Generation four — the Lovable handoff of 28 September 2026 — is a set of ROLES, each with a light
    and a dark value, rather than a fourth run of flat names. They reach the web as --color-<role>,
    the name the handoff's own @theme block gives them, so they do not overwrite the three
    current-generation names they share a word with (surface, danger, info) on a screen that still
    reads those. The dark values are emitted only under :root[data-theme="dark"]: on 29 September 2026
    the founder saw the product dark under a dark OS scheme and decided light is the default and dark
    an option a person switches on (components/ThemeToggle.tsx). No prefers-color-scheme block, so the
    OS never decides.
    yet, which is the point — the variables exist before any screen is restyled for them. */
 const semantic = tokens.semantic;
 const roles = semantic.names;
 const semanticEntries = mode => roles.map(role => [role, semantic[mode][role]]);
 const semanticCss = mode => semanticEntries(mode).map(([role, { hex }]) => ` --color-${kebab(role)}:${hex.toLowerCase()};`).join('\n');
 const radii = Object.entries(tokens.radius);
 /* The alphas, emitted as alphas. The token file declares charcoalMuted as 0.72 and says in its own
    note why it cannot be a flattened grey: #5C5C5C fails on paleSage at 4.36 and on softSage at
    3.51, while the same ink at 72% composites with whatever it sits on and darkens as the ground
    does. The flattened per-ground pairs are emitted too, for measuring — but a platform handed only
    those has been handed the thing the note warns against, and Android reported exactly that: it
    could not spend the token as an alpha, so it used a local constant instead. */
 const alphas = Object.entries(tokens.opacity ?? {}).filter(([name]) => !name.startsWith('_'));
 /* The type scale and the motion duration used to reach the stylesheet and stop there, so both
    native apps typed the six sizes out by hand — and both, independently, reached past the top of
    the scale for a 22 that did not exist. A number that only one of three platforms can read is a
    number the other two will invent. */
 const type = Object.entries(tokens.typography.scale);
 const spacing = tokens.spacing;
 /* The curve and the three durations. They lived in apps/web/src/surface/glass.css, where only the
    web could reach them, so both native apps were guessing at what "the same easing" meant. A curve
    is a number like any other and belongs where the other numbers are. */
 const [ex1, ey1, ex2, ey2] = tokens.motion.easeSoft;

 /* ---- Web ------------------------------------------------------------------------------------
    A separate file rather than a block inside styles.css, because a generated file has to be a
    file for the build to be able to tell that it is stale. */
 const css = banner('css') + ':root{\n'
  + colours.map(([name, hex]) => ` --${kebab(name)}:${hex.toLowerCase()};`).join('\n') + '\n'
  + semanticCss('light') + '\n'
  + radii.map(([name, value]) => ` --r-${kebab(name)}:${value}px;`).join('\n') + '\n'
  + spacing.map(value => ` --space-${value}:${value}px;`).join('\n') + '\n'
  + Object.entries(tokens.elevation).map(([name, value]) => ` ${cssShadowNames[name] ?? `--shadow-${kebab(name)}`}:${value};`).join('\n') + '\n'
  + Object.entries(tokens.typography.stacks).map(([name, stack]) => ` --font-${name}:${stack};`).join('\n') + '\n'
  + ` --motion-duration:${tokens.motion.durationMs}ms;\n`
  + ` --ease-soft:cubic-bezier(${ex1},${ey1},${ex2},${ey2});\n`
  + ` --t-quick:${tokens.motion.quickMs}ms;\n`
  + ` --t-settle:${tokens.motion.settleMs}ms;\n`
  + ` --t-enter:${tokens.motion.enterMs}ms;\n`
  + '}\n'
  + ':root[data-theme="dark"]{\n' + semanticCss('dark') + '\n}\n';

 /* ---- iOS ------------------------------------------------------------------------------------
    The hex stays in a trailing comment because that is the number a designer recognises; the three
    channels are the number SwiftUI wants. Nobody should have to divide by 255 to review a palette. */
 const swiftColour = ([name, hex]) => `    static let ${name} = Color(red: ${channel(hex, 0)}, green: ${channel(hex, 1)}, blue: ${channel(hex, 2)})`;
 const swiftColours = colours.map(swiftColour);
 const widest = Math.max(...swiftColours.map(line => line.length));
 const swiftSemantic = mode => {
  const lines = semanticEntries(mode).map(([role, { hex }]) => `        static let ${role} = Color(red: ${channel(hex, 0)}, green: ${channel(hex, 1)}, blue: ${channel(hex, 2)})`);
  const w = Math.max(...lines.map(line => line.length));
  return lines.map((line, index) => `${line.padEnd(w)} // ${semanticEntries(mode)[index][1].hex}${semanticEntries(mode)[index][1].oklch ? ` ${semanticEntries(mode)[index][1].oklch}` : ''}`).join('\n');
 };
 const swift = banner('swift') + `
import SwiftUI

enum ThusoTheme {
${swiftColours.map((line, index) => `${line.padEnd(widest)} // ${colours[index][1]}`).join('\n')}
}
/// Generation four, the Lovable handoff of 28 September 2026: nineteen roles, each in a light and a
/// dark value, converted exactly from the handoff's oklch (kept in the trailing comment). Nothing
/// on iOS reads them yet; they exist so that restyling a screen is a matter of reaching for one.
enum ThusoSemantic {
    enum Light {
${swiftSemantic('light')}
    }
    enum Dark {
${swiftSemantic('dark')}
    }
}
enum ThusoRadius {
${radii.map(([name, value]) => `    static let ${name}: CGFloat = ${value}`).join('\n')}
}
/// Opacities, as opacities. A flattened grey cannot follow the ground it sits on; an alpha has no
/// choice but to.
enum ThusoOpacity {
${alphas.map(([name, value]) => `    static let ${name}: Double = ${value}`).join('\n')}
}
enum ThusoSpacing {
${spacing.map(value => `    static let space${value}: CGFloat = ${value}`).join('\n')}
}
/// The type scale, in points. SwiftUI text should be a semantic style so it answers Dynamic Type;
/// these are for the places that genuinely need a measurement — a glyph sized from its own tile,
/// a chart label, a @ScaledMetric base.
enum ThusoType {
${type.map(([name, value]) => `    static let ${name}: CGFloat = ${value}`).join('\n')}
    static let minimumBody: CGFloat = ${tokens.typography.minimumBody}
    /// Nothing in any of the three apps renders text below this.
    static let minimumRendered: CGFloat = ${tokens.typography.minimumRendered}
}
/// One curve and three durations, shared with the web and with Android. \`soft\` is the only easing
/// this product uses; reach for a spring only where a gesture is genuinely being tracked.
///
/// Reduced motion REMOVES an animation rather than shortening it, so the call site is
/// \`ThusoMotion.soft(...)\` wrapped in a check of \`accessibilityReduceMotion\`, never a shorter
/// duration — a 420ms entrance run at 80ms is still a thing that moved.
enum ThusoMotion {
    static let duration: TimeInterval = ${tokens.motion.durationMs / 1000}
    static let respectsReducedMotion = ${tokens.motion.respectReducedMotion}
    static let quick: TimeInterval = ${tokens.motion.quickMs / 1000}
    static let settle: TimeInterval = ${tokens.motion.settleMs / 1000}
    static let enter: TimeInterval = ${tokens.motion.enterMs / 1000}
    static func soft(_ duration: TimeInterval = settle) -> Animation {
        .timingCurve(${ex1}, ${ey1}, ${ex2}, ${ey2}, duration: duration)
    }
}
`;

 /* ---- Android --------------------------------------------------------------------------------
    Top-level vals in za.co.mythuso.ui, which is where every screen already reaches for them. */
 const kotlin = banner('kotlin') + `
package za.co.mythuso.ui

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

${colours.map(([name, hex]) => `val ${composeNames[name] ?? pascal(name)} = Color(0xFF${hex.replace('#', '').toUpperCase()})`).join('\n')}

/** Generation four, the Lovable handoff of 28 September 2026: nineteen roles, each in a light and a
    dark value, converted exactly from the handoff's oklch (kept in the trailing comment). Nothing on
    Android reads them yet; they exist so that restyling a screen is a matter of reaching for one. */
object ThusoSemantic {
    object Light {
${semanticEntries('light').map(([role, { hex, oklch }]) => `        val ${role} = Color(0xFF${hex.replace('#', '').toUpperCase()})${oklch ? ` // ${oklch}` : ''}`).join('\n')}
    }
    object Dark {
${semanticEntries('dark').map(([role, { hex, oklch }]) => `        val ${role} = Color(0xFF${hex.replace('#', '').toUpperCase()})${oklch ? ` // ${oklch}` : ''}`).join('\n')}
    }
}
object ThusoRadius {
${radii.map(([name, value]) => `    val ${name} = ${value}.dp`).join('\n')}
}
/** Opacities, as opacities. A flattened grey cannot follow the ground it sits on; an alpha has no
    choice but to. */
object ThusoOpacity {
${alphas.map(([name, value]) => `    const val ${name} = ${value}f`).join('\n')}
}
object ThusoSpacing {
${spacing.map(value => `    val space${value} = ${value}.dp`).join('\n')}
}
/** The type scale, in sp, so it scales with the reader's font size setting. */
object ThusoType {
${type.map(([name, value]) => `    val ${name} = ${value}.sp`).join('\n')}
    val minimumBody = ${tokens.typography.minimumBody}.sp
    /** Nothing in any of the three apps renders text below this. */
    val minimumRendered = ${tokens.typography.minimumRendered}.sp
}
/** One curve and three durations, shared with the web and with iOS. \`EaseSoft\` is the only easing
    this product uses.

    Reduced motion REMOVES an animation rather than shortening it. On Android that is the system
    animator duration scale, which reports 0f when a reader has turned animations off — so a
    duration multiplied by \`animatorScale()\` is genuinely none rather than merely brief. */
object ThusoMotion {
    const val durationMs = ${tokens.motion.durationMs}
    const val respectsReducedMotion = ${tokens.motion.respectReducedMotion}
    const val quickMs = ${tokens.motion.quickMs}
    const val settleMs = ${tokens.motion.settleMs}
    const val enterMs = ${tokens.motion.enterMs}
    val EaseSoft = CubicBezierEasing(${ex1}f, ${ey1}f, ${ex2}f, ${ey2}f)
}
`;

 return [
  { path: 'apps/web/src/tokens.generated.css', content: css },
  { path: 'apps/ios/MyThuso/DesignSystem/Tokens.swift', content: swift },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/ui/Tokens.kt', content: kotlin }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitTokens()) {
  writeFileSync(file.path, file.content);
  console.log(`tokens → ${file.path}`);
 }
}
