/* Thuso Money's contract, written out for two native apps by a machine.

   packages/catalog/money.json holds the ways to pay, the four payment states and their words, the
   cash code, the sentence a phone shows when it has no provider, the doctor's per-case fee and three
   signed sample cases. The web and the engine read that file. iOS and Android cannot, so this writes
   it into MoneyData.swift and MoneyData.kt, and scripts/check-boundaries.mjs compares what is on disk
   with what this would write on every build.

   Two things are resolved here rather than copied.

   The doctor's fee range is not in money.json. It is cited there, as a file and a path, and read
   from packages/catalog/business-model.json at generation time — so the range on a doctor's phone and
   the range in the funding proposal's model are one number. The fee itself is emitted as nil and
   null while the contract says null, and there is nowhere in either file to type a figure.

   The refusal statements a native screen renders — the undecided fee and the card number — are read
   from packages/catalog/apis/money.json by id. packages/catalog/apis.json's own generator leaves
   refusal sentences out of the clients on purpose, because a screen should render the answer a route
   gave. A native preview has no route to ask, so these few are emitted, and the build holds them to
   the contract like every other generated sentence.

   Escaping: Swift needs its quotes escaped; Kotlin needs backslash, quote and dollar. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/catalog/money.json';
const API = 'packages/catalog/apis/money.json';
const RENDERED_REFUSALS = ['doctor-fee-undecided', 'card-number-held', 'scheme-sees-a-payment'];

const swift = value => {
 if (String(value).includes('\\')) throw new Error(`Cannot write ${JSON.stringify(value)} as a Swift literal here`);
 return `"${String(value).replace(/"/g, '\\"')}"`;
};
const kotlin = value => `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const optSwift = value => (value === null || value === undefined ? 'nil' : typeof value === 'number' ? String(value) : swift(value));
const optKotlin = value => (value === null || value === undefined ? 'null' : typeof value === 'number' ? String(value) : kotlin(value));

const banner = () => [
 `Generated by scripts/emit-money.mjs from ${SOURCE}, ${API} and the file each fee's range is cited from.`,
 'Do not edit by hand — run `npm run money`. The build fails if this file and its sources disagree,',
 'so an edit here is lost rather than merely wrong.',
 '',
 'The doctor\'s fee is nil while the contract says null. The range beside it was read from the file',
 'the contract cites, and the types and the arithmetic are hand-written in Money.swift and Money.kt.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function emitMoney(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const api = JSON.parse(readFileSync(root + API, 'utf8'));
 const statement = id => {
  const found = [...api.refusals, ...api.routes.flatMap(r => r.refusals)].find(r => r.id === id);
  if (!found) throw new Error(`${API} has no refusal "${id}", which a native money screen renders.`);
  return found.statement;
 };
 const rangeOf = fee => {
  const cited = JSON.parse(readFileSync(root + fee.rangeFrom.file, 'utf8'));
  const range = fee.rangeFrom.path.split('.').reduce((at, key) => at?.[key], cited);
  if (!Array.isArray(range) || range.length !== 2) throw new Error(`The fee "${fee.feeCode}" cites ${fee.rangeFrom.file}#${fee.rangeFrom.path}, which is not a range of two numbers.`);
  return range;
 };
 const fees = contract.doctorFees.map(fee => ({ ...fee, range: rangeOf(fee) }));

 const swiftFile = `${banner()}

import Foundation

extension Money {
    static let currency = ${swift(contract.currency)}
    static let methods: [MoneyMethod] = [
${contract.methods.map(m => `        .init(id: ${swift(m.id)}, name: ${swift(m.name)}, detail: ${swift(m.detail)}, forVisit: ${m.for.includes('visit')}, forPlan: ${m.for.includes('plan')}, offered: ${m.offered})`).join(',\n')}
    ]
    static let states: [MoneyPaymentState] = [
${contract.states.map(s => `        .init(id: ${swift(s.id)}, name: ${swift(s.name)}, words: ${swift(s.words)})`).join(',\n')}
    ]
    static let cashCodeLength = ${contract.cash.codeLength}
    static let cashPendingWords = ${swift(contract.cash.pendingWords)}
    static let providerlessWords = ${swift(contract.providerless.words)}
    static let doctorFees: [DoctorFee] = [
${fees.map(f => `        .init(feeCode: ${swift(f.feeCode)}, name: ${swift(f.name)}, amount: ${optSwift(f.amount)}, decidedBy: ${optSwift(f.decidedBy)}, decidedOn: ${optSwift(f.decidedOn)},
              rangeLow: ${f.range[0]}, rangeHigh: ${f.range[1]}, source: ${swift(f.source)},
              undecided: ${swift(f.undecided)}, whoDecides: ${swift(f.whoDecides)})`).join(',\n')}
    ]
    static let casesWords = ${swift(contract.casesWords)}
    static let sampleCases: [SignedCase] = [
${contract.sampleCases.map(c => `        .init(reviewRef: ${swift(c.reviewRef)}, onDays: ${c.onDays})`).join(',\n')}
    ]
    /* Rendered word for word, from packages/catalog/apis/money.json. */
    static let refusals: [String: String] = [
${RENDERED_REFUSALS.map(id => `        ${swift(id)}: ${swift(statement(id))}`).join(',\n')}
    ]
}
`;

 const kotlinFile = `${banner()}

package za.co.mythuso.model

object MoneyData {
    const val currency = ${kotlin(contract.currency)}
    val methods = listOf(
${contract.methods.map(m => `        MoneyMethod(${kotlin(m.id)}, ${kotlin(m.name)}, ${kotlin(m.detail)}, forVisit = ${m.for.includes('visit')}, forPlan = ${m.for.includes('plan')}, offered = ${m.offered})`).join(',\n')}
    )
    val states = listOf(
${contract.states.map(s => `        MoneyPaymentState(${kotlin(s.id)}, ${kotlin(s.name)}, ${kotlin(s.words)})`).join(',\n')}
    )
    const val cashCodeLength = ${contract.cash.codeLength}
    const val cashPendingWords = ${kotlin(contract.cash.pendingWords)}
    const val providerlessWords = ${kotlin(contract.providerless.words)}
    val doctorFees = listOf(
${fees.map(f => `        DoctorFee(
            ${kotlin(f.feeCode)}, ${kotlin(f.name)}, amount = ${optKotlin(f.amount)}, decidedBy = ${optKotlin(f.decidedBy)}, decidedOn = ${optKotlin(f.decidedOn)},
            rangeLow = ${f.range[0]}, rangeHigh = ${f.range[1]}, source = ${kotlin(f.source)},
            undecided = ${kotlin(f.undecided)}, whoDecides = ${kotlin(f.whoDecides)}
        )`).join(',\n')}
    )
    const val casesWords = ${kotlin(contract.casesWords)}
    val sampleCases = listOf(
${contract.sampleCases.map(c => `        SignedCase(${kotlin(c.reviewRef)}, ${c.onDays})`).join(',\n')}
    )
    /* Rendered word for word, from packages/catalog/apis/money.json. */
    val refusals: Map<String, String> = mapOf(
${RENDERED_REFUSALS.map(id => `        ${kotlin(id)} to ${kotlin(statement(id))}`).join(',\n')}
    )
}
`;

 return [
  { path: 'apps/ios/MyThuso/Models/MoneyData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/MoneyData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitMoney()) {
  writeFileSync(file.path, file.content);
  console.log(`money → ${file.path}`);
 }
}
