/* Thuso Money's contract, written out for two native apps by a machine.

   packages/catalog/money.json holds the ways to pay, the four payment states and their words, the
   cash code, the sentence a phone shows when it has no provider, the doctor's per-case fee, three
   signed sample cases and Money's settings. The web and the engine read that file. iOS and Android
   cannot, so this writes it into MoneyData.swift and MoneyData.kt, and scripts/check-boundaries.mjs
   compares what is on disk with what this would write on every build.

   Three things are resolved here rather than copied.

   The doctor's fee is Money's setting doctor-case-fee, and whether it may be paid is the setting
   doctor-fee-confirmed. A phone has no admin surface, so it is given each default through
   scripts/settings-defaults.mjs, with the sentence saying whether it was decided, and the range an
   admin may set is the setting's bounds, which cite the range the documents give. Nothing in either
   generated file is a number anybody typed.

   The sentence a nurse reads about her share is the setting nurse-share-sentence, given the same way.

   The refusal statements a native screen renders — the unconfirmed fee and the card number — are read
   from packages/catalog/apis/money.json by id. packages/catalog/apis.json's own generator leaves
   refusal sentences out of the clients on purpose, because a screen should render the answer a route
   gave. A native preview has no route to ask, so these few are emitted, and the build holds them to
   the contract like every other generated sentence.

   Escaping: Swift needs its quotes escaped; Kotlin needs backslash, quote and dollar. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { settingBounds, settingDefault } from './settings-defaults.mjs';

const SOURCE = 'packages/catalog/money.json';
const API = 'packages/catalog/apis/money.json';
const RENDERED_REFUSALS = ['doctor-fee-undecided', 'card-number-held', 'scheme-sees-a-payment'];

const swift = value => {
 if (String(value).includes('\\')) throw new Error(`Cannot write ${JSON.stringify(value)} as a Swift literal here`);
 return `"${String(value).replace(/"/g, '\\"')}"`;
};
const kotlin = value => `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const comment = (indent, lines) => lines.map(line => `${indent}// ${line}`).join('\n');

const banner = () => [
 `Generated by scripts/emit-money.mjs from ${SOURCE} and ${API}.`,
 'Do not edit by hand — run `npm run money`. The build fails if this file and its sources disagree,',
 'so an edit here is lost rather than merely wrong.',
 '',
 'The doctor\'s fee, whether it is confirmed and a nurse\'s share sentence are Money\'s settings. Each is',
 'its default, with a comment saying whether anybody decided it; the types and the arithmetic are',
 'hand-written in Money.swift and Money.kt.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function emitMoney(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const api = JSON.parse(readFileSync(root + API, 'utf8'));
 const statement = id => {
  const found = [...api.refusals, ...api.routes.flatMap(r => r.refusals)].find(r => r.id === id);
  if (!found) throw new Error(`${API} has no refusal "${id}", which a native money screen renders.`);
  return found.statement;
 };
 const fees = contract.doctorFees.map(fee => {
  const amount = settingDefault(SOURCE, contract, fee.amountSetting);
  const confirmed = settingDefault(SOURCE, contract, fee.confirmedSetting);
  return { ...fee, amount, confirmedByDefault: confirmed, range: settingBounds(SOURCE, contract, fee.amountSetting) };
 });
 const share = settingDefault(SOURCE, contract, contract.nurseShareSetting);
 const feeNotes = f => [`${f.amountSetting}: ${f.amount.note}`, `${f.confirmedSetting}: ${f.confirmedByDefault.note}`];

 const swiftFile = `${banner()}

import Foundation

extension Money {
    static let currency = ${swift(contract.currency)}
    static let methods: [MoneyMethod] = [
${contract.methods.map(m => `        .init(id: ${swift(m.id)}, name: ${swift(m.name)}, detail: ${swift(m.detail)}, forVisit: ${m.for.includes('visit')}, forPlan: ${m.for.includes('plan')}, offered: ${m.offered})`).join(',\n')}
    ]
    static let states: [MoneyPaymentState] = [
${contract.states.map(s => `        .init(id: ${swift(s.id)}, name: ${swift(s.name)}, words: ${swift(s.words)})`).join(',\n')}
    ]
    static let cashCodeLength = ${contract.cash.codeLength}
    static let cashPendingWords = ${swift(contract.cash.pendingWords)}
    static let providerlessWords = ${swift(contract.providerless.words)}
    static let doctorFees: [DoctorFee] = [
${fees.map(f => `${comment('        ', feeNotes(f))}
        .init(feeCode: ${swift(f.feeCode)}, name: ${swift(f.name)}, amountCents: ${f.amount.value}, confirmed: ${f.confirmedByDefault.value},
              rangeLowCents: ${f.range.lowest}, rangeHighCents: ${f.range.highest}, source: ${swift(f.source)},
              unconfirmedWords: ${swift(f.unconfirmed)}, confirmedWords: ${swift(f.confirmed)}, whoSets: ${swift(f.whoSets)})`).join(',\n')}
    ]
${comment('    ', [`${contract.nurseShareSetting}: ${share.note}`])}
    static let nurseShareSentence = ${swift(share.value)}
    static let casesWords = ${swift(contract.casesWords)}
    static let sampleCases: [SignedCase] = [
${contract.sampleCases.map(c => `        .init(reviewRef: ${swift(c.reviewRef)}, onDays: ${c.onDays})`).join(',\n')}
    ]
    /* Rendered word for word, from packages/catalog/apis/money.json. */
    static let refusals: [String: String] = [
${RENDERED_REFUSALS.map(id => `        ${swift(id)}: ${swift(statement(id))}`).join(',\n')}
    ]
}
`;

 const kotlinFile = `${banner()}

package za.co.mythuso.model

object MoneyData {
    const val currency = ${kotlin(contract.currency)}
    val methods = listOf(
${contract.methods.map(m => `        MoneyMethod(${kotlin(m.id)}, ${kotlin(m.name)}, ${kotlin(m.detail)}, forVisit = ${m.for.includes('visit')}, forPlan = ${m.for.includes('plan')}, offered = ${m.offered})`).join(',\n')}
    )
    val states = listOf(
${contract.states.map(s => `        MoneyPaymentState(${kotlin(s.id)}, ${kotlin(s.name)}, ${kotlin(s.words)})`).join(',\n')}
    )
    const val cashCodeLength = ${contract.cash.codeLength}
    const val cashPendingWords = ${kotlin(contract.cash.pendingWords)}
    const val providerlessWords = ${kotlin(contract.providerless.words)}
    val doctorFees = listOf(
${fees.map(f => `${comment('        ', feeNotes(f))}
        DoctorFee(
            ${kotlin(f.feeCode)}, ${kotlin(f.name)}, amountCents = ${f.amount.value}, confirmed = ${f.confirmedByDefault.value},
            rangeLowCents = ${f.range.lowest}, rangeHighCents = ${f.range.highest}, source = ${kotlin(f.source)},
            unconfirmedWords = ${kotlin(f.unconfirmed)}, confirmedWords = ${kotlin(f.confirmed)}, whoSets = ${kotlin(f.whoSets)}
        )`).join(',\n')}
    )
${comment('    ', [`${contract.nurseShareSetting}: ${share.note}`])}
    const val nurseShareSentence = ${kotlin(share.value)}
    const val casesWords = ${kotlin(contract.casesWords)}
    val sampleCases = listOf(
${contract.sampleCases.map(c => `        SignedCase(${kotlin(c.reviewRef)}, ${c.onDays})`).join(',\n')}
    )
    /* Rendered word for word, from packages/catalog/apis/money.json. */
    val refusals: Map<String, String> = mapOf(
${RENDERED_REFUSALS.map(id => `        ${kotlin(id)} to ${kotlin(statement(id))}`).join(',\n')}
    )
}
`;

 return [
  { path: 'apps/ios/MyThuso/Models/MoneyData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/MoneyData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitMoney()) {
  writeFileSync(file.path, file.content);
  console.log(`money → ${file.path}`);
 }
}
