/* Thuso Kit's registry, readings and wearable links, written out for two native apps by a machine.
 *
 * packages/catalog/devices.json holds the device classes, sources and sample qualities — each saying whether
 * it may carry clinical weight — the marks and what they mean, the health and calibration states, the recall
 * reasons, the wearable link's words, and the three settings. packages/catalog/apis/devices.json holds every
 * refusal sentence, resolved here so the sentence a route answers with and the sentence a phone shows are one
 * string. A wearable link's scope and each measure's unit are packages/catalog/records.json's, and the consent
 * version a link is made under is packages/catalog/consent.json's. The web reads all of them through
 * packages/engines/src/devices/domain; iOS and Android cannot read JSON at runtime, so the copy is generated
 * rather than typed and scripts/check-boundaries.mjs compares it on every build.
 *
 * WHAT A PHONE IS GIVEN TO DECIDE CLINICAL WEIGHT WITH. The flags, and nothing else: carriesClinicalWeight on a
 * class and a quality, simulated on a source. Each app's hand-written Devices model asks the same five questions
 * packages/engines/src/devices/domain/readings.ts carriesWeight() asks, and the build holds both to it. No
 * reference range is emitted, because whether a reading is concerning is the clinical governance board's.
 *
 * THE SETTINGS ARE DEFAULTS. An admin changes them on the web; neither app reaches a settings route, so both
 * use the defaults written here and say so in the sentence scripts/settings-defaults.mjs writes for every engine.
 *
 * Escaping: Swift needs its quotes escaped; Kotlin needs backslash, quote and $, because a lone $ starts a
 * template.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { settingDefault } from './settings-defaults.mjs';

const SOURCE = 'packages/catalog/devices.json';
const API = 'packages/catalog/apis/devices.json';
const RECORDS = 'packages/catalog/records.json';
const CONSENT = 'packages/catalog/consent.json';

const swift = value => {
 if (String(value).includes('\\')) throw new Error(`Cannot write ${JSON.stringify(value)} as a Swift literal here`);
 return `"${String(value).replace(/"/g, '\\"')}"`;
};
const kotlin = value => `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const camel = key => key.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

const banner = () => [
 `Generated by scripts/emit-devices.mjs from ${SOURCE}, ${API}, ${RECORDS} and ${CONSENT}.`,
 'Do not edit by hand — run `npm run devices`. The build fails if this file and its sources disagree,',
 'so an edit here is lost rather than merely wrong.',
 '',
 'A device class, a source and a sample quality each say whether a reading may carry clinical weight. A',
 'consumer device never does, and a reading without weight is never announced to anybody. The three',
 'settings are PROPOSALS an admin changes on the web; this app has no admin surface and uses them as written.',
 'Nothing here contacts an instrument, a phone\'s health store or a watch.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function emitDevices(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const api = JSON.parse(readFileSync(root + API, 'utf8'));
 const records = JSON.parse(readFileSync(root + RECORDS, 'utf8'));
 const consent = JSON.parse(readFileSync(root + CONSENT, 'utf8'));

 const stale = settingDefault(SOURCE, contract, 'stale-after-minutes');
 const due = settingDefault(SOURCE, contract, 'calibration-due-days');
 const deposit = settingDefault(SOURCE, contract, 'kit-deposit');

 const purpose = consent.purposes.find(p => p.id === contract.wearableLinks.consentPurpose);
 if (!purpose) throw new Error(`${CONSENT} has no purpose "${contract.wearableLinks.consentPurpose}", which a wearable link asks for.`);
 const consentVersion = Math.max(...purpose.versions.map(v => v.version));

 /* Every refusal the engine or a live route declares, once by id. Two routes that share an id share its words. */
 const refusals = new Map();
 for (const r of [...api.refusals, ...api.routes.filter(route => !route.withdrawn).flatMap(route => route.refusals)]) {
  const seen = refusals.get(r.id);
  if (seen && seen.statement !== r.statement) throw new Error(`${API} declares "${r.id}" in two different sentences.`);
  refusals.set(r.id, { id: r.id, status: r.status, statement: r.statement });
 }
 for (const cls of contract.deviceClasses) if (typeof cls.carriesClinicalWeight !== 'boolean') throw new Error(`${SOURCE} class "${cls.id}" does not say whether it carries clinical weight.`);
 if (contract.deviceClasses.find(c => c.id === 'consumer')?.carriesClinicalWeight !== false) throw new Error(`${SOURCE} no longer declares a consumer device without clinical weight. That is the refusal this engine exists for, and it is not generated into a phone in any other form.`);

 const measures = records.observations.measures.map(m => ({ id: m.id, unit: m.unit }));
 const strings = block => Object.entries(block).filter(([key, value]) => typeof value === 'string' && !key.startsWith('_'));
 const texts = [
  ['NurseText', strings(contract.screens.nurse)],
  ['OpsText', strings(contract.screens.ops)],
  ['WearableText', [...strings(contract.wearableLinks).filter(([key]) => !['consentPurpose', 'scopeFrom'].includes(key)), ['stateLabel', contract.wearableLinks.state.label], ['stateId', contract.wearableLinks.state.id],
   /* The consent's name and what withdrawing does. Never its wording: a recorded consent is a fingerprint of those
      exact words, and scripts/check-boundaries.mjs allows them in the two readers that build the fingerprint and nowhere else. */
   ['consentName', purpose.name], ['consentWithdrawal', purpose.withdrawal]]],
  ['KitText', strings(contract.kits)],
  ['RuleText', [
   ['whereValuesLive', contract.whereValuesLive.sentence], ['clinicalWeight', contract.clinicalWeight.statement], ['neverPublishes', contract.clinicalWeight.neverPublishes],
   ['marksMean', contract.marksMean], ['staleMeans', contract.health.staleMeans], ['calibrationNeverRefuses', contract.health.calibrationNeverRefuses],
   ['recallEffectiveFrom', contract.recall.effectiveFrom], ['recallNeverUndone', contract.recall.neverUndone], ['preview', contract.screens.preview]
  ]]
 ];
 const choices = [
  ['healthStates', contract.health.states], ['calibrationStates', contract.health.calibration], ['recallReasons', contract.recall.reasons],
  ['lossReasons', contract.kits.lossReasons], ['kitStates', contract.kits.states], ['intendedUses', contract.intendedUses], ['consentStates', contract.consentStates]
 ];

 const swiftFile = `${banner()}

import Foundation

extension Devices {
    /// ${stale.note}
    static let staleAfterMinutes = ${stale.value}
    /// ${due.note}
    static let calibrationDueDays = ${due.value}
    /// ${deposit.note}
    static let kitDepositCents = ${deposit.value}
    /// The wearable-readings consent version in force, from ${CONSENT}.
    static let wearableConsentVersion = ${consentVersion}

    static let deviceClasses: [DeviceClassSpec] = [
${contract.deviceClasses.map(c => `        .init(id: ${swift(c.id)}, label: ${swift(c.label)}, carriesClinicalWeight: ${c.carriesClinicalWeight})`).join(',\n')}
    ]
    static let sources: [DeviceSourceSpec] = [
${contract.sources.map(s => `        .init(id: ${swift(s.id)}, label: ${swift(s.label)}, simulated: ${s.simulated}, classes: [${s.classes.map(swift).join(', ')}])`).join(',\n')}
    ]
    static let qualities: [DeviceQualitySpec] = [
${contract.qualities.map(q => `        .init(id: ${swift(q.id)}, label: ${swift(q.label)}, carriesClinicalWeight: ${q.carriesClinicalWeight})`).join(',\n')}
    ]
    static let marks: [DeviceMarkSpec] = [
${contract.marks.map(m => `        .init(id: ${swift(m.id)}, label: ${swift(m.label)}, sentence: ${swift(m.sentence)})`).join(',\n')}
    ]
    static let platforms: [WearablePlatformSpec] = [
${contract.wearableLinks.platforms.map(p => `        .init(id: ${swift(p.id)}, name: ${swift(p.name)}, phone: ${swift(p.phone)})`).join(',\n')}
    ]
    /// Each measure a reading or a wearable link may name, and the unit it is recorded in, from ${RECORDS}.
    static let measureUnits: [(id: String, unit: String)] = [
${measures.map(m => `        (id: ${swift(m.id)}, unit: ${swift(m.unit)})`).join(',\n')}
    ]

${choices.map(([name, list]) => `    static let ${name}: [DevicesChoice] = [
${list.map(c => `        .init(id: ${swift(c.id)}, label: ${swift(c.label)})`).join(',\n')}
    ]`).join('\n')}

${texts.map(([name, entries]) => `    enum ${name} {
${entries.map(([key, value]) => `        static let ${camel(key)} = ${swift(value)}`).join('\n')}
    }`).join('\n\n')}

    static let refusals: [DevicesRefusal] = [
${[...refusals.values()].map(r => `        .init(id: ${swift(r.id)}, status: ${r.status}, statement: ${swift(r.statement)})`).join(',\n')}
    ]
}
`;

 const kotlinFile = `${banner()}

package za.co.mythuso.model

object DevicesData {
    /** ${stale.note} */
    const val staleAfterMinutes = ${stale.value}
    /** ${due.note} */
    const val calibrationDueDays = ${due.value}
    /** ${deposit.note} */
    const val kitDepositCents = ${deposit.value}
    /** The wearable-readings consent version in force, from ${CONSENT}. */
    const val wearableConsentVersion = ${consentVersion}

    val deviceClasses = listOf(
${contract.deviceClasses.map(c => `        DeviceClassSpec(${kotlin(c.id)}, ${kotlin(c.label)}, ${c.carriesClinicalWeight})`).join(',\n')}
    )
    val sources = listOf(
${contract.sources.map(s => `        DeviceSourceSpec(${kotlin(s.id)}, ${kotlin(s.label)}, ${s.simulated}, listOf(${s.classes.map(kotlin).join(', ')}))`).join(',\n')}
    )
    val qualities = listOf(
${contract.qualities.map(q => `        DeviceQualitySpec(${kotlin(q.id)}, ${kotlin(q.label)}, ${q.carriesClinicalWeight})`).join(',\n')}
    )
    val marks = listOf(
${contract.marks.map(m => `        DeviceMarkSpec(${kotlin(m.id)}, ${kotlin(m.label)}, ${kotlin(m.sentence)})`).join(',\n')}
    )
    val platforms = listOf(
${contract.wearableLinks.platforms.map(p => `        WearablePlatformSpec(${kotlin(p.id)}, ${kotlin(p.name)}, ${kotlin(p.phone)})`).join(',\n')}
    )
    /** Each measure a reading or a wearable link may name, and the unit it is recorded in, from ${RECORDS}. */
    val measureUnits = listOf(
${measures.map(m => `        ${kotlin(m.id)} to ${kotlin(m.unit)}`).join(',\n')}
    )

${choices.map(([name, list]) => `    val ${name} = listOf(
${list.map(c => `        DevicesChoice(${kotlin(c.id)}, ${kotlin(c.label)})`).join(',\n')}
    )`).join('\n')}

${texts.map(([name, entries]) => `    object ${name} {
${entries.map(([key, value]) => `        const val ${camel(key)} = ${kotlin(value)}`).join('\n')}
    }`).join('\n\n')}

    val refusals = listOf(
${[...refusals.values()].map(r => `        DevicesRefusal(${kotlin(r.id)}, ${r.status}, ${kotlin(r.statement)})`).join(',\n')}
    )
}
`;

 return [
  { path: 'apps/ios/MyThuso/Models/DevicesData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/DevicesData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitDevices()) {
  writeFileSync(file.path, file.content);
  console.log(`devices → ${file.path}`);
 }
}
