/* The care plans and their monthly prices, written out for two native apps, by a machine.

   Both apps typed the five plans into their plans screens — "R199 / month", "R249 / month" — beside
   the same numbers in packages/catalog/business-model.json. The web had been moved off its copy in
   September; the phones never were. On 14 September 2026 the founder replaced the single R249 Thuso
   Mom with MyThuso for Mom at three prices, and a change like that is exactly the one a typed copy
   survives: the web would have said R399 and both phones R249.

   So the subscriptions come from the business model and the three tiers from
   packages/catalog/mom-plans.json, and nothing a phone shows about a plan's price is typed there. The
   business model's `mom` row has no price of its own — it names the tier file — and this generator
   refuses a row that names any other.

   Since 15 September 2026 the plan's name, each tier's name, whether tiers stack, Plus's urgent
   call-outs, what priority SOS means and whether WhatsApp is used after a visit are Money's settings in
   packages/catalog/money.json. A phone has no admin surface, so it is given each default through
   scripts/settings-defaults.mjs, with the sentence saying whether anybody decided it, and the plan is
   read into mom-plans.json's words by the same code the web and the engine use —
   packages/engines/src/money/domain/settings.ts — so "One urgent nurse call-out a month" and
   "Everything in Essential" are worked out, never typed, on all three platforms.

   What is not written here is whether anything is real. Each inclusion carries the id of the
   capability it depends on, and the phones ask their generated capabilities table for the sentence,
   the same way the web does. A notice copied into this file would outlive the day the capability is
   connected.

   Escaping is the hazard, and the two languages disagree about it:
     - Swift needs only its quotes escaped.
     - Kotlin needs backslash, quote and dollar escaped, because a lone $ starts a string template. */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { settingDefault } from './settings-defaults.mjs';
import { planSettingKeys, planTermsFrom } from '../packages/engines/src/money/domain/settings.ts';

const SOURCE = 'packages/catalog/mom-plans.json';
const MODEL = 'packages/catalog/business-model.json';
const SETTINGS = 'packages/catalog/money.json';

const swift = value => {
 if (value.includes('\\')) throw new Error(`Cannot write ${JSON.stringify(value)} as a Swift literal here`);
 return `"${value.replace(/"/g, '\\"')}"`;
};
const kotlin = value => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const optSwift = value => (value ? swift(value) : 'nil');
const optKotlin = value => (value ? kotlin(value) : 'null');

const banner = () => [
 `Generated by scripts/emit-plans.mjs from ${SOURCE}, ${MODEL} and Money's settings in ${SETTINGS}.`,
 'Do not edit by hand — run `npm run plans`. The build fails if this file and its sources disagree,',
 'so an edit here is lost rather than merely wrong.',
 '',
 'Every monthly price a plans screen shows is below, and none is typed in a screen. MyThuso for Mom',
 'has three, from the Master Blueprint v4, and its business-model row has none of its own. Each',
 'inclusion names the capability it depends on; the sentence shown beside it is read from the',
 'generated capabilities table, so it disappears when that capability is connected and not before.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function emitPlans(root = '') {
 const plan = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const model = JSON.parse(readFileSync(root + MODEL, 'utf8'));
 const money = JSON.parse(readFileSync(root + SETTINGS, 'utf8'));

 for (const s of model.subscriptions) {
  if (s.tiersIn && s.tiersIn !== 'mom-plans.json') throw new Error(`Subscription "${s.id}" names tiers in ${s.tiersIn}; the only tier file is ${SOURCE}.`);
  if (s.tiersIn && s.price !== null) throw new Error(`Subscription "${s.id}" names a tier file and still carries a price of ${s.price}. One of the two is a second copy.`);
 }
 /* Every setting the plan reads, as its default with the sentence saying whether anybody decided it. */
 const defaults = planSettingKeys().map(key => ({ key, ...settingDefault(SETTINGS, money, key) }));
 const terms = planTermsFrom(Object.fromEntries(defaults.map(d => [d.key, d.value])), 1);
 /* The generator is the first reader of the contract, so it is the first place a missing field can be
    named — rather than a TypeError from the escaper with no field in it. */
 for (const t of terms.tiers) {
  if (!Number.isInteger(t.price)) throw new Error(`Tier "${t.id}" has no whole-rand price.`);
  for (const i of t.includes) if (!i.text || !i.capability) throw new Error(`Inclusion "${i.id}" on tier "${t.id}" has no text or names no capability.`);
 }
 const notes = indent => defaults.map(d => `${indent}// ${d.key}: ${d.note}`).join('\n');

 const swiftFile = `${banner()}

import Foundation

extension Plans {
    /// The business model's subscriptions. A row with \`tiered\` set is priced by its tiers below.
    static let subscriptions: [PlanSubscription] = [
${model.subscriptions.map(s => `        .init(id: ${swift(s.id)}, name: ${swift(s.name)}, price: ${s.price ?? 'nil'}, phase: ${s.phase},
              includes: ${swift(s.includes)}, tiered: ${Boolean(s.tiersIn)})`).join(',\n')}
    ]

    // MyThuso for Mom as Money's settings read it by default. Neither app has an admin surface:
${notes('    ')}
    static let mom = MomPlan(
        id: ${swift(plan.id)},
        name: ${swift(terms.name)},
        payerHeadline: ${swift(plan.payer.headline)},
        payerStatement: ${swift(plan.payer.statement)},
        tiers: [
${terms.tiers.map(t => `            .init(id: ${swift(t.id)}, name: ${swift(t.name)}, price: ${t.price}, phase: ${t.phase}, cadence: ${swift(t.cadence)},
                  inherits: ${optSwift(t.inherits)}, includes: [
${t.includes.map(i => `                .init(id: ${swift(i.id)}, text: ${swift(i.text)}, capability: ${swift(i.capability)},
                      device: ${optSwift(i.device)}, detail: ${optSwift(i.detail)})`).join(',\n')}
            ])`).join(',\n')}
        ],
        addOnsStatement: ${swift(plan.addOns.statement)},
        addOns: [
${plan.addOns.items.map(a => `            .init(id: ${swift(a.id)}, name: ${swift(a.name)})`).join(',\n')}
        ],
        splittingStatement: ${swift(plan.splitting.statement)},
        splittingCapability: ${swift(plan.splitting.capability)},
        refusals: [
${plan.refusals.map(r => `            .init(id: ${swift(r.id)}, sentence: ${swift(r.sentence)})`).join(',\n')}
        ])
}
`;

 const kotlinFile = `${banner()}

package za.co.mythuso.model

/** The business model's subscriptions. A row with \`tiered\` set is priced by its tiers below. */
val planSubscriptions = listOf(
${model.subscriptions.map(s => `    PlanSubscription(${kotlin(s.id)}, ${kotlin(s.name)}, ${s.price ?? 'null'}, ${s.phase},
        ${kotlin(s.includes)}, ${Boolean(s.tiersIn)})`).join(',\n')}
)

// MyThuso for Mom as Money's settings read it by default. Neither app has an admin surface:
${notes('')}
val momPlan = MomPlan(
    id = ${kotlin(plan.id)},
    name = ${kotlin(terms.name)},
    payerHeadline = ${kotlin(plan.payer.headline)},
    payerStatement = ${kotlin(plan.payer.statement)},
    tiers = listOf(
${terms.tiers.map(t => `        MomTier(${kotlin(t.id)}, ${kotlin(t.name)}, ${t.price}, ${t.phase}, ${kotlin(t.cadence)}, ${optKotlin(t.inherits)}, listOf(
${t.includes.map(i => `            MomInclusion(${kotlin(i.id)}, ${kotlin(i.text)}, ${kotlin(i.capability)},
                ${optKotlin(i.device)}, ${optKotlin(i.detail)})`).join(',\n')}
        ))`).join(',\n')}
    ),
    addOnsStatement = ${kotlin(plan.addOns.statement)},
    addOns = listOf(
${plan.addOns.items.map(a => `        MomAddOn(${kotlin(a.id)}, ${kotlin(a.name)})`).join(',\n')}
    ),
    splittingStatement = ${kotlin(plan.splitting.statement)},
    splittingCapability = ${kotlin(plan.splitting.capability)},
    refusals = listOf(
${plan.refusals.map(r => `        MomRefusal(${kotlin(r.id)}, ${kotlin(r.sentence)})`).join(',\n')}
    )
)
`;

 return [
  { path: 'apps/ios/MyThuso/Models/PlansData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/PlansData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 if (!existsSync(SOURCE)) throw new Error(`${SOURCE} is missing; run this from the repository root.`);
 for (const file of emitPlans()) {
  writeFileSync(file.path, file.content);
  console.log(`plans → ${file.path}`);
 }
}
