/* Group payers, written out for two native apps by a machine.

   packages/catalog/groups.json holds what a group is, the two ways a member may let it read what it
   paid for her, the states an invitation moves through and the words each side reads. The phones draw
   the member's half — an invitation, her choice, and leaving — so that is what this writes into
   GroupsData.swift and GroupsData.kt, with the refusals a member can meet read from
   packages/catalog/apis/money.json by id, and the monthly limit from Money's setting through
   scripts/settings-defaults.mjs.

   WHAT IS NOT WRITTEN. The treasurer's screen: a group's own view is a back-office reading of many
   people's payments, and neither phone has a door onto it. Nor any amount of its own — a phone shows
   the limit, which is a setting's default, and nothing else with a currency on it.

   Escaping: Swift needs its quotes escaped; Kotlin needs backslash, quote and dollar. */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { settingDefault } from './settings-defaults.mjs';

const SOURCE = 'packages/catalog/groups.json';
const API = 'packages/catalog/apis/money.json';
const MONEY = 'packages/catalog/money.json';
/* The three a member meets on a phone: agreeing is hers, an employer is never shown her days, and no group's money is
   held here. Each is read from the route that declares it rather than typed. */
const RENDERED_REFUSALS = ['only-the-member-agrees', 'employer-sees-health', 'group-holds-money'];

const swift = value => {
 if (String(value).includes('\\')) throw new Error(`Cannot write ${JSON.stringify(value)} as a Swift literal here`);
 return `"${String(value).replace(/"/g, '\\"')}"`;
};
const kotlin = value => `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;

const banner = () => [
 `Generated by scripts/emit-groups.mjs from ${SOURCE}, ${API} and ${MONEY}.`,
 'Do not edit by hand — run `npm run groups`. The build fails if this file and its sources disagree,',
 'so an edit here is lost rather than merely wrong.',
 '',
 'The member\'s half of a group that pays for its members: an invitation, the ways she may let it read what',
 'it paid for her, and the refusals she can meet. No group exists, nobody is invited and nothing is charged.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function emitGroups(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const api = JSON.parse(readFileSync(root + API, 'utf8'));
 const money = JSON.parse(readFileSync(root + MONEY, 'utf8'));
 const statement = id => {
  const found = [...api.refusals, ...api.routes.flatMap(r => r.refusals)].find(r => r.id === id);
  if (!found) throw new Error(`${API} has no refusal "${id}", which a native group screen renders.`);
  return found.statement;
 };
 const limit = settingDefault(MONEY, money, contract.settings.monthlyLimit);
 const member = contract.screen.member;
 const kinds = contract.kinds;
 const details = contract.lineDetails;
 const states = contract.states;
 const refusalName = id => id.split('-').map((word, i) => (i ? word[0].toUpperCase() + word.slice(1) : word)).join('');

 const swiftFile = `${banner()}

import Foundation

enum GroupsData {
    /// The most a group's account is charged for one member in a calendar month, in cents.
    /// ${contract.settings.monthlyLimit}: ${limit.note}
    static let memberMonthlyLimitCents = ${limit.value}
    static let previewGroupName = ${swift(contract.preview.groupName)}
    static let noPooledMoney = ${swift(contract.noPooledMoney.statement)}

    static let kinds: [GroupKind] = [
${kinds.map(k => `        .init(id: ${swift(k.id)}, name: ${swift(k.name)}, lineDetails: [${k.lineDetails.map(swift).join(', ')}])`).join(',\n')}
    ]

    static let lineDetails: [GroupLineDetail] = [
${details.map(d => `        .init(id: ${swift(d.id)}, name: ${swift(d.name)}, detail: ${swift(d.detail)})`).join(',\n')}
    ]

    static let states: [GroupState] = [
${states.map(s => `        .init(id: ${swift(s.id)}, name: ${swift(s.name)}, memberWords: ${swift(s.memberWords)})`).join(',\n')}
    ]

    enum Words {
        static let heading = ${swift(member.heading)}
        static let intro = ${swift(member.intro)}
        static let choose = ${swift(member.choose)}
        static let agree = ${swift(member.agree)}
        static let leave = ${swift(member.leave)}
        static let limit = ${swift(member.limit)}
        static let payWith = ${swift(member.payWith)}
        static let paid = ${swift(member.paid)}
        static let employerOnly = ${swift(member.employerOnly)}
        static let preview = ${swift(contract.screen.preview)}
    }

    /// The refusals a member can meet, in ${API}'s own words.
${RENDERED_REFUSALS.map(id => `    static let ${refusalName(id)} = ${swift(statement(id))}`).join('\n')}
}
`;

 const kotlinFile = `${banner()}

package za.co.mythuso.model

object GroupsData {
    /** The most a group's account is charged for one member in a calendar month, in cents.
     *  ${contract.settings.monthlyLimit}: ${limit.note} */
    const val memberMonthlyLimitCents = ${limit.value}
    const val previewGroupName = ${kotlin(contract.preview.groupName)}
    const val noPooledMoney = ${kotlin(contract.noPooledMoney.statement)}

    val kinds = listOf(
${kinds.map(k => `        GroupKind(${kotlin(k.id)}, ${kotlin(k.name)}, listOf(${k.lineDetails.map(kotlin).join(', ')}))`).join(',\n')}
    )

    val lineDetails = listOf(
${details.map(d => `        GroupLineDetail(${kotlin(d.id)}, ${kotlin(d.name)}, ${kotlin(d.detail)})`).join(',\n')}
    )

    val states = listOf(
${states.map(s => `        GroupState(${kotlin(s.id)}, ${kotlin(s.name)}, ${kotlin(s.memberWords)})`).join(',\n')}
    )

    object Words {
        const val heading = ${kotlin(member.heading)}
        const val intro = ${kotlin(member.intro)}
        const val choose = ${kotlin(member.choose)}
        const val agree = ${kotlin(member.agree)}
        const val leave = ${kotlin(member.leave)}
        const val limit = ${kotlin(member.limit)}
        const val payWith = ${kotlin(member.payWith)}
        const val paid = ${kotlin(member.paid)}
        const val employerOnly = ${kotlin(member.employerOnly)}
        const val preview = ${kotlin(contract.screen.preview)}
    }

    /** The refusals a member can meet, in ${API}'s own words. */
${RENDERED_REFUSALS.map(id => `    const val ${refusalName(id)} = ${kotlin(statement(id))}`).join('\n')}
}
`;

 return [
  { path: 'apps/ios/MyThuso/Models/GroupsData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/GroupsData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 if (!existsSync(SOURCE)) throw new Error(`${SOURCE} is missing; run this from the repository root.`);
 for (const file of emitGroups()) {
  writeFileSync(file.path, file.content);
  console.log(`groups → ${file.path}`);
 }
}
