/* The emergency pathway, written out for two native apps, by a machine.

   Everything about Thuso SOS that a person reads — the three real South African emergency numbers,
   the eight conditions that end the questions, the refusals, the failure screens and the sentences
   about what standing down does — lives in packages/catalog/sos.json. The web reads that file. iOS
   and Android cannot, and should not, for the reason the vetting generator gives.

   On this feature the argument for generating rather than transcribing is stronger than anywhere
   else in the repository. An ambulance number typed by hand into a Swift file and a Kotlin file is
   an ambulance number that can be typed wrong twice, on the one screen where a wrong digit is not a
   cosmetic defect. Nothing below is typed. The check in scripts/check-boundaries.mjs then compares
   this output against what is on disk on every build, and separately asserts that the numbers are
   the ones South Africa actually uses.

   The other thing resolved here is the target. "Under 45 minutes" is not written down in sos.json
   at all: 45 is the duration of the `sos` row in packages/catalog/services.json, the same row the
   patient is quoted R398 from, and the sentences that need it write {target}. It is filled in here
   at generation time and at runtime on the web, so the promise on the screen and the service being
   sold cannot come apart. The price and the nurse's share come from the same row; Thuso Alert's
   monthly price comes from packages/catalog/business-model.json. There is nowhere in the contract
   to type any of the four.

   Escaping is the hazard, and the two languages disagree about it:
     - Swift needs only its quotes escaped.
     - Kotlin needs backslash, quote and dollar escaped, because a lone backslash is an escape and a
       lone $ starts a string template.
   The sentences carry en-dashes and curly quotes; those are simply UTF-8 and need nothing. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/catalog/sos.json';
const CATALOGUE = 'packages/catalog/services.json';
const MODEL = 'packages/catalog/business-model.json';

const swift = value => {
 if (value.includes('\\')) throw new Error(`Cannot write ${JSON.stringify(value)} as a Swift literal here`);
 return `"${value.replace(/"/g, '\\"')}"`;
};
const kotlin = value => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const listSwift = values => `[${values.map(swift).join(', ')}]`;
const listKotlin = values => `listOf(${values.map(kotlin).join(', ')})`;

const banner = () => [
 `Generated by scripts/emit-sos.mjs from ${SOURCE}, ${CATALOGUE} and ${MODEL}.`,
 'Do not edit by hand — run `npm run sos`. The build fails if this file and its sources disagree,',
 'so an edit here is lost rather than merely wrong.',
 '',
 'The emergency numbers below are the real South African ones and are not typed twice: they are',
 'written from the contract, and scripts/check-boundaries.mjs asserts that they are still 10177,',
 '112 and 10111 on every build. A wrong digit on this screen is not a cosmetic defect.',
 '',
 'The under-45-minute target, the price of the visit and the nurse\'s share are the `sos` row of the',
 'service catalogue, resolved when this file was written. Thuso Alert\'s monthly price is the',
 '`alert` subscription in the business model. None of the four is a number anybody typed.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function emitSos(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const catalogue = JSON.parse(readFileSync(root + CATALOGUE, 'utf8'));
 const model = JSON.parse(readFileSync(root + MODEL, 'utf8'));

 const service = catalogue.find(s => s.id === 'sos');
 if (!service) throw new Error('packages/catalog/services.json has no `sos` row, so the emergency pathway has no service to describe');
 const alert = model.subscriptions.find(s => s.id === 'alert');
 if (!alert) throw new Error('packages/catalog/business-model.json has no `alert` subscription, so Thuso Alert has no price to be honest about');
 /* The generator is the first reader of the contract, so it is the first place a missing sentence
    can be named. Without this a failure that has lost its "instead" reaches a string escaper and
    comes back as a TypeError with no field in it — true, and useless to whoever has to fix it. */
 const need = (object, field, what) => {
  if (typeof object?.[field] !== 'string' || !object[field]) throw new Error(`${what} has no ${field}. ${SOURCE} is not complete enough to write two native apps from.`);
 };
 for (const failure of contract.failures) need(failure, 'instead', `Failure "${failure.id}"`);
 for (const reason of contract.standDown.reasons) {
  need(reason, 'nurseIsTold', `Stand-down reason "${reason.id}"`);
  need(reason, 'recorded', `Stand-down reason "${reason.id}"`);
 }
 for (const number of contract.emergency.numbers) need(number, 'whenToUse', `Emergency number ${number.number}`);
 /* The one substitution in the file. A sentence that needs the target writes {target}; there is no
    other token, and a stray one would show up on the screen rather than being silently dropped. */
 const fill = text => text.replace(/\{target\}/g, String(service.duration));

 const e = contract.emergency, f = contract.redFlags, r = contract.routing;
 const t = contract.target, c = contract.coverage, s = contract.standDown, a = contract.alert, rec = contract.record;

 const swiftFile = `${banner()}

import Foundation

extension Sos {
    /// The catalogue's own numbers for the \`sos\` service and the \`alert\` subscription. Read, never typed.
    static let targetMinutes = ${service.duration}
    static let visitPrice = ${service.price}
    static let visitNurseShare = ${service.nurseShare}
    static let visitPhase = ${service.phase}
    static let alertMonthly = ${alert.price}
    static let alertPhase = ${alert.phase}

    /* First on the screen, and first in this file. Every number below is a real South African
       emergency number; nothing in the app dials any of them. */
    static let emergency = SosEmergency(
        headline: ${swift(e.headline)},
        lead: ${swift(e.lead)},
        notAnAmbulance: ${swift(e.notAnAmbulance)},
        previewNote: ${swift(e.previewNote)},
        whyFirst: ${swift(e.whyFirst)},
        numbers: [
${e.numbers.map(n => `            .init(id: ${swift(n.id)}, number: ${swift(n.number)}, name: ${swift(n.name)},
                  detail: ${swift(n.detail)},
                  whenToUse: ${swift(n.whenToUse)})`).join(',\n')}
        ])

    /* Any one of these ends the questions. The list is closed on purpose: it is short enough to
       read while frightened, and every entry is a condition where minutes decide the outcome. */
    static let redFlags = SosRedFlags(
        prompt: ${swift(f.prompt)},
        help: ${swift(f.help)},
        noneLabel: ${swift(f.noneLabel)},
        endsTheQuestions: ${swift(f.endsTheQuestions)},
        conditions: [
${f.conditions.map(x => `            .init(id: ${swift(x.id)}, name: ${swift(x.name)}, detail: ${swift(x.detail)})`).join(',\n')}
        ])

    static let routing = SosRouting(
        isNotTriage: ${swift(r.isNotTriage)},
        noAlgorithm: ${swift(r.noAlgorithm)},
        questions: [
${r.questions.map(q => `            .init(id: ${swift(q.id)}, prompt: ${swift(q.prompt)}, help: ${swift(q.help)}, kind: ${swift(q.kind)})`).join(',\n')}
        ])

    static let outcomes: [SosOutcome] = [
${contract.outcomes.map(o => `        .init(id: ${swift(o.id)}, name: ${swift(o.name)}, headline: ${swift(o.headline)},
              detail: ${swift(o.detail)}, offersVisit: ${o.offersVisit})`).join(',\n')}
    ]

    static let target = SosTarget(
        title: ${swift(fill(t.title))},
        statement: ${swift(fill(t.statement))},
        whenItCannotBeMet: ${swift(fill(t.whenItCannotBeMet))},
        arrivalUnknown: ${swift(fill(t.arrivalUnknown))},
        estimateIsNotTheTarget: ${swift(fill(t.estimateIsNotTheTarget))})

    static let coverage = SosCoverage(
        statement: ${swift(c.statement)},
        areas: ${listSwift(c.areas)},
        hours: SosHours(opensAt: ${swift(c.hours.opensAt)}, closesAt: ${swift(c.hours.closesAt)},
                        days: ${swift(c.hours.days)}, note: ${swift(c.hours.note)}),
        honestNote: ${swift(c.honestNote)})

    static let standDown = SosStandDown(
        title: ${swift(s.title)},
        statement: ${swift(s.statement)},
        reasons: [
${s.reasons.map(x => `            .init(id: ${swift(x.id)}, label: ${swift(x.label)},
                  nurseIsTold: ${swift(x.nurseIsTold)},
                  recorded: ${swift(x.recorded)})`).join(',\n')}
        ],
        noAnswerRule: ${swift(s.noAnswerRule)},
        chargeRule: ${swift(s.chargeRule)},
        nurseNote: ${swift(s.nurseNote)})

    /* Four ways a panic button fails and one way vetting stops it. Each carries what to do
       instead, because a failure screen without one is a dead end wearing an apology. */
    static let failures: [SosFailure] = [
${contract.failures.map(x => `        .init(id: ${swift(x.id)}, name: ${swift(x.name)}, what: ${swift(x.what)},
              instead: ${swift(x.instead)})`).join(',\n')}
    ]

    static let alert = SosAlert(
        name: ${swift(a.name)},
        what: ${swift(a.what)},
        phaseNote: ${swift(a.phaseNote)},
        honesty: [
${a.honesty.map(x => `            .init(id: ${swift(x.id)}, sentence: ${swift(x.sentence)})`).join(',\n')}
        ],
        notCover: ${swift(a.notCover)})

    static let record = SosRecord(
        title: ${swift(rec.title)},
        statement: ${swift(rec.statement)},
        kept: [
${rec.kept.map(x => `            ${swift(x)}`).join(',\n')}
        ],
        notKept: [
${rec.notKept.map(x => `            ${swift(x)}`).join(',\n')}
        ])

    /* Rendered word for word. A rule paraphrased on one platform is a different promise on that
       platform, which is the whole reason these live in one file. */
    static let rules: [SosRule] = [
${contract.rules.map(x => `        .init(id: ${swift(x.id)}, title: ${swift(fill(x.title))}, sentence: ${swift(fill(x.sentence))})`).join(',\n')}
    ]

    static let refusals: [SosRefusal] = [
${contract.refusals.map(x => `        .init(id: ${swift(x.id)}, sentence: ${swift(x.sentence)})`).join(',\n')}
    ]
}
`;

 const kotlinFile = `${banner()}

package za.co.mythuso.model

/** The catalogue's own numbers for the \`sos\` service and the \`alert\` subscription. Read, never typed. */
const val sosTargetMinutes = ${service.duration}
const val sosVisitPrice = ${service.price}
const val sosVisitNurseShare = ${service.nurseShare}
const val sosVisitPhase = ${service.phase}
const val sosAlertMonthly = ${alert.price}
const val sosAlertPhase = ${alert.phase}

/* First on the screen, and first in this file. Every number below is a real South African emergency
   number; nothing in the app dials any of them. */
val sosEmergency = SosEmergency(
    ${kotlin(e.headline)},
    ${kotlin(e.lead)},
    ${kotlin(e.notAnAmbulance)},
    ${kotlin(e.previewNote)},
    ${kotlin(e.whyFirst)},
    listOf(
${e.numbers.map(n => `        SosNumber(${kotlin(n.id)}, ${kotlin(n.number)}, ${kotlin(n.name)},
            ${kotlin(n.detail)},
            ${kotlin(n.whenToUse)})`).join(',\n')}
    )
)

/* Any one of these ends the questions. The list is closed on purpose: it is short enough to read
   while frightened, and every entry is a condition where minutes decide the outcome. */
val sosRedFlags = SosRedFlags(
    ${kotlin(f.prompt)},
    ${kotlin(f.help)},
    ${kotlin(f.noneLabel)},
    ${kotlin(f.endsTheQuestions)},
    listOf(
${f.conditions.map(x => `        SosCondition(${kotlin(x.id)}, ${kotlin(x.name)}, ${kotlin(x.detail)})`).join(',\n')}
    )
)

val sosRouting = SosRouting(
    ${kotlin(r.isNotTriage)},
    ${kotlin(r.noAlgorithm)},
    listOf(
${r.questions.map(q => `        SosQuestion(${kotlin(q.id)}, ${kotlin(q.prompt)}, ${kotlin(q.help)}, ${kotlin(q.kind)})`).join(',\n')}
    )
)

val sosOutcomes = listOf(
${contract.outcomes.map(o => `    SosOutcome(${kotlin(o.id)}, ${kotlin(o.name)}, ${kotlin(o.headline)},
        ${kotlin(o.detail)}, ${o.offersVisit})`).join(',\n')}
)

val sosTarget = SosTarget(
    ${kotlin(fill(t.title))},
    ${kotlin(fill(t.statement))},
    ${kotlin(fill(t.whenItCannotBeMet))},
    ${kotlin(fill(t.arrivalUnknown))},
    ${kotlin(fill(t.estimateIsNotTheTarget))}
)

val sosCoverage = SosCoverage(
    ${kotlin(c.statement)},
    ${listKotlin(c.areas)},
    SosHours(${kotlin(c.hours.opensAt)}, ${kotlin(c.hours.closesAt)}, ${kotlin(c.hours.days)},
        ${kotlin(c.hours.note)}),
    ${kotlin(c.honestNote)}
)

val sosStandDown = SosStandDown(
    ${kotlin(s.title)},
    ${kotlin(s.statement)},
    listOf(
${s.reasons.map(x => `        SosStandDownReason(${kotlin(x.id)}, ${kotlin(x.label)},
            ${kotlin(x.nurseIsTold)},
            ${kotlin(x.recorded)})`).join(',\n')}
    ),
    ${kotlin(s.noAnswerRule)},
    ${kotlin(s.chargeRule)},
    ${kotlin(s.nurseNote)}
)

/* Four ways a panic button fails and one way vetting stops it. Each carries what to do instead,
   because a failure screen without one is a dead end wearing an apology. */
val sosFailures = listOf(
${contract.failures.map(x => `    SosFailure(${kotlin(x.id)}, ${kotlin(x.name)}, ${kotlin(x.what)},
        ${kotlin(x.instead)})`).join(',\n')}
)

val sosAlert = SosAlert(
    ${kotlin(a.name)},
    ${kotlin(a.what)},
    ${kotlin(a.phaseNote)},
    listOf(
${a.honesty.map(x => `        SosAlertNote(${kotlin(x.id)}, ${kotlin(x.sentence)})`).join(',\n')}
    ),
    ${kotlin(a.notCover)}
)

val sosRecord = SosRecord(
    ${kotlin(rec.title)},
    ${kotlin(rec.statement)},
    listOf(
${rec.kept.map(x => `        ${kotlin(x)}`).join(',\n')}
    ),
    listOf(
${rec.notKept.map(x => `        ${kotlin(x)}`).join(',\n')}
    )
)

/* Rendered word for word. A rule paraphrased on one platform is a different promise on that
   platform, which is the whole reason these live in one file. */
val sosRules = listOf(
${contract.rules.map(x => `    SosRule(${kotlin(x.id)}, ${kotlin(fill(x.title))}, ${kotlin(fill(x.sentence))})`).join(',\n')}
)

val sosRefusals = listOf(
${contract.refusals.map(x => `    SosRefusal(${kotlin(x.id)}, ${kotlin(x.sentence)})`).join(',\n')}
)
`;

 return [
  { path: 'apps/ios/MyThuso/Models/SosData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/SosData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitSos()) {
  writeFileSync(file.path, file.content);
  console.log(`sos → ${file.path}`);
 }
}
