/* The locale table, written out for two native apps, by a machine.

   Localisation was the last big table in this repository still typed three times. The same shell
   strings existed as a TypeScript dictionary, a Swift dictionary and a Kotlin map, and the only
   thing holding them together was a check that asked whether each of the three files mentioned each
   locale code. That check cannot see a key translated on Android and forgotten on iOS, cannot see a
   locale carrying forty strings where another carries thirty-five, and cannot see two platforms
   disagreeing about what a word means — all three of which were true when this file was written:
   isiZulu called vetting `Ukuqinisekiswa` on iOS and `Ukuhlolwa` on Android, and `vettingApply` was
   "Apply to join" on one and "Start an application" on the other.

   packages/catalog/locales.json is the table now. The web reads it. iOS and Android cannot, and
   should not, for the reason the vetting generator gives: an app that parses JSON to draw a tab bar
   is a web app wearing a Compose hat. What comes out below is ordinary Swift and Kotlin source.

   Three things about this generator are decisions rather than plumbing.

   A key is emitted for a platform only if it names that platform in `surfaces`. The navigation
   labels are web-only because iOS and Android have a tab bar rather than a sidebar; the tab bar
   labels are on all three. So "every key in every platform" is not the invariant — "every key a
   platform claims, in every locale that claims its set" is, and check-boundaries.mjs enforces that
   against this file rather than against three others.

   A locale carries whole *sets*, not individual keys. isiXhosa carries the shell and not the hero
   banner, and that is written down rather than discovered: a missing key falls back to English, and
   a fallback nobody declared is indistinguishable from a mistake.

   And `|` becomes `\n`. The hero headline is one string with a line break in it; the web renders
   that break as a <br/> and native renders it as a newline. Rather than store the break twice, the
   contract stores the character the web wants and this generator writes the character SwiftUI and
   Compose want. It is the same latitude emit-teleconsult.mjs takes when it renames `where` to
   `place` because Swift has taken the word.

   Escaping is the hazard, and the two languages disagree about it:
     - Swift needs its quotes escaped, and the newline written as an escape rather than a real one.
     - Kotlin needs backslash, quote and dollar escaped.
   The strings carry ṱ, ḓ, en-dashes, middots and curly quotes; those are simply UTF-8 and need
   nothing, which is worth knowing rather than guessing at. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/catalog/locales.json';

/* The line break the hero headline carries. Stored as the character the web renders as a <br/>;
   written out as the character a SwiftUI Text and a Compose Text render as a new line. */
const nativeText = value => value.replace(/\|/g, '\n');

const swift = value => {
 if (value.includes('\\')) throw new Error(`Cannot write ${JSON.stringify(value)} as a Swift literal here`);
 return `"${nativeText(value).replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
};
const kotlin = value => `"${nativeText(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$').replace(/\n/g, '\\n')}"`;
const optSwift = value => (value === null || value === undefined ? 'nil' : swift(value));
const optKotlin = value => (value === null || value === undefined ? 'null' : kotlin(value));

const banner = () => [
 `Generated by scripts/emit-locales.mjs from ${SOURCE}.`,
 'Do not edit by hand — run `npm run locales`. The build fails if this file and the locale source',
 'disagree, so an edit here is lost rather than merely wrong.',
 '',
 'A locale carries whole sets of keys, and which sets it carries is declared in the source. A key',
 'it does not carry falls back to English rather than to a blank or to its own name.',
 '',
 'Every locale below except English is machine-drafted and has not been read by a person who speaks',
 'it. `reviewNotice` is the sentence that says so, and it is shown to the reader — a draft that',
 'does not announce itself is worse than no translation at all in a health app.',
 '',
 'No clinical string has a key here. A reference range, a dose, an observation label and a refusal',
 'sentence from a clinical contract are English in every locale, and clinicalLocale() below is what',
 'makes that structural rather than a promise.',
 '',
 'validateSaId, HeroSlideCopy and heroSlides() are hand-written in Localisation.swift and',
 'Localisation.kt beside this file, because they are decisions rather than data.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function emitLocales(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const states = Object.fromEntries(contract.reviewStates.map(s => [s.id, s]));
 const keysFor = platform => contract.keys.filter(k => k.surfaces.includes(platform));
 const stringFor = (locale, key) => contract.strings[locale.code][key.id] ?? contract.strings['en-ZA'][key.id];
 const carries = (locale, key) => locale.sets.includes(key.set);

 const iosKeys = keysFor('ios');
 const androidKeys = keysFor('android');

 /* ---- iOS ------------------------------------------------------------------------------------ */
 const swiftFile = `${banner()}

import Foundation

enum ThusoLocale: String, CaseIterable, Identifiable {
${contract.locales.map(l => `    case ${l.swift} = ${swift(l.code)}`).join('\n')}
    var id: String { rawValue }
    var native: String {
        switch self {
${contract.locales.map(l => `        case .${l.swift}: return ${swift(l.native)}`).join('\n')}
        }
    }
    /// What the reader is told about how much of this language has been checked, and by whom.
    var reviewLabel: String {
        switch self {
${contract.locales.map(l => `        case .${l.swift}: return ${swift(states[l.review.state].label)}`).join('\n')}
        }
    }
    /// nil only where there is nothing to warn about. Every screen that offers this locale shows it.
    var reviewNotice: String? {
        switch self {
${contract.locales.map(l => `        case .${l.swift}: return ${optSwift(states[l.review.state].notice)}`).join('\n')}
        }
    }
    /// True only where a named clinician who reads the language has signed the review off in
    /// ${SOURCE}. Nothing in the app may set this.
    var clinicallyReviewed: Bool {
        switch self {
${contract.locales.map(l => `        case .${l.swift}: return ${l.clinicalReview.state !== 'none'}`).join('\n')}
        }
    }
    /// The sets of keys this locale carries in full. Anything else falls back to English.
    var sets: [String] {
        switch self {
${contract.locales.map(l => `        case .${l.swift}: return [${l.sets.map(swift).join(', ')}]`).join('\n')}
        }
    }
}

enum ThusoString: String {
${iosKeys.map(k => `    case ${k.swift}`).join('\n')}
}

private let table: [ThusoLocale: [ThusoString: String]] = [
${contract.locales.map(l => `    .${l.swift}: [
${iosKeys.filter(k => carries(l, k)).map(k => `        .${k.swift}: ${swift(stringFor(l, k))}`).join(',\n')}
    ]`).join(',\n')}
]

func thuso(_ key: ThusoString, _ locale: ThusoLocale) -> String {
    table[locale]?[key] ?? table[.english]?[key] ?? key.rawValue
}

/* Clinical wording is rendered in the locale this returns, never in the one the reader chose.
   A reference range, a dose, an observation label and a refusal sentence out of a clinical
   contract are safety-critical text, and a mistranslated instruction is a safety problem rather
   than a polish problem — so they stay in English until a clinician who reads the language has
   signed the review off in ${SOURCE}.

   This is the only place that decision is taken. There is no clinical key in the table above for
   a translator to fill in, so there is nothing for a screen to render even if it forgot to ask. */
func clinicalLocale(_ locale: ThusoLocale) -> ThusoLocale {
    locale.clinicallyReviewed ? locale : .english
}
/// Shown wherever clinical copy sits inside a screen the reader chose another language for.
let clinicalLanguageRefusal = ${swift(contract.clinicalRule.refusal)}

/* Everything the language screen has to say, said once. Every one of these sentences used to be
   typed into a SwiftUI view, a Compose screen and a TSX file, and the three had already drifted:
   two of them still promised seven languages that had by then been added. */
enum ThusoLanguageNotes {
    static let clinicalRule = ${swift(contract.clinicalRule.sentence)}
    static let fallback = ${swift(contract.fallback)}
    static let signLanguageName = ${swift(contract.signLanguage.name)}
    static let signLanguageStatus = ${swift(contract.signLanguage.status)}
    static let signLanguageWhyNotListed = ${swift(contract.signLanguage.whyNotInTheList)}
    static let signLanguageRequirement = ${swift(contract.signLanguage.requirement.label)}
    static let signLanguageRequirementDetail = ${swift(contract.signLanguage.requirement.detail)}
    static let signLanguageNotBuilt = ${swift(contract.signLanguage.notYetBuilt)}
    static let signLanguageMustHappen: [(String, String)] = [
${contract.signLanguage.mustHappen.map(r => `        (${swift(r.title)}, ${swift(r.sentence)})`).join(',\n')}
    ]
    static let signLanguageNeverHappens: [String] = [
${contract.signLanguage.mustNeverHappen.map(r => `        ${swift(r.sentence)}`).join(',\n')}
    ]
}
`;

 /* ---- Android -------------------------------------------------------------------------------- */
 const kotlinFile = `${banner().replace(/^\/\//gm, ' *').replace(/^/, '/*\n').replace(/$/, '\n */')}

package za.co.mythuso.model

enum class ThusoLocale(
    val code: String,
    val native: String,
    val reviewLabel: String,
    val reviewNotice: String?,
    val clinicallyReviewed: Boolean,
    val sets: List<String>
) {
${contract.locales.map(l => `    ${l.kotlin}(${kotlin(l.code)}, ${kotlin(l.native)}, ${kotlin(states[l.review.state].label)}, ${optKotlin(states[l.review.state].notice)}, ${l.clinicalReview.state !== 'none'}, listOf(${l.sets.map(kotlin).join(', ')}))`).join(',\n')}
}

enum class Phrase { ${androidKeys.map(k => k.kotlin).join(', ')} }

private val phrases: Map<ThusoLocale, Map<Phrase, String>> = mapOf(
${contract.locales.map(l => `    ThusoLocale.${l.kotlin} to mapOf(
${androidKeys.filter(k => carries(l, k)).map(k => `        Phrase.${k.kotlin} to ${kotlin(stringFor(l, k))}`).join(',\n')}
    )`).join(',\n')}
)

private val english = phrases.getValue(ThusoLocale.ENGLISH)

fun thuso(phrase: Phrase, locale: ThusoLocale): String = phrases[locale]?.get(phrase) ?: english[phrase] ?: phrase.name

/* Clinical wording is rendered in the locale this returns, never in the one the reader chose.
   A reference range, a dose, an observation label and a refusal sentence out of a clinical
   contract are safety-critical text, and a mistranslated instruction is a safety problem rather
   than a polish problem — so they stay in English until a clinician who reads the language has
   signed the review off in ${SOURCE}.

   This is the only place that decision is taken. There is no clinical key in the table above for
   a translator to fill in, so there is nothing for a screen to render even if it forgot to ask. */
fun clinicalLocale(locale: ThusoLocale): ThusoLocale = if (locale.clinicallyReviewed) locale else ThusoLocale.ENGLISH

/** Shown wherever clinical copy sits inside a screen the reader chose another language for. */
const val CLINICAL_LANGUAGE_REFUSAL = ${kotlin(contract.clinicalRule.refusal)}

/* Everything the language screen has to say, said once. Every one of these sentences used to be
   typed into a SwiftUI view, a Compose screen and a TSX file, and the three had already drifted:
   two of them still promised seven languages that had by then been added. */
object ThusoLanguageNotes {
    const val clinicalRule = ${kotlin(contract.clinicalRule.sentence)}
    const val fallback = ${kotlin(contract.fallback)}
    const val signLanguageName = ${kotlin(contract.signLanguage.name)}
    const val signLanguageStatus = ${kotlin(contract.signLanguage.status)}
    const val signLanguageWhyNotListed = ${kotlin(contract.signLanguage.whyNotInTheList)}
    const val signLanguageRequirement = ${kotlin(contract.signLanguage.requirement.label)}
    const val signLanguageRequirementDetail = ${kotlin(contract.signLanguage.requirement.detail)}
    const val signLanguageNotBuilt = ${kotlin(contract.signLanguage.notYetBuilt)}
    val signLanguageMustHappen: List<Pair<String, String>> = listOf(
${contract.signLanguage.mustHappen.map(r => `        ${kotlin(r.title)} to ${kotlin(r.sentence)}`).join(',\n')}
    )
    val signLanguageNeverHappens: List<String> = listOf(
${contract.signLanguage.mustNeverHappen.map(r => `        ${kotlin(r.sentence)}`).join(',\n')}
    )
}
`;

 return [
  { path: 'apps/ios/MyThuso/Models/LocalisationData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/LocalisationData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitLocales()) {
  writeFileSync(file.path, file.content);
  console.log(`locales → ${file.path}`);
 }
}
