/* The two-tone headline, written out for two native apps by a machine.

   packages/catalog/framing.json is the shortest contract in this repository and it exists for the
   least glamorous reason: the same four pairs of sentences were typed into WorkspaceNavigation.
   framing on iOS and workspaceFraming on Android, and both comments said out loud that the honest
   home was a file like the source this reads. A headline is the first thing anybody reads on a
   screen and the cheapest thing in the product to change in a hurry; two copies of it is how a
   nurse and a doctor come to be addressed in two slightly different voices by one product.

   THE PATIENT'S FRAMING IS NOT WRITTEN OUT, IT IS POINTED AT. Its two lines are already in
   packages/catalog/locales.json in every language MyThuso offers, so writing the English here would
   have created the third copy while removing the second. What is emitted instead is the key: the
   Swift case and the Kotlin enum constant the locale generator produced, resolved from the key id
   in the contract so a renamed key breaks the build here rather than rendering a blank greeting on
   the one screen every patient opens first.

   Escaping: Swift needs its quotes escaped; Kotlin needs backslash, quote and dollar, because a
   lone $ starts a template. The sentences carry curly quotes and full stops and need nothing. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/catalog/framing.json';
const LOCALES = 'packages/catalog/locales.json';

const swift = value => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const kotlin = value => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const wrap = (text, width = 94) => text.match(new RegExp(`.{1,${width}}(\\s|$)`, 'g')).map(line => line.trim());

/* The accent line is set at the display step beside a lead line of the same size. Past this it is a
   paragraph in disguise and the screen has lost its subject. 34 is the longest the founder wrote. */
const ACCENT_LIMIT = 34;

export function emitFraming(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const locales = JSON.parse(readFileSync(root + LOCALES, 'utf8'));
 const keyById = new Map(locales.keys.map(key => [key.id, key]));

 const literal = [], pointed = [];
 for (const framing of contract.framings) {
  if (framing.fromLocale && (framing.lead || framing.accent)) throw new Error(`Framing "${framing.id}" both points at locale keys and types its own lines. Two sources for one headline is the drift this contract exists to remove.`);
  if (framing.fromLocale) { pointed.push(framing); continue; }
  if (!framing.lead || !framing.accent) throw new Error(`Framing "${framing.id}" is missing a lead or an accent line. The headline is two tones; one of them is not a headline, it is a heading.`);
  if (framing.accent.length > ACCENT_LIMIT) throw new Error(`Framing "${framing.id}"'s accent line is ${framing.accent.length} characters and the display step allows ${ACCENT_LIMIT}. At forty points beside a lead line of the same size, a sentence that long runs to three lines and the screen has no subject left.`);
  literal.push(framing);
 }
 /* A pointed framing resolves to a generated identifier on each platform. Doing it here rather than
    at the call site is what makes a renamed locale key a build failure instead of a blank greeting. */
 for (const framing of pointed) {
  for (const [slot, id] of Object.entries(framing.fromLocale)) {
   if (!keyById.has(id)) throw new Error(`Framing "${framing.id}" points its ${slot} line at the locale key "${id}", which packages/catalog/locales.json has not got.`);
   const key = keyById.get(id);
   for (const surface of ['ios', 'android']) {
    if (!key.surfaces.includes(surface)) throw new Error(`Framing "${framing.id}" points its ${slot} line at "${id}", which locales.json does not render on ${surface}. A headline half of which is missing on one phone is worse than one written twice.`);
   }
  }
 }
 if (pointed.length !== 1 || pointed[0].id !== 'patient') throw new Error('The patient framing is the only one this generator knows how to point at the locale table, and it expects exactly one. Teach it the shape before adding a second.');
 const patient = pointed[0];
 const patientSlot = (slot, field) => keyById.get(patient.fromLocale[slot])[field];

 const banner = () => [
  `Generated by scripts/emit-framing.mjs from ${SOURCE}.`,
  'Do not edit by hand — run `npm run framing`. The build fails if this file and the source',
  'disagree, so an edit here is lost rather than merely wrong.',
  '',
  'How a screen introduces itself: a lead line saying what the reader is here to do and an accent',
  'line saying what the screen gives them for it. StudioHeadline draws both, and nothing in either',
  'app may type one — scripts/check-boundaries.mjs fails on a framing string in any other source.',
  '',
  "The patient's framing is not here as words. It is two locale keys, because those two lines are",
  'already translated into every language MyThuso offers and a copy in English would have been a',
  'slogan nobody had reviewed on the first screen a patient opens.'
 ].map(line => (line ? `// ${line}` : '//')).join('\n');

 const swiftFramings = literal.map(f => `        .init(id: ${swift(f.id)}, role: ${f.role ? swift(f.role) : 'nil'},
              lead: ${swift(f.lead)}, accent: ${swift(f.accent)})`).join(',\n');

 const swiftFile = `${banner()}

import Foundation

enum FramingData {
    /// One screen's introduction. \`role\` is the workspace this frames, or nil for a framing that
    /// belongs to a screen rather than to somebody's job.
    struct Framing: Identifiable, Hashable {
        let id: String
        let role: String?
        let lead: String
        let accent: String
    }

${wrap(contract.rules.oneHeadlinePerScreen).map(line => `    // ${line}`).join('\n')}
    static let framings: [Framing] = [
${swiftFramings}
    ]
    static func framing(id: String) -> Framing? { framings.first { $0.id == id } }
    /// The framing for a role, or nil. Deliberately optional: a role nobody has framed gets the
    /// plain section heading rather than somebody else's words, which is what the switch statement
    /// this replaced did silently with its default branch.
    static func framing(role: String) -> Framing? { framings.first { $0.role == role } }

${wrap(patient.why).map(line => `    // ${line}`).join('\n')}
    static let patientLead = ThusoString.${patientSlot('lead', 'swift')}
    static let patientAccent = ThusoString.${patientSlot('accent', 'swift')}
    static let patientDetail = ThusoString.${patientSlot('detail', 'swift')}
}
`;

 const kotlinFramings = literal.map(f => `    Framing(
        ${kotlin(f.id)}, ${f.role ? kotlin(f.role) : 'null'},
        ${kotlin(f.lead)}, ${kotlin(f.accent)}
    )`).join(',\n');

 const kotlinFile = `${banner()}

package za.co.mythuso.model

/**
 * One screen's introduction. [role] is the workspace this frames, or null for a framing that
 * belongs to a screen rather than to somebody's job.
 */
data class Framing(val id: String, val role: String?, val lead: String, val accent: String)

${wrap(contract.rules.oneHeadlinePerScreen).map((line, i) => `${i ? '   ' : '/* '}${line}`).join('\n')} */
val screenFramings = listOf(
${kotlinFramings}
)

object FramingData {
    fun byId(id: String) = screenFramings.firstOrNull { it.id == id }
    /* The framing for a role, or null. Deliberately nullable: a role nobody has framed gets the
       plain section heading rather than somebody else's words, which is what the when expression
       this replaced did silently with its else branch. */
    fun forRole(role: String) = screenFramings.firstOrNull { it.role == role }

${wrap(patient.why, 88).map((line, i) => `${i ? '       ' : '    /* '}${line}`).join('\n')} */
    val patientLead = Phrase.${patientSlot('lead', 'kotlin')}
    val patientAccent = Phrase.${patientSlot('accent', 'kotlin')}
    val patientDetail = Phrase.${patientSlot('detail', 'kotlin')}
}
`;

 return [
  { path: 'apps/ios/MyThuso/Models/FramingData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/FramingData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitFraming()) {
  writeFileSync(file.path, file.content);
  console.log(`framing → ${file.path}`);
 }
}
