/* The plugin / skill allow-list, written out for the web app by a machine.

   packages/catalog/plugins.json is the one place that knows which named skills GilbertOne's tool
   gateway may reach, in which jurisdiction, behind which grant, and the shape each one's input must
   match — and the sentence each refusal answers with. The web will import a typed projection of it,
   written here, so no screen types its own copy of an allow-list entry or softens a refusal sentence:
   a skill is offered because this file says so, in these words, or it is not offered at all.

   NOTHING READS IT YET (audit of 1 October 2026). apps/web/src/lib/plugins.generated.ts is emitted and
   imported by no screen, because no screen offers a skill: the gateway the routes below describe is
   "proposed" until the founder decides where it lives. It is kept rather than retired because the
   generated-file check is today the only thing that parses plugins.json end to end and holds it to a
   typed shape, and because the first screen that offers a skill must read the allow-list from here
   rather than type it — retiring the projection now would invite exactly that copy. When the founder
   decides the gateway has no screen at all, retire it: this emitter, its `plugins` script and its place
   in `generate`, and its entry in the generated list in scripts/check-boundaries.mjs.

   This is a DATA contract, not an engine file. It is deliberately not one of packages/catalog/apis/
   — that directory holds exactly one file per engine declared in packages/catalog/events.json, and
   scripts/check-boundaries.mjs refuses any other — so the four routes it documents are conceptual and
   every one is "proposed". They become governed routes only when the founder decides whether the
   plugin gateway extends the access engine's tool-gateway or becomes an engine of its own.

   WHAT IS DELIBERATELY NOT EMITTED. The keys beginning with an underscore — _note, _routesNote,
   _schemaFieldTypesNote — are commentary for whoever opens the contract, and no other emitter carries
   them either: a generated file has its own banner explaining itself. The audience vocabulary is not
   re-declared here, because it lives in packages/gilbertone/src/engine.ts and is already held to the
   web's roles and the assistant contract by scripts/check-boundaries.mjs; a fourth copy would be a
   fourth place to disagree. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/catalog/plugins.json';

const banner = (allowlisted, revoked, jurisdictions) => [
 `Generated by scripts/emit-plugins.mjs from ${SOURCE}.`,
 'Do not edit by hand — run `npm run plugins`. The build fails if this file and its source disagree,',
 'so an edit here is lost rather than merely wrong.',
 '',
 `The skill allow-list GilbertOne's tool gateway reaches: ${allowlisted} allowlisted and ${revoked} revoked,`,
 `scoped to ${jurisdictions} jurisdiction(s), and the sentence each refusal answers with. A skill is offered`,
 'because this file says so, in these words, or it is not offered at all. The routes the contract',
 'documents are conceptual and "proposed": nothing here invokes a skill over a network.',
 '',
 'The keys beginning with an underscore in the contract are commentary and are not written out.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function emitPlugins(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));

 /* The generator is the first reader of the contract, so it is the first place a missing field can be
    named. Without this an allow-list entry that has lost its route or its grants reaches a projection
    and comes back as undefined on a screen — true, and useless to whoever has to fix it. */
 const states = new Set((contract.pluginStates ?? []).map(s => s.id));
 if (!states.size) throw new Error(`${SOURCE} declares no pluginStates, so no plugin can say whether it is allowlisted or revoked.`);
 const fieldTypes = new Set(contract.schemaFieldTypes ?? []);
 if (!fieldTypes.size) throw new Error(`${SOURCE} declares no schemaFieldTypes, so a plugin schema has no vocabulary to name a field in.`);
 const declaredJurisdictions = new Set((contract.jurisdictions ?? []).map(j => j.id));
 if (!declaredJurisdictions.has(contract.jurisdiction)) throw new Error(`${SOURCE} names "${contract.jurisdiction}" as its jurisdiction but declares no such jurisdiction.`);

 for (const refusal of contract.refusals ?? []) {
  for (const field of ['id', 'statement', 'why']) {
   if (typeof refusal[field] !== 'string' || !refusal[field]) throw new Error(`${SOURCE} refusal "${refusal.id ?? '?'}" has no ${field}. A refusal nobody can read is not a refusal.`);
  }
  if (typeof refusal.status !== 'number') throw new Error(`${SOURCE} refusal "${refusal.id}" has no HTTP status.`);
 }

 for (const plugin of contract.plugins ?? []) {
  for (const field of ['id', 'name', 'engine', 'route', 'purpose']) {
   if (typeof plugin[field] !== 'string' || !plugin[field]) throw new Error(`${SOURCE} plugin "${plugin.id ?? '?'}" has no ${field}. ${SOURCE} is not complete enough to write an allow-list from.`);
  }
  if (typeof plugin.version !== 'number') throw new Error(`${SOURCE} plugin "${plugin.id}" has no version.`);
  if (!states.has(plugin.status)) throw new Error(`${SOURCE} plugin "${plugin.id}" has status ${JSON.stringify(plugin.status)}, which no pluginState declares.`);
  if (!Array.isArray(plugin.jurisdictions) || !plugin.jurisdictions.length) throw new Error(`${SOURCE} plugin "${plugin.id}" names no jurisdiction, so it is approved nowhere and should not be listed as allowlisted.`);
  for (const j of plugin.jurisdictions) if (!declaredJurisdictions.has(j)) throw new Error(`${SOURCE} plugin "${plugin.id}" names jurisdiction "${j}", which the contract does not declare.`);
  if (!Array.isArray(plugin.requiredGrants)) throw new Error(`${SOURCE} plugin "${plugin.id}" has no requiredGrants list; a skill behind no grant says so with an empty list.`);
  if (!Array.isArray(plugin.audiences) || !plugin.audiences.length) throw new Error(`${SOURCE} plugin "${plugin.id}" names no audience, so it is offered to nobody.`);
  const input = plugin.schema?.input;
  if (!Array.isArray(input)) throw new Error(`${SOURCE} plugin "${plugin.id}" has no schema.input list; a skill that takes nothing says so with an empty list.`);
  for (const field of input) {
   if (typeof field.field !== 'string' || !field.field) throw new Error(`${SOURCE} plugin "${plugin.id}" has a schema field with no name.`);
   if (!fieldTypes.has(field.type)) throw new Error(`${SOURCE} plugin "${plugin.id}" field "${field.field}" has type ${JSON.stringify(field.type)}, which schemaFieldTypes does not declare.`);
   if (typeof field.required !== 'boolean') throw new Error(`${SOURCE} plugin "${plugin.id}" field "${field.field}" does not say whether it is required.`);
  }
  if (plugin.status === 'revoked' && !plugin.revoked?.why) throw new Error(`${SOURCE} plugin "${plugin.id}" is revoked without saying why. A revocation nobody can read is not a revocation.`);
 }

 const allowlisted = contract.plugins.filter(p => p.status === 'allowlisted').length;
 const revoked = contract.plugins.filter(p => p.status === 'revoked').length;

 const refusals = contract.refusals.map(r => ({ id: r.id, status: r.status, statement: r.statement, why: r.why }));
 const jurisdictions = contract.jurisdictions.map(j => ({ id: j.id, label: j.label, why: j.why }));
 const plugins = contract.plugins.map(p => ({
  id: p.id, name: p.name, version: p.version, status: p.status, jurisdictions: p.jurisdictions,
  engine: p.engine, route: p.route, purpose: p.purpose, requiredGrants: p.requiredGrants,
  audiences: p.audiences,
  revoked: p.status === 'revoked' ? { on: p.revoked.on, why: p.revoked.why } : null,
  schema: { input: p.schema.input.map(f => ({ field: f.field, type: f.type, required: f.required, why: f.why })) }
 }));

 const webFile = `${banner(allowlisted, revoked, declaredJurisdictions.size)}

export type PluginStatus = ${[...states].map(s => JSON.stringify(s)).join(' | ')};

export type PluginSchemaFieldType = ${[...fieldTypes].map(t => JSON.stringify(t)).join(' | ')};

export interface PluginSchemaField {
 readonly field: string;
 readonly type: PluginSchemaFieldType;
 readonly required: boolean;
 readonly why: string;
}

export interface PluginRefusal {
 readonly id: string;
 readonly status: number;
 readonly statement: string;
 readonly why: string;
}

export interface PluginJurisdiction {
 readonly id: string;
 readonly label: string;
 readonly why: string;
}

export interface PluginEntry {
 readonly id: string;
 readonly name: string;
 readonly version: number;
 readonly status: PluginStatus;
 readonly jurisdictions: readonly string[];
 readonly engine: string;
 readonly route: string;
 readonly purpose: string;
 readonly requiredGrants: readonly string[];
 readonly audiences: readonly string[];
 readonly revoked: { readonly on: string; readonly why: string } | null;
 readonly schema: { readonly input: readonly PluginSchemaField[] };
}

/** The jurisdiction the allow-list is read against when a caller names none. */
export const pluginJurisdiction: string = ${JSON.stringify(contract.jurisdiction)};

export const pluginJurisdictions: readonly PluginJurisdiction[] = ${JSON.stringify(jurisdictions, null, 1)};

/** Every refusal sentence a plugin meets, word for word from the contract. */
export const pluginRefusals: readonly PluginRefusal[] = ${JSON.stringify(refusals, null, 1)};

/** Every registered skill, allowlisted and revoked, in the contract's own order. */
export const plugins: readonly PluginEntry[] = ${JSON.stringify(plugins, null, 1)};
`;

 return [
  { path: 'apps/web/src/lib/plugins.generated.ts', content: webFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitPlugins()) {
  writeFileSync(file.path, file.content);
  console.log(`plugins → ${file.path}`);
 }
}
