/* The shop, written out for two native apps by a machine.

   packages/catalog/shop.json is the feature. Twelve things a household buys between visits, five
   categories, seven refusals — and one absence that matters more than any of them: there is no
   medicine in it, and there is no field in which a medicine could describe itself.

   WHAT THIS GENERATOR REFUSES TO EMIT. A product may carry `does` and may not carry `treats`,
   `claims`, `indication`, `schedule` or `prescription`. Those five names are checked here and the
   generator throws, because the sentence that sells a device and the sentence that makes a medical
   claim about it are one word apart, and the person reading it is alone with a card in their hand.
   The `neverSold` vocabulary is applied to every id, name and `does` sentence for the same reason:
   the shop cannot grow into a pharmacy by increments if each increment fails the build.

   Prices are emitted as integer cents. A rand in a Double is a rounding error waiting for a
   checkout screen, and the one place it is allowed to be a rand is the contract a human reads.

   Escaping: Swift needs its quotes escaped; Kotlin needs backslash, quote and dollar, because a
   lone $ starts a template. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/catalog/shop.json';
const FORBIDDEN_FIELDS = ['treats', 'claims', 'indication', 'schedule', 'prescription'];

const swift = value => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const kotlin = value => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const wrap = (text, width = 94) => text.match(new RegExp(`.{1,${width}}(\\s|$)`, 'g')).map(line => line.trim());

export function emitShop(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));

 if (!contract.refusals?.length) throw new Error('packages/catalog/shop.json declares no refusals, and the refusals are the feature.');
 const categories = new Set(contract.categories.map(c => c.id));
 for (const product of contract.products) {
  for (const field of FORBIDDEN_FIELDS) {
   if (field in product) throw new Error(`Product "${product.id}" carries a "${field}" field. A shop listing states what a thing does and never what it treats — see the generator.`);
  }
  if (!categories.has(product.category)) throw new Error(`Product "${product.id}" is in the category "${product.category}", which shop.json has not got.`);
  if (!Number.isInteger(product.price) || product.price <= 0) throw new Error(`Product "${product.id}" has no whole-rand price.`);
  const haystack = `${product.id} ${product.name} ${product.does}`.toLowerCase();
  const hit = contract.neverSold.find(word => haystack.includes(word.toLowerCase()));
  if (hit) throw new Error(`Product "${product.id}" matches the never-sold word "${hit}". This shop does not sell medicine, and the check is what keeps that true.`);
  if (!product.does.trim().endsWith('.')) throw new Error(`Product "${product.id}" has a "does" that is not a sentence.`);
 }
 for (const refusal of contract.refusals) {
  if (!refusal.sentence || !refusal.why) throw new Error(`Refusal "${refusal.id}" is missing its sentence or its reasoning. The sentence is what a person reads; the reasoning is what stops the next person deleting it.`);
 }

 const banner = () => [
  `Generated by scripts/emit-shop.mjs from ${SOURCE}.`,
  'Do not edit by hand — run `npm run shop`. The build fails if this file and the source',
  'disagree, so an edit here is lost rather than merely wrong.',
  '',
  'The MyThuso shop. Devices, consumables and wellness goods — and no medicine, at all, of any',
  'schedule. Supplying medicine is a licensed activity under the Medicines and Related Substances',
  'Act 101 of 1965, and a shop that sells a monitor today and a painkiller tomorrow has become a',
  'pharmacy without a licence. A listing says what a thing does and never what it treats.',
  '',
  'Prices are integer cents. Nothing here is a real service: no card is charged, no order is',
  'placed and nothing is delivered.'
 ].map(line => (line ? `// ${line}` : '//')).join('\n');

 const swiftFile = `${banner()}

import Foundation

enum ShopData {
    /// A thing a household can buy. \`does\` is what the object physically does; there is no field
    /// for what it treats, and the generator throws if one is added — see scripts/emit-shop.mjs.
    struct Product: Identifiable, Hashable {
        let id: String; let name: String; let category: String
        let priceCents: Int; let stock: Int; let does: String; let needsReading: Bool
    }
    struct Category: Identifiable, Hashable { let id: String; let name: String; let blurb: String; let pointsEligible: Bool }
    /// Something the shop will not do, in the words a person reads.
    struct Refusal: Identifiable, Hashable { let id: String; let sentence: String }

    static let currency = ${swift(contract.currency)}
    static let deliveryFeeCents = ${contract.delivery.fee * 100}
    static let deliveryFreeAboveCents = ${contract.delivery.freeAbove * 100}
    static let deliveryStandardDays = ${contract.delivery.standardDays}

    static let categories: [Category] = [
${contract.categories.map(c => `        .init(id: ${swift(c.id)}, name: ${swift(c.name)},
              blurb: ${swift(c.blurb)}, pointsEligible: ${c.pointsEligible})`).join(',\n')}
    ]

    static let products: [Product] = [
${contract.products.map(p => `        .init(id: ${swift(p.id)}, name: ${swift(p.name)}, category: ${swift(p.category)},
              priceCents: ${p.price * 100}, stock: ${p.stock},
              does: ${swift(p.does)}, needsReading: ${p.needsReading})`).join(',\n')}
    ]

${wrap(contract._neverSoldNote).map(line => `    // ${line}`).join('\n')}
    static let neverSold: [String] = [${contract.neverSold.map(swift).join(', ')}]

    static let refusals: [Refusal] = [
${contract.refusals.map(r => `        .init(id: ${swift(r.id)}, sentence: ${swift(r.sentence)})`).join(',\n')}
    ]

    static func product(_ id: String) -> Product? { products.first { $0.id == id } }
    static func category(_ id: String) -> Category? { categories.first { $0.id == id } }
    static func refusal(_ id: String) -> Refusal? { refusals.first { $0.id == id } }
}
`;

 const kotlinFile = `${banner()}

package za.co.mythuso.model

data class ShopProduct(
    val id: String, val name: String, val category: String,
    val priceCents: Int, val stock: Int, val does: String, val needsReading: Boolean
)
data class ShopCategory(val id: String, val name: String, val blurb: String, val pointsEligible: Boolean)
data class ShopRefusal(val id: String, val sentence: String)

val shopCategories = listOf(
${contract.categories.map(c => `    ShopCategory(${kotlin(c.id)}, ${kotlin(c.name)}, ${kotlin(c.blurb)}, ${c.pointsEligible})`).join(',\n')}
)

val shopProducts = listOf(
${contract.products.map(p => `    ShopProduct(${kotlin(p.id)}, ${kotlin(p.name)}, ${kotlin(p.category)}, ${p.price * 100}, ${p.stock}, ${kotlin(p.does)}, ${p.needsReading})`).join(',\n')}
)

val shopNeverSold = listOf(${contract.neverSold.map(kotlin).join(', ')})

val shopRefusals = listOf(
${contract.refusals.map(r => `    ShopRefusal(${kotlin(r.id)}, ${kotlin(r.sentence)})`).join(',\n')}
)

object ShopData {
    const val currency = ${kotlin(contract.currency)}
    const val deliveryFeeCents = ${contract.delivery.fee * 100}
    const val deliveryFreeAboveCents = ${contract.delivery.freeAbove * 100}
    const val deliveryStandardDays = ${contract.delivery.standardDays}

    fun product(id: String) = shopProducts.firstOrNull { it.id == id }
    fun category(id: String) = shopCategories.firstOrNull { it.id == id }
    fun refusal(id: String) = shopRefusals.firstOrNull { it.id == id }
}
`;

 return [
  { path: 'apps/ios/MyThuso/Models/ShopData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/ShopData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitShop()) {
  writeFileSync(file.path, file.content);
  console.log(`shop → ${file.path}`);
 }
}
