/* The record contract, written out for two native apps, by a machine.

   Six master areas, three sensitivity classes, the eight-item navigation, 42 record types with the
   FHIR resource each maps to and the capability each is gated by, one standardised consultation and
   one summary card live in packages/catalog/records.json. The web reads that file. iOS and Android
   cannot, and should not, for the reason the vetting table gives: an app that parses JSON to draw a
   list is a web app wearing a Compose hat. So the contract was hand-mirrored, twice, by two people
   who never spoke to each other.

   It had already drifted by the time this was written. records.json says a prescription is opened
   by view-clinical-record *or* dispense — a pharmacy sees the medicine it is being asked to hand
   over — and it says so in a sentence that names the promise vetting.json makes. Both native copies
   carry the older, shorter version: one capability, and the sentence stopping at the full stop
   before the promise. Nobody typed that in on purpose; it is simply what happens to a sentence
   copied by hand and then improved in one place. Generated, the drift has nowhere to come from.

   What comes out is ordinary Swift and Kotlin source, compiled into the binaries, parsing nothing
   at runtime. Only the contract is generated. The reasoning about it — how an entry raises its own
   class, why a cleared nurse still sees nothing until the patient releases it, the fictional
   patients it is all demonstrated on — stays hand-written in Records.swift and Records.kt beside
   these files, exactly as Vetting.swift sits beside the generated VettingData.swift.

   Escaping is the hazard here, and the two languages disagree about it:
     - Swift needs only its quotes escaped; a backslash would want a raw string, #"…"#.
     - Kotlin needs backslash, quote and dollar escaped, because a lone backslash is an escape and
       a lone $ starts a string template.
   The summaries carry curly quotes, apostrophes, en-dashes and em-dashes. Those are simply UTF-8
   and need nothing, which is worth knowing rather than guessing at — and worth saying, because the
   temptation when transcribing a contract by hand is to tidy an apostrophe. Every sentence below
   leaves this generator byte-identical to the one in the JSON. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/catalog/records.json';

/* Swift: a value carrying a backslash goes into a raw string so the backslash is the character it
   looks like. Nothing in the contract does today, which is precisely why the case is handled here
   rather than discovered later. */
const swift = value => {
 if (value.includes('\\')) {
  if (value.includes('"#')) throw new Error(`Cannot write ${JSON.stringify(value)} as a Swift raw string`);
  return `#"${value}"#`;
 }
 return `"${value.replace(/"/g, '\\"')}"`;
};
/* Kotlin: backslash, quote and dollar all mean something inside a literal. The dollar is escaped
   unconditionally — the first summary to mention a price would otherwise compile into a template
   expression, or fail to compile at all, depending on what followed it. */
const kotlin = value => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;

const swiftList = values => `[${values.map(swift).join(', ')}]`;
const kotlinList = values => `listOf(${values.map(kotlin).join(', ')})`;

/* The sensitivity ids become Swift enum cases, so they have to be things Swift will accept as
   identifiers. Every id in the contract is a single lower-case word; a hyphenated one added later
   would produce a file that does not compile, and this says so at the point of generation rather
   than several minutes into a build. */
const swiftCase = id => {
 if (!/^[a-z][A-Za-z0-9]*$/.test(id)) throw new Error(`Sensitivity id ${JSON.stringify(id)} is not a Swift case name`);
 return id;
};

const banner = () => [
 `Generated by scripts/emit-records.mjs from ${SOURCE}.`,
 'Do not edit by hand — run `npm run records`. The build fails if this file and the record source',
 'disagree, so an edit here is lost rather than merely wrong.',
 '',
 'The areas, classes, record types, FHIR mappings, gating capabilities, consultation sections,',
 'reference ranges, reading explanations and summary card are the contract itself. The reasoning',
 'about them, and the fictional patients they are demonstrated on, are hand-written in',
 'Records.swift and Records.kt beside this file.',
 '',
 'The explanations carry no reference range and no label of their own. A reading is judged against',
 'the observations above, in this same file, so the prose explaining a number and the number that',
 'flags it cannot become two answers.',
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function emitRecords(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const { areas, sensitivity, navigation, records, consultation, observations, explanations, summaryCard } = contract;
 /* The qualification is not a field of its own anywhere. It is the note on the observations
    section of the standard consultation, and both apps render that one sentence rather than a
    second one written beside the numbers. Read here so a missing note fails generation rather
    than shipping a range with nothing qualifying it. */
 const observationsNote = consultation.sections.find(s => s.id === 'observations')?.note;
 if (!observationsNote) throw new Error('The observations consultation section carries no note, so the reference ranges would be written into both native apps with nothing saying they are indicative');
 /* A range whose ends are the wrong way round would flag every reading ever taken. It is the one
    arithmetic error in this contract that a compiler cannot see, and Swift's ClosedRange traps on
    it at runtime rather than at build time, so it is refused before either file is written. */
 for (const m of observations.measures) if (!(m.low < m.high)) throw new Error(`Reference range for ${m.id} is ${m.low}\u2013${m.high}, which is not a range`);

 /* ---- iOS ------------------------------------------------------------------------------------
    The shape types are declared here rather than in Records.swift because they are the contract's
    shape, not a decision about it: adding a field to records.json should add it here and nowhere
    else. `RecordSensitivity` is an enum whose case order is load-bearing — `rank` in Records.swift
    reads it to decide that an entry may raise its own class and never lower it — so the order the
    catalogue lists the classes in is the order they are declared in.

    `note` on a class is not carried as a field. It is an instruction to whoever edits the contract,
    it names the file it is written in, and no screen has ever read it; carried as a String it would
    be a sentence about the catalogue's own shape sitting in a struct a view could put in front of a
    patient. It is written out as a comment beside the list it is about instead, so it still changes
    when the JSON changes and still reaches the only reader it was ever aimed at. */
 const swiftSensitivity = entry => {
  const lines = [
   `        .init(id: .${swiftCase(entry.id)}, name: ${swift(entry.name)},`,
   `              detail: ${swift(entry.detail)},`,
   `              guardianDefault: ${swift(entry.guardianDefault)}, summaryHeader: ${swift(entry.summaryHeader)}`
  ];
  if (entry.categories) {
   lines[lines.length - 1] += ',';
   if (entry.note) lines.push(`              // ${entry.note}`);
   lines.push(`              categories: ${swiftList(entry.categories)}`);
  }
  return lines.join('\n') + ')';
 };

 const swiftType = record => {
  const lines = [
   `        .init(id: ${swift(record.id)}, name: ${swift(record.name)}, area: ${swift(record.area)}, fhir: ${swift(record.fhir)}, sensitivity: .${swiftCase(record.sensitivity)}`,
   `              gatedBy: ${swiftList(record.gatedBy)}`,
   `              summary: ${swift(record.summary)}`
  ];
  /* Absent on all but one record, so it is left off entirely rather than written as an empty
     list: the default on the struct is what says "this record draws no line between reading and
     writing", and forty-one empty brackets would say it forty-one times. */
  if (record.writtenBy) lines.push(`              writtenBy: ${swiftList(record.writtenBy)}`);
  return lines.join(',\n') + ')';
 };

 /* A memberwise initialiser takes its arguments in declaration order, so note is written before
    gatedBy whatever order the JSON lists them in. No section carries both today; a section that
    did would otherwise generate Swift that does not compile, and for a reason nobody would enjoy
    tracking down. */
 const swiftSection = section => {
  let out = `        .init(id: ${swift(section.id)}, name: ${swift(section.name)}, required: ${section.required}`;
  if (section.note) out += `,\n              note: ${swift(section.note)}`;
  if (section.gatedBy) out += `, gatedBy: ${swift(section.gatedBy)}`;
  return out + ')';
 };

 const swiftFile = `${banner()}

import Foundation

// MARK: - Shapes

struct RecordArea: Identifiable, Hashable {
    let id: String
    let name: String
    let detail: String
}
/// Three classes, in order of how much harm a disclosure does. The order is load-bearing: an
/// entry may raise its own class, never lower it, and \`rank\` in Records.swift reads this order.
enum RecordSensitivity: String, CaseIterable, Identifiable, Hashable {
    case ${sensitivity.map(s => swiftCase(s.id)).join(', ')}
    var id: String { rawValue }
}
struct RecordSensitivityClass: Identifiable, Hashable {
    let id: RecordSensitivity
    let name: String
    let detail: String
    let guardianDefault: String
    let summaryHeader: String
    var categories: [String] = []
}
struct RecordType: Identifiable, Hashable {
    let id: String
    let name: String
    let area: String
    let fhir: String
    let sensitivity: RecordSensitivity
    let gatedBy: [String]
    let summary: String
    /// Set only where the contract separates writing a record from reading one.
    var writtenBy: [String] = []
}
struct ConsultationSection: Identifiable, Hashable {
    let id: String
    let name: String
    let required: Bool
    var note: String?
    var gatedBy: String?
}
struct SoapHeading: Identifiable, Hashable {
    let id: String
    let name: String
    let detail: String
}
/// What one of the seven readings measures, and what a number outside its range may follow from.
/// Prose, written by a person, reviewed by nobody yet — \`RecordExplanationProvenance.unreviewed\`
/// is on the screen saying so. It carries no label, no unit and no range: those are the
/// \`ObservationRange\` of the same id, so the paragraph and the number that flags it cannot
/// disagree. \`urgent\` holds ids into the emergency contract, resolved through SosData, so a screen
/// can neither invent a red flag nor soften one.
struct RecordExplanation: Identifiable, Hashable {
    let id: String
    /// What the instrument is actually measuring, in one sentence.
    let measures: String
    /// What a reading above the range may follow from. Never what it is.
    let above: String
    /// And below. For several of these the honest answer is "often nothing at all".
    let below: String
    /// What a person can do about it today. Never a change to a medicine.
    let whatToDo: String
    /// Ids in packages/catalog/sos.json's red flags. Resolved through the contract, never retyped.
    let urgent: [String]
}
/// Where the explanations come from and what they are not. Five sentences that belong on the screen
/// rather than in a policy: a reader deciding how much weight to give a paragraph about their own
/// blood pressure is owed the provenance of it before the paragraph, not after.
struct RecordExplanationProvenance {
    let written: String
    let unreviewed: String
    let ranges: String
    let whoDecides: String
    let neverChange: String
}
struct RecordSummaryCard {
    let why: String
    let fields: [String]
    let withheld: String
}
/// One of the seven readings a nurse takes, and the indicative adult range it is flagged against.
/// Deliberately not named Observation: the assessment screen still declares its own, and this is
/// the contract's copy that replaces it. Both ends of the range are inclusive.
struct ObservationRange: Identifiable, Hashable {
    let id: String
    let label: String
    let unit: String
    let low: Double
    let high: Double
    /// The input's granularity. Below 1 is also the sign that the reading is written to one decimal.
    let step: Double
    let placeholder: String
    var range: ClosedRange<Double> { low...high }
}

// MARK: - The contract

enum Records {
    static let areas: [RecordArea] = [
${areas.map(a => `        .init(id: ${swift(a.id)}, name: ${swift(a.name)}, detail: ${swift(a.detail)})`).join(',\n')}
    ]

    static let sensitivities: [RecordSensitivityClass] = [
${sensitivity.map(swiftSensitivity).join(',\n')}
    ]

    /// The navigation, in the contract's order — ${navigation.length} tabs against ${records.length} record types, because the
    /// data model and the order somebody reads it in are deliberately not the same list.
    static let navigation: [String] = ${swiftList(navigation)}

    static let types: [RecordType] = [
${records.map(swiftType).join(',\n')}
    ]

    static let consultationWhy = ${swift(consultation.why)}

    static let consultationSections: [ConsultationSection] = [
${consultation.sections.map(swiftSection).join(',\n')}
    ]

    static let soap: [SoapHeading] = [
${consultation.soap.map(h => `        .init(id: ${swift(h.id)}, name: ${swift(h.name)}, detail: ${swift(h.detail)})`).join(',\n')}
    ]

    static let observationsWhy = ${swift(observations.why)}
    /// The sentence every screen showing a range shows with it. Not written twice: it is the note
    /// on the observations consultation section above.
    static let observationsNote = ${swift(observationsNote)}

    /// ${observationsNote}
    static let observations: [ObservationRange] = [
${observations.measures.map(m => `        .init(id: ${swift(m.id)}, label: ${swift(m.label)}, unit: ${swift(m.unit)}, low: ${m.low}, high: ${m.high}, step: ${m.step}, placeholder: ${swift(m.placeholder)})`).join(',\n')}
    ]

    static let explanationsWhy = ${swift(explanations.why)}
    /// ${explanations.theLineItMustNotCross}
    static let explanations: [RecordExplanation] = [
${explanations.entries.map(e => `        .init(id: ${swift(e.id)},
              measures: ${swift(e.measures)},
              above: ${swift(e.above)},
              below: ${swift(e.below)},
              whatToDo: ${swift(e.whatToDo)},
              urgent: ${swiftList(e.urgent)})`).join(',\n')}
    ]
    static func explanation(_ id: String) -> RecordExplanation? { explanations.first { $0.id == id } }

    /// ${explanations.provenanceWhy}
    static let explanationProvenance = RecordExplanationProvenance(
        written: ${swift(explanations.provenance.written)},
        unreviewed: ${swift(explanations.provenance.unreviewed)},
        ranges: ${swift(explanations.provenance.ranges)},
        whoDecides: ${swift(explanations.provenance.whoDecides)},
        neverChange: ${swift(explanations.provenance.neverChange)})

    static let summaryCard = RecordSummaryCard(
        why: ${swift(summaryCard.why)},
        fields: ${swiftList(summaryCard.fields)},
        withheld: ${swift(summaryCard.withheld)})
}
`;

 /* ---- Android --------------------------------------------------------------------------------
    Top-level declarations in za.co.mythuso.model, which is the name every screen already uses.
    Sensitivity stays a String and gatedBy a List<String>: the rank map that orders the three
    classes, and the Sensitive interface that resolves an entry against its type, are reasoning
    rather than contract, and they live in Records.kt. Moving them here would move a decision into
    a generated file, which is the one thing generation is not for. */
 const kotlinSensitivity = entry => {
  const lines = [
   `    RecordSensitivity(`,
   `        ${kotlin(entry.id)}, ${kotlin(entry.name)},`,
   `        ${kotlin(entry.detail)},`,
   `        ${kotlin(entry.guardianDefault)}, ${kotlin(entry.summaryHeader)}`
  ];
  if (entry.categories) {
   lines[lines.length - 1] += ',';
   if (entry.note) lines.push(`        // ${entry.note}`);
   lines.push(`        ${kotlinList(entry.categories)}`);
  }
  return lines.join('\n') + '\n    )';
 };

 const kotlinType = record => {
  const lines = [
   `    RecordType(`,
   `        ${kotlin(record.id)}, ${kotlin(record.name)}, ${kotlin(record.area)}, ${kotlin(record.fhir)},`,
   `        ${kotlin(record.sensitivity)}, ${kotlinList(record.gatedBy)},`,
   `        ${kotlin(record.summary)}`
  ];
  /* Kotlin takes the same view as Swift for the same reason: writtenBy defaults to an empty list,
     and the forty-one records that do not separate writing from reading say nothing about it. */
  if (record.writtenBy) {
   lines[lines.length - 1] += ',';
   lines.push(`        ${kotlinList(record.writtenBy)}`);
  }
  return lines.join('\n') + '\n    )';
 };

 /* Named arguments, so order is free here — but a note is a whole sentence and a gate is one word,
    and a list of twelve sections stops being readable if a sentence is hung off the end of a line
    that already reads as a row. Sections carrying a note are wrapped; the rest stay on one line. */
 const kotlinSection = section => {
  const head = `${kotlin(section.id)}, ${kotlin(section.name)}, ${section.required}`;
  const named = [];
  if (section.note) named.push(`note = ${kotlin(section.note)}`);
  if (section.gatedBy) named.push(`gatedBy = ${kotlin(section.gatedBy)}`);
  if (!named.length) return `    ConsultationSection(${head})`;
  if (section.note) return `    ConsultationSection(\n        ${head},\n        ${named.join(', ')}\n    )`;
  return `    ConsultationSection(${head}, ${named.join(', ')})`;
 };

 const kotlinFile = `${banner()}

package za.co.mythuso.model

data class RecordArea(val id: String, val name: String, val detail: String)
data class RecordSensitivity(
    val id: String, val name: String, val detail: String,
    val guardianDefault: String, val summaryHeader: String, val categories: List<String> = emptyList()
)
data class RecordType(
    val id: String, val name: String, val area: String, val fhir: String,
    val sensitivity: String, val gatedBy: List<String>, val summary: String,
    /* Set only where the contract separates writing a record from reading one. */
    val writtenBy: List<String> = emptyList()
)
data class ConsultationSection(
    val id: String, val name: String, val required: Boolean,
    val note: String? = null, val gatedBy: String? = null
)
data class SoapHeading(val id: String, val name: String, val detail: String)
data class RecordSummaryCard(val why: String, val fields: List<String>, val withheld: String)
/**
 * What one of the seven readings measures, and what a number outside its range may follow from.
 * Prose, written by a person, reviewed by nobody yet — recordExplanationProvenance.unreviewed is on
 * the screen saying so. It carries no label, no unit and no range: those are the ObservationRange of
 * the same id, so the paragraph and the number that flags it cannot disagree. urgent holds ids into
 * the emergency contract, resolved through SosData, so a screen can neither invent a red flag nor
 * soften one.
 */
data class RecordExplanation(
    val id: String,
    /** What the instrument is actually measuring, in one sentence. */
    val measures: String,
    /** What a reading above the range may follow from. Never what it is. */
    val above: String,
    /** And below. For several of these the honest answer is "often nothing at all". */
    val below: String,
    /** What a person can do about it today. Never a change to a medicine. */
    val whatToDo: String,
    /** Ids in packages/catalog/sos.json's red flags. Resolved through the contract, never retyped. */
    val urgent: List<String>
)
/**
 * Where the explanations come from and what they are not. Five sentences that belong on the screen
 * rather than in a policy: a reader deciding how much weight to give a paragraph about their own
 * blood pressure is owed the provenance of it before the paragraph, not after.
 */
data class RecordExplanationProvenance(
    val written: String, val unreviewed: String, val ranges: String,
    val whoDecides: String, val neverChange: String
)
/**
 * One of the seven readings a nurse takes, and the indicative adult range it is flagged against.
 * Deliberately not named Observation: the assessment screen still declares its own, and this is the
 * contract's copy that replaces it. Both ends of the range are inclusive.
 */
data class ObservationRange(
    val id: String, val label: String, val unit: String,
    val low: Double, val high: Double, val step: Double, val placeholder: String
)

val recordAreas = listOf(
${areas.map(a => `    RecordArea(${kotlin(a.id)}, ${kotlin(a.name)}, ${kotlin(a.detail)}),`).join('\n')}
)

val recordSensitivities = listOf(
${sensitivity.map(entry => kotlinSensitivity(entry) + ',').join('\n')}
)

val recordNavigation = ${kotlinList(navigation)}

val recordTypes = listOf(
${records.map(record => kotlinType(record) + ',').join('\n')}
)

const val consultationWhy =
    ${kotlin(consultation.why)}

val consultationSections = listOf(
${consultation.sections.map(section => kotlinSection(section) + ',').join('\n')}
)

val soapHeadings = listOf(
${consultation.soap.map(h => `    SoapHeading(${kotlin(h.id)}, ${kotlin(h.name)}, ${kotlin(h.detail)}),`).join('\n')}
)

const val observationsWhy =
    ${kotlin(observations.why)}

/* The sentence every screen showing a range shows with it. Not written twice: it is the note on the
   observations consultation section above. */
const val observationsNote =
    ${kotlin(observationsNote)}

/* ${observationsNote} */
val observationRanges = listOf(
${observations.measures.map(m => `    ObservationRange(${kotlin(m.id)}, ${kotlin(m.label)}, ${kotlin(m.unit)}, ${m.low.toFixed(1)}, ${m.high.toFixed(1)}, ${m.step.toFixed(1)}, ${kotlin(m.placeholder)}),`).join('\n')}
)

const val recordExplanationsWhy =
    ${kotlin(explanations.why)}

/* ${explanations.theLineItMustNotCross} */
val recordExplanations = listOf(
${explanations.entries.map(e => `    RecordExplanation(
        ${kotlin(e.id)},
        ${kotlin(e.measures)},
        ${kotlin(e.above)},
        ${kotlin(e.below)},
        ${kotlin(e.whatToDo)},
        ${kotlinList(e.urgent)}
    ),`).join('\n')}
)

/* ${explanations.provenanceWhy} */
val recordExplanationProvenance = RecordExplanationProvenance(
    ${kotlin(explanations.provenance.written)},
    ${kotlin(explanations.provenance.unreviewed)},
    ${kotlin(explanations.provenance.ranges)},
    ${kotlin(explanations.provenance.whoDecides)},
    ${kotlin(explanations.provenance.neverChange)}
)

val recordSummaryCard = RecordSummaryCard(
    ${kotlin(summaryCard.why)},
    ${kotlinList(summaryCard.fields)},
    ${kotlin(summaryCard.withheld)}
)
`;

 return [
  { path: 'apps/ios/MyThuso/Models/RecordsData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/RecordsData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitRecords()) {
  writeFileSync(file.path, file.content);
  console.log(`records → ${file.path}`);
 }
}
