/* What the offline queue survives, written out for two native apps by a machine.

   This generator exists for one section of packages/catalog/capture.json and it is deliberate that
   it is only one. The rest of that contract — the six states, the four conflicts, the provenances,
   the instruments — is read by the web and hand-written in the native models beside it, and pulling
   all of it through a generator is a separate job from this one. What is generated here is the
   `durability` section, because that was the part written twice in different words about the same
   disk: Android's FileBook carried three sentences about a JSON file in the app's private storage,
   iOS's two queue screens carried six about a JSON file in Application Support, and nothing in this
   repository compared them. A nurse reading the Android sentence and the iOS list would not have
   known they describe one behaviour.

   WHAT IT REFUSES TO FLATTEN. Three platforms do not keep the same things, and pretending they do
   would be a lie in the one place a nurse is deciding whether to trust the app with a morning's
   work. The web's store is a module-level array and loses everything on a reload, because
   scripts/check-boundaries.mjs forbids the browser's local storage, session storage and IndexedDB
   across apps/web/src. So each store carries its own event sets, and what is held in common — the
   promise that a captured entry survives a crash, a restart and a sign-out — is checked rather than
   asserted: scripts/check-boundaries.mjs fails the build if two file-backed stores stop agreeing
   about what they survive.

   BEHAVIOUR AND COPY ARE SEPARATE FIELDS. `survives`/`lostTo` are event ids — what is true of the
   store. `says` is the sentences a screen renders today, word for word. They are not the same list
   on Android, where the file loses a lost phone and a second device exactly as the iOS one does and
   the sentence on screen mentions neither. Holding both is what makes that gap visible.

   Escaping: Swift needs its quotes escaped; Kotlin needs backslash, quote and dollar, because a
   lone $ starts a template. The sentences carry curly quotes, em-dashes and apostrophes, all of
   which are plain UTF-8 and need nothing. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/catalog/capture.json';

const swift = value => {
 if (value.includes('\\')) {
  if (value.includes('"#')) throw new Error(`Cannot write ${JSON.stringify(value)} as a Swift raw string`);
  return `#"${value}"#`;
 }
 return `"${value.replace(/"/g, '\\"')}"`;
};
const kotlin = value => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const swiftList = values => `[${values.map(swift).join(', ')}]`;
const kotlinList = values => (values.length ? `listOf(${values.map(kotlin).join(', ')})` : 'emptyList()');

const banner = () => [
 `Generated by scripts/emit-capture.mjs from ${SOURCE}.`,
 'Do not edit by hand — run `npm run capture`. The build fails if this file and the source',
 'disagree, so an edit here is lost rather than merely wrong.',
 '',
 'What the offline queue survives, and what loses it. Two fields per store and the difference',
 'between them matters: survives/lostTo are what is true of the store, and says is what a screen',
 'renders. A store whose behaviour is wider than what it says is a screen with a gap in it.',
 '',
 'Nothing here is encrypted by MyThuso and nothing here is sent anywhere. Fictional readings.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function emitCapture(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const d = contract.durability;
 const eventIds = new Set(d.events.map(e => e.id));
 /* Generation is the last place an id can still be caught cheaply. A store claiming to survive an
    event nobody has named would compile into both apps as a string that resolves to nothing. */
 for (const store of d.stores) {
  for (const id of [...store.survives, ...store.lostTo]) {
   if (!eventIds.has(id)) throw new Error(`Store "${store.id}" names the event "${id}", which is not in durability.events`);
  }
  const both = store.survives.filter(id => store.lostTo.includes(id));
  if (both.length) throw new Error(`Store "${store.id}" both survives and is lost to ${both.join(', ')}. A store cannot do both, and a screen rendering this would say both.`);
 }

 const swiftStore = s => `        .init(id: ${swift(s.id)}, platform: ${swift(s.platform)}, kind: ${swift(s.kind)},
              heldIn: ${swift(s.where)},
              survives: ${swiftList(s.survives)},
              lostTo: ${swiftList(s.lostTo)},
              saysSurvives: [${s.says.survives.map(line => `\n                  ${swift(line)}`).join(',')}],
              saysLostTo: [${s.says.lostTo.map(line => `\n                  ${swift(line)}`).join(',')}])`;

 const swiftFile = `${banner()}

import Foundation

enum CaptureData {
    /// Something that can happen to a phone or a tab, named once so two platforms cannot call the
    /// same event by two names and then disagree about it without anybody noticing.
    struct DurabilityEvent: Identifiable, Hashable { let id: String; let name: String }
    /// One place work waits. \`survives\` and \`lostTo\` are behaviour; \`saysSurvives\` and
    /// \`saysLostTo\` are the sentences a screen renders, and they are deliberately separate fields.
    struct Store: Identifiable, Hashable {
        let id: String
        let platform: String
        /// "file" or "memory". A memory store is one that says out loud that it keeps nothing.
        let kind: String
        let heldIn: String
        let survives: [String]
        let lostTo: [String]
        let saysSurvives: [String]
        let saysLostTo: [String]
    }

${d._note.match(/.{1,94}(\s|$)/g).map(line => `    // ${line.trim()}`).join('\n')}
    static let durabilityEvents: [DurabilityEvent] = [
${d.events.map(e => `        .init(id: ${swift(e.id)}, name: ${swift(e.name)})`).join(',\n')}
    ]
    static func durabilityEvent(_ id: String) -> DurabilityEvent? { durabilityEvents.first { $0.id == id } }

    static let stores: [Store] = [
${d.stores.map(swiftStore).join(',\n')}
    ]
    /// The stores this platform actually has. A screen asks for its own and never renders another
    /// platform's promise, which is how three sets of sentences became one contract in the first
    /// place.
    static func stores(on platform: String) -> [Store] { stores.filter { $0.platform == platform } }
    static func store(_ id: String) -> Store? { stores.first { $0.id == id } }

    /// ${d.quarantinedFile.why}
    static let quarantinedFile = ${swift(d.quarantinedFile.sentence)}
    /// ${d.notEncrypted.why}
    static let notEncrypted = ${swift(d.notEncrypted.sentence)}
}
`;

 /* Kotlin cannot infer the element type of an empty listOf(), and the web store says nothing at all
    about what it survives — there is nothing for it to say. So an empty one is written with its type
    on it rather than left for a compiler to guess at. */
 const saysList = lines => (lines.length
  ? `listOf(${lines.map(line => `\n            ${kotlin(line)}`).join(',')}\n        )`
  : 'emptyList<String>()');

 const kotlinStore = s => `    QueueStore(
        ${kotlin(s.id)}, ${kotlin(s.platform)}, ${kotlin(s.kind)},
        ${kotlin(s.where)},
        ${kotlinList(s.survives)},
        ${kotlinList(s.lostTo)},
        ${saysList(s.says.survives)},
        ${saysList(s.says.lostTo)}
    )`;

 const kotlinFile = `${banner()}

package za.co.mythuso.model

/**
 * Something that can happen to a phone or a tab, named once so two platforms cannot call the same
 * event by two names and then disagree about it without anybody noticing.
 */
data class DurabilityEvent(val id: String, val name: String)

/**
 * One place work waits. survives and lostTo are behaviour; saysSurvives and saysLostTo are the
 * sentences a screen renders, and they are deliberately separate fields.
 */
data class QueueStore(
    val id: String,
    val platform: String,
    /** "file" or "memory". A memory store is one that says out loud that it keeps nothing. */
    val kind: String,
    val heldIn: String,
    val survives: List<String>,
    val lostTo: List<String>,
    val saysSurvives: List<String>,
    val saysLostTo: List<String>
)

${d._note.match(/.{1,94}(\s|$)/g).map((line, i) => `${i ? '   ' : '/* '}${line.trim()}`).join('\n')} */
val durabilityEvents = listOf(
${d.events.map(e => `    DurabilityEvent(${kotlin(e.id)}, ${kotlin(e.name)}),`).join('\n')}
)

val queueStores = listOf(
${d.stores.map(store => kotlinStore(store) + ',').join('\n')}
)

object CaptureData {
    fun durabilityEvent(id: String) = durabilityEvents.firstOrNull { it.id == id }
    /* The stores this platform actually has. A screen asks for its own and never renders another
       platform's promise, which is how three sets of sentences became one contract in the first
       place. */
    fun stores(platform: String) = queueStores.filter { it.platform == platform }
    fun store(id: String) = queueStores.firstOrNull { it.id == id }

    /* ${d.quarantinedFile.why} */
    const val quarantinedFile = ${kotlin(d.quarantinedFile.sentence)}
    /* ${d.notEncrypted.why} */
    const val notEncrypted = ${kotlin(d.notEncrypted.sentence)}
}
`;

 return [
  { path: 'apps/ios/MyThuso/Models/CaptureData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/CaptureData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitCapture()) {
  writeFileSync(file.path, file.content);
  console.log(`capture → ${file.path}`);
 }
}
