/* The case pathway's two cited numbers and the seven condition titles, written out for the web by a
   machine.

   packages/catalog/case.json types no number: the indicative ranges are packages/catalog/records.json's
   and the very-high line is the one packages/catalog/knowledge/conditions.json gives in cond-008's
   whenToSeeDoctor sentence. The web cannot import the knowledge base for one sentence — sixty-four
   entries would travel into the assistant's chunk to read a pair out of one of them — so this reads
   the pair out of the sentence here, once, and writes it beside the citation it came from. A sentence
   that no longer carries exactly one top-over-bottom pair stops the generator rather than falling back
   to a number somebody typed.

   The condition titles are written so the nurse's screen can say "Behind it: Hypertension (cond-008)"
   without the entry, and every id case.json's findings name is held to an entry that lists headache. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const CASE = 'packages/catalog/case.json';
const CONDITIONS = 'packages/catalog/knowledge/conditions.json';
const INTAKE = 'packages/catalog/symptom-intake.json';

const PAIR = /(?<![a-z0-9])(\d{2,3})\s*\/\s*(\d{2,3})(?![a-z0-9])/gi;

export function emitCase(root = '') {
 const contract = JSON.parse(readFileSync(root + CASE, 'utf8'));
 const conditions = JSON.parse(readFileSync(root + CONDITIONS, 'utf8'));
 const intake = JSON.parse(readFileSync(root + INTAKE, 'utf8'));
 const cited = contract.pathway.bands['very-high'].from;
 const [file, path] = cited.split('#');
 if (file !== CONDITIONS) throw new Error(`${CASE} cites the very-high line from ${file}; this generator reads ${CONDITIONS}.`);
 const [conditionId, field] = path.split('.');
 const entry = conditions.find(c => c.id === conditionId);
 if (!entry || typeof entry[field] !== 'string') throw new Error(`${CONDITIONS} has no ${conditionId}.${field} to read the very-high line from.`);
 const pairs = [...entry[field].matchAll(PAIR)];
 if (pairs.length !== 1) throw new Error(`${conditionId}.${field} carries ${pairs.length} top-over-bottom pairs; the pathway reads exactly one.`);
 const veryHigh = { systolic: Number(pairs[0][1]), diastolic: Number(pairs[0][2]) };

 const group = intake.groups.find(g => Array.isArray(g.questionsFrom));
 if (!group) throw new Error(`${INTAKE} has no group with questionsFrom, so there is no pathway to write.`);
 const ids = [...new Set([...group.questionsFrom, ...contract.findings.rules.flatMap(r => r.conditionIds)])].sort();
 const titles = ids.map(id => {
  const found = conditions.find(c => c.id === id);
  if (!found) throw new Error(`${id} is named by ${CASE} or ${INTAKE} and ${CONDITIONS} has no such entry.`);
  return [id, found.title];
 });

 const target = 'apps/web/src/lib/case-pathway.generated.ts';
 const lines = [
  `/* Generated by scripts/emit-case.mjs from ${CASE}, ${CONDITIONS} and ${INTAKE}.`,
  '   Do not edit by hand — run `npm run case`. The build fails if this file and its sources disagree.',
  '',
  '   The one pair of numbers the case pathway does not take from records.json: the line the knowledge',
  `   base gives for urgent care, read out of ${conditionId}'s own sentence rather than typed. */`,
  '',
  'export const veryHighLine = {',
  `  citedFrom: ${JSON.stringify(cited)},`,
  `  systolic: ${veryHigh.systolic},`,
  `  diastolic: ${veryHigh.diastolic},`,
  `  sentence: ${JSON.stringify(entry[field])}`,
  '} as const;',
  '',
  '/* The knowledge-base entries the headache questions and the findings draw on, by id and title. */',
  'export const pathwayConditions: Readonly<Record<string, string>> = {',
  ...titles.map(([id, title], i) => `  ${JSON.stringify(id)}: ${JSON.stringify(title)}${i < titles.length - 1 ? ',' : ''}`),
  '};',
  ''
 ];
 return [{ path: target, content: lines.join('\n') }];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitCase()) {
  writeFileSync(file.path, file.content);
  console.log(`case → ${file.path}`);
 }
}
