/* Booking a visit and the thread about it, written out for two native apps by a machine.

   packages/catalog/booking.json holds the words of the person step, the review, the three booking
   states, the visit thread, the handover desk and Access's settings. The web and packages/engines read
   it; iOS and Android cannot read JSON at runtime, so this writes BookingData.swift and BookingData.kt
   and scripts/check-boundaries.mjs compares both with what this would write on every build.

   WHAT IS RESOLVED HERE RATHER THAN COPIED. A refusal a route answers with is the route's sentence, in
   packages/catalog/apis/access.json; booking.json names it by route and id, and this looks it up — so a
   phone renders the route's own words, and a refusal booking.json names that the route does not
   declare stops the build instead of compiling an empty string. The badge a nurse must hold is the
   verified tier's name and sentence in packages/catalog/trust.json. The emergency numbers in the
   thread's "nobody watches" sentence and in what GilbertOne says out of hours are packages/catalog/sos.json's.
   The names of the roles who answer a handover are packages/catalog/vetting.json's. None is typed twice.

   ACCESS'S SETTINGS. Neither phone has an admin surface, so each uses the default of each Access setting
   as the contract gives it, written through scripts/settings-defaults.mjs with the sentence saying it is a
   proposal nobody has decided. The longest thread message, the hours a thread stays open after its visit,
   whether photos are on, the named-nurse fallback, who answers a handover and the desk's hours are all
   here and nowhere else on a phone.

   WHAT IS NOT EMITTED. Prices, durations and the cancellation window. Each native app already reads
   services and the window from its own generated or catalogued source, and a second copy here would be
   a price that can disagree with the one on the service row.

   Escaping: Swift needs its quotes escaped; Kotlin needs backslash, quote and dollar, because a lone $
   starts a template. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { settingDefault } from './settings-defaults.mjs';

const SOURCE = 'packages/catalog/booking.json';

const swift = value => `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const kotlin = value => `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
const optSwift = value => (value === null || value === undefined ? 'nil' : swift(value));
const optKotlin = value => (value === null || value === undefined ? 'null' : kotlin(value));

const banner = () => [
 `Generated by scripts/emit-booking.mjs from ${SOURCE}, with refusals from packages/catalog/apis/access.json,`,
 'the badge from packages/catalog/trust.json, the emergency numbers from packages/catalog/sos.json and role',
 'names from packages/catalog/vetting.json.',
 'Do not edit by hand — run `npm run booking`. The build fails if this file and its sources disagree,',
 'so an edit here is lost rather than merely wrong.',
 '',
 'Nothing here books anybody. The booking and messaging capabilities are simulated, and every screen that',
 'reads this says so from the capabilities contract.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function resolveBooking(root = '') {
 const read = file => JSON.parse(readFileSync(root + file, 'utf8'));
 const contract = read(SOURCE);
 const access = read('packages/catalog/apis/access.json');
 const trust = read('packages/catalog/trust.json');
 const sos = read('packages/catalog/sos.json');
 const vetting = read('packages/catalog/vetting.json');

 const tier = trust.tiers.find(t => t.id === contract.person.badge.tier);
 if (!tier) throw new Error(`${SOURCE} names the badge tier "${contract.person.badge.tier}", which packages/catalog/trust.json does not have.`);
 const number = id => {
  const found = sos.emergency.numbers.find(n => n.id === id);
  if (!found) throw new Error(`packages/catalog/sos.json has no emergency number "${id}".`);
  return found.number;
 };
 const say = text => text.replace(/\{(ambulance|mobile)\}/g, (_, id) => number(id));
 const roleName = id => {
  const found = vetting.roles.find(r => r.id === id);
  if (!found) throw new Error(`${SOURCE} names the role "${id}", which packages/catalog/vetting.json does not have.`);
  return found.name;
 };
 const routeRefusals = contract.routeRefusals.map(({ route, id }) => {
  const declared = access.routes.find(r => `${r.method} ${r.path}@${r.version}` === route);
  if (!declared) throw new Error(`${SOURCE} names a refusal of ${route}, which packages/catalog/apis/access.json does not declare.`);
  const refusal = declared.refusals.find(r => r.id === id);
  if (!refusal) throw new Error(`${SOURCE} names the refusal "${id}" of ${route}, which the route does not declare.`);
  return { id, route, status: refusal.status, sentence: refusal.statement };
 });
 const refusals = [...contract.refusals.map(r => ({ id: r.id, route: null, status: null, sentence: r.sentence })), ...routeRefusals];
 const settings = {
  fallback: settingDefault(SOURCE, contract, 'named-nurse-fallback'),
  maxCharacters: settingDefault(SOURCE, contract, 'visit-thread-max-characters'),
  photos: settingDefault(SOURCE, contract, 'visit-thread-photos'),
  openHours: settingDefault(SOURCE, contract, 'visit-thread-open-hours-after-visit'),
  answeredBy: settingDefault(SOURCE, contract, 'handover-answered-by'),
  hours: settingDefault(SOURCE, contract, 'handover-hours')
 };
 /* That every value the fallback may take has a rule, and every rule is a value, is scripts/check-boundaries.mjs's to hold. */
 if (!contract.person.fallback.rules.some(rule => rule.setting === settings.fallback.value)) throw new Error(`${SOURCE} defaults named-nurse-fallback to "${settings.fallback.value}", which has no rule in person.fallback, so a phone could not say what happens.`);
 return { contract, tier, say, refusals, settings, roleName };
}

export function emitBooking(root = '') {
 const { contract, tier, say, refusals, settings, roleName } = resolveBooking(root);
 const { person, time, review, thread, handover } = contract;
 const { fallback } = person;

 const swiftFile = `${banner()}

import Foundation

enum BookingData {
    static let publishes: [String] = [${contract.publishes.map(swift).join(', ')}]

    enum Person {
        static let stepLabel = ${swift(person.stepLabel)}
        static let heading = ${swift(person.heading)}
        static let lead = ${swift(person.lead)}
        static let options: [BookingPersonOption] = [
${person.options.map(o => `            .init(id: ${swift(o.id)}, name: ${swift(o.name)}, detail: ${swift(o.detail)})`).join(',\n')}
        ]
        /// The take-visit gate decides whether a badge is current; the words are trust.json's verified tier.
        static let badgeCapability = ${swift(person.badge.decidedBy)}
        static let badgeName = ${swift(tier.name)}
        static let badgeSentence = ${swift(tier.sentence)}
        static let worksIn = ${swift(person.worksIn)}
        static let namedHeading = ${swift(person.namedHeading)}
        static let notOfferedHeading = ${swift(person.notOfferedHeading)}
        static let noPrevious = ${swift(person.noPrevious)}
        static let previousNotOffered = ${swift(person.previousNotOffered)}
        static let asapNeedsNearest = ${swift(person.asapNeedsNearest)}
        static let continuity = ${swift(person.continuity)}
    }

    /// What happens to a visit asked of one nurse by name when she cannot take it in Care's offer window.
    enum Fallback {
        /// Access's setting named-nurse-fallback. ${settings.fallback.note}
        static let inForce = ${swift(settings.fallback.value)}
        static let heading = ${swift(fallback.heading)}
        static let rules: [BookingFallbackRule] = [
${fallback.rules.map(r => `            .init(setting: ${swift(r.setting)}, offersAsap: ${r.offersAsap}, asksPatient: ${r.asksPatient}, resolvesTo: ${optSwift(r.resolvesTo)}, sentence: ${swift(r.sentence)})`).join(',\n')}
        ]
        static let choices: [BookingFallbackChoice] = [
${fallback.choices.map(c => `            .init(id: ${swift(c.id)}, name: ${swift(c.name)}, sentence: ${swift(c.sentence)})`).join(',\n')}
        ]
        static let reviewLabel = ${swift(fallback.reviewLabel)}
    }

    enum Time {
        static let fewerHours = ${swift(time.fewerHours)}
        static let noHoursLeft = ${swift(time.noHoursLeft)}
    }

    enum Review {
        static let nurseLabel = ${swift(review.nurseLabel)}
        static let nearestValue = ${swift(review.nearestValue)}
        static let priceLabel = ${swift(review.priceLabel)}
        static let cancellingLabel = ${swift(review.cancellingLabel)}
    }

    static let states: [BookingStateWords] = [
${contract.states.map(s => `        .init(id: ${swift(s.id)}, name: ${swift(s.name)}, patientWords: ${swift(s.patientWords)}, event: ${swift(s.event)})`).join(',\n')}
    ]
    static let transitions: [BookingTransition] = [
${contract.transitions.map(t => `        .init(from: ${optSwift(t.from)}, to: ${swift(t.to)})`).join(',\n')}
    ]
    static let statusHeading = ${swift(contract.statusHeading)}
    enum StatusWords {
        static let reached = ${swift(contract.statusWords.reached)}
        static let current = ${swift(contract.statusWords.current)}
        static let waiting = ${swift(contract.statusWords.waiting)}
    }
    static let acceptedBy = ${swift(contract.acceptedBy)}
    static let asapStaysRequested = ${swift(contract.asapStaysRequested)}

    /// booking.json's own refusals, then the routes' refusals it names, each in the route's words.
    static let refusals: [BookingRefusal] = [
${refusals.map(r => `        .init(id: ${swift(r.id)}, route: ${optSwift(r.route)}, status: ${r.status ?? 'nil'}, sentence: ${swift(r.sentence)})`).join(',\n')}
    ]

    enum Thread {
        static let title = ${swift(thread.title)}
        static let openLabel = ${swift(thread.openLabel)}
        static let lead = ${swift(thread.lead)}
        static let notARecord = ${swift(thread.notARecord)}
        static let nobodyWatches = ${swift(say(thread.nobodyWatches))}
        static let inputLabel = ${swift(thread.inputLabel)}
        static let sendLabel = ${swift(thread.sendLabel)}
        /// Access's setting visit-thread-max-characters. ${settings.maxCharacters.note}
        static let maxCharacters = ${settings.maxCharacters.value}
        /// Access's setting visit-thread-open-hours-after-visit. ${settings.openHours.note}
        static let openHoursAfterVisit = ${settings.openHours.value}
        /// Access's setting visit-thread-photos, which waits on a doctor's clinical review. ${settings.photos.note}
        static let photos = ${settings.photos.value}
        static let empty = ${swift(thread.empty)}
        static let kept = ${swift(thread.kept)}
        static let you = ${swift(thread.you)}
        static let openAfterVisit = ${swift(thread.openAfterVisit)}
        static let wordsOnly = ${swift(thread.wordsOnly)}
        static let photosNotInPreview = ${swift(thread.photosNotInPreview)}
        static let closedBecause: [BookingThreadClosed] = [
${thread.closedBecause.map(c => `            .init(id: ${swift(c.id)}, sentence: ${swift(c.sentence)})`).join(',\n')}
        ]
    }

    /// Who answers a GilbertOne handover and when. The emergency numbers are sos.json's and are not a setting.
    enum Handover {
        /// Access's setting handover-answered-by, as vetting.json names the roles. ${settings.answeredBy.note}
        static let answeredBy: [String] = [${settings.answeredBy.value.map(id => swift(roleName(id))).join(', ')}]
        /// Access's setting handover-hours, in Johannesburg time. ${settings.hours.note}
        static let hours: [HandoverWindow] = [
${settings.hours.value.map(w => `            .init(post: ${swift(w.post)}, days: [${w.days.map(swift).join(', ')}], from: ${swift(w.from)}, to: ${swift(w.to)})`).join(',\n')}
        ]
        static let answeredByLabel = ${swift(handover.answeredByLabel)}
        static let outOfHours = ${swift(handover.outOfHours)}
        static let outOfHoursNumbers = ${swift(say(handover.outOfHoursNumbers))}
        static let callback = ${swift(handover.callback)}
        static let opensToday = ${swift(handover.opensToday)}
        static let opensTomorrow = ${swift(handover.opensTomorrow)}
        static let opensOn = ${swift(handover.opensOn)}
    }
}
`;

 const kotlinFile = `${banner()}

package za.co.mythuso.model

object BookingData {
    val publishes = listOf(${contract.publishes.map(kotlin).join(', ')})

    object Person {
        const val stepLabel = ${kotlin(person.stepLabel)}
        const val heading = ${kotlin(person.heading)}
        const val lead = ${kotlin(person.lead)}
        val options = listOf(
${person.options.map(o => `            BookingPersonOption(${kotlin(o.id)}, ${kotlin(o.name)}, ${kotlin(o.detail)})`).join(',\n')}
        )
        /** The take-visit gate decides whether a badge is current; the words are trust.json's verified tier. */
        const val badgeCapability = ${kotlin(person.badge.decidedBy)}
        const val badgeName = ${kotlin(tier.name)}
        const val badgeSentence = ${kotlin(tier.sentence)}
        const val worksIn = ${kotlin(person.worksIn)}
        const val namedHeading = ${kotlin(person.namedHeading)}
        const val notOfferedHeading = ${kotlin(person.notOfferedHeading)}
        const val noPrevious = ${kotlin(person.noPrevious)}
        const val previousNotOffered = ${kotlin(person.previousNotOffered)}
        const val asapNeedsNearest = ${kotlin(person.asapNeedsNearest)}
        const val continuity = ${kotlin(person.continuity)}
    }

    /** What happens to a visit asked of one nurse by name when she cannot take it in Care's offer window. */
    object Fallback {
        /** Access's setting named-nurse-fallback. ${settings.fallback.note} */
        const val inForce = ${kotlin(settings.fallback.value)}
        const val heading = ${kotlin(fallback.heading)}
        val rules = listOf(
${fallback.rules.map(r => `            BookingFallbackRule(${kotlin(r.setting)}, ${r.offersAsap}, ${r.asksPatient}, ${optKotlin(r.resolvesTo)}, ${kotlin(r.sentence)})`).join(',\n')}
        )
        val choices = listOf(
${fallback.choices.map(c => `            BookingFallbackChoice(${kotlin(c.id)}, ${kotlin(c.name)}, ${kotlin(c.sentence)})`).join(',\n')}
        )
        const val reviewLabel = ${kotlin(fallback.reviewLabel)}
    }

    object Time {
        const val fewerHours = ${kotlin(time.fewerHours)}
        const val noHoursLeft = ${kotlin(time.noHoursLeft)}
    }

    object Review {
        const val nurseLabel = ${kotlin(review.nurseLabel)}
        const val nearestValue = ${kotlin(review.nearestValue)}
        const val priceLabel = ${kotlin(review.priceLabel)}
        const val cancellingLabel = ${kotlin(review.cancellingLabel)}
    }

    val states = listOf(
${contract.states.map(s => `        BookingStateWords(${kotlin(s.id)}, ${kotlin(s.name)}, ${kotlin(s.patientWords)}, ${kotlin(s.event)})`).join(',\n')}
    )
    val transitions = listOf(
${contract.transitions.map(t => `        BookingTransition(${optKotlin(t.from)}, ${kotlin(t.to)})`).join(',\n')}
    )
    const val statusHeading = ${kotlin(contract.statusHeading)}
    object StatusWords {
        const val reached = ${kotlin(contract.statusWords.reached)}
        const val current = ${kotlin(contract.statusWords.current)}
        const val waiting = ${kotlin(contract.statusWords.waiting)}
    }
    const val acceptedBy = ${kotlin(contract.acceptedBy)}
    const val asapStaysRequested = ${kotlin(contract.asapStaysRequested)}

    /** booking.json's own refusals, then the routes' refusals it names, each in the route's words. */
    val refusals = listOf(
${refusals.map(r => `        BookingRefusal(${kotlin(r.id)}, ${optKotlin(r.route)}, ${r.status ?? 'null'}, ${kotlin(r.sentence)})`).join(',\n')}
    )

    object Thread {
        const val title = ${kotlin(thread.title)}
        const val openLabel = ${kotlin(thread.openLabel)}
        const val lead = ${kotlin(thread.lead)}
        const val notARecord = ${kotlin(thread.notARecord)}
        const val nobodyWatches = ${kotlin(say(thread.nobodyWatches))}
        const val inputLabel = ${kotlin(thread.inputLabel)}
        const val sendLabel = ${kotlin(thread.sendLabel)}
        /** Access's setting visit-thread-max-characters. ${settings.maxCharacters.note} */
        const val maxCharacters = ${settings.maxCharacters.value}
        /** Access's setting visit-thread-open-hours-after-visit. ${settings.openHours.note} */
        const val openHoursAfterVisit = ${settings.openHours.value}
        /** Access's setting visit-thread-photos, which waits on a doctor's clinical review. ${settings.photos.note} */
        const val photos = ${settings.photos.value}
        const val empty = ${kotlin(thread.empty)}
        const val kept = ${kotlin(thread.kept)}
        const val you = ${kotlin(thread.you)}
        const val openAfterVisit = ${kotlin(thread.openAfterVisit)}
        const val wordsOnly = ${kotlin(thread.wordsOnly)}
        const val photosNotInPreview = ${kotlin(thread.photosNotInPreview)}
        val closedBecause = listOf(
${thread.closedBecause.map(c => `            BookingThreadClosed(${kotlin(c.id)}, ${kotlin(c.sentence)})`).join(',\n')}
        )
    }

    /** Who answers a GilbertOne handover and when. The emergency numbers are sos.json's and are not a setting. */
    object Handover {
        /** Access's setting handover-answered-by, as vetting.json names the roles. ${settings.answeredBy.note} */
        val answeredBy = listOf(${settings.answeredBy.value.map(id => kotlin(roleName(id))).join(', ')})
        /** Access's setting handover-hours, in Johannesburg time. ${settings.hours.note} */
        val hours = listOf(
${settings.hours.value.map(w => `            HandoverWindow(${kotlin(w.post)}, listOf(${w.days.map(kotlin).join(', ')}), ${kotlin(w.from)}, ${kotlin(w.to)})`).join(',\n')}
        )
        const val answeredByLabel = ${kotlin(handover.answeredByLabel)}
        const val outOfHours = ${kotlin(handover.outOfHours)}
        const val outOfHoursNumbers = ${kotlin(say(handover.outOfHoursNumbers))}
        const val callback = ${kotlin(handover.callback)}
        const val opensToday = ${kotlin(handover.opensToday)}
        const val opensTomorrow = ${kotlin(handover.opensTomorrow)}
        const val opensOn = ${kotlin(handover.opensOn)}
    }
}
`;

 return {
  swift: { path: 'apps/ios/MyThuso/Models/BookingData.swift', content: swiftFile },
  kotlin: { path: 'apps/android/app/src/main/java/za/co/mythuso/model/BookingData.kt', content: kotlinFile }
 };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 const { swift: s, kotlin: k } = emitBooking();
 writeFileSync(s.path, s.content);
 writeFileSync(k.path, k.content);
 console.log(`wrote ${s.path}\nwrote ${k.path}`);
}
