/* The vetting table, written out for two native apps, by a machine.

   The roles, the checks, the capabilities, the issuing authorities and
   every refusal sentence live in packages/catalog/vetting.json. The web reads that file. iOS and Android cannot,
   and should not: an app that parses JSON to draw a list is a web app wearing a Compose hat. So the
   table was hand-mirrored into Swift and Kotlin and a boundary check compared roughly two hundred
   substrings to keep the three honest.

   The check was doing the right job the wrong way round. Comparing hand-written copies can only
   ever notice drift after somebody introduces it; generating the copies means the drift has nowhere
   to come from. What comes out is ordinary Swift and Kotlin source, compiled into the binaries.

   Only the tables are generated. The credential validators, the lifecycle arithmetic, the 45-day
   window, the second-reviewer rule, summarise(), can() and the fixtures stay hand-written where
   they are, because they are decisions rather than data.

   Escaping is the hazard here, and the two languages disagree about it:
     - Swift takes a regex raw, #"^\d{8}$"#, so the backslash survives to the regex engine.
     - Kotlin takes it escaped, "^\\d{8}\$", because a lone backslash is an escape and a lone $
       starts a string template.
   Refusal sentences and check details carry en-dashes, em-dashes and apostrophes; those are simply
   UTF-8 and need nothing, which is worth knowing rather than guessing at. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/catalog/vetting.json';

/* Swift: a value carrying a backslash goes into a raw string so the backslash is the character it
   looks like. Everything else is an ordinary literal with quotes and backslashes escaped. */
const swift = value => {
 if (value.includes('\\')) {
  if (value.includes('"#')) throw new Error(`Cannot write ${JSON.stringify(value)} as a Swift raw string`);
  return `#"${value}"#`;
 }
 return `"${value.replace(/"/g, '\\"')}"`;
};
/* Kotlin: backslash, quote and dollar all mean something inside a literal. The dollar is escaped
   unconditionally — "$" at the end of a regex happens to be harmless, and relying on that is how a
   generator earns a bug the first time a sentence mentions a price. */
const kotlin = value => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;

const swiftInt = value => (value === null ? 'nil' : String(value));
const kotlinInt = value => (value === null ? 'null' : String(value));

const banner = () => [
 `Generated by scripts/emit-vetting.mjs from ${SOURCE}.`,
 'Do not edit by hand — run `npm run vetting`. The build fails if this file and the vetting source',
 'disagree, so an edit here is lost rather than merely wrong.',
 '',
 'The ids, credential formats, refusal sentences and scope options are the contract itself. The',
 'lifecycle, the validators and the fixtures that use this table are hand-written in Vetting.swift',
 'and Vetting.kt beside it.'
].map(line => (line ? `// ${line}` : '//')).join('\n');

export function emitVetting(root = '') {
 const table = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const scoped = table.roles.filter(role => role.scope);

 /* ---- iOS ------------------------------------------------------------------------------------
    An extension rather than the enum itself, so Vetting.swift keeps ownership of the type and of
    every function that reasons about it. */
 const swiftFile = `${banner()}

import Foundation

extension Vetting {
    static let capabilities: [VettingCapability] = [
${table.capabilities.map(c => `        .init(id: ${swift(c.id)}, name: ${swift(c.name)}, detail: ${swift(c.detail)})`).join(',\n')}
    ]
    /* The formats are the ones the issuing bodies actually use, so the preview can say "that is not
       a SANC number" locally, without sending anything anywhere. The numbers entered are fictional. */
    static let authorities: [VettingAuthority] = [
${table.authorities.map(a => `        .init(id: ${swift(a.id)}, name: ${swift(a.name)}, short: ${swift(a.short)},
              verifies: ${swift(a.verifies)}, format: ${swift(a.format)},
              pattern: ${swift(a.pattern)}, example: ${swift(a.example)}, hint: ${swift(a.hint)})`).join(',\n')}
    ]
    static let roles: [VettedRole] = [
${table.roles.map(role => `        VettedRole(id: ${swift(role.id)}, name: ${swift(role.name)}, party: ${swift(role.party)}, workspace: ${swift(role.workspace)},
                   summary: ${swift(role.summary)},
                   grants: [
${role.grants.map(g => `                    .init(capability: ${swift(g.capability)}, refusal: ${swift(g.refusal)})`).join(',\n')}
                   ],
                   checks: [
${role.checks.map(c => `                    .init(id: ${swift(c.id)}, name: ${swift(c.name)}, detail: ${swift(c.detail)}, authority: ${swift(c.authority)}, evidence: ${swift(c.evidence)}, renewMonths: ${swiftInt(c.renewMonths)}, risk: ${swift(c.risk)}, gate: ${swift(c.gate)})`).join(',\n')}
                   ])`).join(',\n')}
    ]
    static let scopes: [String: RoleScope] = [
${scoped.map(role => `        ${swift(role.id)}: RoleScope(label: ${swift(role.scope.label)}, note: ${swift(role.scope.note)},
                        options: [${role.scope.options.map(swift).join(', ')}])`).join(',\n')}
    ]
    /* The seven onboarding gates, in order, each with the rule a person is refused under and the
       sentence they are shown. The fail rules are rendered word for word from here. */
    static let gates: [VettingGate] = [
${table.gates.map(g => `        .init(id: ${swift(g.id)}, order: ${g.order}, name: ${swift(g.name)}, hardStop: ${g.hardStop}, evidencedBy: ${g.evidencedBy ? swift(g.evidencedBy) : 'nil'},
              failRule: ${swift(g.failRule)},
              statement: ${swift(g.statement)})`).join(',\n')}
    ]
    static let gateRules = VettingGateRules(
        lapse: ${swift(table.gateRules.lapse)},
        suspended: ${swift(table.gateRules.suspended)},
        declined: ${swift(table.gateRules.declined)},
        notActivated: ${swift(table.gateRules.notActivated)},
        status: ${swift(table.gateRules.status)})
    /* Why no check sits at a gate, per role and per gate, in the role's own words. */
    static let gateNotes: [String: [String: VettingGateNote]] = [
${table.roles.map(role => `        ${swift(role.id)}: [${Object.entries(role.gateNotes).map(([gate, note]) => `
            ${swift(gate)}: VettingGateNote(kind: ${swift(note.kind)}, sentence: ${swift(note.sentence)})`).join(',')}${Object.keys(role.gateNotes).length ? '\n        ' : ':'}]`).join(',\n')}
    ]
}
`;

 /* ---- Android --------------------------------------------------------------------------------
    Top-level vals in za.co.mythuso.model, which is the name every screen already uses. */
 const kotlinFile = `${banner()}

package za.co.mythuso.model

val vettingCapabilities = listOf(
${table.capabilities.map(c => `    VettingCapability(${kotlin(c.id)}, ${kotlin(c.name)}, ${kotlin(c.detail)})`).join(',\n')}
)

/* The formats are the ones the issuing bodies actually use, so the phone can say "that is not a
   SANC number" on its own, without sending anything anywhere. The numbers entered are fictional. */
val vettingAuthorities = listOf(
${table.authorities.map(a => `    VettingAuthority(
        ${kotlin(a.id)}, ${kotlin(a.name)}, ${kotlin(a.short)},
        ${kotlin(a.verifies)}, ${kotlin(a.format)},
        ${kotlin(a.pattern)}, ${kotlin(a.example)}, ${kotlin(a.hint)}
    )`).join(',\n')}
)

val vettingRoles = listOf(
${table.roles.map(role => `    VettingRole(
        ${kotlin(role.id)}, ${kotlin(role.name)}, ${kotlin(role.party)}, ${kotlin(role.workspace)},
        ${kotlin(role.summary)},
        listOf(
${role.grants.map(g => `            VettingGrant(${kotlin(g.capability)}, ${kotlin(g.refusal)})`).join(',\n')}
        ),
        listOf(
${role.checks.map(c => `            VettingCheck(${kotlin(c.id)}, ${kotlin(c.name)}, ${kotlin(c.detail)}, ${kotlin(c.authority)}, ${kotlin(c.evidence)}, ${kotlinInt(c.renewMonths)}, ${kotlin(c.risk)}, ${kotlin(c.gate)})`).join(',\n')}
        )
    )`).join(',\n')}
)

val vettingScopes: Map<String, ScopeOfPractice> = mapOf(
${scoped.map(role => `    ${kotlin(role.id)} to ScopeOfPractice(
        ${kotlin(role.scope.label)},
        ${kotlin(role.scope.note)},
        listOf(${role.scope.options.map(kotlin).join(', ')})
    )`).join(',\n')}
)

/* The seven onboarding gates, in order, each with the rule a person is refused under and the
   sentence they are shown. The fail rules are rendered word for word from here. */
val vettingGates = listOf(
${table.gates.map(g => `    VettingGate(
        ${kotlin(g.id)}, ${g.order}, ${kotlin(g.name)}, ${g.hardStop}, ${g.evidencedBy ? kotlin(g.evidencedBy) : 'null'},
        ${kotlin(g.failRule)},
        ${kotlin(g.statement)}
    )`).join(',\n')}
)

val vettingGateRules = VettingGateRules(
    ${kotlin(table.gateRules.lapse)},
    ${kotlin(table.gateRules.suspended)},
    ${kotlin(table.gateRules.declined)},
    ${kotlin(table.gateRules.notActivated)},
    ${kotlin(table.gateRules.status)}
)

/* Why no check sits at a gate, per role and per gate, in the role's own words. */
val vettingGateNotes: Map<String, Map<String, VettingGateNote>> = mapOf(
${table.roles.map(role => `    ${kotlin(role.id)} to mapOf${Object.keys(role.gateNotes).length ? '' : '<String, VettingGateNote>'}(${Object.entries(role.gateNotes).map(([gate, note]) => `
        ${kotlin(gate)} to VettingGateNote(${kotlin(note.kind)}, ${kotlin(note.sentence)})`).join(',')}${Object.keys(role.gateNotes).length ? '\n    ' : ''})`).join(',\n')}
)
`;

 return [
  { path: 'apps/ios/MyThuso/Models/VettingData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/VettingData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitVetting()) {
  writeFileSync(file.path, file.content);
  console.log(`vetting → ${file.path}`);
 }
}
