/* One palette, written out three times, by a machine.

   The design language is described once in packages/design-tokens/tokens.json. Until now that file
   was a reference nobody read: the same eighteen colours were re-typed as CSS custom properties, as
   SwiftUI Color(red:green:blue:) and as Compose Color(0xFF…), and nothing checked that the three
   agreed. A palette drifting apart is not a clinical-safety problem the way a reference range is,
   but it is the seam nobody was watching, and a hand-converted colour channel is exactly the kind
   of thing a reviewer's eye slides over.

   Generating the native files does not make the apps less native. What comes out is SwiftUI source
   and Compose source, compiled into the binaries, parsing nothing at runtime — the same code
   somebody would have typed, minus the arithmetic.

   scripts/check-boundaries.mjs imports emitTokens() and compares what it returns against what is on
   disk, so a stale generated file and a hand-edited one both fail the build. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/design-tokens/tokens.json';

const kebab = name => name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
const pascal = name => name[0].toUpperCase() + name.slice(1);
const channel = (hex, index) => (parseInt(hex.slice(1 + index * 2, 3 + index * 2), 16) / 255).toFixed(3);

/* Two Compose names cannot be taken as they stand. `Body` reads as a layout slot rather than a text
   colour, and `Surface` is a material3 composable this package star-imports everywhere. Both were
   already renamed by hand in Theme.kt; the rename simply moved here. */
const composeNames = { body: 'BodyText', surface: 'SurfaceWhite' };

/* Two shadow names are load-bearing: styles.css says var(--shadow) and var(--shadow-raised) in
   rules this generator does not own. */
const cssShadowNames = { card: '--shadow', raised: '--shadow-raised' };

const banner = extension => {
 const lines = [
  `Generated by scripts/emit-tokens.mjs from ${SOURCE}.`,
  'Do not edit by hand — run `npm run tokens`. The build fails if this file and the token source',
  'disagree, so an edit here is lost rather than merely wrong.'
 ];
 if (extension === 'css') return `/* ${lines.join('\n   ')} */\n`;
 return lines.map(line => `// ${line}`).join('\n') + '\n';
};

export function emitTokens(root = '') {
 const tokens = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const colours = Object.entries(tokens.color);
 const radii = Object.entries(tokens.radius);
 const spacing = tokens.spacing;

 /* ---- Web ------------------------------------------------------------------------------------
    A separate file rather than a block inside styles.css, because a generated file has to be a
    file for the build to be able to tell that it is stale. */
 const css = banner('css') + ':root{\n'
  + colours.map(([name, hex]) => ` --${kebab(name)}:${hex.toLowerCase()};`).join('\n') + '\n'
  + radii.map(([name, value]) => ` --r-${kebab(name)}:${value}px;`).join('\n') + '\n'
  + spacing.map(value => ` --space-${value}:${value}px;`).join('\n') + '\n'
  + Object.entries(tokens.elevation).map(([name, value]) => ` ${cssShadowNames[name] ?? `--shadow-${kebab(name)}`}:${value};`).join('\n') + '\n'
  + Object.entries(tokens.typography.stacks).map(([name, stack]) => ` --font-${name}:${stack};`).join('\n') + '\n'
  + ` --motion-duration:${tokens.motion.durationMs}ms;\n`
  + '}\n';

 /* ---- iOS ------------------------------------------------------------------------------------
    The hex stays in a trailing comment because that is the number a designer recognises; the three
    channels are the number SwiftUI wants. Nobody should have to divide by 255 to review a palette. */
 const swiftColour = ([name, hex]) => `    static let ${name} = Color(red: ${channel(hex, 0)}, green: ${channel(hex, 1)}, blue: ${channel(hex, 2)})`;
 const swiftColours = colours.map(swiftColour);
 const widest = Math.max(...swiftColours.map(line => line.length));
 const swift = banner('swift') + `
import SwiftUI

enum ThusoTheme {
${swiftColours.map((line, index) => `${line.padEnd(widest)} // ${colours[index][1]}`).join('\n')}
}
enum ThusoRadius {
${radii.map(([name, value]) => `    static let ${name}: CGFloat = ${value}`).join('\n')}
}
enum ThusoSpacing {
${spacing.map(value => `    static let space${value}: CGFloat = ${value}`).join('\n')}
}
`;

 /* ---- Android --------------------------------------------------------------------------------
    Top-level vals in za.co.mythuso.ui, which is where every screen already reaches for them. */
 const kotlin = banner('kotlin') + `
package za.co.mythuso.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

${colours.map(([name, hex]) => `val ${composeNames[name] ?? pascal(name)} = Color(0xFF${hex.replace('#', '').toUpperCase()})`).join('\n')}

object ThusoRadius {
${radii.map(([name, value]) => `    val ${name} = ${value}.dp`).join('\n')}
}
object ThusoSpacing {
${spacing.map(value => `    val space${value} = ${value}.dp`).join('\n')}
}
`;

 return [
  { path: 'apps/web/src/tokens.generated.css', content: css },
  { path: 'apps/ios/MyThuso/DesignSystem/Tokens.swift', content: swift },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/ui/Tokens.kt', content: kotlin }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitTokens()) {
  writeFileSync(file.path, file.content);
  console.log(`tokens → ${file.path}`);
 }
}
