/* ThusoIQ Core's event contracts, written out for two native apps by a machine.

   packages/catalog/events.json declares the engines and the envelope, and lists the files that
   contribute an `events` array — itself, the assistant contract and the trust contract, which are
   written by other people against the same shape. This generator reads every one of those that
   exists and emits the three things a native app needs to talk about an event without typing its
   name: the type as a constant, the engine that owns it, and the version.

   WHAT IS DELIBERATELY NOT EMITTED. The payloads. A native app does not publish to the bus — no
   app in this repository does — and a payload description compiled into a phone is a second copy
   of a frozen shape that nobody would remember to regenerate. The envelope's never-list is not
   emitted either: it is enforced where events are declared, by scripts/check-boundaries.mjs, not
   at a call site on a phone.

   A source file that is listed and does not exist yet is skipped rather than refused, so that this
   contract can land before the contracts that contribute to it. The day one of them lands, the
   generated files stop matching and the build says to run `npm run events`.

   The lock. `eventFingerprint` is exported for scripts/check-boundaries.mjs and for whoever appends
   a line to packages/catalog/events.lock. It fingerprints the type, the version, the owner and each
   payload field's name, type and whether it is required — the shape a subscriber is built against —
   and nothing else, so rewording a `why` or adding a subscriber is not a version change and changing
   a field is. The type and version were not in it until 14 September, when person.under_review@1 and
   person.deactivated@1 were found sharing one fingerprint: same owner, same payload, so the lock could
   not tell one from the other. Every line was re-locked in that one change.

   Withdrawn versions are not emitted. A version withdrawn from the contract stays in events.json and
   in the lock as the record of what was frozen, and nothing may publish or subscribe to it — leaving
   it out of both apps is how neither of them can.

   Escaping: Swift needs its quotes escaped; Kotlin needs backslash, quote and dollar, because a
   lone $ starts a template. */

import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'packages/catalog/events.json';

const swift = value => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const kotlin = value => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;

export const eventFingerprint = event => createHash('sha256')
 .update(JSON.stringify({ type: event.type, version: event.version, owner: event.owner, payload: (event.payload ?? []).map(f => [f.field, f.type, f.required === true]) }))
 .digest('hex').slice(0, 16);

/* Every event from every source that exists, in source order. Shared with the check so the two can
   never disagree about which events there are. */
export function collectEvents(root = '') {
 const contract = JSON.parse(readFileSync(root + SOURCE, 'utf8'));
 const events = [];
 const skipped = [];
 for (const source of contract.sources) {
  if (!existsSync(root + source)) { skipped.push(source); continue; }
  const declared = JSON.parse(readFileSync(root + source, 'utf8')).events;
  if (declared === undefined) { skipped.push(source); continue; }
  if (!Array.isArray(declared)) throw new Error(`${source} has an "events" key that is not a list. Every source of events uses the shape in ${SOURCE}.`);
  for (const event of declared) events.push({ ...event, source });
 }
 return { contract, events, skipped };
}

const camel = type => type.split(/[._]/).map((part, i) => (i ? part[0].toUpperCase() + part.slice(1) : part)).join('');
const upper = type => type.replace(/[.]/g, '_').toUpperCase();

export function emitEvents(root = '') {
 const { contract, events: declared } = collectEvents(root);
 const events = declared.filter(e => !e.withdrawn);
 const types = [...new Set(events.map(e => e.type))];
 /* Two types that differ only in punctuation would collapse into one constant and one of them would
    silently vanish from both apps. */
 for (const [name, of] of [['Swift', camel], ['Kotlin', upper]]) {
  const seen = new Map();
  for (const type of types) {
   if (seen.has(of(type))) throw new Error(`${type} and ${seen.get(of(type))} become the same ${name} constant. Rename one of them in its contract.`);
   seen.set(of(type), type);
  }
 }

 const banner = [
  `Generated by scripts/emit-events.mjs from ${contract.sources.join(', ')}.`,
  'Do not edit by hand — run `npm run events`. The build fails if this file and its sources',
  'disagree, so an edit here is lost rather than merely wrong.',
  '',
  'Event types, their owning engine and their version. Nothing in this app publishes to a bus, and',
  'no payload shape is written here: a frozen shape compiled into a phone is a copy nobody regenerates.',
  'Withdrawn versions are left out, so no code in this app can name one.'
 ].map(line => (line ? `// ${line}` : '//')).join('\n');

 const swiftFile = `${banner}

import Foundation

enum EventsData {
    struct Engine: Identifiable { let id: String; let name: String; let productName: String }
    struct Event: Identifiable {
        let type: String; let version: Int; let owner: String
        var id: String { "\\(type)@\\(version)" }
    }

    static let contractVersion = ${contract.version}
    static let frozen = ${contract.frozen === true}

    static let engines: [Engine] = [
${contract.engines.map(e => `        Engine(id: ${swift(e.id)}, name: ${swift(e.name)}, productName: ${swift(e.productName)})`).join(',\n')}
    ]

    static let events: [Event] = [
${events.map(e => `        Event(type: ${swift(e.type)}, version: ${e.version}, owner: ${swift(e.owner)})`).join(',\n')}
    ]

    enum Types {
${types.map(t => `        static let ${camel(t)} = ${swift(t)}`).join('\n')}
    }

    static func owner(of type: String) -> String? { events.first { $0.type == type }?.owner }
}
`;

 const kotlinFile = `${banner}

package za.co.mythuso.model

object EventsData {
    data class Engine(val id: String, val name: String, val productName: String)
    data class Event(val type: String, val version: Int, val owner: String)

    const val CONTRACT_VERSION = ${contract.version}
    const val FROZEN = ${contract.frozen === true}

    val engines = listOf(
${contract.engines.map(e => `        Engine(${kotlin(e.id)}, ${kotlin(e.name)}, ${kotlin(e.productName)})`).join(',\n')}
    )

    val events = listOf(
${events.map(e => `        Event(${kotlin(e.type)}, ${e.version}, ${kotlin(e.owner)})`).join(',\n')}
    )

    object Types {
${types.map(t => `        const val ${upper(t)} = ${kotlin(t)}`).join('\n')}
    }

    fun ownerOf(type: String) = events.firstOrNull { it.type == type }?.owner
}
`;

 return [
  { path: 'apps/ios/MyThuso/Models/EventsData.swift', content: swiftFile },
  { path: 'apps/android/app/src/main/java/za/co/mythuso/model/EventsData.kt', content: kotlinFile }
 ];
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
 for (const file of emitEvents()) {
  writeFileSync(file.path, file.content);
  console.log(`events → ${file.path}`);
 }
}
