// Generated by scripts/emit-booking.mjs from packages/catalog/booking.json, with refusals from packages/catalog/apis/access.json,
// the badge from packages/catalog/trust.json, the emergency numbers from packages/catalog/sos.json and role
// names from packages/catalog/vetting.json.
// Do not edit by hand — run `npm run booking`. The build fails if this file and its sources disagree,
// so an edit here is lost rather than merely wrong.
//
// Nothing here books anybody. The booking and messaging capabilities are simulated, and every screen that
// reads this says so from the capabilities contract.

package za.co.mythuso.model

object BookingData {
    val publishes = listOf("booking.requested@2", "booking.confirmed@2", "booking.cancelled@1", "conversation.handover@1")

    object Person {
        const val stepLabel = "Nurse"
        const val heading = "Who would you like to come?"
        const val lead = "Every nurse offered here is cleared to enter a home today. Ask for one by name, or let the roster send whoever is nearest."
        val options = listOf(
            BookingPersonOption("nearest", "Whoever is nearest and cleared", "The nearest nurse whose badge is current takes the visit. You are told who before anybody sets off."),
            BookingPersonOption("previous", "The nurse you saw last time", "Offered only while her badge is still current. If it is not, the reason is shown instead of her name."),
            BookingPersonOption("named", "A nurse you choose by name", "From the nurses whose badge is current, nearest first.")
        )
        /** The take-visit gate decides whether a badge is current; the words are trust.json's verified tier. */
        const val badgeCapability = "take-visit"
        const val badgeName = "Verified"
        const val badgeSentence = "Identity, credentials and background are all in order today."
        const val worksIn = "Works in {zone}"
        const val namedHeading = "Nurses you can ask for"
        const val notOfferedHeading = "Not offered, and why"
        const val noPrevious = "There is no earlier visit for {person}, so there is nobody to ask for again."
        const val previousNotOffered = "The nurse {person} saw last time is not being offered. {reason}"
        const val asapNeedsNearest = "As soon as someone is free means whoever is nearest. To see one nurse in particular, choose an hour she is offered."
        const val continuity = "Asking for the same nurse is asking, not booking her. An hour she is not offered at is not shown."
    }

    /** What happens to a visit asked of one nurse by name when she cannot take it in Care's offer window. */
    object Fallback {
        /** Access's setting named-nurse-fallback. A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
        const val inForce = "patient-chooses"
        const val heading = "If {nurse} cannot take it within {minutes} minutes"
        val rules = listOf(
            BookingFallbackRule("patient-chooses", true, true, null, "You choose now what happens if {nurse} cannot take this visit within {minutes} minutes of it reaching her."),
            BookingFallbackRule("wait-for-named", false, false, "wait", "If {nurse} cannot take this visit within {minutes} minutes of it reaching her, it waits for her and you are told so. Nobody else is sent."),
            BookingFallbackRule("soonest-automatically", true, false, "soonest", "If {nurse} cannot take this visit within {minutes} minutes of it reaching her, the soonest nurse whose badge is current takes it, and you are told who before she sets off.")
        )
        val choices = listOf(
            BookingFallbackChoice("wait", "Wait for {nurse}", "The visit waits for her, and you are told she has not taken it yet. Nobody else is sent."),
            BookingFallbackChoice("soonest", "The soonest nurse who is free", "The soonest nurse whose badge is current takes it instead, and you are told who before she sets off.")
        )
        const val reviewLabel = "If she cannot take it"
    }

    object Time {
        const val fewerHours = "{nurse} is already booked at some of these hours, so they are not shown. Nothing here is a time she was not offered."
        const val noHoursLeft = "{nurse} has no hour left on this day. Choose another day, or ask for whoever is nearest."
    }

    object Review {
        const val nurseLabel = "Nurse"
        const val nearestValue = "Whoever is nearest and cleared, named before she sets off"
        const val priceLabel = "Price"
        const val cancellingLabel = "Cancelling"
    }

    val states = listOf(
        BookingStateWords("requested", "Asked for", "You asked for this visit. Nothing is held until a nurse's hour is accepted.", "booking.requested@2"),
        BookingStateWords("confirmed", "Accepted", "The simulated roster accepted it and holds the hour. No real nurse did.", "booking.confirmed@2"),
        BookingStateWords("cancelled", "Cancelled", "This visit was called off. It stays here with the reason given.", "booking.cancelled@1")
    )
    val transitions = listOf(
        BookingTransition(null, "requested"),
        BookingTransition("requested", "confirmed"),
        BookingTransition("requested", "cancelled"),
        BookingTransition("confirmed", "cancelled")
    )
    const val statusHeading = "Where this booking stands"
    object StatusWords {
        const val reached = "Done"
        const val current = "Now"
        const val waiting = "Not yet"
    }
    const val acceptedBy = "Care's engine is not running, so the simulated roster stands in for it. It accepts a chosen hour at once and says that it did, because a preview that waited for nobody would be a screen that never moves."
    const val asapStaysRequested = "Nobody is looking for a nurse, because nothing is running that could. This visit stays asked for, and the screen says so rather than inventing somebody on the way."

    /** booking.json's own refusals, then the routes' refusals it names, each in the route's words. */
    val refusals = listOf(
        BookingRefusal("confirm-after-cancel", null, null, "A cancelled booking is not confirmed afterwards. Book again if the visit is still wanted."),
        BookingRefusal("confirm-without-a-time", null, null, "Nothing is accepted until there is an hour to hold."),
        BookingRefusal("nurse-badge-not-current", null, null, "A nurse is offered only while her badge is current, so this nurse is not offered."),
        BookingRefusal("slot-not-offered", "POST /v1/access/bookings@2", 409, "That time was not offered, so it cannot be booked."),
        BookingRefusal("service-not-here", "POST /v1/access/bookings@2", 422, "That service is not offered where the visit would be."),
        BookingRefusal("booking-not-found", "GET /v1/access/bookings/{bookingRef}@1", 404, "There is no booking of yours with that reference."),
        BookingRefusal("cancel-after-arrival", "POST /v1/access/bookings/{bookingRef}/cancel@1", 409, "This visit has already started. Speak to the nurse who is with you, or call the Control Tower."),
        BookingRefusal("reason-not-listed", "POST /v1/access/bookings/{bookingRef}/cancel@1", 422, "Choose one of the listed reasons, or say you would rather not."),
        BookingRefusal("thread-closed", "POST /v1/access/visit-threads/{bookingRef}/messages@1", 409, "This visit's thread is closed, so nothing more can be written in it."),
        BookingRefusal("no-attachments", "POST /v1/access/visit-threads/{bookingRef}/messages@1", 422, "A visit thread carries words only. Nothing can be attached."),
        BookingRefusal("not-on-this-visit", "POST /v1/access/visit-threads/{bookingRef}/messages@1", 403, "Only the patient and the nurse on this visit write in its thread."),
        BookingRefusal("message-too-long", "POST /v1/access/visit-threads/{bookingRef}/messages@1", 422, "A message here is kept short. Say the rest to the nurse at the visit."),
        BookingRefusal("no-summary", "POST /v1/access/conversations/{conversationRef}/handover@2", 422, "A handover goes with a structured summary, or it does not go.")
    )

    object Thread {
        const val title = "Messages about this visit"
        const val openLabel = "Messages with your nurse"
        const val lead = "Between you and the nurse on this visit, about getting there and getting in."
        const val notARecord = "These messages are not part of your health record. Anything clinical you want a nurse to know, tell her at the visit, where it is written down properly."
        const val nobodyWatches = "Nobody watches this thread for emergencies. If it cannot wait, call 10177, or 112 from a mobile."
        const val inputLabel = "Message to your nurse"
        const val sendLabel = "Send"
        /** Access's setting visit-thread-max-characters. A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
        const val maxCharacters = 500
        /** Access's setting visit-thread-open-hours-after-visit. A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
        const val openHoursAfterVisit = 24
        /** Access's setting visit-thread-photos, which waits on a doctor's clinical review. A proposal nobody has decided. Not clinically reviewed. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
        const val photos = false
        const val empty = "No messages yet. Anything you write stays with this visit."
        const val kept = "Kept with this visit. Not delivered: nothing reaches her phone."
        const val you = "You"
        const val openAfterVisit = "This visit is finished. Its thread stays open for anything that follows from it until {closes}, and then it closes."
        const val wordsOnly = "Words only. Photos and files cannot be sent in this thread."
        const val photosNotInPreview = "Photos are not in this preview yet."
        val closedBecause = listOf(
            BookingThreadClosed("visit-completed", "This visit is finished, so its thread is closed. What was said stays here to read."),
            BookingThreadClosed("booking-cancelled", "This visit was cancelled, so its thread is closed. What was said stays here to read.")
        )
    }

    /** Who answers a GilbertOne handover and when. The emergency numbers are sos.json's and are not a setting. */
    object Handover {
        /** Access's setting handover-answered-by, as vetting.json names the roles. A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
        val answeredBy = listOf("Registered nurse")
        /** Access's setting handover-hours, in Johannesburg time. A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
        val hours = listOf(
            HandoverWindow("handover-desk", listOf("mon", "tue", "wed", "thu", "fri", "sat", "sun"), "06:00", "22:00")
        )
        const val answeredByLabel = "Who answers"
        const val outOfHours = "Nobody is on the nurse handover desk now."
        const val outOfHoursNumbers = "If this cannot wait, do not wait for a nurse. Call 10177, or 112 from a mobile."
        const val callback = "A nurse on the desk would call you back when it opens, {when}. In this preview nobody will, because nobody is on the other end."
        const val opensToday = "today at {time}"
        const val opensTomorrow = "tomorrow at {time}"
        const val opensOn = "on {day} at {time}"
    }
}
