// Generated by scripts/emit-capabilities.mjs from packages/catalog/capabilities.json.
// Do not edit by hand — run `npm run capabilities`. The build fails if this file and its source
// disagree, so an edit here is lost rather than merely wrong.
//
// The 20 things MyThuso either does or only draws, and the sentence each one shows while it
// is not connected. No screen writes its own version of that sentence: it names a capability and
// the sentence is rendered from here, word for word, or it is not rendered at all. When an
// integration lands, one boolean changes in the contract and the notice disappears from every
// platform at once.
//
// The keys beginning with an underscore in the contract are commentary and are not written out.
// `requiresPermissions` names the only permissions either app may declare — today three, all for
// Gilbert's push-to-talk — and scripts/check-boundaries.mjs refuses any permission no capability
// has asked for.

package za.co.mythuso.model

/** One thing MyThuso either does or only draws. `evidence` is null until there is a file to open,
 *  `neverSoften` is carried only by the two capabilities somebody would be tempted to soften, and
 *  `requiresPermissions` names the only permissions an app may declare, and only voice carries
 *  any. */
data class Simulation(val supplier: String, val notice: String, val refuses: List<String>)

data class Capability(
    val id: String,
    val name: String,
    val connected: Boolean,
    val evidence: String?,
    val blockedBy: List<String>,
    val notice: String,
    /** "absent", "on-device", "simulated" or "connected". A simulated capability is never quieter than an absent
     *  one: it renders [Simulation.notice] where the absent notice would have gone. */
    val state: String,
    val simulation: Simulation?,
    val surfaces: List<String>,
    val neverSoften: String?,
    val requiresPermissions: List<String>
) {
    /** The sentence a screen shows, or null because the thing is real now. Never call [notice]
     *  directly: a simulated capability that showed the absent sentence would be telling a nurse
     *  nothing is connected while a simulator answers her. */
    val noticeToShow: String? get() = if (connected) null else simulation?.notice ?: notice
}

data class CapabilityRule(val id: String, val statement: String, val why: String)

/** In the contract's own order, which is roughly the order a person meets them. */
val capabilities = listOf(
    Capability("accounts", "Accounts and sign-in", false,
        "apps/api/src/identity",
        listOf(
            "An SMS provider for one-time codes.",
            "An answer to what a one-time code costs somebody who has none. DNS and TLS were the second blocker here until 10 September and are done — mythuso.co.za serves https on both names, and the identity service is still switched off, because a certificate makes the endpoint safe to reach and does not make it safe to run."
        ),
        "Sign-in is not switched on yet. This account is local to your browser and disappears when you close it.",
        "simulated",
        Simulation("A simulated one-time-code channel, in process.", "Sign-in is simulated. The code is produced here and shown to you; no message leaves this machine and no provider is contacted.", listOf(
            "Send anything to a real handset.",
            "Accept a code it did not itself produce.",
            "Survive a restart as a real account would.",
            "Grant a role. The demo login chooses which workspace to draw; it authenticates nobody, and no workspace it opens is reached by having permission to."
        )),
        listOf("sign-in", "profile", "sign-out"),
        null,
        emptyList()),
    Capability("booking", "Booking a visit", false,
        null,
        listOf(
            "A nurse roster with real availability.",
            "Payment, because a visit nobody can pay for is not booked."
        ),
        "This does not book a visit. Nobody is dispatched and nothing is charged.",
        "simulated",
        Simulation("A simulated nurse roster, in process.", "The roster is simulated. These nurses are fictional and none of them has agreed to attend.", listOf(
            "Commit a real person to a time.",
            "Offer a nurse whose simulated vetting has lapsed.",
            "Offer a nurse whose vetting has not finished.",
            "Book outside a zone dispatch can reach."
        )),
        listOf("booking", "visits", "visit-detail"),
        null,
        emptyList()),
    Capability("payments", "Taking payment", false,
        null,
        listOf(
            "A South African payment provider, contracted and integrated.",
            "A merchant account."
        ),
        "No payment is taken. The prices shown are the catalogue's and no card is charged.",
        "simulated",
        Simulation("A simulated South African card and EFT provider, in process.", "Payment is simulated. No card is charged, no bank is contacted and no money moves.", listOf(
            "Hold a card number, even a fictional one.",
            "Settle, because settlement is a fact about a bank.",
            "Produce a receipt that does not say it is simulated."
        )),
        listOf("booking", "wallet", "plans"),
        null,
        emptyList()),
    Capability("payouts", "Paying a nurse", false,
        null,
        listOf(
            "A payment provider.",
            "Verified bank details, which need the identity service switched on."
        ),
        "No money moves. These figures are the catalogue's arithmetic on sample visits.",
        "simulated",
        Simulation("A simulated bank payout channel, in process.", "The payout is simulated. Nothing is paid, and the bank details on this screen are fictional.", listOf(
            "Pay anybody.",
            "Verify a real bank account.",
            "Reverse a payout that never left."
        )),
        listOf("earnings", "payout-history"),
        null,
        emptyList()),
    Capability("credential-verification", "Confirming a credential with the body that issued it", false,
        "apps/api/src/vetting/authority.ts",
        listOf(
            "An agreement or accreditation with each of the thirteen authorities. All thirteen adapters answer not-integrated.",
            "A contracted identity provider for the identity check."
        ),
        "No credential on this screen has been confirmed with the body that issued it. A reviewer has looked at a document the applicant supplied, which is not the same thing.",
        "simulated",
        Simulation("Simulated answers from the thirteen authorities, in process.", "Credential answers are simulated. No authority has been asked, and a cleared result here confirms nothing.", listOf(
            "Answer for a registration number that is not in the simulated register.",
            "Return cleared for a lapsed check.",
            "Be read as confirmation by any screen that grants a capability."
        )),
        listOf("vetting", "nurse-profile", "roster"),
        null,
        emptyList()),
    Capability("dispatch", "Dispatching a nurse", false,
        null,
        listOf(
            "Live positions from nurse devices.",
            "An accepted-visit protocol.",
            "Booking, which is what would create something to dispatch."
        ),
        "Dispatch is not connected. These positions and visits are sample data, drawn from real coordinates.",
        "simulated",
        Simulation("Simulated nurse positions, in process.", "Positions are simulated. No device is reporting, and this movement is generated on this machine.", listOf(
            "Carry a patient id, a visit id or an address.",
            "Place a pin on anybody's home.",
            "Claim an arrival time it has not derived."
        )),
        listOf("dispatch", "control-tower", "incidents"),
        null,
        emptyList()),
    Capability("clinical-records", "Holding a clinical record", false,
        null,
        listOf(
            "The controls in docs/PRIVACY-AND-SECURITY.md.",
            "An Information Officer's sign-off on retention.",
            "SA-resident hosting for special personal information."
        ),
        "This record is sample data. Nothing you type here is stored, and no real record exists behind this screen.",
        "absent",
        null,
        listOf("passport", "patient-file", "assessment", "capture", "live-well"),
        null,
        emptyList()),
    Capability("teleconsultation", "The consultation call", false,
        null,
        listOf(
            "No media stack. Neither app declares a camera permission, and the consultation asks for no microphone — the only microphone either app asks for is Gilbert's push-to-talk, named under the voice capability.",
            "A doctor panel with a real rota."
        ),
        "The consultation has never asked this device for the camera or the microphone, and no connection is opened. What follows is the design of a consultation, drawn at full size.",
        "simulated",
        Simulation("A simulated session broker, in process.", "The call is simulated. No camera or microphone is opened, and no media stack exists behind this screen.", listOf(
            "Open a camera or a microphone.",
            "Declare a media permission on either native app.",
            "Simulate a line quality better than the ladder permits."
        )),
        listOf("teleconsult", "waiting-room"),
        null,
        emptyList()),
    Capability("screening", "AI-assisted screening", false,
        null,
        listOf(
            "No model, no vendor and no licence. The frame around it — provenance, sign-off, conflict resolution — is built; the screening is not."
        ),
        "Nothing here is screened by software. The frame around a result is real; the result is sample data.",
        "simulated",
        Simulation("A simulated screening model, in process.", "This screening is simulated. No model produced it, and it is not a clinical opinion.", listOf(
            "Issue a diagnosis.",
            "Be signed off by anybody but a named clinician.",
            "Produce an urgent result without naming a red flag the emergency contract holds."
        )),
        listOf("capture", "screening-result", "review-queue"),
        null,
        emptyList()),
    Capability("voice", "Talking to Gilbert", false,
        null,
        listOf(
            "No contracted South African speech provider: so English only, only on phones that recognise it offline, and nothing heard on the web.",
            "No language model. Gilbert answers only from its approved sentences, and says so when it cannot assess something.",
            "No decision about a recording beyond keeping none, so nothing is recorded and no transcript leaves the phone."
        ),
        "Gilbert listens only after you tap the sphere on a phone, hears English only, turns speech into text on the phone and keeps no recording. On the web you type. Nothing you say or type is sent anywhere.",
        "on-device",
        null,
        listOf("assistant", "voice", "home"),
        "No listening affordance may be drawn unless the microphone is actually open, and none at all on the web — not an enabled one, not a disabled one, not a decorative one. A control that looks like it is listening and is not is worse than no control, and on a health product it is the kind of worse that gets believed.",
        listOf("NSMicrophoneUsageDescription", "NSSpeechRecognitionUsageDescription", "android.permission.RECORD_AUDIO")),
    Capability("devices", "The connected kit", false,
        null,
        listOf(
            "No device is contacted. No Bluetooth or eSIM permission is declared."
        ),
        "No device is connected. These readings are sample data and no instrument has been paired.",
        "simulated",
        Simulation("A simulated instrument, in process.", "The instrument is simulated. No Bluetooth session is opened and no device is contacted.", listOf(
            "Open a Bluetooth or eSIM session.",
            "Declare a device permission on either native app.",
            "Produce a reading without its provenance mark."
        )),
        listOf("kit", "capture", "provenance"),
        null,
        emptyList()),
    Capability("dispensing", "Sending a prescription to a pharmacy", false,
        null,
        listOf(
            "A contracted pharmacy network.",
            "A pharmacist's review of the substitution classes."
        ),
        "No prescription reaches a pharmacy. The substitution rules on this screen are real and have not been read by a pharmacist.",
        "simulated",
        Simulation("A simulated pharmacy network, in process.", "The pharmacy is simulated. No prescription is sent and no pharmacist has seen it.", listOf(
            "Substitute outside the classes the Act permits.",
            "Change a molecule or a strength.",
            "Dispense without a simulated pharmacist's registration."
        )),
        listOf("dispensing", "orders", "prescription"),
        null,
        emptyList()),
    Capability("interpreting", "Booking an interpreter", false,
        null,
        listOf(
            "No interpreter is contacted.",
            "SATI's accreditation route for SASL is drafted and unconfirmed."
        ),
        "No interpreter is contacted. The roster and the refusals are real; the people on it are not.",
        "simulated",
        Simulation("A simulated interpreter roster, in process.", "The interpreter is simulated. Nobody has been booked and nobody is expecting this visit.", listOf(
            "Offer a family member or a child.",
            "Charge a patient for a cancelled accommodation.",
            "Dispatch a visit that needs an interpreter and has none."
        )),
        listOf("interpreting", "booking", "teleconsult"),
        null,
        emptyList()),
    Capability("messaging", "Reaching a person", false,
        null,
        listOf(
            "No SMS, email or push provider.",
            "No WhatsApp channel, so no report or photo after a visit reaches anybody's phone, and no decision yet on whether a visit photo may travel over WhatsApp at all."
        ),
        "Nothing is sent. No message, invitation or reminder reaches anybody.",
        "simulated",
        Simulation("A simulated delivery channel, in process.", "Messages are simulated. A receipt is produced here; nothing reaches a handset, an inbox or a push service.", listOf(
            "Reach any address outside this machine.",
            "Report a delivery it did not simulate.",
            "Retry, because a simulated failure is a chosen failure."
        )),
        listOf("family", "invitations", "notifications", "requests"),
        null,
        emptyList()),
    Capability("emergency", "The emergency pathway", false,
        null,
        listOf(
            "No contracted ambulance partner.",
            "No urgent rota.",
            "The routing questions have not been reviewed by a clinician."
        ),
        "This does not call anybody. In a real emergency dial 10177 or 112 from your phone.",
        "simulated",
        Simulation("A simulated acknowledgement channel, in process.", "This acknowledgement is simulated. No ambulance service has been contacted. In a real emergency call 10177, or 112 from a mobile.", listOf(
            "Replace or delay the emergency numbers on any screen.",
            "Claim an ambulance is coming.",
            "Answer at all until the real numbers have been shown first."
        )),
        listOf("sos", "alert"),
        "The ambulance number on this screen is real and always shown first, connected or not. The one refusal on this pathway that is not about MyThuso is the one that matters most.",
        emptyList()),
    Capability("doctor-review", "A doctor reviewing a nurse's visit", false,
        null,
        listOf(
            "A panel of HPCSA-registered doctors, contracted and on a rota.",
            "A Medical Director who owns the panel and signs off how a review is done."
        ),
        "No doctor reviews anything yet. There is no doctor panel, and a review shown in this preview was written by nobody.",
        "absent",
        null,
        listOf("plans"),
        null,
        emptyList()),
    Capability("medicine-collection", "Collecting chronic medicine for a patient", false,
        null,
        listOf(
            "An arrangement to collect from CCMDD pick-up points and clinic pharmacies on a patient's written authorisation.",
            "A partner pharmacy for private scripts."
        ),
        "No medicine is collected. MyThuso has no arrangement with CCMDD, a clinic or a pharmacy to collect on anybody's behalf.",
        "absent",
        null,
        listOf("plans"),
        null,
        emptyList()),
    Capability("thuso-devices", "MyThuso's own devices", false,
        null,
        listOf(
            "Industrial design, firmware and a pilot run with a local electronics partner.",
            "SAHPRA and ICASA certification."
        ),
        "Thuso Band and Thuso Home have not been built. They are designs with a target cost, and nobody can be given one.",
        "absent",
        null,
        listOf("plans"),
        null,
        emptyList()),
    Capability("carers", "Carers in the home", false,
        null,
        listOf(
            "Carers recruited, trained and supervised by registered nurses, planned for phase 3.",
            "A written scope of what a carer may and may not do in somebody's home."
        ),
        "No carer is employed or contracted. Carer hours are planned under a registered nurse's supervision, and none can be given yet.",
        "absent",
        null,
        listOf("plans"),
        null,
        emptyList()),
    Capability("laboratory-results", "Laboratory orders and results", false,
        null,
        listOf(
            "A laboratory accredited to ISO 15189 by SANAS, contracted to collect samples, run tests and release results.",
            "A clinical governance decision on who acknowledges a result, and how quickly."
        ),
        "No laboratory is connected. No sample is taken and no test is run, and a result shown here is a synthetic reference to nothing.",
        "absent",
        null,
        listOf("lab-orders", "results"),
        null,
        emptyList())
)

/* How the notices are meant to be used. Rendered on the readiness screens rather than only obeyed,
   because a rule nobody can read is a rule the next person breaks by accident. */
val capabilityRules = listOf(
    CapabilityRule("one-notice-per-screen",
        "A screen renders the notice for the capability it depends on. Not three of them stacked, and not one it does not use.",
        "A nurse's schedule carried a Design preview banner, a WORKSPACE · DEMO eyebrow and a Fictional workspace paragraph before any content — three sentences saying one thing, filling the screen above the first visit. A reader who is told the same thing three times has been told it none."),
    CapabilityRule("the-notice-is-the-contract",
        "No screen writes its own not-connected sentence. It names a capability and the sentence is rendered from this file.",
        "Sixty hand-typed variations cannot be switched off together, and some of them will be wrong. One place that knows means one boolean to change when an integration lands."),
    CapabilityRule("connected-needs-evidence",
        "A capability may be marked connected only when `evidence` names a file that exists and `blockedBy` is empty. The build refuses it otherwise.",
        "The failure mode is never a lie. It is somebody clearing a banner off a layout because the screenshot looked better without it."),
    CapabilityRule("scaffolding-is-not-a-disclosure",
        "A state picker and a gallery of loading states are development tools. They are removed from what ships, and removing them says nothing about whether anything is connected.",
        "The two got tangled: taking the demo furniture out felt like claiming the product was live. They are separate questions and this file answers only the second. This rule named a role switcher as well until 12 September, when the founder made one the way in; see a-demo-login-is-not-an-account for why that is a change to what ships rather than to what is claimed."),
    CapabilityRule("a-demo-login-is-not-an-account",
        "The demo login is what ships, because there is nothing to sign in to. Every surface it opens renders the accounts notice, and the switcher says in the contract's own words that it grants no role.",
        "Four sign-in screens each carried this capability's notice, each explained that there are no accounts, and each then asked the reader to choose a workspace anyway. Replacing them with one switcher is honest about what was already happening — but it moves the notice off four screens at once, and a screen that stops speaking is exactly the disclosure failure a-simulation-says-so exists to refuse. So the notice moves with it rather than being dropped, and the switcher carries the refusal too: an auto login that looks like an account is worse than a sign-in wall with nothing behind it, because the wall at least admits it is a door."),
    CapabilityRule("simulated-is-not-connected",
        "`state: simulated` never sets `connected: true`, and the two may not disagree. A simulated capability still lists everything blocking it.",
        "The whole hazard of a simulator is that it works. A person who has watched a payment go through end to end is one edit away from believing a payment provider exists, and the status page is the page a funder reads. So the boolean that removes every notice in the product is left alone, and the build fails if the state and the boolean drift apart."),
    CapabilityRule("a-simulation-says-so",
        "A simulated capability renders its simulation notice, word for word, wherever the absent notice would have rendered. No screen may be quieter for being simulated than it was for being absent.",
        "The failure mode is not a screen that lies. It is a screen that stops speaking: the sentence goes away because something now answers, and nobody notices that what answers is a fixture. Silence is the disclosure failure, so the notice never disappears until the state is connected."),
    CapabilityRule("a-simulation-is-not-reachable-from-the-network",
        "No simulator may be reached over HTTP. The eleven feed routes go on refusing every payload, and a simulated event enters in process through a function of its own.",
        "apps/api/src/feeds/index.ts argues that a route which could accept under some condition is a route somebody finds the condition for, usually late at night with a vendor on the phone. A simulation flag on those routes would be exactly that condition. So `decide` still has no acceptance to construct, and the simulators sit beside the boundary rather than inside it."),
    CapabilityRule("voice-is-on-device",
        "`voice` alone is on-device: the phone recognises speech, Gilbert answers from a contract, and nothing is connected.",
        "English push-to-talk on the phone, decided on 14 September 2026, is neither a stand-in answering (simulated) nor a supplier (connected). The state says exactly what is true, and the notice stays.")
)
