// Generated by scripts/emit-care.mjs from packages/catalog/care.json, with the refusal sentences it points at.
// Do not edit by hand — run `npm run care`. The build fails if this file and the source disagree,
// so an edit here is lost rather than merely wrong.
//
// No checklist step is written here and none is coming from here: a draft protocol carries a name
// and a number, and a service lists only which protocols govern it.

package za.co.mythuso.model

object CareData {
    data class Requirement(val serviceId: String, val scope: String?, val protocolIds: List<String>, val supervisedBy: String?)
    data class Stage(val id: String, val name: String)

    const val seedPhase = 1
    /** A proposal awaiting Head of Operations. Nobody has decided it. */
    const val offerExpiresAfterMinutes = 10

    const val outsideScope = "You are only ever dispatched to work inside your registered scope. The Control Tower cannot override that."
    const val noCurrentTrustScore = "Nobody without a current Trust Score is offered a visit."
    const val carerWithoutRn = "A supervised carer is not offered a visit without their registered nurse."
    const val noBase = "Nobody is offered a visit from a place the map cannot measure a distance from."
    const val noEligibleClinician = "Everybody eligible for this visit has been asked, so it goes to a dispatcher."
    const val withheldIsNotLast = "A nurse who fails a gate is withheld, not ranked last. She is not on the list at all, and the reason is said."
    const val declined = "It has gone to the next nurse who is eligible for it."
    const val lapsed = "Nobody answered in time, so it went to the next nurse who is eligible for it."
    const val offerExpired = "That offer has lapsed."
    const val notYourOffer = "That offer was made to somebody else."
    const val distanceBasis = "Straight line between suburb centres"
    const val markerNamed = "Your patient asked for you"
    const val markerPrevious = "You have seen this patient before"
    const val locationWhileShared = "Today, until this visit is complete, this patient is shown the suburb you are in. Never a street, and nothing after the visit ends."
    const val locationBeyondTheVisit = "A nurse's location is not shared beyond the visit."
    const val startCodeWrong = "The visit code did not match, so the visit has not started."
    const val notToday = "That visit is not today."
    const val checklistNotRatified = "A checklist runs only under a ratified protocol."
    const val checklistNoProtocol = "No protocol in the register covers this service, so there is no checklist to run."
    const val draftCarriesNothing = "A draft protocol holds a name and a version number. It holds no content, no threshold, no dose and no number of any other kind."
    const val recordSentence = "The readings and your sign-off are the visit assessment. This visit is handed over and completed against what it seals, and against nothing typed here."
    const val encounterIncomplete = "The encounter has required sections missing."
    const val handoverWithoutVisit = "A visit that has not started is not handed to a doctor."
    const val handoverQueued = "Handed to the doctors' review queue."
    const val completeCodeWrong = "The visit code did not match, so the visit is not complete."
    const val encounterUnsigned = "The encounter is not signed."
    const val completeWithoutStart = "A visit that never started cannot be completed."
    const val billable = "The visit is complete. Money is told it is billable and is told nothing about what happened at it."

    val requirements = listOf(
        Requirement("vitals", "Chronic care", listOf("vitals-and-chronic-check", "infection-control-and-sharps"), null),
        Requirement("wound", "Wound care", listOf("wound-care", "infection-control-and-sharps"), null),
        Requirement("mother", "Maternal & child", listOf("mother-and-baby-check"), null),
        Requirement("blood", "Phlebotomy", listOf("phlebotomy", "infection-control-and-sharps"), null),
        Requirement("injection", null, listOf("injection-administration", "infection-control-and-sharps"), null),
        Requirement("planning", null, listOf(), null),
        Requirement("postop", "Post-operative", listOf("post-operative-assessment", "infection-control-and-sharps"), null),
        Requirement("senior", "Elderly care", listOf("elderly-assessment"), null),
        Requirement("certificate", null, listOf("medical-certificate-criteria"), null),
        Requirement("screening", null, listOf("device-use-and-ai-result-handling"), null),
        Requirement("sos", null, listOf("emergency-escalation-and-referral"), null),
        Requirement("mens", null, listOf(), null),
        Requirement("mental", null, listOf(), null),
        Requirement("allied", null, listOf(), null),
        Requirement("carer", null, listOf(), "nurse")
    )

    val stages = listOf(
        Stage("route", "On the way"),
        Stage("start", "Start with the code"),
        Stage("checklist", "Checklist"),
        Stage("record", "Readings and sign-off"),
        Stage("handover", "Hand to a doctor"),
        Stage("complete", "Complete with the code")
    )

    object Preview {
        const val appointmentRef = "TH-3107"
        const val serviceId = "wound"
        const val zone = "parktown"
        const val dayOffset = 0
        const val slot = "16:00"
        const val clinicianRef = "N-205"
        val previousClinicianRefs = listOf("N-205")
        const val visitCode = "482190"
        const val encounterRef = "enc-preview-3107"
    }

    fun requirement(serviceId: String) = requirements.firstOrNull { it.serviceId == serviceId }
}
