// Generated by scripts/emit-care-tips.mjs from packages/catalog/care-tips.json.
// Do not edit by hand — run `npm run care-tips`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// General guidance, shown after a visit. Not reviewed by a clinician yet — the review notice is
// shown beside every tip until one has signed it.

package za.co.mythuso.model

object CareTipsData {
    const val version = 1

    object Review {
        /** Null until a registered clinician has read and signed the tips. */
        val reviewedBy: String? = null
        const val notice = "These tips are waiting for a clinical reviewer. Your nurse’s advice comes first."
    }

    object Door {
        const val opens = "Care tips"
        const val heading = "Care tips for the weeks ahead"
        const val detail = "Short, general tips on medicines, readings and being ready, to read one at a time."
        const val action = "Read the care tips"
        const val opening = "Opening the care tips."
    }

    object Screen {
        const val eyebrow = "AFTER YOUR VISIT"
        const val heading = "A few things that help between visits"
        const val lead = "Read them one at a time, at your own pace. None of them replaces what your nurse told you at the visit."
        /** "{n}" and "{total}" are filled by the screen. */
        const val counter = "Tip {n} of {total}"
        const val progressLabel = "Choose a tip"
        /** "{n}" and "{title}" are filled by the screen. */
        const val jumpLabel = "Tip {n}: {title}"
        const val back = "Back"
        const val next = "Next tip"
        const val startAgain = "Start again"
        const val refusalsHeading = "What these tips will not do"
        const val emergencyLabel = "Emergency numbers"
    }

    val refusals = listOf(
        "A tip never tells you how much of a medicine to take, or when to start or stop one. That is for whoever prescribed it.",
        "A tip never says what is wrong with you. Only a nurse or a doctor who has seen you can.",
        "A tip is the same for everybody. It does not know your readings, and it does not replace the plan your nurse gave you."
    )

    val tips = listOf(
        CareTip("medicine-list", "medicines", "Medicines",
            "One list for every medicine",
            "Write down every medicine you take, named as it is on the box, and keep the list with the boxes. Show both to the nurse at each visit, so nothing is missed or taken twice.",
            za.co.mythuso.ui.BrandMint, za.co.mythuso.ui.BrandInk, dark = false),
        CareTip("blood-pressure-routine", "blood-pressure", "Blood pressure",
            "Same chair, same time of day",
            "If you have been asked to check your blood pressure at home, sit quietly for a few minutes first and take it at the same time each day. Readings taken the same way can be compared fairly.",
            za.co.mythuso.ui.StudioLilac, za.co.mythuso.ui.StudioInk, dark = false),
        CareTip("bag-by-the-door", "be-ready", "Be ready",
            "A bag by the door",
            "Keep your identity document, your clinic card and your current medicines together in one place, so they are ready to go if you need help in a hurry.",
            za.co.mythuso.ui.StudioPeach, za.co.mythuso.ui.StudioInk, dark = false),
        CareTip("water", "water", "Water",
            "Sip through the day",
            "Keep water within reach and sip it through the day, especially in summer heat. If a nurse or a doctor has told you to limit what you drink, follow their advice instead.",
            za.co.mythuso.ui.StudioLime, za.co.mythuso.ui.StudioInk, dark = false),
        CareTip("when-to-call", "when-to-call", "When to call",
            "Know when not to wait",
            "If you feel worse than you did at the visit, contact your clinic or your doctor the same day rather than waiting for the next visit. If someone collapses, cannot breathe or has chest pain, call an ambulance first.",
            za.co.mythuso.ui.StudioNight, za.co.mythuso.ui.StudioPaper, dark = true)
    )
}
