package za.co.mythuso.model

/*
 * The consultation toolkit's reasoning on Android (2 October 2026): which tools a clinician reaches in a
 * consultation, in what order, and what each one says to this clinician, in this consultation, right now.
 *
 * The shapes below are what ConsultationToolkitData.kt constructs positionally, generated by
 * scripts/emit-consultation-toolkit.mjs from packages/catalog/consultation-toolkit.json; every sentence is
 * that file's. Whether this party may use a tool is the vetting register's, asked live through can(); what
 * the line allows a doctor to decide is Teleconsult.permitted(); the sentence a room without a nurse is
 * given is teleconsult.json's own. This file joins them and decides nothing of its own — a port of
 * apps/web/src/lib/consultation-toolkit.ts, answer for answer, so the three platforms shut the same tool
 * for the same reason.
 *
 * WHY THE ORDER OF THE ANSWERS. Being built comes first, because a tool with no screen has nothing to refuse.
 * Then the register: a doctor whose registration lapsed is refused every decision whatever the line is doing.
 * Then the encounter: a call that ended without counting as a consultation decides nothing, permanently. Then
 * the room: a medicine is not started and a certificate is not written for a patient nobody in the room has
 * examined, for the length of the appointment. Only then the line, which is the one answer that changes back.
 */

data class ToolkitCallGate(val limit: String, val refusal: String)
data class ToolkitToolSpec(
    val id: String, val name: String, val short: String, val capability: String?, val summary: String,
    /* The capability whose not-connected notice speaks for this tool, and whether the toolkit draws it
       (true) or the tool's own screen already does (false) — one notice, never two. */
    val honesty: String, val drawnByToolkit: Boolean,
    val decision: Boolean, val signsAfterCall: Boolean, val pending: Boolean,
    val onCall: List<ToolkitCallGate>,
    /* The Android screen the tool opens, by composable name, or null where this phone says what the tool
       is and opens nothing. */
    val androidScreen: String?
)
data class ToolkitRefusedSpec(val tool: String, val sentence: String)
data class ToolkitSurfaceSpec(
    val id: String, val role: String, val homeId: String, val homeName: String, val homeShort: String,
    val heading: String, val from: String?, val tools: List<String>, val refused: List<ToolkitRefusedSpec>
)
data class ToolkitRefusalSpec(val id: String, val sentence: String, val surfaces: List<String>)

/** The call, as far as a tool needs to know it. Null on a surface that is not a call. */
data class ToolkitCall(val connectionId: String, val nursePresent: Boolean, val ended: Boolean, val countsAsConsultation: Boolean)

/** What a tool says to this clinician right now. Every state but open carries the sentence it is shut with. */
sealed class ToolkitToolState {
    object Open : ToolkitToolState()
    data class Pending(val reason: String) : ToolkitToolState()
    data class Withheld(val reason: String) : ToolkitToolState()
    data class Closed(val reason: String) : ToolkitToolState()
    data class Room(val reason: String) : ToolkitToolState()
    data class Waiting(val reason: String) : ToolkitToolState()

    /** The sentence a shut tool opens to, and nothing else; null when it is open. */
    val sentence: String? get() = when (this) {
        Open -> null
        is Pending -> reason
        is Withheld -> reason
        is Closed -> reason
        is Room -> reason
        is Waiting -> reason
    }
    /** What the state is called on the tool's own row, when it is anything but open — the web's stateWord. */
    val word: String? get() = when (this) {
        Open -> null
        is Pending -> ConsultationToolkitData.Words.statePending
        is Withheld -> ConsultationToolkitData.Words.withheld
        is Closed -> ConsultationToolkitData.Words.stateClosed
        is Room -> ConsultationToolkitData.Words.stateRoom
        is Waiting -> ConsultationToolkitData.Words.waiting
    }
}

object ConsultationToolkit {
    private val placeholder = Regex("\\{(\\w+)\\}")
    /** A contract sentence with its {names} filled; a name with no value is left as written. */
    fun fill(template: String, values: Map<String, String>): String =
        placeholder.replace(template) { match -> values[match.groupValues[1]] ?: match.value }

    fun tool(id: String): ToolkitToolSpec = ConsultationToolkitData.tools.firstOrNull { it.id == id }
        ?: error("consultation-toolkit.json holds no tool \"$id\"")
    fun surface(id: String): ToolkitSurfaceSpec = ConsultationToolkitData.surfaces.firstOrNull { it.id == id }
        ?: error("consultation-toolkit.json holds no surface \"$id\"")
    /** The tools a surface lists, in its order. */
    fun toolsOf(surface: ToolkitSurfaceSpec): List<ToolkitToolSpec> = surface.tools.map(::tool)
    /** The toolkit's own refusals said on this surface: those that name no surface are said on every one. */
    fun refusalsOn(surface: ToolkitSurfaceSpec): List<ToolkitRefusalSpec> =
        ConsultationToolkitData.refusals.filter { it.surfaces.isEmpty() || surface.id in it.surfaces }

    fun stateOf(tool: ToolkitToolSpec, subject: VettingSubject, call: ToolkitCall?): ToolkitToolState {
        if (tool.pending) return ToolkitToolState.Pending(fill(ConsultationToolkitData.Gates.beingBuilt, mapOf("tool" to tool.name)))
        tool.capability?.let { capability ->
            val decision = can(subject, capability)
            if (!decision.allowed) return ToolkitToolState.Withheld(decision.reason ?: ConsultationToolkitData.Words.withheld)
        }
        if (call == null) return ToolkitToolState.Open
        val decides = tool.decision || tool.signsAfterCall
        if (!decides) return ToolkitToolState.Open
        if (call.ended && !call.countsAsConsultation)
            return ToolkitToolState.Closed(fill(ConsultationToolkitData.Gates.notAConsultation, mapOf("tool" to tool.name)))
        /* A limit that needs the nurse is the room's answer, said in the teleconsultation's own words. Asked of
           the room rather than of permitted(), because a dropped line withdraws the nurse's limit too — and a
           doctor told "nobody here has examined the patient" while the nurse is standing beside her would be
           told something false. */
        for (gate in tool.onCall) {
            val limit = callClinicalLimits.firstOrNull { it.id == gate.limit }
            if (limit?.needs == "nurse" && !call.nursePresent) return ToolkitToolState.Room(Teleconsult.refusal(gate.refusal).sentence)
        }
        if (!call.ended && !tool.decision) return ToolkitToolState.Open
        if (!call.ended && Teleconsult.permitted(call.connectionId, call.nursePresent).none { it.id == "conclude" })
            return ToolkitToolState.Waiting(fill(ConsultationToolkitData.Gates.lineDoesNotAllow, mapOf("tool" to tool.name)))
        return ToolkitToolState.Open
    }
}
