// Generated by scripts/emit-events.mjs from packages/catalog/events.json, packages/catalog/assistant.json, packages/catalog/trust.json.
// Do not edit by hand — run `npm run events`. The build fails if this file and its sources
// disagree, so an edit here is lost rather than merely wrong.
//
// One sealed constant per live event version, carrying the engine that owns it. Nothing in this app
// publishes to a bus, and no payload shape is written here. A withdrawn version has no constant and
// an EventKey cannot be made outside this file, so no code in this app can name one.

package za.co.mythuso.model

object EventsData {
    data class Engine(val id: String, val name: String, val productName: String)

    // A live event version. The constructor is private: only the constants below make one, and it is
    // not a data class, so there is no copy() to change its version with.
    class EventKey private constructor(val type: String, val version: Int, val owner: String) {
        override fun toString() = "$type@$version"
        override fun equals(other: Any?) = other is EventKey && other.type == type && other.version == version
        override fun hashCode() = 31 * type.hashCode() + version

        companion object {
            val APPOINTMENT_REQUESTED_V1 = EventKey("appointment.requested", 1, "care")
            val APPOINTMENT_OFFERED_V1 = EventKey("appointment.offered", 1, "care")
            val APPOINTMENT_BOOKED_V2 = EventKey("appointment.booked", 2, "care")
            val APPOINTMENT_CONFIRMED_V1 = EventKey("appointment.confirmed", 1, "care")
            val APPOINTMENT_EN_ROUTE_V1 = EventKey("appointment.en_route", 1, "care")
            val APPOINTMENT_IN_PROGRESS_V2 = EventKey("appointment.in_progress", 2, "care")
            val APPOINTMENT_COMPLETED_V2 = EventKey("appointment.completed", 2, "care")
            val APPOINTMENT_NO_SHOW_V1 = EventKey("appointment.no_show", 1, "care")
            val APPOINTMENT_CANCELLED_V1 = EventKey("appointment.cancelled", 1, "care")
            val APPOINTMENT_FOLLOW_UP_REQUIRED_V1 = EventKey("appointment.follow_up_required", 1, "care")
            val PERSON_VERIFIED_V1 = EventKey("person.verified", 1, "trust")
            val PERSON_PROBATION_V1 = EventKey("person.probation", 1, "trust")
            val PERSON_TRUST_UPDATED_V2 = EventKey("person.trust_updated", 2, "trust")
            val PERSON_UNDER_REVIEW_V1 = EventKey("person.under_review", 1, "trust")
            val PERSON_SUSPENDED_V1 = EventKey("person.suspended", 1, "trust")
            val PERSON_REINSTATED_V1 = EventKey("person.reinstated", 1, "trust")
            val PERSON_DEACTIVATED_V1 = EventKey("person.deactivated", 1, "trust")
            val CREDENTIAL_EXPIRING_V1 = EventKey("credential.expiring", 1, "trust")
            val CREDENTIAL_LAPSED_V1 = EventKey("credential.lapsed", 1, "trust")
            val PARTNER_VERIFIED_V1 = EventKey("partner.verified", 1, "trust")
            val PARTNER_SUSPENDED_V1 = EventKey("partner.suspended", 1, "trust")
            val PASSPORT_RECORD_CREATED_V1 = EventKey("passport.record.created", 1, "record")
            val PASSPORT_ENTRY_WRITTEN_V1 = EventKey("passport.entry.written", 1, "record")
            val PASSPORT_ENTRY_SUPERSEDED_V1 = EventKey("passport.entry.superseded", 1, "record")
            val PASSPORT_CONSENT_GRANTED_V3 = EventKey("passport.consent.granted", 3, "record")
            val PASSPORT_CONSENT_REVOKED_V3 = EventKey("passport.consent.revoked", 3, "record")
            val PASSPORT_ACCESS_READ_V1 = EventKey("passport.access.read", 1, "record")
            val PASSPORT_ACCESS_BREAKGLASS_V1 = EventKey("passport.access.breakglass", 1, "record")
            val PASSPORT_EXPORT_GENERATED_V1 = EventKey("passport.export.generated", 1, "record")
            val ALERT_RAISED_V1 = EventKey("alert.raised", 1, "core")
            val ALERT_ACKNOWLEDGED_V1 = EventKey("alert.acknowledged", 1, "core")
            val ALERT_ESCALATED_V1 = EventKey("alert.escalated", 1, "core")
            val ALERT_CLOSED_V1 = EventKey("alert.closed", 1, "core")
            val MARKET_ORDER_PLACED_V1 = EventKey("market.order.placed", 1, "money")
            val MARKET_ORDER_PAID_V1 = EventKey("market.order.paid", 1, "money")
            val MARKET_ORDER_SHIPPED_V1 = EventKey("market.order.shipped", 1, "money")
            val MARKET_ORDER_DELIVERED_V1 = EventKey("market.order.delivered", 1, "money")
            val MARKET_ORDER_RETURNED_V1 = EventKey("market.order.returned", 1, "money")
            val LOOP_OPENED_V1 = EventKey("loop.opened", 1, "core")
            val LOOP_ACKNOWLEDGED_V1 = EventKey("loop.acknowledged", 1, "core")
            val LOOP_ESCALATED_V1 = EventKey("loop.escalated", 1, "core")
            val LOOP_CLOSED_V1 = EventKey("loop.closed", 1, "core")
            val PROTOCOL_RATIFIED_V1 = EventKey("protocol.ratified", 1, "core")
            val BOOKING_REQUESTED_V2 = EventKey("booking.requested", 2, "access")
            val BOOKING_CONFIRMED_V2 = EventKey("booking.confirmed", 2, "access")
            val BOOKING_CANCELLED_V1 = EventKey("booking.cancelled", 1, "access")
            val CONVERSATION_HANDOVER_V1 = EventKey("conversation.handover", 1, "access")
            val VISIT_HANDOVER_SUBMITTED_V1 = EventKey("visit.handover.submitted", 1, "care")
            val TRIAGE_COMPLETED_V2 = EventKey("triage.completed", 2, "clinical")
            val REVIEW_SIGNED_V1 = EventKey("review.signed", 1, "clinical")
            val RESULT_ACKNOWLEDGED_V1 = EventKey("result.acknowledged", 1, "clinical")
            val GUIDANCE_DELIVERED_V1 = EventKey("guidance.delivered", 1, "clinical")
            val CHECKIN_OVERDUE_V1 = EventKey("checkin.overdue", 1, "safety")
            val PANIC_RAISED_V1 = EventKey("panic.raised", 1, "safety")
            val SOS_RAISED_V1 = EventKey("sos.raised", 1, "safety")
            val NOK_NOTIFIED_V1 = EventKey("nok.notified", 1, "safety")
            val SENTINEL_RUNG_RAISED_V1 = EventKey("sentinel.rung_raised", 1, "safety")
            val SAFEGUARDING_REPORTED_V1 = EventKey("safeguarding.reported", 1, "safety")
            val ADMISSION_NEED_IDENTIFIED_V1 = EventKey("admission.need_identified", 1, "movement")
            val FACILITY_CANDIDATE_SELECTED_V1 = EventKey("facility.candidate_selected", 1, "movement")
            val ADMISSION_PREAUTH_SUBMITTED_V1 = EventKey("admission.preauth.submitted", 1, "movement")
            val ADMISSION_PREAUTH_DECIDED_V1 = EventKey("admission.preauth.decided", 1, "movement")
            val ADMISSION_REQUESTED_V1 = EventKey("admission.requested", 1, "movement")
            val ADMISSION_ACCEPTED_V1 = EventKey("admission.accepted", 1, "movement")
            val ADMISSION_WAITLISTED_V1 = EventKey("admission.waitlisted", 1, "movement")
            val ADMISSION_DECLINED_V1 = EventKey("admission.declined", 1, "movement")
            val TRANSPORT_ENROUTE_V1 = EventKey("transport.enroute", 1, "movement")
            val ADMISSION_ARRIVED_V1 = EventKey("admission.arrived", 1, "movement")
            val TRIAGE_VERIFIED_V1 = EventKey("triage.verified", 1, "movement")
            val ADMISSION_HANDOVER_COMPLETE_V1 = EventKey("admission.handover_complete", 1, "movement")
            val TRIP_REQUESTED_V1 = EventKey("trip.requested", 1, "movement")
            val TRIP_ACCEPTED_V1 = EventKey("trip.accepted", 1, "movement")
            val TRUST_SHIFT_START_MATCHED_V1 = EventKey("trust.shift_start.matched", 1, "trust")
            val TRUST_SHIFT_START_REFUSED_V1 = EventKey("trust.shift_start.refused", 1, "trust")
            val TRUST_DOOR_VERIFIED_V1 = EventKey("trust.door.verified", 1, "trust")
            val TRUST_DOOR_MISMATCHED_V1 = EventKey("trust.door.mismatched", 1, "trust")
            val PASSPORT_SHARE_LINK_CREATED_V1 = EventKey("passport.share.link_created", 1, "record")
            val PASSPORT_SHARE_LINK_USED_V1 = EventKey("passport.share.link_used", 1, "record")
            val PASSPORT_ANOMALY_DETECTED_V1 = EventKey("passport.anomaly.detected", 1, "record")
            val PASSPORT_ADMISSION_DETECTED_V1 = EventKey("passport.admission.detected", 1, "record")
            val PASSPORT_DISCHARGE_RECEIVED_V1 = EventKey("passport.discharge.received", 1, "record")
            val PRESCRIPTION_PRESCRIBED_V1 = EventKey("prescription.prescribed", 1, "medicines")
            val PRESCRIPTION_VERIFIED_V1 = EventKey("prescription.verified", 1, "medicines")
            val DISPENSE_COMPLETED_V1 = EventKey("dispense.completed", 1, "medicines")
            val DELIVERY_COLLECTED_V1 = EventKey("delivery.collected", 1, "medicines")
            val DELIVERY_HANDED_OVER_V1 = EventKey("delivery.handed_over", 1, "medicines")
            val LAB_ORDER_PLACED_V1 = EventKey("lab.order.placed", 1, "medicines")
            val LAB_RESULT_RECEIVED_V1 = EventKey("lab.result.received", 1, "medicines")
            val READING_INGESTED_V1 = EventKey("reading.ingested", 1, "devices")
            val DEVICE_STALE_V1 = EventKey("device.stale", 1, "devices")
            val DEVICE_RECALLED_V1 = EventKey("device.recalled", 1, "devices")
            val PAYMENT_SUCCEEDED_V1 = EventKey("payment.succeeded", 1, "money")
            val PAYMENT_FAILED_V1 = EventKey("payment.failed", 1, "money")
            val PAYMENT_REFUNDED_V1 = EventKey("payment.refunded", 1, "money")
            val PAYOUT_SCHEDULED_V1 = EventKey("payout.scheduled", 1, "money")
            val PAYOUT_PAID_V1 = EventKey("payout.paid", 1, "money")
            val CLAIM_SUBMITTED_V2 = EventKey("claim.submitted", 2, "money")
            val CLAIM_DECIDED_V1 = EventKey("claim.decided", 1, "money")
            val VISIT_BILLABLE_V1 = EventKey("visit.billable", 1, "care")
            val REVIEW_BILLABLE_V1 = EventKey("review.billable", 1, "clinical")
            val PULSE_SESSION_STARTED_V1 = EventKey("pulse.session.started", 1, "pulse")
            val PULSE_LISTENING_STARTED_V1 = EventKey("pulse.listening.started", 1, "pulse")
            val PULSE_UTTERANCE_FINALISED_V2 = EventKey("pulse.utterance.finalised", 2, "pulse")
            val PULSE_THINKING_STARTED_V1 = EventKey("pulse.thinking.started", 1, "pulse")
            val PULSE_DEVICE_HIGHLIGHT_V1 = EventKey("pulse.device.highlight", 1, "pulse")
            val PULSE_GUIDANCE_PRESENTED_V1 = EventKey("pulse.guidance.presented", 1, "pulse")
            val PULSE_ESCALATION_STARTED_V2 = EventKey("pulse.escalation.started", 2, "pulse")
            val PULSE_HANDOVER_COMPLETED_V1 = EventKey("pulse.handover.completed", 1, "pulse")
            val TRUST_WEIGHT_DECIDED_V2 = EventKey("trust.weight.decided", 2, "trust")
            val TRUST_DISPATCH_WITHHELD_V1 = EventKey("trust.dispatch.withheld", 1, "trust")
            val RECORD_BREAKGLASS_REVIEW_DUE_V1 = EventKey("record.breakglass.review_due", 1, "record")
            val RECORD_AUDIT_CHAIN_BROKEN_V1 = EventKey("record.audit.chain_broken", 1, "record")

            val all = listOf(
                APPOINTMENT_REQUESTED_V1,
                APPOINTMENT_OFFERED_V1,
                APPOINTMENT_BOOKED_V2,
                APPOINTMENT_CONFIRMED_V1,
                APPOINTMENT_EN_ROUTE_V1,
                APPOINTMENT_IN_PROGRESS_V2,
                APPOINTMENT_COMPLETED_V2,
                APPOINTMENT_NO_SHOW_V1,
                APPOINTMENT_CANCELLED_V1,
                APPOINTMENT_FOLLOW_UP_REQUIRED_V1,
                PERSON_VERIFIED_V1,
                PERSON_PROBATION_V1,
                PERSON_TRUST_UPDATED_V2,
                PERSON_UNDER_REVIEW_V1,
                PERSON_SUSPENDED_V1,
                PERSON_REINSTATED_V1,
                PERSON_DEACTIVATED_V1,
                CREDENTIAL_EXPIRING_V1,
                CREDENTIAL_LAPSED_V1,
                PARTNER_VERIFIED_V1,
                PARTNER_SUSPENDED_V1,
                PASSPORT_RECORD_CREATED_V1,
                PASSPORT_ENTRY_WRITTEN_V1,
                PASSPORT_ENTRY_SUPERSEDED_V1,
                PASSPORT_CONSENT_GRANTED_V3,
                PASSPORT_CONSENT_REVOKED_V3,
                PASSPORT_ACCESS_READ_V1,
                PASSPORT_ACCESS_BREAKGLASS_V1,
                PASSPORT_EXPORT_GENERATED_V1,
                ALERT_RAISED_V1,
                ALERT_ACKNOWLEDGED_V1,
                ALERT_ESCALATED_V1,
                ALERT_CLOSED_V1,
                MARKET_ORDER_PLACED_V1,
                MARKET_ORDER_PAID_V1,
                MARKET_ORDER_SHIPPED_V1,
                MARKET_ORDER_DELIVERED_V1,
                MARKET_ORDER_RETURNED_V1,
                LOOP_OPENED_V1,
                LOOP_ACKNOWLEDGED_V1,
                LOOP_ESCALATED_V1,
                LOOP_CLOSED_V1,
                PROTOCOL_RATIFIED_V1,
                BOOKING_REQUESTED_V2,
                BOOKING_CONFIRMED_V2,
                BOOKING_CANCELLED_V1,
                CONVERSATION_HANDOVER_V1,
                VISIT_HANDOVER_SUBMITTED_V1,
                TRIAGE_COMPLETED_V2,
                REVIEW_SIGNED_V1,
                RESULT_ACKNOWLEDGED_V1,
                GUIDANCE_DELIVERED_V1,
                CHECKIN_OVERDUE_V1,
                PANIC_RAISED_V1,
                SOS_RAISED_V1,
                NOK_NOTIFIED_V1,
                SENTINEL_RUNG_RAISED_V1,
                SAFEGUARDING_REPORTED_V1,
                ADMISSION_NEED_IDENTIFIED_V1,
                FACILITY_CANDIDATE_SELECTED_V1,
                ADMISSION_PREAUTH_SUBMITTED_V1,
                ADMISSION_PREAUTH_DECIDED_V1,
                ADMISSION_REQUESTED_V1,
                ADMISSION_ACCEPTED_V1,
                ADMISSION_WAITLISTED_V1,
                ADMISSION_DECLINED_V1,
                TRANSPORT_ENROUTE_V1,
                ADMISSION_ARRIVED_V1,
                TRIAGE_VERIFIED_V1,
                ADMISSION_HANDOVER_COMPLETE_V1,
                TRIP_REQUESTED_V1,
                TRIP_ACCEPTED_V1,
                TRUST_SHIFT_START_MATCHED_V1,
                TRUST_SHIFT_START_REFUSED_V1,
                TRUST_DOOR_VERIFIED_V1,
                TRUST_DOOR_MISMATCHED_V1,
                PASSPORT_SHARE_LINK_CREATED_V1,
                PASSPORT_SHARE_LINK_USED_V1,
                PASSPORT_ANOMALY_DETECTED_V1,
                PASSPORT_ADMISSION_DETECTED_V1,
                PASSPORT_DISCHARGE_RECEIVED_V1,
                PRESCRIPTION_PRESCRIBED_V1,
                PRESCRIPTION_VERIFIED_V1,
                DISPENSE_COMPLETED_V1,
                DELIVERY_COLLECTED_V1,
                DELIVERY_HANDED_OVER_V1,
                LAB_ORDER_PLACED_V1,
                LAB_RESULT_RECEIVED_V1,
                READING_INGESTED_V1,
                DEVICE_STALE_V1,
                DEVICE_RECALLED_V1,
                PAYMENT_SUCCEEDED_V1,
                PAYMENT_FAILED_V1,
                PAYMENT_REFUNDED_V1,
                PAYOUT_SCHEDULED_V1,
                PAYOUT_PAID_V1,
                CLAIM_SUBMITTED_V2,
                CLAIM_DECIDED_V1,
                VISIT_BILLABLE_V1,
                REVIEW_BILLABLE_V1,
                PULSE_SESSION_STARTED_V1,
                PULSE_LISTENING_STARTED_V1,
                PULSE_UTTERANCE_FINALISED_V2,
                PULSE_THINKING_STARTED_V1,
                PULSE_DEVICE_HIGHLIGHT_V1,
                PULSE_GUIDANCE_PRESENTED_V1,
                PULSE_ESCALATION_STARTED_V2,
                PULSE_HANDOVER_COMPLETED_V1,
                TRUST_WEIGHT_DECIDED_V2,
                TRUST_DISPATCH_WITHHELD_V1,
                RECORD_BREAKGLASS_REVIEW_DUE_V1,
                RECORD_AUDIT_CHAIN_BROKEN_V1
            )
        }
    }

    const val CONTRACT_VERSION = 1
    const val FROZEN = true

    val engines = listOf(
        Engine("core", "ThusoIQ Core", "ThusoIQ"),
        Engine("access", "Access", "Gilbert"),
        Engine("pulse", "Gilbert Pulse Interaction Engine", "Gilbert Pulse"),
        Engine("care", "Care", "Thuso Nurse"),
        Engine("clinical", "Clinical Intelligence", "Thuso AI"),
        Engine("safety", "Safety", "Sentinel"),
        Engine("movement", "Movement", "Thuso Ride"),
        Engine("trust", "Trust", "Verify"),
        Engine("record", "Record", "Health Passport"),
        Engine("medicines", "Medicines & Labs", "Thuso Pharmacy"),
        Engine("devices", "Devices", "Thuso Kit"),
        Engine("money", "Money", "Thuso Money")
    )

    val events get() = EventKey.all

    fun ownerOf(type: String) = events.firstOrNull { it.type == type }?.owner
}
