// Generated by scripts/emit-geography.mjs from packages/catalog/geography.json.
// Do not edit by hand — run `npm run geography`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// Coordinates only. The arithmetic that consumes them — distance, projection, province, arrival
// estimate — is hand-written on this platform against packages/geo/README.md, because those are
// decisions rather than data and generating them would hide the decision.

package za.co.mythuso.model

object GeographyData {
    const val city = "Johannesburg"
    const val province = "Gauteng"
    const val phase = 1
    const val coverageSentence = "Phase one is northern Johannesburg and Soweto. Everywhere else on this map is drawn because it is there, not because anybody is working in it."

    val centre = LatLng(-26.172, 27.992)
    const val spanKm = 28.0
    const val zoom = 10.4
    const val minZoom = 8.5
    /** Fifteen is a privacy limit, not a performance one: above it a reader can pick out one house. */
    const val maxZoom = 15.0

    const val coordinateDecimals = 3
    const val precisionMetres = 110
    const val precisionSentence = "Every position in this preview is rounded to three decimal places — about a hundred metres. The suburbs are real; nobody lives at these points."

    val zones = listOf(
        Zone("randburg", "Randburg", LatLng(-26.094, 27.999), 3.0),
        Zone("rosebank", "Rosebank", LatLng(-26.146, 28.042), 2.4),
        Zone("parktown", "Parktown", LatLng(-26.184, 28.040), 2.2),
        Zone("melville", "Melville", LatLng(-26.175, 27.999), 2.2),
        Zone("soweto", "Soweto", LatLng(-26.249, 27.908), 4.0)
    )

    val marks = listOf(
        MapMark("zone", "Service zone", "A suburb MyThuso covers, drawn at its working radius."),
        MapMark("nurse-free", "Nurse available", "Cleared by vetting and not on a visit."),
        MapMark("nurse-busy", "Nurse on a visit", "Positioned, but not dispatchable until the visit closes."),
        MapMark("nurse-blocked", "Blocked by vetting", "Drawn where they are and refused all the same. A lapsed credential withdraws dispatch by arithmetic, not by somebody remembering."),
        MapMark("visit-waiting", "Visit awaiting a nurse", "Plotted at the centre of its suburb, never at its address."),
        MapMark("visit-assigned", "Assigned", "A nurse has accepted it.")
    )

    /**
     * No tile server is contacted by any native build. The schematic below is what both apps draw,
     * and it is why tileAttribution is carried without being rendered: the day a native map draws
     * streets, the credit is already here, in the same words the web renders, out of the same file.
     */
    const val schematicName = "Schematic"
    const val schematicSentence = "This map is drawn from the coordinates alone: the zones, the visits and the nurses, in their real positions, without streets behind them. No tile server is asked for anything."
    const val attributionRequired = true
    const val tileSource = "OpenFreeMap"
    const val tileAttribution = "OpenFreeMap © OpenMapTiles Data from OpenStreetMap"
    const val tileLicence = "Map data © OpenStreetMap contributors, under the Open Database Licence. Tile schema by OpenMapTiles. The OpenFreeMap software is MIT."

    const val privacySentence = "A map in MyThuso plots suburbs, not addresses."
    val privacyRules = listOf(
        GeographyRule("address-is-not-a-pin", "A visit awaiting a nurse is drawn at the centre of its suburb. Its street address is never a coordinate on any map, on any screen, at any zoom.", "A home address beside a health service is not a location, it is a diagnosis with a doorstep. The controller assigning the visit needs to know which suburb it is in; they do not need to know which house until they are the one going to it, and then it is in the visit, not on the board."),
        GeographyRule("a-nurse-is-not-tracked-between-visits", "A nurse who is not sharing a position has none, and the board says so rather than placing them somewhere plausible.", "An empty space is a true statement about a phone in a bag. A guessed pin is a false statement about a person's whereabouts, and it is the one a dispatcher would act on."),
        GeographyRule("no-history-drawn", "No map here draws where anybody has been. A position is the current one or it is absent.", "A track is a record of a person's movements. Nothing in this product needs one, so nothing in this product keeps one, and there is no screen that could be persuaded to show one."),
        GeographyRule("only-on-the-day", "MyThuso shows you where a nurse is on the day of your visit and not before. A nurse’s whereabouts between visits is her own, in the same way your address is yours.", "The sharpest rule on the patient's half of this map, and it is arithmetic rather than copy: no state that draws a nurse is reachable unless the visit is today, so there is no path through arrival that puts her on a map a fortnight early. A patient who can open a screen a fortnight before her appointment and watch a nurse move around Johannesburg has been handed a tracking device, and no part of arranging a home visit needs one. Before the day there is nothing to watch, and the screen says so rather than drawing an empty map."),
        GeographyRule("no-doorstep-at-either-end", "A nurse is drawn in the suburb she is working in, and your visit is drawn in the centre of yours — at both ends, at every zoom.", "address-is-not-a-pin read the other way round. That rule protects the patient's door from the board; this one protects the nurse's position from the patient, and says so in the same breath so neither reads as the exception. A nurse's working day is her private life as much as an address is somebody's."),
        GeographyRule("nothing-is-measured", "Nothing on this screen is being measured. No nurse’s device is read, no arrival is timed against your window, and nobody has been told you are watching.", "A patient looking at a moving estimate assumes somebody is watching back. Nobody is: the positions are this file's own zone centres, no geolocation permission is requested by any platform, and opening the screen is not an event anybody is sent. Said out loud on the screen, because the assumption is the thing that needs correcting."),
        GeographyRule("nothing-leaves-for-a-tile", "The tile server is asked for streets. It is never told what is on top of them — no visit, no patient, no nurse position is sent to any mapping provider.", "A map vendor that can see your pins can see your caseload. The zones, the visits and the nurses are drawn by this application on top of tiles that know nothing about them."),
        GeographyRule("a-tile-request-is-a-viewport", "Asking for streets still tells the tile server something: which square of the map is open, the internet address that asked, and the time. Over a visit that is roughly which suburb a patient is in and roughly when somebody came to the house. Streets are off until the person looking turns them on, and the schematic asks nobody anything.", "Until this map drew streets no tile was ever fetched, so there was nothing to disclose and nobody had disclosed it. Now there is. A viewport is not a pin, but a health service whose viewports a third party can watch has handed over a weaker version of the same thing, and one nobody agreed to. The sentence is rendered beside the switch rather than filed in a policy page, because the switch is where the decision is actually made.")
    )

    val refusals = listOf(
        GeographyRefusal("nobody-on-the-way-yet", "Nobody is on the way yet, so there is nothing to follow. You will see where she is on the day of your visit.", "What a patient reads ahead of the day. It says what is refused and leaves her somewhere to stand, which is the difference between a state and a blank — and it does not repeat the rule underneath it, because only-on-the-day is said once in the list of what this screen is not."),
        GeographyRefusal("no-window-no-nurse", "This visit has no time yet, so there is nobody assigned to be on the way. When a nurse accepts it you will be told who is coming and when.", "An as-soon-as-possible visit has no window, and a visit with no window has not been accepted by anybody. Drawing a nurse for it would invent an assignment that has not happened."),
        GeographyRefusal("visit-behind-you", "This visit is not ahead of you, so there is nothing to follow. What happened at it is in the visit itself.", "A past or cancelled visit has no arrival. The screen sends the reader to the record rather than to an empty map, because the question behind opening it is usually about what was found."),
        GeographyRefusal("not-an-arrival-time", "This is not an arrival time. It is the distance between two suburbs, divided by a speed — it does not know the traffic, the road, or the visit she is finishing first.", "No routing provider is connected, and a straight line through Johannesburg is optimistic by roughly a third. The figure is shown because a patient waiting at home is owed something; the sentence carrying it refuses the promise the figure looks like, in the same breath, rather than in a footnote."),
        GeographyRefusal("outside-south-africa", "That position is not in South Africa. It has not been drawn.", "packages/geo refuses the coordinate before a map sees it. A pin in the Atlantic is a data fault, and the map's job is to be the place it becomes visible rather than the place it is smoothed over."),
        GeographyRefusal("outside-coverage", "MyThuso is not working in that area yet. You can be told when it is.", "Refusing a booking outside phase one is the whole point of naming a phase. An app that takes the booking anyway has moved the disappointment to the patient's front door."),
        GeographyRefusal("no-position-shared", "This nurse is not sharing a position right now, so they are not on the map.", "Said out loud, on the board, next to the count. A dispatcher who cannot see the difference between nobody-there and nobody-reporting will read the map as the first one.")
    )
}
