// Generated by scripts/emit-interpreting.mjs from packages/catalog/interpreting.json.
// Do not edit by hand — run `npm run interpreting`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// Every interpreter below carries the hours they are actually free, unresolved. Which of them is the
// first free after the hour a patient asked for — and whether there is one at all — is worked out in
// Interpreting.swift and Interpreting.kt beside this file, from the same hours the web works it out
// from. A resolved wait here would mean the arithmetic lived in a generator, and a screen that is
// handed a number never has to decide whether it knows one.

package za.co.mythuso.model

const val interpreterRequirementId = "sasl-interpreter"
const val interpreterRoleId = "interpreter"
const val interpreterParticipantId = "interpreter"

/* Drafted, not confirmed. `confirmedBy` is null and every screen that shows this check says so —
   the same rule the locale contract holds a translation to. */
val interpreterAccreditation = InterpreterAccreditation(
    "South African Translators’ Institute", "SATI", "sati",
    "SATI runs an accreditation examination for South African Sign Language interpreters, and MyThuso has written its vetting check against that route: accreditation held with SATI, membership current, verified with SATI rather than taken from a certificate the applicant supplies.",
    null,
    null,
    null,
    "Nobody has confirmed that this is the right route. No Deaf South African, no accredited SASL interpreter and nobody at SATI, DeafSA or PanSALB has read the row in the vetting table or the six checks hanging off it. The membership-number format is deliberately not asserted — the vetting register accepts the number as it appears on the certificate rather than claiming to know its shape — because guessing a format is how a real interpreter gets told their real number is invalid. If accreditation runs through a different body, this is the wrong body and the check is the wrong check. It is written down under the name of the body it names so that it can be corrected by somebody who knows, rather than discovered by an interpreter who is refused.",
    "A named person at the accrediting body, their organisation and the date they read it, recorded in the three fields above. Until those are filled in, every screen that shows this check says that it is drafted."
)

val interpretingModes = listOf(
    InterpretingMode("in-person", "In the room", "The interpreter is at the address with you, in the same room as the nurse.", "The default for a home visit. A picture on a phone held at arm's length is not a signing space, and a visit where somebody has to hold the camera is a visit where somebody is not examining the patient."),
    InterpretingMode("video-remote", "On video, from elsewhere", "The interpreter joins on video, on a screen big enough to sign to.", "Faster to arrange and the only way this works after hours in most of the country. It depends on a line good enough to see hands on, which is why a call that drops to sound only is rebooked rather than continued."),
    InterpretingMode("tactile", "Hand over hand", "Tactile interpreting, for a patient who is Deafblind. The interpreter must be in the room; there is no remote version of it.", "The scarcest of the three by a long way, and the one this preview is least able to promise. Where none is free the screen says it does not know when one will be, rather than putting up a number.")
)

/* Free hours, unresolved. Interpreting.kt decides which one answers a request. */
val interpreterRoster = listOf(
    Interpreter(
        "I-701", "Nomvula Sithole", "1002481",
        "video-remote", "Johannesburg",
        listOf("Clinical consultation", "Home visit", "Mental health"),
        listOf(FreeDay(1, listOf("10:00", "11:00", "15:00")), FreeDay(2, listOf("09:00", "14:00")), FreeDay(4, listOf("08:00", "16:00")))
    ),
    Interpreter(
        "I-702", "Sipho Radebe", "1003117",
        "video-remote", "Johannesburg",
        listOf("Clinical consultation", "Paediatric", "After hours"),
        listOf(FreeDay(3, listOf("11:00", "12:00")), FreeDay(5, listOf("09:00", "10:00")))
    ),
    Interpreter(
        "I-703", "Karabo Mahlangu", "1004062",
        "in-person", "Johannesburg North",
        listOf("Clinical consultation", "Home visit", "Sexual and reproductive health"),
        listOf(FreeDay(5, listOf("14:00")))
    ),
    Interpreter(
        "I-704", "Thandiwe Nkosi", "1004890",
        "tactile", "Gauteng",
        listOf("Clinical consultation", "Home visit", "Deafblind (tactile) interpreting"),
        listOf()
    )
)

val interpreterHold = InterpreterHold(
    "Held for an interpreter", "This visit is held until an interpreter is free",
    "The visit is not booked and nobody has been dispatched. It is waiting for an interpreter, which is what the account asked for, and it stays waiting rather than going out without one.",
    "A nurse who arrives without the interpreter is a nurse standing in a room where nothing can be said. That is not a visit that half worked; it is a visit that did not happen, at the patient's expense and in the patient's home.",
    "The first interpreter free for this mode is offered here, with the day and the hour. Nothing is confirmed until that offer is accepted."
)

val interpreterEstimate = InterpreterEstimate(
    "The first interpreter free for this is",
    "We do not know when. Every hour we can see is taken, and we can only see the five days this app offers — so any number here would be one we made up.",
    "There is no estimate on this screen because there is nothing to work one out from. The screen does not show the day you asked for, it does not show a dash, and it never shows zero: a number here is a number somebody would plan a day off work around.",
    "Five days is as far ahead as MyThuso offers a visit at all. An interpreter free on the sixth is an interpreter this screen cannot see, and saying so is not the same as saying there is none."
)

val interpreterCancellation = InterpreterCancellation(
    0, "MyThuso",
    "Cancel — no interpreter was available",
    "Cancelling costs nothing, now or at any point while the visit is held. There is no window in which it becomes chargeable and no notice period, because the wait is not something the patient did.",
    "This is not recorded as a patient cancellation. MyThuso could not provide an accommodation it undertook to provide, and the record says that in those words — not ‘cancelled by patient’, and not ‘no longer required’. A service that files its own failure under the patient's name will keep failing and will look, in its own figures, like a service nobody wanted.",
    "Cancelling this visit does not switch the requirement off. It stays on the account, because it is a fact about the person and not a preference about this booking."
)

val interpreterWithdrawal = InterpreterWithdrawal(
    true,
    "The interpreter is on this call and will hear everything you tell the doctor. May they stay?",
    "Asking the interpreter to leave ends the consultation. It does not continue without them.",
    "A consultation the patient cannot follow is not one they can consent to, and consent to treatment is not something a doctor may take from a nod. So the call stops and is rebooked with a different interpreter — the patient's objection is to this interpreter, not to being understood.",
    "Ending the call is not a penalty for withdrawing. Nothing is charged, the encounter is written up as interrupted like any other, and the rebooking is offered on the same screen. Withdrawal here is exactly as easy as it is for every other person on the roster."
)

val interpreterCost = InterpreterCost(false, "The interpreter is never charged for — not as a line on the invoice, not folded into the visit price, and not as a surcharge on the hour it takes to arrange. An accommodation that is billed is a fee for being Deaf.")

/* Rendered word for word. A refusal paraphrased on one platform is a different promise on that
   platform, which is the whole reason these live in one file. */
val interpretingRules = listOf(
    InterpretingRule("held-not-dispatched", "A visit that needs an interpreter is held, not sent", "When the account records the requirement and no interpreter is free at the hour chosen, the visit is held. It is never confirmed and never dispatched on the understanding that somebody will manage — managing is what happens instead of a consultation."),
    InterpretingRule("estimate-says-when-it-does-not-know", "A wait that does not know says so", "When there is no free hour to measure a wait from, this screen says it does not know and says why. It does not show the day that was asked for, it does not show a dash, and it never shows zero."),
    InterpretingRule("cancelling-is-free-and-is-ours", "Cancelling because we could not staff it is free, and it is our cancellation", "A patient waiting for an accommodation may cancel at any point at no cost, and the cancellation is recorded against MyThuso rather than against them. Dressing a service failure up as the patient's choice is how the failure stops being visible."),
    InterpretingRule("one-roster", "The interpreter is the one already on the call roster", "A SASL interpreter joins a teleconsultation as the interpreter participant the roster already has — named, cleared, bound by the same confidentiality as the clinicians and consented to like everybody else. There is no second mechanism, because a second mechanism is where an unnamed person gets added."),
    InterpretingRule("vetted-like-anybody-else", "An interpreter is a vetted party", "An interpreter hears an entire consultation — the history, the examination and the part the patient nearly did not say. So they are identified, police-cleared, accredited, trained for a health setting and personally bound to confidentiality before they are on any roster, and a lapsed check withdraws them by arithmetic rather than by somebody noticing."),
    InterpretingRule("requirement-travels", "The requirement lives on the account", "It is set once and applies to every booking and every call from then on. A Deaf patient does not explain themselves again at each visit, and no screen asks them to confirm it as though it might have changed."),
    InterpretingRule("interpreter-sees-no-record", "Hearing a consultation is not reading a record", "An interpreter is granted one thing: to interpret. They are not given the patient summary, the clinical record, results or a protected category, because the interpreting is live and a record is not — and a party who can open a file after the call is a party who can read one they were never in the room for.")
)

val interpretingRefusals = listOf(
    InterpretingRefusal("family-as-interpreter", "A family member is never the interpreter", "Not a spouse, not an adult child, not a neighbour who signs a little. Three reasons, and each on its own is enough. Accuracy: a relative interprets what they understood and what they think is kind, and a clinical history is neither of those. Coercion: a person who depends on their family cannot be asked, through their family, whether their family is hurting them. And a patient has the right to say something the people they live with will not hear — a pregnancy, a diagnosis, a fear about the person doing the interpreting — and a family member in that chair removes the right without anybody having to refuse it."),
    InterpretingRefusal("child-as-interpreter", "A child is never an interpreter", "Under no circumstance, at no age, for no relative, in no emergency. Not to save a wait, not because they offered, and not because the alternative is rebooking. A child interpreting a diagnosis for a parent is a harm the appointment caused, and it is done to the child rather than by them."),
    InterpretingRefusal("written-english-instead", "Writing English at somebody is not an accommodation", "SASL is a language with its own grammar. It is not English on the hands and it has no written form, and for many Deaf South Africans written English is a second language learnt through a school system that was not built for them. A note pushed across a table, a form, a consent line and a discharge instruction are all offered in addition to interpretation and never instead of it. A nod is not comprehension, and neither is a signature."),
    InterpretingRefusal("dispatch-without-an-interpreter", "No visit goes out without the interpreter it needs", "There is no override on this screen, for the patient, the nurse or the Control Tower. A visit that needs an interpreter and has not got one is held, and if the wait is not acceptable it is cancelled at no cost — those are the two doors, and there is not a third."),
    InterpretingRefusal("interpreter-opens-the-record", "An interpreter is never given the record", "Not the summary, not the history, not the results, and never a protected category. What an interpreter hears they hear because they are in the room; what a record holds they have no route to, then or afterwards."),
    InterpretingRefusal("unnamed-interpreter", "Nobody interprets anonymously", "The interpreter is named to the patient — name, accreditation and how they will be present — before they are on the call or at the door. An interpreter the patient cannot name is an interpreter the patient did not agree to."),
    InterpretingRefusal("billed-as-an-extra", "The accommodation is never billed", "Not on the invoice, not inside the visit price, not as a call-out. There is no plan in which an interpreter is an upgrade."),
    InterpretingRefusal("cancellation-filed-against-the-patient", "Our failure is never filed under the patient's name", "A visit cancelled because MyThuso could not find an interpreter is not a patient cancellation, is not ‘no longer required’ and does not count against anybody's record. It counts against MyThuso, where it can be seen and argued about.")
)

val interpretingLabels = InterpretingLabels(
    "Interpreters",
    "This account uses South African Sign Language",
    "How should the interpreter be present?",
    "Who is available",
    "No interpreter is free at that time",
    "An interpreter is free at that time",
    "Held for an interpreter",
    "What an interpreter is checked for",
    "What this will not do",
    "Nothing free in the days we can see"
)

const val interpretingNotYetBuilt = "Nothing here contacts an interpreter, holds a real visit or books anybody's time. The roster is four fictional people with fictional availability, the accreditation route is drafted and unconfirmed, and no Deaf South African has read a word of this screen. What is built is the shape: the vetting row, the roster, the hold, the honest wait and the refusals — so that the arrangement can be argued with before it is relied on."
