// Generated by scripts/emit-movement.mjs from packages/catalog/movement.json, packages/catalog/apis/movement.json and packages/catalog/geography.json.
// Do not edit by hand — run `npm run movement`. The build fails if this file and its sources disagree,
// so an edit here is lost rather than merely wrong.
//
// Thuso Ride is non-emergency transport and never an ambulance. A responder sees a trip offered to them, accepts or
// declines it, reads the emergency summary only while the trip is under way, and hands the patient over by role
// with the checklist. The heartbeat interval is a PROPOSAL an admin changes on the web; this app has no admin
// surface and uses it as written. Nothing here reads this phone's position or reaches a responder.

package za.co.mythuso.model

object MovementData {
    /** A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
    const val HEARTBEAT_INTERVAL_SECONDS = 10

    const val NOT_AN_AMBULANCE = "Thuso Ride is non-emergency transport. It is not an ambulance service: nobody on a trip gives care in transit, and it never takes a P1."
    const val EMS_BOUNDARY = "Counsel's opinion on where the emergency medical services line falls has not been written. Until it is, Thuso Ride takes no P1, and no P2 a clinician did not set."
    const val PREVIEW = "A preview. No trip reaches a responder, no vehicle moves and this phone's position is never read. The trip is held on this screen and forgotten when it closes."
    const val POSITION_RULE = "A responder's position is kept only during a trip they accepted, one position at a time and never as a track, and it is dropped when the trip's window closes."

    val priorities = listOf(
        MovementPriority("P1", "P1 · emergency", false, "A P1 is an emergency. It needs a licensed ambulance service, and no licensed ambulance partner is connected to MyThuso."),
        MovementPriority("P2", "P2 · today, set by a clinician", true, "A P2 is set by a nurse or doctor whose vetting is current, in their own name, with a reason. No triage protocol is ratified, so nothing sets one on its own."),
        MovementPriority("P3", "P3 · scheduled", true, "A P3 is a scheduled trip, requested ahead of its pick-up.")
    )
    val tripStates = listOf(
        MovementChoice("requested", "Waiting for a responder"),
        MovementChoice("accepted", "A responder accepted"),
        MovementChoice("handed-over", "Handed over at the destination")
    )
    val receivingRoles = listOf(
        MovementChoice("admissions-desk", "The admissions desk"),
        MovementChoice("receiving-nurse", "The receiving nurse"),
        MovementChoice("receiving-doctor", "The receiving doctor"),
        MovementChoice("emergency-unit-reception", "The emergency unit's reception")
    )
    val checklist = listOf(
        "The patient is inside, and seated or in a bed.",
        "The person receiving the patient said who they are, by role.",
        "Nothing the patient brought is left in the vehicle."
    )
    val facilities = listOf(
        MovementChoice("facility-synthetic-1", "Synthetic district hospital · Randburg"),
        MovementChoice("facility-synthetic-2", "Synthetic regional hospital · Parktown"),
        MovementChoice("facility-synthetic-3", "Synthetic maternity unit · Soweto"),
        MovementChoice("facility-synthetic-4", "Synthetic step-down unit · Rosebank")
    )
    val zones = listOf(
        MovementChoice("randburg", "Randburg"),
        MovementChoice("rosebank", "Rosebank"),
        MovementChoice("parktown", "Parktown"),
        MovementChoice("melville", "Melville"),
        MovementChoice("soweto", "Soweto")
    )

    object ResponderText {
        const val HEADING = "Your trips"
        const val INTRO = "Trips offered to you, the trip you accepted and its hand-over. You give transport, not care."
        const val OFFERED = "Offered to you"
        const val NO_OFFERS = "No trip is offered to you right now."
        const val ACCEPT = "Accept this trip"
        const val DECLINE = "Decline"
        const val DECLINED = "Declined. The trip goes to the next responder."
        const val DESTINATION = "To {facility}"
        const val PICKUP = "Pick-up in {zone} from {when}"
        const val SUMMARY_HEADING = "Emergency summary"
        const val SUMMARY_OPEN = "Opened through the Health Passport under the patient's grant for this trip: {categories}. Nothing else opens."
        const val SUMMARY_NOT_YET = "The emergency summary opens only once you have accepted the trip."
        const val SUMMARY_CLOSED = "The emergency summary closed at the hand-over."
        const val HANDOVER_HEADING = "Hand-over at the destination"
        const val RECEIVING_ROLE = "Received by"
        const val CHECKLIST_HEADING = "Hand-over checklist"
        const val CHECKLIST_DONE = "I followed the checklist"
        const val HANDOVER = "Record the hand-over"
        const val HANDED_OVER = "Handed over at {when}. The trip is closed."
        const val HEARTBEAT = "While a trip is under way this phone sends its position every {interval}, the interval in force, and never between trips."
    }

    /** The sentences the responder's routes refuse in, word for word from packages/catalog/apis/movement.json. */
    object Refusals {
        const val NOT_VERIFIED = "A responder without a current verification is not online."
        const val HALF_A_POSITION = "A position is a latitude and a longitude together."
        const val POSITION_WITHOUT_A_TRIP = "A position is sent only during a trip you accepted, and never between trips."
        const val TRIP_NOT_YOURS = "That trip is not one you accepted."
        const val POSITION_AFTER_THE_WINDOW = "That trip's window has closed. Its position is no longer kept or read."
        const val TRIP_NOT_OFFERED = "That trip was not offered to you."
        const val TRIP_TAKEN = "Somebody else accepted that trip first."
        const val TRIP_CLOSED = "That trip is closed: it was handed over, or its window has run out."
        const val SELF_ASSIGNED_P2 = "A responder cannot assign themselves a P2."
        const val UNNAMED_RECEIVER = "A hand-over names who received the patient."
        const val CHECKLIST_NOT_FOLLOWED = "A hand-over is recorded only when its checklist was followed."
    }

    val previewTrip = MovementPreviewTrip("TRIP-0412", "P3", "randburg", 90, "facility-synthetic-1", "R-311")
}
