// Generated by scripts/emit-icons.mjs from packages/catalog/icons.json.
// Do not edit by hand — run `npm run icons`. The build fails if this file and the source disagree,
// so an edit here is lost rather than merely wrong.
//
// The MyThuso icon family, drawn by the design handoff of 28 September 2026 and adopted exactly.
// Primary patient destinations and healthcare actions; Lucide stays for universal utility actions;
// never both for one concept; the signal dot pulses only for something live or time-sensitive.

package za.co.mythuso.model

import za.co.mythuso.R

/** One icon of the family: its drawable, and the sentence that says when it is used. */
data class MyThusoIcon(val id: String, val name: String, val meaning: String, val drawable: Int)

object MyThusoIconsData {
    const val version = 1
    const val size = 24

    /** The family's rules, word for word. */
    val rules = listOf(
        "Use the MyThuso icon family for primary patient destinations, healthcare actions and branded feature entry points.",
        "Use Lucide only for universal utility actions such as search, close, download, arrows and overflow controls.",
        "Never mix a generic icon and a MyThuso icon for the same concept.",
        "The signal animation is for live or time-sensitive actions only. An icon that merely names a place does not pulse."
    )

    /** The signal dot every icon carries, and its pulse: scale only, on the shared curve, and only for
        something live. Under a zero animator scale it does not run at all. */
    object Signal {
        const val cx = 18.6f
        const val cy = 5.4f
        const val radius = 2.05f
        const val scaleFrom = 1f
        const val scaleTo = 1.25f
        const val durationMs = 1800
    }

    val icons = listOf(
        MyThusoIcon("dashboard", "Dashboard", "The patient's overview: the home destination, where visits, readings and messages meet.", R.drawable.ic_mythuso_dashboard),
        MyThusoIcon("health", "Health", "The patient's health: the passport, readings and what they mean.", R.drawable.ic_mythuso_health),
        MyThusoIcon("visit", "Visit", "A nurse's visit: booking one, the ones coming, and the one happening now.", R.drawable.ic_mythuso_visit),
        MyThusoIcon("quick", "Quick", "A quick action: the shortest way to the thing a patient does most.", R.drawable.ic_mythuso_quick),
        MyThusoIcon("results", "Results", "Results: a lab order, a reading that has been reviewed, an answer that has come back.", R.drawable.ic_mythuso_results),
        MyThusoIcon("medication", "Medication", "Medicines: a prescription, a repeat, a dispensing on its way.", R.drawable.ic_mythuso_medication),
        MyThusoIcon("mind", "Mind", "Mind and wellbeing: Live well, a check-in, the crisis lines.", R.drawable.ic_mythuso_mind),
        MyThusoIcon("messages", "Messages", "Messages: the thread with a nurse, a note for the visit, a reply waiting.", R.drawable.ic_mythuso_messages),
        MyThusoIcon("family", "Family", "Family: the household, the people a patient cares for and who care for them.", R.drawable.ic_mythuso_family),
        MyThusoIcon("settings", "Settings", "The patient's own settings destination: privacy, access and preferences. The handoff drew it as a member of the family, so it is one; a gear inside a screen that is merely a utility control stays Lucide.", R.drawable.ic_mythuso_settings)
    )

    fun icon(id: String): MyThusoIcon? = icons.firstOrNull { it.id == id }
}
