// Generated by scripts/emit-passport.mjs from packages/catalog/passport.json.
// Do not edit by hand — run `npm run passport`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// No reference range appears below, and none is coming from here. What a reading is judged against
// lives in packages/catalog/records.json and reaches this app as RecordsData; a copy beside the
// reading it flags is how a number that decides whether a doctor sees something comes to have two
// answers.
//
// Fictional patient, invented readings, nothing stored and nothing sent.

package za.co.mythuso.model

object PassportData {
    data class Holder(val name: String, val passportId: String, val issuedBy: String)
    data class Reviewer(val name: String, val registration: String)
    data class Readings(val dayOffset: Long, val values: Map<String, Double>, val note: String? = null)
    data class Review(val assessment: String, val plan: String, val next: String, val reviewedDayOffset: Long)
    data class Document(val name: String, val kind: String, val dayOffset: Long, val reviewed: Boolean, val opens: String? = null)
    data class Device(val id: String, val name: String, val offeredOn: List<String>, val sheet: String, val withdraw: String)
    data class Refusal(val id: String, val sentence: String)

    val holder = Holder("Lerato Molefe", "TH-2048-3920", "Akhanya IT Innovations")
    val reviewer = Reviewer("Dr N. Khumalo", "MP 0741225")

    // Four home visits over three months, oldest first. Every day is an offset from today rather
    // than a date, because the charts these draw were once literal arrays labelled '12 Aug'
    // through '4 Sep' — right the week somebody typed them and a year wrong by the next winter.
    // The third set is the one worth opening: a systolic above its upper reference on the day a
    // dose was missed, with the reason the person gave for it at the visit.
    val readingSets = listOf(
        Readings(-87, mapOf("systolic" to 128.0, "diastolic" to 82.0, "pulse" to 76.0, "respiratory" to 16.0, "temperature" to 36.7, "oxygen" to 98.0, "glucose" to 5.6)),
        Readings(-59, mapOf("systolic" to 134.0, "diastolic" to 86.0, "pulse" to 74.0, "respiratory" to 16.0, "temperature" to 36.6, "oxygen" to 98.0, "glucose" to 6.1)),
        Readings(-31, mapOf("systolic" to 141.0, "diastolic" to 90.0, "pulse" to 80.0, "respiratory" to 18.0, "temperature" to 37.0, "oxygen" to 97.0, "glucose" to 5.4), "Missed medication"),
        Readings(-3, mapOf("systolic" to 136.0, "diastolic" to 85.0, "pulse" to 72.0, "respiratory" to 16.0, "temperature" to 36.8, "oxygen" to 98.0, "glucose" to 5.2))
    )

    // The four the trends screen leads with. Seven charts on one phone screen is a wall; these are
    // the four a person with a blood-pressure diagnosis actually watches, and the rest are one tap
    // below in the same shape. The other three are not listed here — they are whatever the
    // observation contract holds that is not one of these, so a reading added to records.json
    // appears on the second screen without anybody editing this file.
    val headlineMeasures = listOf("systolic", "diastolic", "pulse", "glucose")

    val lastReview = Review(
        "Blood pressure is coming down again. The reading a month ago was above the reference range on the day a dose was missed; this one is inside it. Nothing here needs an urgent appointment.",
        "Keep taking the medicine at the same time each morning. Bring the boxes to the next visit so the nurse can check what is left.",
        "A nurse visit in about four weeks, or sooner if you feel unwell.",
        -2
    )

    // What the record holds, rather than what a screen offers to generate. None of these carries a
    // date of its own: each is issued out of the visit the last reading set was taken at, so a
    // document cannot claim a day on which no visit happened. Every one is marked reviewed by the
    // doctor named above, because a clinical document nobody signed is not a document.
    val documents = listOf(
        Document("Visit summary", "Clinical summary", -3, true),
        Document("Laboratory results", "Pathology report", -3, true, "Laboratory order LAB-0023"),
        Document("Medical certificate", "Certificate", -3, true)
    )

    // The integrations the passport offers and cannot open. Each owes the same three answers
    // before a person could sensibly say yes: exactly what would be read, exactly what would not,
    // and the fact that none of it is connected. The third is not written here — it is the devices
    // capability's notice in packages/catalog/capabilities.json, rendered rather than restated.
    // What is here is the part no other contract holds: how a particular operating system asks the
    // question, and where a person goes to take the answer back. Apple Health is the iPhone's
    // store and Health Connect is Android's, so each native app offers one of them; the web screen
    // is read on both phones and offers all three.
    val devices = listOf(
        Device("apple-health", "Apple Health", listOf("web", "ios"),
               "iOS asks you, on your own phone, one reading type at a time. MyThuso never sees the question and never sees a type you decline.",
               "Health → Sharing → Apps, on your phone. Withdrawing it stops new readings; it does not remove what is already on your record."),
        Device("health-connect", "Health Connect", listOf("web", "android"),
               "Health Connect asks you, on your own phone, one reading type at a time. MyThuso never sees the question and never sees a type you decline.",
               "Health Connect → App permissions, on your phone. Withdrawing it stops new readings; it does not remove what is already on your record."),
        Device("thuso-kit", "Thuso Kit", listOf("web", "ios", "android"),
               "The kit is paired at a visit, by the nurse, in front of you. Nothing pairs itself and nothing pairs while you are not there.",
               "Ask the nurse to unpair it, or unpair it from this screen once the kit is connected. An unpaired instrument sends nothing.")
    )
    fun devicesOn(platform: String) = devices.filter { platform in it.offeredOn }

    // The sentences the passport says out loud rather than merely obeys. See the Swift banner above.
    val refusals = listOf(
        Refusal("no-interpretation", "Nothing on this screen interprets a reading for you. What a number means for a particular person is a clinical judgement, and MyThuso does not make one."),
        Refusal("protected-not-by-permission", "These are released by you, entry by entry, and a permission sheet cannot hand one over on your behalf."),
        Refusal("asks-for-nothing-else", "A permission it does not need is a permission it does not ask for."),
        Refusal("nothing-goes-back", "Readings would come in. Your record would not go out to a store you did not choose to put it in."),
        Refusal("reading-types-only", "MyThuso asks for reading types and nothing else.")
    )
    fun refusal(id: String) = refusals.first { it.id == id }.sentence
}
