// Generated by scripts/emit-programmes.mjs from packages/catalog/programmes.json and packages/catalog/services.json.
// Do not edit by hand — run `npm run programmes`. The build fails if this file and the two sources
// disagree, so an edit here is lost rather than merely wrong.
//
// Every cohort below carries its real counts, unsuppressed. The floor — twelve people, four fifths
// dominance, and the secondary rule that hides a second group when only one would otherwise be
// hidden — is applied in Programmes.swift and Programmes.kt beside this file, from the same numbers
// the web applies it from. A pre-suppressed table here would mean the rule lived in a generator and
// the apps drew whatever they were handed.
//
// Each statement line names a service; what it cost is that service's price in the catalogue,
// resolved when this file was written. It is not a number anybody typed.

package za.co.mythuso.model

/* A judgement, not a standard. Nothing in POPIA names a number; this one is written down so it can
   be argued with, which is the opposite of a threshold buried in a query. */
val suppressionFloor = SuppressionFloor(
    12, 0.8, 5, 2,
    "A department of four is not anonymous, and neither is a shift of nine. Twelve is the smallest group in which one person is not obviously identifiable to colleagues who know who was away that week — and where it still would be, the dominance rule below closes the gap.",
    "A group of fourteen in which thirteen answered the same way tells the employer there is exactly one person who did not, and fourteen colleagues can usually work out who. A cell is suppressed when one answer covers four fifths of it, whichever answer it is: ‘almost nobody’ identifies as surely as ‘almost everybody’.",
    "Counts are published to the nearest five. A figure that moves by one between two reports names the person who moved it, and two reports a month apart are the easiest thing in the world to put side by side.",
    "If suppression hides only one group, that group's number is the total minus the ones that were published. So a second group is suppressed as well — the smallest that was going to be reported — and the arithmetic stops working. This is the rule that is always left out, and it is the one that makes the others real."
)

val employerSees = listOf(
    Disclosure("How many people were eligible", "The denominator. Without it, uptake is a number about nothing."),
    Disclosure("How many took part", "Rounded to the nearest five, and only where the group is big enough to report at all."),
    Disclosure("How many were advised to see a doctor", "An aggregate outcome, which is what a programme is bought for: whether it found anything."),
    Disclosure("What it cost", "They are paying for it. An invoice by service and date, with no clinical detail on it anywhere."),
    Disclosure("Which of their groups could not be reported, and why", "A blank with no explanation reads as an error and invites somebody to go and ask. A blank that says ‘fewer than twelve people’ is an answer.")
)

val employerNeverSees = listOf(
    Disclosure("A name", "Not on a list, not in a total of one, not in an export, not on request."),
    Disclosure("Who took part", "Attendance is a health fact about a person. An employer knowing who went is an employer able to ask why the others did not."),
    Disclosure("Who declined", "There is no such category. A decline and a not-yet look exactly alike, deliberately."),
    Disclosure("Any result, reading, diagnosis or referral belonging to a person", "This is the one that has no exception, and it is why the aggregate-only undertaking is a vetting check rather than a clause."),
    Disclosure("Anything about a group of fewer than twelve", "Not the uptake, not the outcome, not the fact that the group exists on the report.")
)

val programmeDeclining = Declining(
    "Declining is invisible",
    "An employee can say no and their employer will not learn that they said no. The report has two numbers — how many were eligible and how many took part — and the difference between them contains people who declined, people who have not got round to it, people who were on leave and people who changed their minds twice. There is no route in this product that separates them, because a product that could separate them would be asked to.",
    "The invitation goes to the employee, from MyThuso, and the reply comes back to MyThuso. The employer is not on that conversation at any point."
)

val programmeEnrolment = listOf(
    ProgrammeStep("Eligibility", "The employer says which groups the programme is offered to. That is a list of jobs, not a list of people — MyThuso matches it against who has an account, and the employer never sees the match."),
    ProgrammeStep("Invitation", "Each eligible person is invited by MyThuso, in their own language, with what the programme is, who pays for it and what their employer will and will not be told."),
    ProgrammeStep("Joining", "The employee joins in their own account. Joining is a consent with a purpose and a period on it, recorded the way every other consent is."),
    ProgrammeStep("Care", "The visit is a visit like any other. The clinical record belongs to the patient and sits where every other clinical record sits."),
    ProgrammeStep("Counting", "The visit adds one to a count. Nothing else about it leaves the record.")
)

val programmeLeaving = listOf(
    ProgrammeStep("You stop being counted", "From the day you leave, nothing you do is added to the employer's figures and the employer stops paying for your care."),
    ProgrammeStep("Figures already published stay published", "A report issued in March does not have your name in it and cannot have you taken out of it. Withdrawing does not un-publish a number, and saying otherwise would be a promise nobody could keep."),
    ProgrammeStep("Your record stays yours", "It was never the employer's, so leaving does not move it, copy it or delete it. It is in your Health Passport, where it was."),
    ProgrammeStep("The employer is not told you left", "Their count changes, and a changed count is not a notification. It is also exactly why the floor and the rounding above exist: a count that moves by one is a message about one person."),
    ProgrammeStep("Nothing is reclaimed from you", "Care the employer already paid for is not billed back to you because you left the programme.")
)

val sponsorSees = listOf(
    Disclosure("That care was given", "The thing they paid for happened. That is the whole of what a payer needs."),
    Disclosure("The date and the amount", "It is their money. A statement they cannot reconcile is a statement they will ring somebody about."),
    Disclosure("What is left of what they set aside", "So they can decide whether to add to it.")
)

val sponsorNeverSees = listOf(
    Disclosure("Why the visit happened", "The reason for care is the care."),
    Disclosure("What was found", "No reading, no result, no diagnosis, no note, no referral. Ever, and not by asking."),
    Disclosure("Whether anything needs following up", "‘A second visit is needed’ is a finding wearing a diary entry's clothes."),
    Disclosure("Which service it was, unless the recipient turns that on", "A line reading ‘sexual health screening’ discloses more than most diagnoses do. So the default statement says an amount and a date, and naming the service is the recipient's switch to flip — never the sponsor's to ask for.")
)

val lineDetailChoices = listOf(
    LineDetailChoice("amount-only", "An amount and a date", "The default. Care was given on this day and cost this much. Nothing else.", true),
    LineDetailChoice("service-named", "An amount, a date and the service", "Only if the recipient switches it on, per sponsor, and only for as long as they leave it on.", false)
)

val sponsorConsent = SponsorConsent(
    "The recipient agrees, in their own account, in their own words",
    "A sponsorship does not start because somebody offered to pay. It starts when the person being paid for says yes, from their own account — which is a vetting check on the sponsor rather than a tick box on the payment.",
    "The recipient can stop it at any time, without telling the sponsor why. Stopping it ends future payments. It does not undo care that has already happened, and it does not bill anybody for it."
)

/* Rendered word for word. A rule paraphrased on one platform is a different promise on that
   platform, which is the whole reason these live in one file. */
val programmeRules = listOf(
    ProgrammeRule("floor-before-anything", "Nothing is reported about a small group", "No figure is published about a group of fewer than twelve people — not the uptake, not the outcome, not a rounded version of either. A department of four is not anonymous, and a report that says so anyway is a report that names four people."),
    ProgrammeRule("dominance-hides-the-one", "A near-unanimous group is not reported either", "Where one answer covers four fifths of a group, the group is not reported. Thirteen of fourteen tells an employer there is exactly one person who is not like the others, and fourteen colleagues can usually work out who."),
    ProgrammeRule("figures-do-not-reconcile", "The parts do not add up to the whole, on purpose", "The groups shown will not sum to the total, and they are not meant to. If they did, anybody could work out what was withheld by subtracting — which would make every suppression above decorative."),
    ProgrammeRule("rounded-not-exact", "Counts are rounded", "Every published count is to the nearest five. A figure that moves by one between two reports names the person who moved it, and two reports a month apart are the easiest thing in the world to lay side by side."),
    ProgrammeRule("taking-part-is-the-employees", "Taking part is the employee's decision, and only theirs", "The invitation comes from MyThuso, the answer goes back to MyThuso, and the employer is not on that conversation. They are told how many people took part. They are never told which, and never told who said no."),
    ProgrammeRule("paying-is-not-permission", "Paying for care grants no access to it", "A sponsor is verified for payment and told in writing, before they pay anything, that it grants no clinical access whatsoever. What they paid for is theirs to see. What was found is not, and there is no amount of money and no relationship that changes that."),
    ProgrammeRule("leaving-does-not-unpublish", "Leaving stops the counting; it does not rewrite what was counted", "From the day you leave, nothing of yours is added to any figure. A report already issued does not contain your name and cannot have you taken out of it, and a product that claimed otherwise would be promising something it could not do.")
)

val programmeRefusals = listOf(
    ProgrammeRefusal("named-result", "An employer never receives a named result. Not on request, not under a contract, not in an emergency, not with the employee's own consent — because if an employee wants their employer to have something they share it themselves, from their own record, to a named person, for a stated purpose and period. That is a different thing, and this product does not do it on their behalf."),
    ProgrammeRefusal("identify-by-subtraction", "No figure is published that another published figure can be subtracted from to reveal a suppressed one. Where suppression would leave a single hidden group, a second group is suppressed as well."),
    ProgrammeRefusal("learn-who-declined", "There is no report, export, filter or support request that tells an employer who declined. Declining is not a state this product records against a name for an employer to ever be given."),
    ProgrammeRefusal("condition-employment", "Nothing MyThuso produces can be used to make taking part a condition of employment, because nothing MyThuso produces says who took part. That is not a policy sitting on top of the data; it is the reason the data is shaped this way."),
    ProgrammeRefusal("require-the-detail", "A sponsor cannot make payment conditional on being told what the care was for. That is buying a record, and it is refused whatever the sponsor's relationship to the patient — a parent, a spouse and an employer are all the same answer here."),
    ProgrammeRefusal("report-below-the-floor", "A group under the floor is not reported at a coarser grain, at a longer interval, or ‘just this once’ for a board pack. It is not reported.")
)

val suppressionReasons = listOf(
    SuppressionReason("below-floor", "Fewer than twelve people. Nothing about this group is reported — not the uptake, not the outcome, and not a rounded version of either."),
    SuppressionReason("dominated", "One answer covers four fifths of this group, which would tell you how many people the rest of it is. Nothing about it is reported."),
    SuppressionReason("secondary", "Withheld so that the group above it cannot be worked out by subtracting the published groups from the total. This one is reportable on its own; it is the arithmetic that is not.")
)

/* Unsuppressed. The floor is applied in Programmes.kt, not here. */
val programmes = listOf(
    Programme(
        "annual-health-check", "Annual health check", "E-012", -118,
        "The whole workforce, once a year. Six groups, three of which cannot be reported — one for being too small twice over, one for a shift of nine, and one where thirteen of fourteen answered the same way.",
        listOf(
            Cohort("shaft", "Shaft operations", 214, 96, 27),
            Cohort("engineering", "Engineering", 148, 61, 18),
            Cohort("administration", "Administration", 38, 19, 5),
            Cohort("drivers", "Drivers", 15, 14, 1),
            Cohort("night-shift", "Night shift, Germiston", 9, 7, 2),
            Cohort("executive", "Executive", 4, 4, 1)
        )
    ),
    Programme(
        "silicosis-screening", "Silicosis screening", "E-012", -61,
        "Four groups, and only one of them falls under the floor — which is the case the secondary rule exists for. Publishing the other three beside the total would give the suppressed one away by subtraction, so the smallest reportable group is withheld as well.",
        listOf(
            Cohort("shaft", "Shaft operations", 214, 141, 39),
            Cohort("engineering", "Engineering", 96, 44, 11),
            Cohort("administration", "Administration", 41, 22, 6),
            Cohort("health-safety", "Mine health and safety", 7, 7, 2)
        )
    )
)

val sponsorStatement = SponsorStatement(
    "S-022", "Grace Mokoena", "Mother",
    3000,
    "Three visits, an amount and a date each. Which visit it was appears only because the recipient has switched that on for this sponsor, and she can switch it off again without saying why.",
    listOf(
        StatementLine(-31, 399, "Elderly care"),
        StatementLine(-17, 249, "Vitals & chronic check"),
        StatementLine(-3, 399, "Elderly care")
    )
)
