// Generated by scripts/emit-scheduling.mjs from packages/catalog/scheduling.json.
// Do not edit by hand — run `npm run scheduling`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// No date appears below. The days offered are computed from the device clock in the timezone named
// here, and a weekday is derived from its own date — which is the defect this contract exists to
// close, so writing one out would defeat the point.

package za.co.mythuso.model

object SchedulingData {
    const val timezone = "Africa/Johannesburg"
    const val timezoneNote = "South Africa has one timezone and does not observe daylight saving, so a visit time means the same thing everywhere MyThuso operates. It is still named rather than assumed, because a device set to another zone must not silently shift a nurse's arrival."
    const val daysOffered = 5
    const val firstDayOffset = 1
    const val firstDayNote = "The strip starts tomorrow. Same-day care is a different thing with a different promise, and it is offered as that rather than as a date chip."
    val slots = listOf("08:00", "09:00", "10:00", "11:00", "12:00", "14:00", "15:00", "16:00", "17:00")
    const val slotNote = "Hourly, with the hour after twelve left out because a nurse eats. The visit's own duration decides when it ends, not the next chip along."
    val kinds = listOf(
        BookingKind("scheduled", "At a time you choose", "You pick the day and the hour, and the nurse arrives in that hour.", false, "Booked for the day and time you chose."),
        BookingKind("asap", "As soon as someone is free", "We look for the nearest available nurse and tell you who is coming and when. If nobody is free, we say so rather than leaving you waiting.", true, "We are looking for a nurse now. You will be told who is coming before they set off.")
    )
    val rules = listOf(
        SchedulingRule("estimate-belongs-to-asap", "An arrival estimate is not a description of an appointment", "An arrival estimate answers “when will somebody get here”, which is only a question when you have asked for care now. Printing one beside a visit you booked for Thursday at ten tells you nothing and reads like a contradiction."),
        SchedulingRule("weekday-from-date", "The weekday is worked out from the date", "A day is shown as the weekday its date actually falls on, computed on the device. A label typed beside a date is a label that will one day disagree with it, and the person who notices will be the one standing at the wrong door."),
        SchedulingRule("duration-decides-the-end", "The visit's own length decides when it ends", "A visit ends its own duration after it starts, from the service catalogue. An hour is not the answer for every visit and pretending otherwise misstates how long somebody has to be at home."),
        SchedulingRule("everything-survives-the-booking", "What you chose is what is booked", "The patient, the service, the date, the time, the address and how you meant to pay all travel from the booking into the visit. A confirmation that quietly drops one of them is a confirmation of something you did not choose.")
    )
    const val chooseWhen = "When would you like the visit?"
    const val scheduledHeading = "Choose a date and time"
    const val noUpcoming = "Nothing booked yet"
    const val noUpcomingDetail = "When you book a visit it will show here, with who is coming and when."
    const val asapPending = "Looking for a nurse"
    const val changeDate = "Change the date or time"
}
