// Generated by scripts/emit-shop.mjs from packages/catalog/shop.json.
// Do not edit by hand — run `npm run shop`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// The MyThuso shop. Devices, consumables and wellness goods — and no medicine, at all, of any
// schedule. Supplying medicine is a licensed activity under the Medicines and Related Substances
// Act 101 of 1965, and a shop that sells a monitor today and a painkiller tomorrow has become a
// pharmacy without a licence. A listing says what a thing does and never what it treats.
//
// Prices are integer cents. Nothing here is a real service: no card is charged, no order is
// placed and nothing is delivered.

package za.co.mythuso.model

data class ShopProduct(
    val id: String, val name: String, val category: String,
    val priceCents: Int, val stock: Int, val does: String, val needsReading: Boolean
)
data class ShopCategory(val id: String, val name: String, val blurb: String, val pointsEligible: Boolean)
data class ShopRefusal(val id: String, val sentence: String)

val shopCategories = listOf(
    ShopCategory("measuring", "Measuring devices", "Things that take a reading at home.", true),
    ShopCategory("consumable", "Consumables", "Dressings, strips and the parts that run out.", true),
    ShopCategory("maternity", "Mother and baby", "For pregnancy and a baby's first year.", true),
    ShopCategory("mobility", "Mobility and safety", "Getting around the house, and not falling in it.", true),
    ShopCategory("firstaid", "First aid", "What a household keeps in the cupboard.", true)
)

val shopProducts = listOf(
    ShopProduct("bp-upper", "Upper-arm blood pressure monitor", "measuring", 74900, 24, "Takes a blood pressure reading from the upper arm and stores the last sixty.", true),
    ShopProduct("oximeter", "Fingertip pulse oximeter", "measuring", 32900, 40, "Estimates oxygen saturation and pulse from a fingertip.", true),
    ShopProduct("thermometer", "Digital thermometer", "measuring", 14900, 60, "Takes a temperature under the arm or in the mouth.", true),
    ShopProduct("glucose-strips", "Glucose test strips, 50", "consumable", 28900, 35, "Fifty single-use strips for a compatible glucose meter.", true),
    ShopProduct("bp-cuff-large", "Large blood pressure cuff", "consumable", 21900, 18, "A wider cuff for an upper arm the standard cuff does not close around.", false),
    ShopProduct("dressings", "Sterile dressing pack", "consumable", 18900, 52, "Sterile gauze, pads and tape for covering a wound between visits.", false),
    ShopProduct("maternity-pillow", "Maternity support pillow", "maternity", 45900, 14, "Supports the back and the abdomen while sleeping in later pregnancy.", false),
    ShopProduct("baby-scale", "Baby weighing scale", "maternity", 89900, 9, "Weighs an infant to the nearest ten grams.", true),
    ShopProduct("grab-rail", "Bathroom grab rail", "mobility", 27900, 26, "Bolts to a wall to hold onto beside a bath or a toilet.", false),
    ShopProduct("walker", "Folding walking frame", "mobility", 109900, 7, "Takes a person's weight through the arms while walking, and folds flat.", false),
    ShopProduct("firstaid-home", "Household first-aid kit", "firstaid", 34900, 31, "Plasters, bandages, gloves, scissors and a foil blanket in one box.", false),
    ShopProduct("bp-diary", "Home readings notebook", "firstaid", 5900, 80, "A printed book for writing down a reading and the date beside it.", false)
)

val shopNeverSold = listOf("medicine", "medication", "tablet", "capsule", "syrup", "antibiotic", "analgesic", "schedule", "prescription", "pharmacy-only", "supplement", "vitamin", "remedy", "treatment")

val shopRefusals = listOf(
    ShopRefusal("no-medicine", "We do not sell medicine here. A medicine reaches you through a pharmacy that has seen a prescription, not through a shop."),
    ShopRefusal("no-payment", "This is a preview. No card is charged, no order is placed and nothing is delivered."),
    ShopRefusal("no-claim", "This tells you what the item does. It does not say what it will do for you — a nurse or a doctor decides that."),
    ShopRefusal("reading-is-not-advice", "This device takes a reading. It does not tell you what the reading means, and a reading on its own is not a diagnosis."),
    ShopRefusal("outside-coverage", "We cannot deliver to this address yet. It is outside the areas MyThuso reaches, and we would rather say so than take the order."),
    ShopRefusal("stock-held-once", "Someone else reserved the last one while this basket was open. It is no longer held for you."),
    ShopRefusal("no-minor-account", "This account belongs to someone under eighteen. A guardian has to place the order.")
)

object ShopData {
    const val currency = "ZAR"
    const val deliveryFeeCents = 6500
    const val deliveryFreeAboveCents = 75000
    const val deliveryStandardDays = 3

    fun product(id: String) = shopProducts.firstOrNull { it.id == id }
    fun category(id: String) = shopCategories.firstOrNull { it.id == id }
    fun refusal(id: String) = shopRefusals.firstOrNull { it.id == id }
}
