// Generated by scripts/emit-sick-note.mjs from packages/catalog/sick-note.json, the teleconsultation's refusal and the protocol it names.
// Do not edit by hand — run `npm run sick-note`. The build fails if this file and its sources
// disagree, so an edit here is lost rather than merely wrong.
//
// Nothing here issues a certificate. The preview signs nothing, sends nothing and stores nothing.

package za.co.mythuso.model

object SickNoteData {
    const val version = 1
    const val capability = "issue-medical-certificate"
    const val notIssued = "Not issued. This is a preview: no certificate was signed, nothing was sent to an employer or a school, and nobody may rely on it. MyThuso does not yet produce a certificate a doctor signs in their own hand."
    const val notIssuedShort = "Not issued — a preview"
    const val memoryOnly = "It is held only in the app's memory while the app is open. Close or reload it and the certificate is gone: nothing was stored, on this device or anywhere else."
    const val notADoctor = "A nurse assessment is not a diagnosis. Prescriptions, sick notes and referrals need a registered doctor to review and sign."
    val writers = listOf("N-205", "D-401", "D-402")
    const val notHeld = "Not on the register. A real certificate carries it; this preview says it has none rather than inventing one."
    val notCarried = listOf("No identity number is carried. Rule 16 asks for the patient's name, and a number that opens every other record about a person has no business on a note handed to an employer.", "No employment number is carried. Rule 16 asks for one where it applies; the patient adds it, because MyThuso holds nothing about anybody's employer.")
    /** The certificate criteria protocol as packages/catalog/protocols.json holds it. */
    const val protocolLine = "Medical certificate criteria, version 1: draft. The criteria a certificate is written against are a protocol nobody has ratified. This composer holds what rule 16 and section 23 require and its own two limits on the period, and nothing clinical."

    object Basis {
        const val homeVisit = "A registered nurse examined the patient in person at home at the consultation named above, and I reviewed what she found. I did not examine the patient myself."
        const val byVideo = "A doctor who joins a visit by video sees the patient on a screen, and that is not an examination. The examination at a home visit is the nurse's."
        const val backdated = "The days before the consultation are certified on what the patient reported, not on anything anybody observed."
    }

    object Diagnosis {
        const val consentLabel = "The patient has agreed, in this consultation, to the illness being described on the certificate"
        const val descriptionLabel = "The illness, in plain words"
        const val descriptionHint = "As the patient would say it to somebody who is not a clinician."
        const val descriptionMaxLength = 160
        const val withheld = "Not described. The patient has not agreed to the illness being written on a document somebody else will read."
    }

    object Period {
        const val backdateDays = 2
        const val maxDays = 14
        const val defaultDays = 3
    }

    object Screen {
        const val title = "Medical certificate"
        const val deskTitle = "Medical certificates"
        const val lead = "A sick note for a patient seen at a consultation: the days they could not work, what that rests on, and the doctor who would sign it."
        const val deskLead = "Choose the consultation the certificate comes out of. A certificate is tied to one; without it there is nothing to certify."
        const val consultationLabel = "Consultation"
        const val writingAs = "Writing as"
        const val fitnessLabel = "Certified as"
        const val fromLabel = "First day"
        const val toLabel = "Last day"
        const val daysLabel = "days"
        const val sign = "Sign the certificate"
        const val signed = "Signed in the preview"
        const val close = "Close"
        const val again = "Write another"
        const val refusedHeading = "Why this cannot be signed"
        const val readyLine = "Every rule is met. Signing in the preview shows the certificate as the patient would see it, marked not issued."
        const val asSeenHeading = "As the patient would see it"
        const val unsigned = "Not signed. A preview signs nothing."
        const val passportHeading = "Written in this session"
        const val rulesHeading = "What it carries, and why"
    }

    /** Rule 16's items, labelled as the contract labels them. */
    val labels = mapOf(
        "practitioner" to "Practitioner",
        "registration" to "HPCSA registration",
        "qualification" to "Qualification",
        "practiceNumber" to "Practice number",
        "practiceAddress" to "Practice address",
        "patient" to "Patient",
        "consultation" to "Consultation",
        "basis" to "What it rests on",
        "statement" to "Certified",
        "period" to "Period of incapacity",
        "issued" to "Issued",
        "signature" to "Signed"
    )

    val fitness = listOf(
        SickNoteFitness("unfit", "Unfit for duty", "In my opinion, based on the examination at this consultation, the patient is unfit for work."),
        SickNoteFitness("light", "Fit for less strenuous duties only", "In my opinion, based on the examination at this consultation, the patient is fit only for less strenuous duties at work.")
    )

    /** Day offsets from today, so the preview never goes stale. */
    val consultations = listOf(
        SickNoteConsultation("TH-2048", "Lerato Molefe", "home-visit", "N-205", 0, "09:40"),
        SickNoteConsultation("TH-2039", "Thabo Molefe", "home-visit", "N-205", -3, "14:10"),
        SickNoteConsultation("TH-2051", "Nomsa Molefe", "video-call", null, 0, "11:15"),
        SickNoteConsultation("TH-2055", "Lerato Molefe", "home-visit", "N-205", 1, "08:30")
    )

    /** Every refusal but the lapsed registration's, which is the vetting register's. "{days}" is filled by the model. */
    val refusals = mapOf(
        "no-consultation" to "No consultation, no certificate. A certificate says what was found at a consultation, and there is none on record under this reference.",
        "from-a-call" to "Not from a call. The sick-note visit in the service catalogue is a visit: a nurse examines the patient in person and a doctor reviews what she found.",
        "not-yet-seen" to "This consultation has not happened yet. A certificate is written about a consultation that has, so the day it was held can never be after the day the certificate is issued.",
        "not-this-patient" to "A certificate names the patient the consultation was about, and nobody else.",
        "not-a-doctor" to "A nurse assessment is not a diagnosis. Prescriptions, sick notes and referrals need a registered doctor to review and sign.",
        "period-backwards" to "The last day of the period is before the first. A period runs forwards.",
        "starts-after-issue" to "The period starts after the day the certificate is issued. A certificate records an incapacity the doctor has found, never one that is expected.",
        "backdated-too-far" to "A certificate reaches back at most {days} days before the consultation, and those days rest on what the patient reported. Earlier than that is not something this consultation can tell anybody.",
        "period-too-long" to "One certificate covers at most {days} days. A longer incapacity is seen again and certified again, so that somebody looks at the patient before the period grows.",
        "diagnosis-without-consent" to "The illness is described only if the patient has agreed to it being on a document somebody else will read. Without that agreement the certificate says only whether the patient can work.",
        "consent-without-description" to "The patient agreed to the illness being described, and nothing is written. Describe it in plain words, or leave the agreement unticked."
    )
}
