// Generated by scripts/emit-skin-check.mjs from packages/catalog/skin-check.json and the knowledge entries it names.
// Do not edit by hand — run `npm run skin-check`. The build fails if this file and its sources
// disagree, so an edit here is lost rather than merely wrong.
//
// General information from public health sources, not reviewed by a clinician yet. No photo is
// read by anything on any platform; see photoReading.

package za.co.mythuso.model

object SkinCheckData {
    const val version = 1
    const val chipLabel = "Show GilbertOne a rash"
    val whatItIsNot = listOf("GilbertOne does not look at your photo. Nothing reads it in this build — it is there for you to compare later and to show your nurse.", "GilbertOne will not say what your rash is. Only a nurse or doctor who sees it can say what yours is.", "Nothing here is a prescription. The care steps are general first aid from public health sources.")
    val required = listOf("who", "signs")

    object Review {
        /** Null until a registered clinician has read and signed the check. */
        val reviewedBy: String? = null
        const val unreviewed = "No clinician has reviewed this skin check yet: its questions, its rules and the information it shows are general, from public health sources, and held inside the app."
        /** "{reviewedBy}" is filled by the screen. */
        const val reviewed = "This skin check was reviewed by {reviewedBy}. Your nurse will still look for herself."
    }

    object Screen {
        const val title = "Show GilbertOne a rash"
        const val lead = "Take or choose a photo of the skin and answer a few set questions. GilbertOne will tell you what public health sources say about rashes like this, and whether a sign means a sister should see it today."
        const val backLabel = "Back to the conversation"
        const val seeLabel = "See what GilbertOne can tell you"
        const val changeLabel = "Change my answers"
        const val endLabel = "End the check"
        const val ended = "The check has ended. The photo is gone from this screen and nothing was kept."
        const val multiHint = "Choose all that fit."
        const val textHint = "In your own words, or leave it empty."
        const val missing = "Answer who the rash is on and the question about signs first. Those two decide what GilbertOne may show you."
    }

    object Photo {
        const val chooseLabel = "Choose a photo"
        const val takeLabel = "Take a photo"
        const val replaceLabel = "Choose a different photo"
        const val removeLabel = "Remove the photo"
        const val alt = "Your photo of the skin, held on this phone only"
        const val held = "Your photo stays on this phone, on this screen only. It is not uploaded, not saved and not sent to anyone, and it is gone when the check ends."
        const val noReader = "Nothing looks at your photo in this build — not GilbertOne, not a computer program and not a person at MyThuso."
        const val videoRefused = "Video is not taken here. A video carries sound, and this build records no sound outside the push-to-talk the founder approved; a still photo shows a rash just as well to your nurse."
        const val notImage = "Choose a photo. Other kinds of file are not taken here."
        /** From packages/catalog/assistant-chat-ui.json#attachments, the panel's own limit. */
        const val limitBytes = 10485760
        const val tooLarge = "Choose a file smaller than 10 MB."
    }

    object SisterToday {
        const val headline = "Show a sister today — do not wait"
        const val lead = "Your answers include a sign that public first-aid guidance says a nurse or doctor should see the same day, and for some signs the guidance says to call an ambulance. GilbertOne has not decided anything about you; below is what the guidance says about that sign."
        const val becauseLabel = "Because you said"
        const val guidanceLabel = "What the guidance says"
        const val arrange = "Book a nurse is where you arrange a visit, or go to your clinic today. Nothing is booked from here — this is a preview."
        const val worse = "If it gets worse quickly, or anybody has trouble breathing, use the emergency numbers in GilbertOne straight away."
    }

    object Information {
        const val headline = "What rashes like this often are"
        const val lead = "Rashes like this are often one of the ones below. This is general information from public health sources, not an answer about your skin."
        const val onlyAClinician = "Only a nurse or doctor who sees it can say what yours is."
        const val looksLabel = "Often looks like"
        const val whenLabel = "When to ask a sister"
        const val maxShown = 4
        const val noneMatched = "Your description does not narrow it down to anything general information can speak to. A nurse who sees it can."
        const val checkFirstHeading = "Check this first"
        const val selfCareHeading = "Looking after it at home"
        const val selfCareLead = "General first-aid steps from public health sources. If anything under When to ask a sister fits, ask one rather than waiting."
        const val warningsLabel = "Take care"
        const val whenToCallLabel = "When to get help"
    }

    object Summary {
        const val title = "Notes for your sister"
        /** "{question}" and "{answer}" are filled by the screen. */
        const val line = "{question}: {answer}"
        const val photoLine = "A photo is on your phone only. Show it to your sister at the visit."
        const val copyLabel = "Copy the notes"
        const val copiedLabel = "Copied"
        const val sendLead = "Sending these notes to a nurse from here is not built."
        /** The handover submit route's own refusal, from packages/catalog/apis/assistant.json. */
        const val sendRefusal = "A handover reaches no clinician from here: the identity, roster and destination contracts it would need do not exist."
    }

    object Knowledge {
        /** "{authority}" is filled by the screen. */
        const val label = "From {authority}."
        const val unreviewed = "Awaiting clinical review."
        /** "{reviewedBy}" is filled by the screen. */
        const val reviewed = "Reviewed by {reviewedBy}."
    }

    const val photoReading = "GilbertOne does not read photos. Reading a photo of skin waits on four things that do not exist yet: a photo-reading protocol ratified with a named clinical reviewer, an impact assessment that covers images, an appointed Information Officer, and a decision on who would process the images and in which country."

    val questions = listOf(
        SkinQuestion("who", "Who is the rash on?", "chips", null, listOf(
            SkinOption("self", "On me", listOf(), listOf()),
            SkinOption("adult", "On another adult", listOf(), listOf()),
            SkinOption("child", "On a child or an older baby", listOf(), listOf()),
            SkinOption("young-baby", "On a baby younger than three months", listOf(), listOf())
        )),
        SkinQuestion("where", "Where on the body is it?", "multi", null, listOf(
            SkinOption("face", "Face", listOf(), listOf()),
            SkinOption("scalp", "Scalp", listOf(), listOf()),
            SkinOption("arms", "Arms or hands", listOf(), listOf()),
            SkinOption("legs", "Legs or feet", listOf(), listOf()),
            SkinOption("body", "Chest, back or belly", listOf(), listOf()),
            SkinOption("groin", "Groin or bottom", listOf(), listOf()),
            SkinOption("nappy", "Nappy area", listOf("cond-059", "cond-065"), listOf()),
            SkinOption("all-over", "All over", listOf(), listOf())
        )),
        SkinQuestion("since", "Since when?", "chips", null, listOf(
            SkinOption("today", "Today", listOf(), listOf()),
            SkinOption("days", "A few days", listOf(), listOf()),
            SkinOption("week", "About a week", listOf(), listOf()),
            SkinOption("longer", "Longer than a week", listOf(), listOf())
        )),
        SkinQuestion("feels", "How does it feel?", "chips", null, listOf(
            SkinOption("itchy", "Itchy", listOf(), listOf()),
            SkinOption("painful", "Painful or burning", listOf(), listOf()),
            SkinOption("both", "Itchy and painful", listOf(), listOf()),
            SkinOption("neither", "Neither", listOf(), listOf())
        )),
        SkinQuestion("looks", "What does it look like?", "multi", null, listOf(
            SkinOption("red-patches", "Red or darker patches", listOf("cond-028", "cond-065", "cond-068", "cond-067"), listOf()),
            SkinOption("welts", "Raised bumps or welts", listOf("cond-066", "cond-070", "cond-069", "cond-031"), listOf()),
            SkinOption("blisters", "Blisters", listOf("cond-033", "cond-034", "cond-032", "cond-065"), listOf()),
            SkinOption("ring", "Ring-shaped", listOf("cond-030", "cond-066"), listOf()),
            SkinOption("scaly", "Scaly or dry", listOf("cond-028", "cond-030", "cond-065"), listOf()),
            SkinOption("weeping", "Weeping or crusted", listOf("cond-032", "cond-028", "cond-065"), listOf()),
            SkinOption("dots", "Small dots or pin-pricks", listOf("cond-069", "cond-031", "cond-070"), listOf("fa-025")),
            SkinOption("peeling", "Peeling", listOf("cond-068", "cond-030", "cond-028"), listOf()),
            SkinOption("other", "Something else", listOf(), listOf())
        )),
        SkinQuestion("spreading", "Is it spreading?", "chips", null, listOf(
            SkinOption("no", "No", listOf(), listOf()),
            SkinOption("slowly", "Slowly", listOf(), listOf()),
            SkinOption("quickly", "Quickly, over hours", listOf(), listOf()),
            SkinOption("unsure", "Not sure", listOf(), listOf())
        )),
        SkinQuestion("fever", "Is there a fever, or a hot and shivery feeling?", "chips", null, listOf(
            SkinOption("yes", "Yes", listOf(), listOf()),
            SkinOption("no", "No", listOf(), listOf()),
            SkinOption("unsure", "Not sure", listOf(), listOf())
        )),
        SkinQuestion("signs", "Are any of these true?", "multi", "none", listOf(
            SkinOption("glass", "The rash does not fade when a glass is pressed on it", listOf(), listOf()),
            SkinOption("airway", "Swelling of the lips, face or tongue, or trouble breathing", listOf(), listOf()),
            SkinOption("burn", "A burn bigger than the palm of the hand, or on the face, hands, feet or genitals", listOf(), listOf()),
            SkinOption("peeling-fever", "Skin blistering or peeling away in large areas, with a fever", listOf(), listOf()),
            SkinOption("hot-spreading", "A red, hot, swollen area spreading quickly, with a fever", listOf(), listOf()),
            SkinOption("none", "None of these", listOf(), listOf())
        )),
        SkinQuestion("new-things", "Anything new recently — a soap, a cream, a food, a plant, an insect or a medicine? Anything else for your nurse?", "text", null, emptyList())
    )

    val rules = listOf(
        SkinRule("glass", "emergency", listOf(SkinCondition("signs", listOf("glass"))),
            "", listOf("fa-025", "cond-043"), null),
        SkinRule("airway", "emergency", listOf(SkinCondition("signs", listOf("airway"))),
            "", listOf("fa-017", "cond-066"), null),
        SkinRule("burn", "sister-today", listOf(SkinCondition("signs", listOf("burn"))),
            "A burn bigger than the palm of the hand, or on the face, hands, feet or genitals.", listOf("fa-007"), null),
        SkinRule("peeling-fever", "sister-today", listOf(SkinCondition("signs", listOf("peeling-fever"))),
            "Skin blistering or peeling away in large areas, with a fever.", listOf("cond-071"), null),
        SkinRule("hot-spreading", "sister-today", listOf(SkinCondition("signs", listOf("hot-spreading"))),
            "A red, hot, swollen area spreading quickly, with a fever.", listOf("cond-067"), null),
        SkinRule("spreading-with-fever", "sister-today", listOf(SkinCondition("spreading", listOf("quickly")), SkinCondition("fever", listOf("yes"))),
            "A rash spreading quickly, with a fever.", listOf("cond-067", "cond-066"), null),
        SkinRule("young-baby", "sister-today", listOf(SkinCondition("who", listOf("young-baby"))),
            "A rash on a baby younger than three months.", listOf(), "The founder's brief of 1 October 2026 names a rash in a baby younger than three months. No entry in the knowledge base says it yet in those words — the nearest are the insect-bite and sunburn entries, which send any bitten or sunburnt baby to a nurse — so the reviewer is asked whether the base should gain the entry or the rule should change.")
    )

    val selfCareAlways = listOf("fa-026")
    val selfCareForCondition = mapOf("cond-068" to "fa-024", "cond-070" to "fa-023")

    val conditions = listOf(
        SkinConditionEntry("cond-028", "Eczema (Atopic Dermatitis)",
            listOf("dry itchy patches", "commonly in elbow and knee creases", "flares then settles", "skin thickening from scratching"),
            "If the skin weeps, crusts or has pus (possible infection), flares are frequent, or sleep is broken by itch. Babies and children with widespread eczema need a clinic plan.",
            "WHO / SA NDoH (PHC) skin guidance", null),
        SkinConditionEntry("cond-030", "Ringworm (Fungal Skin Infection)",
            listOf("ring-shaped scaly patch with a clear centre", "itching", "slowly expanding rim", "can affect scalp, body, feet (athlete's foot) or groin"),
            "If the scalp is involved (needs tablets, not cream), there is no improvement after two weeks of cream, or the person has diabetes or a weakened immune system.",
            "SA NDoH Standard Treatment Guidelines (PHC)", null),
        SkinConditionEntry("cond-031", "Scabies",
            listOf("intense itching, worse at night", "thin burrow lines between fingers, on wrists, waist", "rash in the same places", "itching in close contacts at the same time"),
            "For treatment cream — everyone in the house must be treated on the same day, so a clinic plan helps. Infants, pregnant women and crusted widespread rash need clinician care.",
            "WHO / SA NDoH (PHC) guidance", null),
        SkinConditionEntry("cond-032", "Impetigo (School Sores)",
            listOf("honey-coloured crusts around nose and mouth", "small blisters that burst", "spreading sores", "common in children"),
            "If sores spread despite hygiene, there are many lesions, or the child is unwell with fever — antibiotics may be needed.",
            "SA NDoH Standard Treatment Guidelines (PHC)", null),
        SkinConditionEntry("cond-033", "Chickenpox",
            listOf("itchy fluid-filled blisters in crops", "fever", "tiredness", "blisters crust over in about a week"),
            "If blisters become infected (redness, pus), the person is pregnant, a newborn is affected, or there is drowsiness, repeated vomiting or breathing difficulty. Keep away from pregnant women who have not had chickenpox.",
            "WHO / SA NDoH (PHC) guidance", null),
        SkinConditionEntry("cond-034", "Shingles (Herpes Zoster)",
            listOf("burning pain in a band on one side of the body", "clusters of blisters on red skin", "tingling days before the rash", "sometimes fever and tiredness"),
            "See a doctor as soon as the rash starts — antiviral tablets work best within 72 hours. Same-day care if the rash is near the eye, there is weakness, or the immune system is weakened (for example by HIV).",
            "WHO / SA NDoH (PHC) guidance", null),
        SkinConditionEntry("cond-043", "Meningitis",
            listOf("severe headache", "fever", "stiff neck", "vomiting", "light intolerance", "rash that does not fade when pressed", "in babies: bulging fontanelle, high-pitched cry, drowsiness, poor feeding"),
            "This is an emergency — call 10177 or go straight to a hospital. Minutes matter, especially with the non-fading rash.",
            "WHO / SA NDoH meningitis guidance", null),
        SkinConditionEntry("cond-059", "Nappy Rash",
            listOf("red skin in the nappy area", "sore patches", "sometimes satellite spots at the edges (thrush)", "baby uncomfortable at changes"),
            "If there are blisters or pus, the rash does not improve after three to four days of care, or it spreads beyond the nappy area.",
            "SA NDoH (PHC) child guidance", null),
        SkinConditionEntry("cond-065", "Contact Dermatitis",
            listOf("itchy skin where something touched it", "dry, cracked or blistered patches", "red on lighter skin; dark brown, purple or grey on darker skin", "often on the hands or face", "appears within hours or days of the contact"),
            "If it keeps coming back, is severe, does not settle with care at home, or you cannot work out what is causing it.",
            "Written for MyThuso in its own words from the NHS website — Contact dermatitis (https://www.nhs.uk/conditions/contact-dermatitis/, reviewed 3 May 2023); checked against MedlinePlus — Rashes (https://medlineplus.gov/rashes.html) and CDC/NIOSH — Skin exposures (https://www.cdc.gov/niosh/skin-exposure/about/index.html)", null),
        SkinConditionEntry("cond-066", "Hives (Urticaria)",
            listOf("raised itchy bumps or patches (welts)", "may sting or burn", "pink or red on lighter skin, harder to see on darker skin", "can appear anywhere and move around", "each patch usually fades within a day or two"),
            "If the rash lasts more than two days, spreads, keeps coming back, or comes with a fever or deep swelling, or you are worried about a child. Call 10177 (or 112 from a cellphone) at once if the lips, mouth, tongue or throat swell, breathing becomes hard, the lips turn blue or grey, or the person becomes confused or faints — that is a severe allergic reaction (anaphylaxis).",
            "Written for MyThuso in its own words from the NHS website — Hives (https://www.nhs.uk/conditions/hives/, reviewed 26 April 2024); checked against MedlinePlus — Hives (https://medlineplus.gov/hives.html) and Anaphylaxis (https://medlineplus.gov/anaphylaxis.html)", null),
        SkinConditionEntry("cond-067", "Cellulitis (Skin Infection)",
            listOf("painful, hot, swollen skin", "redness that spreads, which can be less obvious on darker skin", "sometimes blisters", "feeling flu-like, with swollen glands", "most often on the lower leg"),
            "Be seen the same day if skin becomes painful, hot and swollen — early treatment stops it getting worse. Call 10177 (or 112 from a cellphone) if it comes with a high fever, a fast heartbeat, purple patches, dizziness, confusion, pale or clammy skin, or fainting.",
            "Written for MyThuso in its own words from the NHS website — Cellulitis (https://www.nhs.uk/conditions/cellulitis/, reviewed 18 April 2024); checked against CDC — Cellulitis (https://www.cdc.gov/group-a-strep/about/cellulitis.html) and MedlinePlus — Cellulitis (https://medlineplus.gov/cellulitis.html)", null),
        SkinConditionEntry("cond-068", "Sunburn",
            listOf("skin hot to the touch", "sore or painful skin", "redness, which may be less visible on darker skin", "flaking or peeling a few days later", "blisters when severe"),
            "If the skin is blistered or swollen, the person has a very high temperature, feels hot and shivery, or is very tired, dizzy, sick or has a headache or cramps — or if a baby or young child is sunburnt.",
            "Written for MyThuso in its own words from the NHS website — Sunburn (https://www.nhs.uk/conditions/sunburn/, reviewed 24 November 2025); checked against CDC — Heat-related illnesses (https://www.cdc.gov/disasters/extremeheat/pdf/Heat_Related_Illness.pdf)", null),
        SkinConditionEntry("cond-069", "Heat Rash (Prickly Heat)",
            listOf("small raised spots", "an itchy, prickly feeling", "mild swelling", "red on lighter skin; may look grey or white on darker skin", "not catching, and common in babies"),
            "If it has not improved after a few days, or you are worried about a baby's rash.",
            "Written for MyThuso in its own words from the NHS website — Heat rash (https://www.nhs.uk/conditions/heat-rash-prickly-heat/, reviewed 9 May 2024); checked against CDC/NIOSH — Heat-related illnesses (https://www.cdc.gov/niosh/heat-stress/about/illnesses.html)", null),
        SkinConditionEntry("cond-070", "Insect Bites (Mosquito, Flea, Bedbug)",
            listOf("small raised itchy lumps", "flea bites often in groups below the knees", "bedbug bites in lines or clusters on skin bared in bed", "red or pink on lighter skin; brown or purple and harder to see on darker skin", "children may get crops of very itchy bumps that keep coming back"),
            "If a bite looks infected (hot, spreading redness, swelling or pus), stays very painful or swollen despite care at home, a baby under one year is bitten, or it gets worse or comes with a fever. Call 10177 (or 112 from a cellphone) if the face, lips or throat swell or breathing becomes difficult.",
            "Written for MyThuso in its own words from the NHS website — Insect bites and stings (https://www.nhs.uk/conditions/insect-bites-and-stings/, reviewed 1 June 2023) and Bedbugs (https://www.nhs.uk/conditions/bedbugs/); checked against CDC — Mosquito bites (https://www.cdc.gov/mosquitoes/about/about-mosquito-bites.html) and Bed bugs (https://www.cdc.gov/bed-bugs/about/index.html)", null),
        SkinConditionEntry("cond-071", "Severe Skin Reaction to a Medicine (Stevens-Johnson Syndrome)",
            listOf("a flu-like illness first: fever, sore throat, aching", "then a fast-spreading rash of round patches, darker in the middle", "blistering and peeling skin", "painful sores in the mouth and throat", "sore eyes that hurt in bright light"),
            "This is an emergency. Call 10177 (or 112 from a cellphone) if a spreading rash blisters or peels, especially after starting a new medicine (in South Africa this includes some HIV and epilepsy medicines), or if there is trouble breathing, a tight chest or throat, or a swollen face or eyes.",
            "Written for MyThuso in its own words from the NHS website — Stevens-Johnson syndrome (https://www.nhs.uk/conditions/stevens-johnson-syndrome/, reviewed 4 March 2026); checked against MedlinePlus Genetics — Stevens-Johnson syndrome/toxic epidermal necrolysis (https://medlineplus.gov/genetics/condition/stevens-johnson-syndrome-toxic-epidermal-necrolysis/)", null)
    )

    val firstAid = listOf(
        SkinFirstAidEntry("fa-007", "Burns and Scalds",
            listOf("Stop the burning: move the person away from the source, switch off electricity at the mains first if live", "Remove jewellery, watches and tight clothing near the burn before swelling starts — but not clothing stuck to the burn", "Cool the burn under cool running water for a full 20 minutes", "Cover loosely with clean cling film laid lengthways, or a clean non-fluffy cloth", "Give paracetamol for pain; keep the person warm — burned skin loses heat", "For chemical burns: flush with running water for at least 20 minutes, remove contaminated clothing while flushing"),
            listOf("Never use ice, butter, toothpaste, eggs or any folk remedy — they trap heat and infect the wound", "Never burst blisters", "Do not apply cotton wool or fluffy material to the burn", "Paraffin stoves and candles are a leading cause of childhood burns in South African homes — keep them out of reach and never leave unattended"),
            "10177 for burns bigger than the person's hand, burns to the face, hands, feet, genitals or joints, any chemical or electrical burn, smoke inhalation, or burns in babies and young children",
            "SA burn care guidance / WHO", null),
        SkinFirstAidEntry("fa-017", "Severe Allergic Reaction (Anaphylaxis)",
            listOf("Recognise it: swollen lips, tongue or throat, difficulty breathing, a widespread itchy rash, faintness or collapse, often within minutes of a food, sting, or medicine", "Call 10177 immediately and say anaphylaxis", "If adrenaline is available (an auto-injector or a clinic ampoule), inject it into the outer thigh without delay — through clothing is fine", "Lay the person flat with legs raised; if breathing is hard, let them sit up slowly", "A second dose may be given after 5 minutes if there is no improvement", "Stay with the person; be ready to start CPR", "Hospital is needed even when the person recovers — symptoms can return hours later"),
            listOf("Adrenaline is the treatment; antihistamine tablets are not a substitute for it", "Never make the person stand or walk suddenly — it can be fatal in anaphylaxis", "Known allergy: carry prescribed adrenaline at all times"),
            "10177 immediately for every suspected anaphylaxis, even if it seems to settle",
            "SA Resuscitation Council / WHO anaphylaxis guidance", null),
        SkinFirstAidEntry("fa-023", "Insect Bites and Stings (Minor)",
            listOf("If a sting is left in the skin, scrape it out sideways with a fingernail or the edge of a bank card", "Wash the area with soap and water", "Hold a cold pack wrapped in a cloth on any swelling", "Raise the bitten or stung part if you can", "Ask a pharmacist about an over-the-counter antihistamine for itching", "Watch the area over the next few days for signs of infection"),
            listOf("Do not use tweezers on a bee or wasp sting — squeezing can push in more venom", "Do not scratch: broken skin can become infected", "Never cut the skin or put on a tourniquet"),
            "10177 (or 112 from a cellphone) at once if the lips, tongue or throat swell, breathing is fast, wheezy or difficult, swallowing is hard, the lips turn blue or grey, or the person becomes confused or faints. Urgent advice for stings in the mouth, throat or near the eyes.",
            "Written for MyThuso in its own words from the NHS website — Insect bites and stings (https://www.nhs.uk/conditions/insect-bites-and-stings/, reviewed 1 June 2023); checked against CDC/NIOSH — Insects and scorpions (https://www.cdc.gov/niosh/outdoor-workers/about/insects-and-scorpions.html) and MedlinePlus — Anaphylaxis (https://medlineplus.gov/anaphylaxis.html)", null),
        SkinFirstAidEntry("fa-024", "Sunburn",
            listOf("Get out of the sun", "Cool the skin with a cool shower, a bath or damp towels", "Apply after-sun or an unperfumed moisturiser (emollient)", "Drink plenty of water", "Wear loose clothing over the burn and keep it out of the sun until it heals"),
            listOf("Do not put ice or petroleum jelly on the skin", "Do not burst blisters, scratch, or pick off peeling skin", "Babies and young children with sunburn need advice from a nurse or doctor"),
            "Urgent help if the skin is badly blistered or swollen, or the person has a very high temperature, shivers, is confused, dizzy or being sick — this may be heat illness and not only sunburn.",
            "Written for MyThuso in its own words from the NHS website — Sunburn (https://www.nhs.uk/conditions/sunburn/, reviewed 24 November 2025); checked against CDC — Heat-related illnesses (https://www.cdc.gov/disasters/extremeheat/pdf/Heat_Related_Illness.pdf)", null),
        SkinFirstAidEntry("fa-025", "The Glass Test for a Rash",
            listOf("Press the side of a clear drinking glass firmly against the rash", "Look through the glass to see whether the spots fade", "If the spots can still be seen through the glass, call 10177 (or 112 from a cellphone) straight away", "On darker skin, check paler places too: the palms, the soles, the roof of the mouth and inside the eyelids", "Look for blue, grey, pale or blotchy skin, lips or tongue", "Do not wait for a rash to appear if the person seems seriously ill"),
            listOf("Not everyone with meningitis or sepsis gets a rash; a rash that fades does not rule them out", "The rash can start as small red pinpricks and spread quickly into red or purple blotches", "Trust your instinct: if you think something is seriously wrong, get help"),
            "10177 (or 112 from a cellphone) immediately for a rash that does not fade under a glass, especially with a fever, a very bad headache, a stiff neck or dislike of bright light, or in a baby or young child.",
            "Written for MyThuso in its own words from the NHS website — Meningitis (https://www.nhs.uk/conditions/meningitis/, reviewed 12 June 2026) and Sepsis (https://www.nhs.uk/conditions/sepsis/, reviewed 14 May 2026); no public-domain page describes the glass test, and CDC — Meningococcal disease symptoms (https://www.cdc.gov/meningococcal/symptoms/index.html) supports the signs to call for", null),
        SkinFirstAidEntry("fa-026", "Caring for an Itchy Rash at Home",
            listOf("Hold a cool compress or cool damp cloth on the itchy area", "Pat or tap the skin instead of scratching, and keep nails short and smooth", "Take short lukewarm baths or showers", "Use an unperfumed moisturiser (emollient) often", "Wear loose cotton clothes and use laundry products for sensitive skin", "Stop any new soap, cream, cosmetic or detergent started before the rash", "Ask a pharmacist about calamine lotion or an over-the-counter antihistamine"),
            listOf("Avoid long hot baths, perfumed soaps and tight, woollen or synthetic clothing", "Itching in pregnancy needs checking by a nurse, midwife or doctor", "An itchy rash with swelling of the face or throat, or trouble breathing, is an emergency"),
            "10177 (or 112 from a cellphone) if itching comes with swelling of the lips, tongue or throat or trouble breathing. Otherwise a nurse or doctor if the itch is severe, covers the whole body, will not settle, comes with a new lump or swelling, or happens in pregnancy.",
            "Written for MyThuso in its own words from the NHS website — Itchy skin (https://www.nhs.uk/conditions/itchy-skin/, reviewed 19 July 2023); checked against MedlinePlus — Itching (https://medlineplus.gov/itching.html) and Rashes (https://medlineplus.gov/rashes.html)", null)
    )

    val fixtures = listOf(
        SkinFixture("itchy welts on an adult", mapOf("who" to listOf("self"), "looks" to listOf("welts"), "feels" to listOf("itchy"), "signs" to listOf("none")), "", "general-information", null, listOf("cond-031", "cond-066", "cond-069", "cond-070")),
        SkinFixture("scaly ring", mapOf("who" to listOf("adult"), "looks" to listOf("ring", "scaly"), "signs" to listOf("none")), "", "general-information", null, listOf("cond-030", "cond-028", "cond-065", "cond-066")),
        SkinFixture("pin-prick dots bring the glass test first", mapOf("who" to listOf("child"), "looks" to listOf("dots"), "signs" to listOf("none")), "", "general-information", null, listOf("cond-031", "cond-069", "cond-070")),
        SkinFixture("nothing described", mapOf("who" to listOf("self"), "signs" to listOf("none")), "", "general-information", null, listOf()),
        SkinFixture("a glass test that does not fade", mapOf("who" to listOf("child"), "signs" to listOf("glass")), "", "emergency", listOf("glass"), null),
        SkinFixture("trouble breathing before anything else is answered", mapOf("signs" to listOf("airway")), "", "emergency", listOf("airway"), null),
        SkinFixture("a large burn", mapOf("who" to listOf("self"), "signs" to listOf("burn")), "", "sister-today", listOf("burn"), null),
        SkinFixture("spreading quickly with a fever", mapOf("who" to listOf("adult"), "spreading" to listOf("quickly"), "fever" to listOf("yes"), "signs" to listOf("none")), "", "sister-today", listOf("spreading-with-fever"), null),
        SkinFixture("spreading quickly without a fever", mapOf("who" to listOf("adult"), "spreading" to listOf("quickly"), "fever" to listOf("no"), "looks" to listOf("red-patches"), "signs" to listOf("none")), "", "general-information", null, listOf("cond-028", "cond-065", "cond-067", "cond-068")),
        SkinFixture("a young baby", mapOf("who" to listOf("young-baby"), "looks" to listOf("red-patches"), "signs" to listOf("none")), "", "sister-today", listOf("young-baby"), null),
        SkinFixture("two signs for today", mapOf("who" to listOf("self"), "signs" to listOf("burn", "hot-spreading")), "", "sister-today", listOf("burn", "hot-spreading"), null),
        SkinFixture("signs unanswered", mapOf("who" to listOf("self"), "looks" to listOf("welts")), "", "incomplete", null, null),
        SkinFixture("an emergency typed into the notes", mapOf("who" to listOf("self"), "signs" to listOf("none")), "she is struggling to breathe", "emergency", null, null),
        SkinFixture("a new soap typed into the notes", mapOf("who" to listOf("self"), "looks" to listOf("red-patches"), "signs" to listOf("none")), "I started a new washing powder last week", "general-information", null, listOf("cond-028", "cond-065", "cond-067", "cond-068"))
    )
}
