// Generated by scripts/emit-verify-in-service.mjs from packages/catalog/verify-in-service.json, packages/catalog/apis/trust.json, packages/catalog/trust.json and packages/catalog/sos.json.
// Do not edit by hand — run `npm run verify-in-service`. The build fails if this file and its sources disagree,
// so an edit here is lost rather than merely wrong.
//
// The door code lifetime and tries, the complaint review window and the unmatched shift-start rule are PROPOSED
// defaults an admin changes on the web back office. This app reaches no settings route, so it uses them as
// written here, and they change in the contract, never in this file. Nothing here is a Trust Score or a face.

package za.co.mythuso.model

object VerifyInServiceData {
    /** A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
    const val doorCodeMinutes = 5
    /** A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
    const val doorCodeAttempts = 3
    /** A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
    const val complaintReviewHours = 24
    /** A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
    const val unmatchedShiftStartDispatch = "withhold"
    /** How many digits a door code has. A design constant of the contract, not a policy. */
    const val doorDigits = 6
    /** The longest complaint the form takes, in characters. */
    const val complaintMaxCharacters = 1000
    /** What the face-match door answers. Never matched without a provider. */
    const val matchOutcome = "not-integrated"

    object ShiftText {
        const val door = "face-match-result"
        const val outcome = "not-integrated"
        const val heading = "Start your shift"
        const val intro = "Starting a shift tells the desk you are working. It is where a face match would happen, and none does."
        const val button = "Start my shift"
        const val started = "Shift started at {at}."
        const val noMatch = "No face match was performed. MyThuso has no identity provider to compare your face with, so nothing was compared, and nothing of your face was taken, kept or sent."
        const val whyNoMatch = "Whether matching a face is biometric information under POPIA section 26 is a decision the Information Officer has not taken (D-3), and no identity provider is contracted. Until both are settled, no image, template or embedding of anybody's face is held anywhere in MyThuso."
        const val dispatchRuleSetting = "unmatched-shift-start-dispatch"
        const val deskHeading = "Shift starts today"
        const val deskIntro = "Every shift started today, and what the rule in force did with it. No face match was performed for any of them, because nothing can perform one."
        const val deskEmpty = "Nobody has started a shift today."
    }

    object NurseDoorText {
        const val heading = "Your door code"
        const val intro = "Show these digits to the person who opens the door. They type them into their own MyThuso app, and it tells them the code is for their visit."
        const val button = "Show my door code"
        const val again = "Show a new code"
        const val expires = "This code stops working at {at}."
        const val tries = "They have {attempts} tries before the desk is told."
        const val preview = "In this preview the code is shown for the patient's next visit, as the nurse that visit is assigned to, so the patient's screen in this same tab can check it. Nothing reaches a door."
    }

    object PatientDoorText {
        const val heading = "Check the nurse at your door"
        const val open = "Check the nurse at your door"
        const val intro = "Before you open the door, ask her for her door code and type it here. MyThuso checks it is the code for your visit."
        const val codeLabel = "Door code"
        const val check = "Check the code"
        const val wrong = "That code does not match your visit. You have {attempts} more tries before the desk is told."
        const val matched = "The code matches your visit."
        const val question = "Is this the person at your door?"
        const val name = "Name"
        const val badge = "Badge"
        const val noBadge = "She has no current verification, so there is no badge to show. Do not open the door."
        const val verified = "You checked the code and the name. The desk has been told she arrived."
        const val mismatch = "Do not open the door. The desk has been told, and a safety incident has been raised."
        const val anyTime = "If the person at the door is not who you expected, say so at any time, with or without a code."
        const val danger = "If you are in danger, call 10111 now."
        const val photo = "MyThuso holds no photograph of a nurse, so none is shown. Check the name and the badge, and ask to see her SANC card."
        const val badgeSentence = "You are shown her badge and never a number. A badge says her identity, registration and background are in order today."
        const val formWhy = "Digits, on every platform. A QR code is one more thing a patient's phone has to scan, which on the web and on Android needs a third-party library the open-source register has not procured (packages/catalog/open-source.json, section 15D). iOS could draw one with CoreImage, but no patient app could read it without a scanner, so a code only the nurse's phone can draw is decoration. Six digits are read aloud through a closed door as easily as they are typed."
    }

    object ComplaintText {
        const val heading = "Make a complaint"
        const val open = "Make a complaint about this visit"
        const val intro = "Tell us what went wrong. A reviewer reads it within {hours} hours."
        const val category = "What is it about?"
        const val account = "What happened"
        const val accountHelp = "In your own words. Up to {characters} characters."
        const val nurseNotTold = "The nurse is told a complaint was made and what was decided. She is not told who made it or what you wrote."
        const val submit = "Send the complaint"
        const val sent = "Your complaint was received. A reviewer reads it by {at}."
        const val scoreRule = "A complaint never changes anybody's Trust Score by itself. A reviewer decides it, and anything that follows is a separate decision."
    }

    val dispatchRules = listOf(
        VerifyInServiceChoice("withhold", "Because no match was performed, you are not offered visits from this shift. The desk can see that, and why."),
        VerifyInServiceChoice("offer-with-desk-flag", "You may be offered visits from this shift, and the desk sees that no face match was performed.")
    )
    val answers = listOf(
        VerifyInServiceChoice("she-is-my-nurse", "Yes, she is my nurse"),
        VerifyInServiceChoice("not-my-nurse", "This is not my nurse")
    )
    val categories = listOf(
        VerifyInServiceChoice("late-or-missed", "The nurse was late, or did not come"),
        VerifyInServiceChoice("conduct", "How I was spoken to or treated"),
        VerifyInServiceChoice("care-given", "The care I was given"),
        VerifyInServiceChoice("privacy", "My information was not kept private"),
        VerifyInServiceChoice("identity-at-the-door", "I was not sure who was at my door"),
        VerifyInServiceChoice("payment", "What I was charged")
    )
    val tiers = listOf(
        VerifyInServiceChoice("verified", "Verified"),
        VerifyInServiceChoice("trusted", "Trusted"),
        VerifyInServiceChoice("senior", "Senior")
    )

    val refusals = listOf(
        VerifyInServiceRefusal("no-current-verification-to-start", 409, "You have no current verification, so a shift cannot start. Your vetting status says why."),
        VerifyInServiceRefusal("no-badge-to-show-at-a-door", 409, "You have no current verification, so there is no door code to show. Speak to the desk."),
        VerifyInServiceRefusal("no-door-code-for-this-visit", 404, "No door code has been shown for this visit. Ask the person at the door to show one, or say they are not your nurse."),
        VerifyInServiceRefusal("door-code-expired", 410, "That code has expired. Ask her to show a new one."),
        VerifyInServiceRefusal("door-check-closed", 409, "This door check is finished. If you are worried about who is at your door, say they are not your nurse."),
        VerifyInServiceRefusal("door-answer-before-code", 409, "Type the code she shows before you say she is your nurse."),
        VerifyInServiceRefusal("complaint-category-unknown", 422, "Choose what the complaint is about from the list."),
        VerifyInServiceRefusal("complaint-account-empty-or-long", 422, "Say what happened in your own words, in no more than the space the form gives.")
    )
}
