// Generated by scripts/emit-assistant.mjs from packages/catalog/apis/assistant.json, the assistant engine's API contract.
// Do not edit by hand — run `npm run assistant`. The build fails if this file and its source
// disagree, so an edit here is lost rather than merely wrong.
//
// The typed client for the contract's built routes: the addresses a phone asks today, each at
// the route's own version, with every request and response field the contract declares, the
// same twelve-second patience the web bridge gives the service, and the error shape a refusal
// arrives in. The routes the contract declares and the service does not answer yet are not
// here — their refusal is the contract's own sentence, and a phone that has not typed it
// cannot soften it.

import Foundation

/// The contract's constants: its version, the one timeout every call shares, the sources whose
/// reply may replace what the phone itself wrote, and the built routes' own addresses — emitted
/// exactly as packages/catalog/apis/assistant.json declares them, so scripts/check-boundaries.mjs
/// can hold this file to the catalog's versions rather than to a copy of them.
enum AssistantApi {
    /// packages/catalog/apis/assistant.json's version.
    static let contractVersion = 1
    /// The one timeout every call shares, in seconds: the web bridge's REFINE_TIMEOUT_MS, exactly,
    /// because the three platforms must give the service the same patience or one of them shows an
    /// answer the others have already given up on.
    static let timeoutSeconds: TimeInterval = 12
    /// The only source values whose reply may replace the phone's own answer: the service's two
    /// live model tiers. The web bridge refuses every other name for the same reason — a sentence
    /// from a tier this file has never heard of is not a sentence to put on a patient's screen.
    /// A third name has to be added here on purpose, never discovered in production.
    static let replySources: [String] = ["model", "orchestrator"]

    /// Each built route at the catalog's own version, for readers and for
    /// scripts/check-boundaries.mjs. The paths below are the same routes minus method and version.
    static let turnAddress = "POST /assistant/v1/turn@2"
    static let knowledgeSearchAddress = "POST /assistant/v1/knowledge/search@2"
    static let statusAddress = "GET /assistant/v1/status@2"
    /// Push-to-talk's two built addresses travel even though no phone calls them yet: the voice
    /// itself is web-only for now, and scripts/check-boundaries.mjs holds every built /v1 route's
    /// literal to the contract — a client that did not name a route the service answers would be
    /// a client written for a smaller service than the one running.
    static let listenAddress = "POST /assistant/v1/listen@3"
    static let speakAddress = "POST /assistant/v1/speak@4"
    /// The five gated addresses, built in the service and refused by all but one of them: both
    /// triage steps answer the engine's triage-not-ratified refusal while no triage protocol is
    /// ratified, the vital reading answers device-data-needs-a-dpia in any process that has not
    /// said it is testing, and the handover submission answers clinician-routing-not-built always.
    /// Their addresses travel and no request or reply shape does — there is nothing for a phone to
    /// send, and nothing it would be answered with but the contract's own sentence, which the
    /// refusal shape below already carries.
    static let triageStartAddress = "POST /assistant/v1/triage/start@3"
    static let triageAnswerAddress = "POST /assistant/v1/triage/answer@3"
    static let vitalsAddress = "POST /assistant/v1/vitals@3"
    static let handoverPrepareAddress = "POST /assistant/v1/handover/prepare@3"
    static let handoverSubmitAddress = "POST /assistant/v1/handover/submit@3"

    static let turnPath = "/assistant/v1/turn"
    static let knowledgeSearchPath = "/assistant/v1/knowledge/search"
    static let statusPath = "/assistant/v1/status"
    static let listenPath = "/assistant/v1/listen"
    static let speakPath = "/assistant/v1/speak"
}

/// POST /v1/turn@2's request. Optional fields are omitted from the JSON when nil — the service
/// reads an absent sessionId as "mint one", exactly as the contract says.
struct AssistantTurnRequest: Encodable {
    var sessionId: String?
    var parentTurnId: String?
    var text: String
    var audience: String?
    var userConsent: Bool
}

/// POST /v1/turn@2's response, field for field.
struct AssistantTurnReply: Decodable {
    let turnId: String
    let sessionId: String
    let route: String
    let classification: String
    let reply: String
    let style: String
    let confidence: Double
    let requiresConfirmation: Bool
    let suggestedActions: [String]
    /// Present only when a refusal policy answered instead of the classifier.
    let refusalId: String?
    /// Which tier wrote the reply; nil means the classifier's own, already on the screen.
    let source: String?
    /// With a model-written reply, the face the catalog gives that answer.
    let cue: String?
}

/// POST /v1/knowledge/search@2's request.
struct AssistantKnowledgeRequest: Encodable {
    var query: String
    var language: String
}

/// One source: the entry's own id, its title, and where it was published from.
struct AssistantKnowledgeSource: Decodable {
    let id: String
    let title: String
    let source: String
}

/// POST /v1/knowledge/search@2's response.
struct AssistantKnowledgeReply: Decodable {
    let sources: [AssistantKnowledgeSource]
    /// How many matches were withheld for want of a source, so a thin answer reads as thin.
    let withheld: Int
}

/// GET /v1/status@1's response: booleans and the mode, and no field that could carry a secret.
struct AssistantStatusReply: Decodable {
    let ok: Bool
    let mode: String
    let azure: Bool
    let ollama: Bool
    let production: Bool
    let activated: Bool
}

/// What the service answers a request it refused: the server's own shape for every non-2xx body.
/// The message is optional because a refusal body may carry no sentence — the 404 carries none —
/// and this client does not invent one.
struct AssistantRefusal: Decodable {
    let error: String
    let refusalId: String?
    let message: String?
}

/// One call's outcome, all four told apart: an answer, a refusal the service wrote, a service
/// that could not be reached at all, and one that answered with something that is not the
/// declared shape. Only answered carries a reply; the apps treat the other three the same way —
/// the phone's own answer stands.
enum AssistantCall<Value> {
    case answered(Value)
    case refused(AssistantRefusal)
    case unreachable
    case unusable
}

/// The client itself. Every function takes the base URL as an argument: this file knows the
/// contract's paths, and the build knows where the service lives.
enum AssistantClient {
    /// One turn: what a phone sends after its own classifier found nothing it could place.
    static func turn(_ request: AssistantTurnRequest, base: URL) async -> AssistantCall<AssistantTurnReply> {
        await post(AssistantApi.turnPath, body: encode(request), base: base, as: AssistantTurnReply.self)
    }

    /// The published knowledge a search may stand on; public at the v1 surface.
    static func knowledgeSearch(_ request: AssistantKnowledgeRequest, base: URL) async -> AssistantCall<AssistantKnowledgeReply> {
        await post(AssistantApi.knowledgeSearchPath, body: encode(request), base: base, as: AssistantKnowledgeReply.self)
    }

    /// The service's versioned status: provider presence, production and the activation gate's own
    /// answer, as GET /assistant/v1/status declares them.
    static func status(base: URL) async -> AssistantCall<AssistantStatusReply> {
        await get(AssistantApi.statusPath, base: base, as: AssistantStatusReply.self)
    }

    /// The native refinement, the acceptance the web bridge applies word for word: the phone asks
    /// about a message it could not place, and the service's sentence replaces the local one only
    /// when the service names a model tier as its source and the sentence carries words.
    /// Everything else — refused, unreachable, timed out, unusable, a classifier echo — returns
    /// nil, and the phone keeps its own answer, exactly as the web panel does.
    ///
    /// userConsent is true because the message is the person's own, typed and sent by her:
    /// pressing Send is the confirmation, and nothing is asked about a message that was not sent.
    static func refine(text: String, sessionId: String?, audience: String?, base: URL) async -> String? {
        let request = AssistantTurnRequest(sessionId: sessionId, parentTurnId: nil, text: text, audience: audience, userConsent: true)
        guard case .answered(let reply) = await turn(request, base: base) else { return nil }
        guard let source = reply.source, AssistantApi.replySources.contains(source) else { return nil }
        let words = reply.reply.trimmingCharacters(in: .whitespacesAndNewlines)
        return words.isEmpty ? nil : words
    }

    // MARK: - The one place a request is made

    private static func encode<Body: Encodable>(_ body: Body) -> Data? {
        try? JSONEncoder().encode(body)
    }

    private static func post<Value: Decodable>(_ path: String, body: Data?, base: URL, as type: Value.Type) async -> AssistantCall<Value> {
        guard let body else { return .unusable }
        return await send(request(path, method: "POST", base: base, body: body), as: type)
    }

    private static func get<Value: Decodable>(_ path: String, base: URL, as type: Value.Type) async -> AssistantCall<Value> {
        await send(request(path, method: "GET", base: base, body: nil), as: type)
    }

    private static func request(_ path: String, method: String, base: URL, body: Data?) -> URLRequest {
        var request = URLRequest(url: base.appendingPathComponent(path))
        request.httpMethod = method
        /* The one timeout the three platforms share; a call that has not answered by then is one
           more unreachable, and the local answer stands. */
        request.timeoutInterval = AssistantApi.timeoutSeconds
        if let body {
            request.httpBody = body
            request.setValue("application/json", forHTTPHeaderField: "content-type")
        }
        return request
    }

    private static func send<Value: Decodable>(_ request: URLRequest, as type: Value.Type) async -> AssistantCall<Value> {
        do {
            let (data, response) = try await URLSession.shared.data(for: request)
            guard let http = response as? HTTPURLResponse else { return .unusable }
            guard (200..<300).contains(http.statusCode) else {
                /* The refusal the service wrote, when the body is that shape; otherwise the status
                   line, which is a fact this client saw rather than a sentence it invented. */
                let refusal = (try? JSONDecoder().decode(AssistantRefusal.self, from: data))
                    ?? AssistantRefusal(error: "http_status_" + String(http.statusCode), refusalId: nil, message: nil)
                return .refused(refusal)
            }
            guard let answer = try? JSONDecoder().decode(Value.self, from: data) else { return .unusable }
            return .answered(answer)
        } catch {
            /* Unreachable, blocked by App Transport Security, timed out, or any other transport
               failure: one fact to every caller — the phone keeps its own answer. */
            return .unreachable
        }
    }
}
