// Generated by scripts/emit-consent-grants.mjs from packages/catalog/consent.json.
// Do not edit by hand — run `npm run consent-grants`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// Nothing is granted, stored or sent. These are the roles a patient could let into their record,
// the defaults a grant sheet starts from, and the sentences it refuses in.

import Foundation

enum ConsentGrantsData {
    struct RecipientRole: Identifiable {
        let id: String; let name: String; let engine: String; let defaultScope: [String]
        let defaultExpiryDays: Int; let sealed: Bool; let boundTo: String?; let identifiable: Bool
        let defaultPurpose: String?
        /// The longest a grant to this role may run, and the purposes it may name. The gateway refuses past either.
        let maxExpiryDays: Int; let allowedPurposes: [String]
    }
    struct Refusal: Identifiable { let id: String; let statement: String }

    /* Revocation has no grace period. The number is here so that a screen saying "takes effect
       immediately" is reading it rather than asserting it. */
    static let revocationGraceSeconds = 0
    /* No consent grant lasts longer than this, for any role — the founder's decision of 2026-09-14. A grant sheet caps its end-date picker here. */
    static let maximumExpiryDays = 90

    static let roles: [RecipientRole] = [
        RecipientRole(id: "caregiver", name: "Caregiver or delegate", engine: "access",
                      defaultScope: ["prescription", "appointment", "care-plan"],
                      defaultExpiryDays: 90, sealed: false, boundTo: nil,
                      identifiable: true, defaultPurpose: "treatment",
                      maxExpiryDays: 90, allowedPurposes: ["treatment", "emergency"]),
        RecipientRole(id: "next-of-kin", name: "Next of kin", engine: "access",
                      defaultScope: ["emergency-card"],
                      defaultExpiryDays: 90, sealed: false, boundTo: nil,
                      identifiable: true, defaultPurpose: "emergency",
                      maxExpiryDays: 90, allowedPurposes: ["emergency"]),
        RecipientRole(id: "nurse-assigned", name: "Assigned MyThuso nurse", engine: "care",
                      defaultScope: ["patient", "allergy", "vitals", "chronic-condition", "medical-history", "immunisation", "child-health", "care-plan", "emergency-card", "prescription", "dispense", "referral", "home-visit"],
                      defaultExpiryDays: 14, sealed: false, boundTo: "episode",
                      identifiable: true, defaultPurpose: "treatment",
                      maxExpiryDays: 14, allowedPurposes: ["treatment", "emergency"]),
        RecipientRole(id: "doctor-assigned", name: "Assigned MyThuso doctor", engine: "care",
                      defaultScope: ["patient", "household", "allergy", "vitals", "chronic-condition", "diagnosis", "medical-history", "immunisation", "child-health", "care-plan", "emergency-card", "consultation", "procedure", "prescription", "medication-catalogue", "dispense", "laboratory", "imaging", "referral", "admission", "home-visit"],
                      defaultExpiryDays: 14, sealed: false, boundTo: "episode",
                      identifiable: true, defaultPurpose: "treatment",
                      maxExpiryDays: 14, allowedPurposes: ["treatment", "diagnostics", "emergency"]),
        RecipientRole(id: "pharmacist", name: "Pharmacist", engine: "medicines",
                      defaultScope: ["prescription", "dispense", "allergy", "chronic-condition"],
                      defaultExpiryDays: 7, sealed: false, boundTo: "episode",
                      identifiable: true, defaultPurpose: "dispensing",
                      maxExpiryDays: 7, allowedPurposes: ["dispensing"]),
        RecipientRole(id: "care-coordinator", name: "Care coordinator", engine: "core",
                      defaultScope: ["task", "appointment", "transport"],
                      defaultExpiryDays: 30, sealed: false, boundTo: "episode",
                      identifiable: true, defaultPurpose: "dispatch",
                      maxExpiryDays: 30, allowedPurposes: ["dispatch"]),
        RecipientRole(id: "responder-on-trip", name: "Thuso Ride responder, during a trip", engine: "movement",
                      defaultScope: ["emergency-card", "transport"],
                      defaultExpiryDays: 1, sealed: false, boundTo: "trip",
                      identifiable: true, defaultPurpose: "dispatch",
                      maxExpiryDays: 1, allowedPurposes: ["dispatch", "emergency"]),
        RecipientRole(id: "scheme-aggregate", name: "Medical scheme, aggregate only", engine: "money",
                      defaultScope: [],
                      defaultExpiryDays: 90, sealed: false, boundTo: nil,
                      identifiable: false, defaultPurpose: nil,
                      maxExpiryDays: 90, allowedPurposes: [])
    ]

    static let refusals: [Refusal] = [
        Refusal(id: "every-grant-expires", statement: "Every grant has an end date. There is no default of forever, and no role whose grant does not expire."),
        Refusal(id: "sealed-needs-an-explicit-tick", statement: "A sealed category is never in a default scope. It is included only when the patient ticks it in on the grant itself."),
        Refusal(id: "scheme-receives-aggregate-only", statement: "A medical scheme receives aggregate data only. There is no grant that lets a scheme, insurer, employer or advertiser read an identifiable record, and none can be made."),
        Refusal(id: "revocation-is-immediate", statement: "Revoking a grant takes effect immediately. There is no grace period and no cached copy that keeps working."),
        Refusal(id: "responder-grant-ends-with-the-trip", statement: "A responder's grant ends when the trip ends, and never lasts longer than a day."),
        Refusal(id: "operations-and-engineering-receive-no-grant", statement: "Operations, support and engineering are not grant recipients. They see metadata, or synthetic data, and never a record.")
    ]

    static func role(_ id: String) -> RecipientRole? { roles.first { $0.id == id } }
    static func refusal(_ id: String) -> String { refusals.first { $0.id == id }?.statement ?? "" }
}
