// Generated by scripts/emit-events.mjs from packages/catalog/events.json, packages/catalog/assistant.json, packages/catalog/trust.json.
// Do not edit by hand — run `npm run events`. The build fails if this file and its sources
// disagree, so an edit here is lost rather than merely wrong.
//
// One sealed constant per live event version, carrying the engine that owns it. Nothing in this app
// publishes to a bus, and no payload shape is written here. A withdrawn version has no constant and
// an EventKey cannot be made outside this file, so no code in this app can name one.

import Foundation

enum EventsData {
    struct Engine: Identifiable { let id: String; let name: String; let productName: String }

    /* A live event version. The initialiser is fileprivate: only this generated file makes one. */
    struct EventKey: Identifiable, Hashable {
        let type: String
        let version: Int
        let owner: String
        var id: String { "\(type)@\(version)" }
        fileprivate init(_ type: String, _ version: Int, _ owner: String) {
            self.type = type
            self.version = version
            self.owner = owner
        }
    }

    static let contractVersion = 1
    static let frozen = true

    static let engines: [Engine] = [
        Engine(id: "core", name: "ThusoIQ Core", productName: "ThusoIQ"),
        Engine(id: "access", name: "Access", productName: "Gilbert"),
        Engine(id: "pulse", name: "Gilbert Pulse Interaction Engine", productName: "Gilbert Pulse"),
        Engine(id: "care", name: "Care", productName: "Thuso Nurse"),
        Engine(id: "clinical", name: "Clinical Intelligence", productName: "Thuso AI"),
        Engine(id: "safety", name: "Safety", productName: "Sentinel"),
        Engine(id: "movement", name: "Movement", productName: "Thuso Ride"),
        Engine(id: "trust", name: "Trust", productName: "Verify"),
        Engine(id: "record", name: "Record", productName: "Health Passport"),
        Engine(id: "medicines", name: "Medicines & Labs", productName: "Thuso Pharmacy"),
        Engine(id: "devices", name: "Devices", productName: "Thuso Kit"),
        Engine(id: "money", name: "Money", productName: "Thuso Money")
    ]

    static let appointmentRequestedV1 = EventKey("appointment.requested", 1, "care")
    static let appointmentOfferedV1 = EventKey("appointment.offered", 1, "care")
    static let appointmentBookedV1 = EventKey("appointment.booked", 1, "care")
    static let appointmentConfirmedV1 = EventKey("appointment.confirmed", 1, "care")
    static let appointmentEnRouteV1 = EventKey("appointment.en_route", 1, "care")
    static let appointmentInProgressV1 = EventKey("appointment.in_progress", 1, "care")
    static let appointmentCompletedV1 = EventKey("appointment.completed", 1, "care")
    static let appointmentNoShowV1 = EventKey("appointment.no_show", 1, "care")
    static let appointmentCancelledV1 = EventKey("appointment.cancelled", 1, "care")
    static let appointmentFollowUpRequiredV1 = EventKey("appointment.follow_up_required", 1, "care")
    static let personVerifiedV1 = EventKey("person.verified", 1, "trust")
    static let personProbationV1 = EventKey("person.probation", 1, "trust")
    static let personTrustUpdatedV2 = EventKey("person.trust_updated", 2, "trust")
    static let personUnderReviewV1 = EventKey("person.under_review", 1, "trust")
    static let personSuspendedV1 = EventKey("person.suspended", 1, "trust")
    static let personReinstatedV1 = EventKey("person.reinstated", 1, "trust")
    static let personDeactivatedV1 = EventKey("person.deactivated", 1, "trust")
    static let credentialExpiringV1 = EventKey("credential.expiring", 1, "trust")
    static let credentialLapsedV1 = EventKey("credential.lapsed", 1, "trust")
    static let partnerVerifiedV1 = EventKey("partner.verified", 1, "trust")
    static let partnerSuspendedV1 = EventKey("partner.suspended", 1, "trust")
    static let passportRecordCreatedV1 = EventKey("passport.record.created", 1, "record")
    static let passportEntryWrittenV1 = EventKey("passport.entry.written", 1, "record")
    static let passportEntrySupersededV1 = EventKey("passport.entry.superseded", 1, "record")
    static let passportConsentGrantedV3 = EventKey("passport.consent.granted", 3, "record")
    static let passportConsentRevokedV3 = EventKey("passport.consent.revoked", 3, "record")
    static let passportAccessReadV1 = EventKey("passport.access.read", 1, "record")
    static let passportAccessBreakglassV1 = EventKey("passport.access.breakglass", 1, "record")
    static let passportExportGeneratedV1 = EventKey("passport.export.generated", 1, "record")
    static let alertRaisedV1 = EventKey("alert.raised", 1, "core")
    static let alertAcknowledgedV1 = EventKey("alert.acknowledged", 1, "core")
    static let alertEscalatedV1 = EventKey("alert.escalated", 1, "core")
    static let alertClosedV1 = EventKey("alert.closed", 1, "core")
    static let marketOrderPlacedV1 = EventKey("market.order.placed", 1, "money")
    static let marketOrderPaidV1 = EventKey("market.order.paid", 1, "money")
    static let marketOrderShippedV1 = EventKey("market.order.shipped", 1, "money")
    static let marketOrderDeliveredV1 = EventKey("market.order.delivered", 1, "money")
    static let marketOrderReturnedV1 = EventKey("market.order.returned", 1, "money")
    static let pulseSessionStartedV1 = EventKey("pulse.session.started", 1, "pulse")
    static let pulseListeningStartedV1 = EventKey("pulse.listening.started", 1, "pulse")
    static let pulseUtteranceFinalisedV2 = EventKey("pulse.utterance.finalised", 2, "pulse")
    static let pulseThinkingStartedV1 = EventKey("pulse.thinking.started", 1, "pulse")
    static let pulseDeviceHighlightV1 = EventKey("pulse.device.highlight", 1, "pulse")
    static let pulseGuidancePresentedV1 = EventKey("pulse.guidance.presented", 1, "pulse")
    static let pulseEscalationStartedV2 = EventKey("pulse.escalation.started", 2, "pulse")
    static let pulseHandoverCompletedV1 = EventKey("pulse.handover.completed", 1, "pulse")
    static let trustWeightDecidedV2 = EventKey("trust.weight.decided", 2, "trust")
    static let trustDispatchWithheldV1 = EventKey("trust.dispatch.withheld", 1, "trust")
    static let recordBreakglassReviewDueV1 = EventKey("record.breakglass.review_due", 1, "record")
    static let recordAuditChainBrokenV1 = EventKey("record.audit.chain_broken", 1, "record")

    static let events: [EventKey] = [
        appointmentRequestedV1,
        appointmentOfferedV1,
        appointmentBookedV1,
        appointmentConfirmedV1,
        appointmentEnRouteV1,
        appointmentInProgressV1,
        appointmentCompletedV1,
        appointmentNoShowV1,
        appointmentCancelledV1,
        appointmentFollowUpRequiredV1,
        personVerifiedV1,
        personProbationV1,
        personTrustUpdatedV2,
        personUnderReviewV1,
        personSuspendedV1,
        personReinstatedV1,
        personDeactivatedV1,
        credentialExpiringV1,
        credentialLapsedV1,
        partnerVerifiedV1,
        partnerSuspendedV1,
        passportRecordCreatedV1,
        passportEntryWrittenV1,
        passportEntrySupersededV1,
        passportConsentGrantedV3,
        passportConsentRevokedV3,
        passportAccessReadV1,
        passportAccessBreakglassV1,
        passportExportGeneratedV1,
        alertRaisedV1,
        alertAcknowledgedV1,
        alertEscalatedV1,
        alertClosedV1,
        marketOrderPlacedV1,
        marketOrderPaidV1,
        marketOrderShippedV1,
        marketOrderDeliveredV1,
        marketOrderReturnedV1,
        pulseSessionStartedV1,
        pulseListeningStartedV1,
        pulseUtteranceFinalisedV2,
        pulseThinkingStartedV1,
        pulseDeviceHighlightV1,
        pulseGuidancePresentedV1,
        pulseEscalationStartedV2,
        pulseHandoverCompletedV1,
        trustWeightDecidedV2,
        trustDispatchWithheldV1,
        recordBreakglassReviewDueV1,
        recordAuditChainBrokenV1
    ]

    static func owner(of type: String) -> String? { events.first { $0.type == type }?.owner }
}
