// Generated by scripts/emit-framing.mjs from packages/catalog/framing.json.
// Do not edit by hand — run `npm run framing`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// How a screen introduces itself: a lead line saying what the reader is here to do and an accent
// line saying what the screen gives them for it. StudioHeadline draws both, and nothing in either
// app may type one — scripts/check-boundaries.mjs fails on a framing string in any other source.
//
// The patient's framing is not here as words. It is two locale keys, because those two lines are
// already translated into every language MyThuso offers and a copy in English would have been a
// slogan nobody had reviewed on the first screen a patient opens.

import Foundation

enum FramingData {
    /// One screen's introduction. `role` is the workspace this frames, or nil for a framing that
    /// belongs to a screen rather than to somebody's job.
    struct Framing: Identifiable, Hashable {
        let id: String
        let role: String?
        let lead: String
        let accent: String
    }

    // A display-size headline is a claim the size of the screen. The role framings appear on the
    // section a role lands on and nowhere else; every other section keeps a plain heading. Four
    // display headlines across four tabs are four claims of the same size, which is the inverse of
    // what a display size is for.
    static let framings: [Framing] = [
        .init(id: "nurse", role: "Nurse",
              lead: "Your round today.", accent: "Make it count."),
        .init(id: "doctor", role: "Doctor",
              lead: "Your judgement.", accent: "A clearer view."),
        .init(id: "partner", role: "Partner",
              lead: "Every order.", accent: "And what it waits on."),
        .init(id: "control-tower", role: "Control Tower",
              lead: "Every visit.", accent: "One board."),
        .init(id: "live-well", role: nil,
              lead: "Live well.", accent: "In your own words.")
    ]
    static func framing(id: String) -> Framing? { framings.first { $0.id == id } }
    /// The framing for a role, or nil. Deliberately optional: a role nobody has framed gets the
    /// plain section heading rather than somebody else's words, which is what the switch statement
    /// this replaced did silently with its default branch.
    static func framing(role: String) -> Framing? { framings.first { $0.role == role } }

    // The sections whose blurb belongs to the screen rather than to somebody's job. A section with
    // nothing useful to say is absent from this list and gets no line, rather than a filler one.
    private static let blurbs: [String: String] = [
        "Schedule": "Today’s visits, in the order you will do them, and the one still waiting for your sign-off.",
        "Review queue": "Cases waiting to be read. Decision support may draft; only a registered doctor signs.",
        "Orders": "Prescriptions and laboratory orders routed to this partner, and what each is waiting on.",
        "Dispatch": "Where every visit is, which nurses are free, and what is running late.",
        "Incidents": "What went wrong, how severe it is, and who is holding it.",
        "Collections": "Sample collections booked against this partner, and the windows they have to be inside.",
        "Results": "Results this partner has produced, and what is holding each one back from release."
    ]
    /// What a section is for. Empty for a section with nothing useful to say, which is deliberately
    /// different from a filler sentence: the heading then stands on its own.
    static func blurb(_ section: String) -> String { blurbs[section] ?? "" }

    // The prototype's patient frame is "Hello, Nomsa." over "Your next visit. Your team. Your
    // health." What ships is the same shape with the locale contract's own words in it — the
    // greeting and the three-word tagline, both reviewed to the same standard as the rest of the
    // shell and both present in every locale offered. Typing the prototype's second line here would
    // have put a slogan nobody had translated on the one screen every patient opens first, in ten
    // languages, to gain nothing the tagline was not already saying.
    static let patientLead = ThusoString.greeting
    static let patientAccent = ThusoString.tagline
    static let patientDetail = ThusoString.greetingSub
}
