// Generated by scripts/emit-geography.mjs from packages/catalog/geography.json.
// Do not edit by hand — run `npm run geography`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// Coordinates only. The arithmetic that consumes them — distance, projection, province, arrival
// estimate — is hand-written on this platform against packages/geo/README.md, because those are
// decisions rather than data and generating them would hide the decision.

import Foundation

extension Geography {
    static let city = "Johannesburg"
    static let province = "Gauteng"
    static let phase = 1
    static let coverageSentence = "Phase one is northern Johannesburg and Soweto. Everywhere else on this map is drawn because it is there, not because anybody is working in it."

    static let centre = Point(lat: -26.172, lng: 27.992)
    static let spanKm = 28.0
    static let zoom = 10.4
    static let minZoom = 8.5
    /// Fifteen is a privacy limit, not a performance one: above it a reader can pick out one house.
    static let maxZoom = 15.0

    static let coordinateDecimals = 3
    static let precisionMetres = 110
    static let precisionSentence = "Every position in this preview is rounded to three decimal places — about a hundred metres. The suburbs are real; nobody lives at these points."

    static let zones: [Zone] = [
        .init(id: "randburg", name: "Randburg",
              at: Point(lat: -26.094, lng: 27.999), radiusKm: 3.0),
        .init(id: "rosebank", name: "Rosebank",
              at: Point(lat: -26.146, lng: 28.042), radiusKm: 2.4),
        .init(id: "parktown", name: "Parktown",
              at: Point(lat: -26.184, lng: 28.040), radiusKm: 2.2),
        .init(id: "melville", name: "Melville",
              at: Point(lat: -26.175, lng: 27.999), radiusKm: 2.2),
        .init(id: "soweto", name: "Soweto",
              at: Point(lat: -26.249, lng: 27.908), radiusKm: 4.0)
    ]

    static let marks: [MapMark] = [
        .init(id: "zone", name: "Service zone", detail: "A suburb MyThuso covers, drawn at its working radius."),
        .init(id: "nurse-free", name: "Nurse available", detail: "Cleared by vetting and not on a visit."),
        .init(id: "nurse-busy", name: "Nurse on a visit", detail: "Positioned, but not dispatchable until the visit closes."),
        .init(id: "nurse-blocked", name: "Blocked by vetting", detail: "Drawn where they are and refused all the same. A lapsed credential withdraws dispatch by arithmetic, not by somebody remembering."),
        .init(id: "visit-waiting", name: "Visit awaiting a nurse", detail: "Plotted at the centre of its suburb, never at its address."),
        .init(id: "visit-assigned", name: "Assigned", detail: "A nurse has accepted it.")
    ]

    /// No tile server is contacted by any native build. The schematic below is what both apps draw,
    /// and it is why tileAttribution is carried without being rendered: the day a native map draws
    /// streets, the credit is already here, in the same words the web renders, out of the same file.
    static let schematicName = "Schematic"
    static let schematicSentence = "This map is drawn from the coordinates alone: the zones, the visits and the nurses, in their real positions, without streets behind them. No tile server is asked for anything."
    static let attributionRequired = true
    static let tileSource = "OpenFreeMap"
    static let tileAttribution = "OpenFreeMap © OpenMapTiles Data from OpenStreetMap"
    static let tileLicence = "Map data © OpenStreetMap contributors, under the Open Database Licence. Tile schema by OpenMapTiles. The OpenFreeMap software is MIT."

    static let privacySentence = "A map in MyThuso plots suburbs, not addresses."
    static let privacyRules: [GeographyRule] = [
        .init(id: "address-is-not-a-pin", statement: "A visit awaiting a nurse is drawn at the centre of its suburb. Its street address is never a coordinate on any map, on any screen, at any zoom.", why: "A home address beside a health service is not a location, it is a diagnosis with a doorstep. The controller assigning the visit needs to know which suburb it is in; they do not need to know which house until they are the one going to it, and then it is in the visit, not on the board."),
        .init(id: "a-nurse-is-not-tracked-between-visits", statement: "A nurse who is not sharing a position has none, and the board says so rather than placing them somewhere plausible.", why: "An empty space is a true statement about a phone in a bag. A guessed pin is a false statement about a person's whereabouts, and it is the one a dispatcher would act on."),
        .init(id: "no-history-drawn", statement: "No map here draws where anybody has been. A position is the current one or it is absent.", why: "A track is a record of a person's movements. Nothing in this product needs one, so nothing in this product keeps one, and there is no screen that could be persuaded to show one."),
        .init(id: "nothing-leaves-for-a-tile", statement: "The tile server is asked for streets. It is never told what is on top of them — no visit, no patient, no nurse position is sent to any mapping provider.", why: "A map vendor that can see your pins can see your caseload. The zones, the visits and the nurses are drawn by this application on top of tiles that know nothing about them."),
        .init(id: "a-tile-request-is-a-viewport", statement: "Asking for streets still tells the tile server something: which square of the map is open, the internet address that asked, and the time. Over a visit that is roughly which suburb a patient is in and roughly when somebody came to the house. Streets are off until the person looking turns them on, and the schematic asks nobody anything.", why: "Until this map drew streets no tile was ever fetched, so there was nothing to disclose and nobody had disclosed it. Now there is. A viewport is not a pin, but a health service whose viewports a third party can watch has handed over a weaker version of the same thing, and one nobody agreed to. The sentence is rendered beside the switch rather than filed in a policy page, because the switch is where the decision is actually made.")
    ]

    static let refusals: [GeographyRefusal] = [
        .init(id: "outside-south-africa", sentence: "That position is not in South Africa. It has not been drawn.", why: "packages/geo refuses the coordinate before a map sees it. A pin in the Atlantic is a data fault, and the map's job is to be the place it becomes visible rather than the place it is smoothed over."),
        .init(id: "outside-coverage", sentence: "MyThuso is not working in that area yet. You can be told when it is.", why: "Refusing a booking outside phase one is the whole point of naming a phase. An app that takes the booking anyway has moved the disappointment to the patient's front door."),
        .init(id: "no-position-shared", sentence: "This nurse is not sharing a position right now, so they are not on the map.", why: "Said out loud, on the board, next to the count. A dispatcher who cannot see the difference between nobody-there and nobody-reporting will read the map as the first one.")
    ]
}
