// Generated by scripts/emit-money.mjs from packages/catalog/money.json, packages/catalog/apis/money.json and the file each fee's range is cited from.
// Do not edit by hand — run `npm run money`. The build fails if this file and its sources disagree,
// so an edit here is lost rather than merely wrong.
//
// The doctor's fee is nil while the contract says null. The range beside it was read from the file
// the contract cites, and the types and the arithmetic are hand-written in Money.swift and Money.kt.

import Foundation

extension Money {
    static let currency = "ZAR"
    static let methods: [MoneyMethod] = [
        .init(id: "card", name: "Card", detail: "On the provider's own page. MyThuso never sees the number.", forVisit: true, forPlan: true, offered: true),
        .init(id: "eft", name: "EFT", detail: "From your bank to the provider, with the visit reference.", forVisit: true, forPlan: true, offered: true),
        .init(id: "debit-order", name: "Debit order", detail: "Taken each month for a plan, under a mandate you give your bank.", forVisit: false, forPlan: true, offered: true),
        .init(id: "cash-otp", name: "Cash, with a code", detail: "You pay the nurse at the door and give her the code this screen shows you.", forVisit: true, forPlan: false, offered: true),
        .init(id: "wallet", name: "Thuso Wallet", detail: "A prepaid balance.", forVisit: true, forPlan: true, offered: false)
    ]
    static let states: [MoneyPaymentState] = [
        .init(id: "pending", name: "Waiting", words: "We are waiting for your bank to answer. Nothing is booked until it does."),
        .init(id: "succeeded", name: "Paid", words: "Your payment went through."),
        .init(id: "failed", name: "Did not go through", words: "Nothing is booked. You can try again, or choose another way to pay."),
        .init(id: "refunded", name: "Refunded", words: "The visit did not go ahead, so the money is going back to the account it came from.")
    ]
    static let cashCodeLength = 6
    static let cashPendingWords = "Nothing has been paid yet. You pay the nurse at the door, and it is recorded as paid when she enters this code after the visit."
    static let providerlessWords = "Nothing was charged. A payment made here would go to the provider's own page, and no provider is connected to this phone."
    static let doctorFees: [DoctorFee] = [
        .init(feeCode: "review-per-case", name: "A doctor's review, per case", amount: nil, decidedBy: nil, decidedOn: nil,
              rangeLow: 35, rangeHigh: 60, source: "The Master Blueprint and the funding proposal give a range for a doctor's per-case review fee. They do not give a price.",
              undecided: "The fee for a doctor's review has not been decided, so no doctor's payout is scheduled. Every case you sign is recorded, and each one is paid once the fee is set.", whoDecides: "The founder, with the lead of the doctor review panel.")
    ]
    static let casesWords = "Each case is a reference and the day you signed it. Money is never told who the patient was or why the review was needed."
    static let sampleCases: [SignedCase] = [
        .init(reviewRef: "RV-3107", onDays: -1),
        .init(reviewRef: "RV-3104", onDays: -2),
        .init(reviewRef: "RV-3098", onDays: -4)
    ]
    /* Rendered word for word, from packages/catalog/apis/money.json. */
    static let refusals: [String: String] = [
        "doctor-fee-undecided": "No doctor's payout is scheduled while the fee is undecided.",
        "card-number-held": "MyThuso never holds a card number.",
        "scheme-sees-a-payment": "No scheme or employer sees what one person paid."
    ]
}
