// Generated by scripts/emit-icons.mjs from packages/catalog/icons.json.
// Do not edit by hand — run `npm run icons`. The build fails if this file and the source disagree,
// so an edit here is lost rather than merely wrong.
//
// The MyThuso icon family, drawn by the design handoff of 28 September 2026 and adopted exactly.
// Primary patient destinations and healthcare actions; Lucide stays for universal utility actions;
// never both for one concept; the signal dot pulses only for something live or time-sensitive.
//
// Each icon is its elements as SwiftUI Path builders in the family's 24-unit space, with H, V, S and T
// spelt out and every SVG arc as cubic Béziers; the view scales them to the size it is given and
// strokes with round caps and joins. Colours are roles resolved against ThusoTheme, so the family
// recolours when the tokens do.

import SwiftUI

enum MyThusoIconsData {
    static let version = 1
    static let size: CGFloat = 24

    /// The family's rules, word for word.
    static let rules: [String] = [
        "Use the MyThuso icon family for primary patient destinations, healthcare actions and branded feature entry points.",
        "Use Lucide only for universal utility actions such as search, close, download, arrows and overflow controls.",
        "Never mix a generic icon and a MyThuso icon for the same concept.",
        "The signal animation is for live or time-sensitive actions only. An icon that merely names a place does not pulse."
    ]

    /// What a stroke or fill is painted with. `current` is the text colour where the icon sits.
    enum Role {
        case current, accent, primary, highlight
        var color: Color {
            switch self {
            case .current: return Color.primary
            case .accent: return ThusoTheme.brandGreen
            case .primary: return ThusoTheme.brandInk
            case .highlight: return ThusoTheme.brandLime
            }
        }
    }

    struct Element {
        let path: Path
        let stroke: Role
        let strokeWidth: CGFloat
    }

    struct Icon: Identifiable {
        let id: String
        let name: String
        let meaning: String
        let elements: [Element]
    }

    /// The signal dot every icon carries, and its pulse: scale only, on the shared curve, and only
    /// for something live. Reduced motion removes it.
    enum Signal {
        static let center = CGPoint(x: 18.6, y: 5.4)
        static let radius: CGFloat = 2.05
        static let fill: Role = .highlight
        static let stroke: Role = .primary
        static let strokeWidth: CGFloat = 1
        static let scaleFrom: CGFloat = 1
        static let scaleTo: CGFloat = 1.25
        static let duration: TimeInterval = 1.8
    }

    /// The patient's overview: the home destination, where visits, readings and messages meet.
    static let dashboard = Icon(id: "dashboard", name: "Dashboard", meaning: "The patient's overview: the home destination, where visits, readings and messages meet.", elements: [
        Element(path: Path { p in
                p.move(to: CGPoint(x: 4.25, y: 9.2))
                p.addLine(to: CGPoint(x: 12, y: 3.4))
                p.addLine(to: CGPoint(x: 19.75, y: 9.2))
                p.addLine(to: CGPoint(x: 19.75, y: 18.25))
                p.addCurve(to: CGPoint(x: 17.75, y: 20.25), control1: CGPoint(x: 19.75, y: 19.3546), control2: CGPoint(x: 18.8546, y: 20.25))
                p.addLine(to: CGPoint(x: 6.25, y: 20.25))
                p.addCurve(to: CGPoint(x: 4.25, y: 18.25), control1: CGPoint(x: 5.1454, y: 20.25), control2: CGPoint(x: 4.25, y: 19.3546))
                p.addLine(to: CGPoint(x: 4.25, y: 9.2))
                p.closeSubpath()
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 8, y: 15.5))
                p.addLine(to: CGPoint(x: 8, y: 12.5))
                p.move(to: CGPoint(x: 12, y: 15.5))
                p.addLine(to: CGPoint(x: 12, y: 9.8))
                p.move(to: CGPoint(x: 16, y: 15.5))
                p.addLine(to: CGPoint(x: 16, y: 11.3))
            }, stroke: .accent, strokeWidth: 2)
    ])

    /// The patient's health: the passport, readings and what they mean.
    static let health = Icon(id: "health", name: "Health", meaning: "The patient's health: the passport, readings and what they mean.", elements: [
        Element(path: Path { p in
                p.move(to: CGPoint(x: 12, y: 20))
                p.addCurve(to: CGPoint(x: 4.5, y: 9.9), control1: CGPoint(x: 12, y: 20), control2: CGPoint(x: 4.5, y: 15.8))
                p.addCurve(to: CGPoint(x: 7.1872, y: 5.7786), control1: CGPoint(x: 4.4582, y: 8.103), control2: CGPoint(x: 5.526, y: 6.4653))
                p.addCurve(to: CGPoint(x: 12, y: 6.8), control1: CGPoint(x: 8.8484, y: 5.092), control2: CGPoint(x: 10.7608, y: 5.4979))
                p.addCurve(to: CGPoint(x: 16.8128, y: 5.7786), control1: CGPoint(x: 13.2392, y: 5.4979), control2: CGPoint(x: 15.1516, y: 5.092))
                p.addCurve(to: CGPoint(x: 19.5, y: 9.9), control1: CGPoint(x: 18.474, y: 6.4653), control2: CGPoint(x: 19.5418, y: 8.103))
                p.addCurve(to: CGPoint(x: 12, y: 20), control1: CGPoint(x: 19.5, y: 15.8), control2: CGPoint(x: 12, y: 20))
                p.closeSubpath()
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 7.8, y: 12))
                p.addLine(to: CGPoint(x: 9.9, y: 12))
                p.addLine(to: CGPoint(x: 11, y: 9.7))
                p.addLine(to: CGPoint(x: 13, y: 14.4))
                p.addLine(to: CGPoint(x: 14.2, y: 12))
                p.addLine(to: CGPoint(x: 16.2, y: 12))
            }, stroke: .accent, strokeWidth: 1.8)
    ])

    /// A nurse's visit: booking one, the ones coming, and the one happening now.
    static let visit = Icon(id: "visit", name: "Visit", meaning: "A nurse's visit: booking one, the ones coming, and the one happening now.", elements: [
        Element(path: Path { p in
                p.move(to: CGPoint(x: 7, y: 5.5))
                p.addLine(to: CGPoint(x: 17, y: 5.5))
                p.addCurve(to: CGPoint(x: 20, y: 8.5), control1: CGPoint(x: 18.6569, y: 5.5), control2: CGPoint(x: 20, y: 6.8431))
                p.addLine(to: CGPoint(x: 20, y: 16.5))
                p.addCurve(to: CGPoint(x: 17, y: 19.5), control1: CGPoint(x: 20, y: 18.1569), control2: CGPoint(x: 18.6569, y: 19.5))
                p.addLine(to: CGPoint(x: 7, y: 19.5))
                p.addCurve(to: CGPoint(x: 4, y: 16.5), control1: CGPoint(x: 5.3431, y: 19.5), control2: CGPoint(x: 4, y: 18.1569))
                p.addLine(to: CGPoint(x: 4, y: 8.5))
                p.addCurve(to: CGPoint(x: 7, y: 5.5), control1: CGPoint(x: 4, y: 6.8431), control2: CGPoint(x: 5.3431, y: 5.5))
                p.closeSubpath()
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 8, y: 3.8))
                p.addLine(to: CGPoint(x: 8, y: 7.2))
                p.move(to: CGPoint(x: 16, y: 3.8))
                p.addLine(to: CGPoint(x: 16, y: 7.2))
                p.move(to: CGPoint(x: 4, y: 9.5))
                p.addLine(to: CGPoint(x: 20, y: 9.5))
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 12, y: 12))
                p.addLine(to: CGPoint(x: 12, y: 16))
                p.move(to: CGPoint(x: 10, y: 14))
                p.addLine(to: CGPoint(x: 14, y: 14))
            }, stroke: .accent, strokeWidth: 2)
    ])

    /// A quick action: the shortest way to the thing a patient does most.
    static let quick = Icon(id: "quick", name: "Quick", meaning: "A quick action: the shortest way to the thing a patient does most.", elements: [
        Element(path: Path { p in
                p.move(to: CGPoint(x: 13.3, y: 2.8))
                p.addLine(to: CGPoint(x: 5.8, y: 13))
                p.addLine(to: CGPoint(x: 10.8, y: 13))
                p.addLine(to: CGPoint(x: 9.8, y: 21.2))
                p.addLine(to: CGPoint(x: 18.4, y: 10))
                p.addLine(to: CGPoint(x: 13.2, y: 10))
                p.addLine(to: CGPoint(x: 13.3, y: 2.8))
                p.closeSubpath()
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 8.1, y: 16.9))
                p.addLine(to: CGPoint(x: 5.9, y: 18.4))
                p.move(to: CGPoint(x: 15.9, y: 5.6))
                p.addLine(to: CGPoint(x: 18.1, y: 4.1))
            }, stroke: .accent, strokeWidth: 1.8)
    ])

    /// Results: a lab order, a reading that has been reviewed, an answer that has come back.
    static let results = Icon(id: "results", name: "Results", meaning: "Results: a lab order, a reading that has been reviewed, an answer that has come back.", elements: [
        Element(path: Path { p in
                p.move(to: CGPoint(x: 8, y: 3.5))
                p.addLine(to: CGPoint(x: 16, y: 3.5))
                p.addLine(to: CGPoint(x: 16, y: 8.7))
                p.addLine(to: CGPoint(x: 19.2, y: 15.8))
                p.addCurve(to: CGPoint(x: 18.9658, y: 18.8335), control1: CGPoint(x: 19.6384, y: 16.786), control2: CGPoint(x: 19.5504, y: 17.9265))
                p.addCurve(to: CGPoint(x: 16.3, y: 20.3), control1: CGPoint(x: 18.3813, y: 19.7406), control2: CGPoint(x: 17.379, y: 20.2919))
                p.addLine(to: CGPoint(x: 7.7, y: 20.3))
                p.addCurve(to: CGPoint(x: 5.0342, y: 18.8335), control1: CGPoint(x: 6.621, y: 20.2919), control2: CGPoint(x: 5.6187, y: 19.7406))
                p.addCurve(to: CGPoint(x: 4.8, y: 15.8), control1: CGPoint(x: 4.4496, y: 17.9265), control2: CGPoint(x: 4.3616, y: 16.786))
                p.addLine(to: CGPoint(x: 8, y: 8.7))
                p.addLine(to: CGPoint(x: 8, y: 3.5))
                p.closeSubpath()
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 7.1, y: 14.2))
                p.addLine(to: CGPoint(x: 16.9, y: 14.2))
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 9.2, y: 17.1))
                p.addLine(to: CGPoint(x: 14.8, y: 17.1))
            }, stroke: .accent, strokeWidth: 2)
    ])

    /// Medicines: a prescription, a repeat, a dispensing on its way.
    static let medication = Icon(id: "medication", name: "Medication", meaning: "Medicines: a prescription, a repeat, a dispensing on its way.", elements: [
        Element(path: Path { p in
                p.move(to: CGPoint(x: 5.4, y: 11.2))
                p.addLine(to: CGPoint(x: 11.2, y: 5.4))
                p.addCurve(to: CGPoint(x: 17.3, y: 5.4), control1: CGPoint(x: 12.8845, y: 3.7155), control2: CGPoint(x: 15.6155, y: 3.7155))
                p.addCurve(to: CGPoint(x: 17.3, y: 11.5), control1: CGPoint(x: 18.9845, y: 7.0845), control2: CGPoint(x: 18.9845, y: 9.8155))
                p.addLine(to: CGPoint(x: 11.5, y: 17.3))
                p.addCurve(to: CGPoint(x: 5.4, y: 17.3), control1: CGPoint(x: 9.8155, y: 18.9845), control2: CGPoint(x: 7.0845, y: 18.9845))
                p.addCurve(to: CGPoint(x: 5.4, y: 11.2), control1: CGPoint(x: 3.7155, y: 15.6155), control2: CGPoint(x: 3.7155, y: 12.8845))
                p.closeSubpath()
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 8.3, y: 8.3))
                p.addLine(to: CGPoint(x: 15.7, y: 15.7))
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 6.4, y: 14.8))
                p.addLine(to: CGPoint(x: 9.2, y: 17.6))
            }, stroke: .accent, strokeWidth: 2)
    ])

    /// Mind and wellbeing: Live well, a check-in, the crisis lines.
    static let mind = Icon(id: "mind", name: "Mind", meaning: "Mind and wellbeing: Live well, a check-in, the crisis lines.", elements: [
        Element(path: Path { p in
                p.move(to: CGPoint(x: 9.2, y: 19.4))
                p.addLine(to: CGPoint(x: 8, y: 19.4))
                p.addCurve(to: CGPoint(x: 5.463, y: 17.9953), control1: CGPoint(x: 6.9692, y: 19.3987), control2: CGPoint(x: 6.0112, y: 18.8683))
                p.addCurve(to: CGPoint(x: 5.3, y: 15.1), control1: CGPoint(x: 4.9149, y: 17.1223), control2: CGPoint(x: 4.8533, y: 16.029))
                p.addCurve(to: CGPoint(x: 3.798, y: 11.4196), control1: CGPoint(x: 4.106, y: 14.2859), control2: CGPoint(x: 3.5145, y: 12.8367))
                p.addCurve(to: CGPoint(x: 6.6, y: 8.6), control1: CGPoint(x: 4.0814, y: 10.0025), control2: CGPoint(x: 5.1847, y: 8.8923))
                p.addCurve(to: CGPoint(x: 10.1033, y: 4.8935), control1: CGPoint(x: 6.7981, y: 6.7157), control2: CGPoint(x: 8.2332, y: 5.1974))
                p.addCurve(to: CGPoint(x: 14.6, y: 7.3), control1: CGPoint(x: 11.9734, y: 4.5896), control2: CGPoint(x: 13.8155, y: 5.5754))
                p.addCurve(to: CGPoint(x: 18.6988, y: 9.3874), control1: CGPoint(x: 16.2906, y: 6.9185), control2: CGPoint(x: 18.0131, y: 7.7957))
                p.addCurve(to: CGPoint(x: 17.4, y: 13.8), control1: CGPoint(x: 19.3845, y: 10.9792), control2: CGPoint(x: 18.8387, y: 12.8335))
                p.addCurve(to: CGPoint(x: 18.3072, y: 17.8207), control1: CGPoint(x: 18.6402, y: 14.7411), control2: CGPoint(x: 19.0232, y: 16.4382))
                p.addCurve(to: CGPoint(x: 14.5, y: 19.4), control1: CGPoint(x: 17.5913, y: 19.2032), control2: CGPoint(x: 15.9843, y: 19.8698))
                p.addLine(to: CGPoint(x: 13.3, y: 19.4))
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 9, y: 13.2))
                p.addCurve(to: CGPoint(x: 15, y: 13.2), control1: CGPoint(x: 10.5, y: 14.7), control2: CGPoint(x: 13.5, y: 14.7))
                p.move(to: CGPoint(x: 12, y: 10.8))
                p.addLine(to: CGPoint(x: 12, y: 20.1))
            }, stroke: .accent, strokeWidth: 1.8)
    ])

    /// Messages: the thread with a nurse, a note for the visit, a reply waiting.
    static let messages = Icon(id: "messages", name: "Messages", meaning: "Messages: the thread with a nurse, a note for the visit, a reply waiting.", elements: [
        Element(path: Path { p in
                p.move(to: CGPoint(x: 4, y: 6.2))
                p.addCurve(to: CGPoint(x: 6.2, y: 4), control1: CGPoint(x: 4, y: 4.985), control2: CGPoint(x: 4.985, y: 4))
                p.addLine(to: CGPoint(x: 17.8, y: 4))
                p.addCurve(to: CGPoint(x: 20, y: 6.2), control1: CGPoint(x: 19.015, y: 4), control2: CGPoint(x: 20, y: 4.985))
                p.addLine(to: CGPoint(x: 20, y: 14.3))
                p.addCurve(to: CGPoint(x: 17.8, y: 16.5), control1: CGPoint(x: 20, y: 15.515), control2: CGPoint(x: 19.015, y: 16.5))
                p.addLine(to: CGPoint(x: 11, y: 16.5))
                p.addLine(to: CGPoint(x: 6.5, y: 19.5))
                p.addLine(to: CGPoint(x: 6.5, y: 16.5))
                p.addLine(to: CGPoint(x: 6.2, y: 16.5))
                p.addCurve(to: CGPoint(x: 4, y: 14.3), control1: CGPoint(x: 4.985, y: 16.5), control2: CGPoint(x: 4, y: 15.515))
                p.addLine(to: CGPoint(x: 4, y: 6.2))
                p.closeSubpath()
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 8, y: 9.2))
                p.addLine(to: CGPoint(x: 16, y: 9.2))
                p.move(to: CGPoint(x: 8, y: 12.5))
                p.addLine(to: CGPoint(x: 13, y: 12.5))
            }, stroke: .accent, strokeWidth: 1.8)
    ])

    /// Family: the household, the people a patient cares for and who care for them.
    static let family = Icon(id: "family", name: "Family", meaning: "Family: the household, the people a patient cares for and who care for them.", elements: [
        Element(path: Path { p in
                p.move(to: CGPoint(x: 6, y: 8))
                p.addCurve(to: CGPoint(x: 9, y: 11), control1: CGPoint(x: 6, y: 9.6569), control2: CGPoint(x: 7.3431, y: 11))
                p.addCurve(to: CGPoint(x: 12, y: 8), control1: CGPoint(x: 10.6569, y: 11), control2: CGPoint(x: 12, y: 9.6569))
                p.addCurve(to: CGPoint(x: 9, y: 5), control1: CGPoint(x: 12, y: 6.3431), control2: CGPoint(x: 10.6569, y: 5))
                p.addCurve(to: CGPoint(x: 6, y: 8), control1: CGPoint(x: 7.3431, y: 5), control2: CGPoint(x: 6, y: 6.3431))
                p.closeSubpath()
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 14.2, y: 9.5))
                p.addCurve(to: CGPoint(x: 16.5, y: 11.8), control1: CGPoint(x: 14.2, y: 10.7703), control2: CGPoint(x: 15.2297, y: 11.8))
                p.addCurve(to: CGPoint(x: 18.8, y: 9.5), control1: CGPoint(x: 17.7703, y: 11.8), control2: CGPoint(x: 18.8, y: 10.7703))
                p.addCurve(to: CGPoint(x: 16.5, y: 7.2), control1: CGPoint(x: 18.8, y: 8.2297), control2: CGPoint(x: 17.7703, y: 7.2))
                p.addCurve(to: CGPoint(x: 14.2, y: 9.5), control1: CGPoint(x: 15.2297, y: 7.2), control2: CGPoint(x: 14.2, y: 8.2297))
                p.closeSubpath()
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 3.8, y: 19))
                p.addCurve(to: CGPoint(x: 9, y: 13.9), control1: CGPoint(x: 4.3, y: 15.7), control2: CGPoint(x: 6.1, y: 13.9))
                p.addCurve(to: CGPoint(x: 14.2, y: 19), control1: CGPoint(x: 11.9, y: 13.9), control2: CGPoint(x: 13.7, y: 15.7))
                p.move(to: CGPoint(x: 13.4, y: 15.6))
                p.addCurve(to: CGPoint(x: 16.5, y: 14), control1: CGPoint(x: 14.2, y: 14.5), control2: CGPoint(x: 15.2, y: 14))
                p.addCurve(to: CGPoint(x: 20.2, y: 18), control1: CGPoint(x: 18.6, y: 14), control2: CGPoint(x: 19.9, y: 15.4))
            }, stroke: .current, strokeWidth: 1.8),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 7.2, y: 8))
                p.addLine(to: CGPoint(x: 10.8, y: 8))
            }, stroke: .accent, strokeWidth: 1.6)
    ])

    /// The patient's own settings destination: privacy, access and preferences. The handoff drew it as a member of the family, so it is one; a gear inside a screen that is merely a utility control stays Lucide.
    static let settings = Icon(id: "settings", name: "Settings", meaning: "The patient's own settings destination: privacy, access and preferences. The handoff drew it as a member of the family, so it is one; a gear inside a screen that is merely a utility control stays Lucide.", elements: [
        Element(path: Path { p in
                p.move(to: CGPoint(x: 12, y: 4.2))
                p.addLine(to: CGPoint(x: 13.4, y: 3))
                p.addLine(to: CGPoint(x: 15.6, y: 4.3))
                p.addLine(to: CGPoint(x: 16, y: 6.1))
                p.addLine(to: CGPoint(x: 17.8, y: 6.8))
                p.addLine(to: CGPoint(x: 19.2, y: 5.8))
                p.addLine(to: CGPoint(x: 21, y: 7.6))
                p.addLine(to: CGPoint(x: 20, y: 9.1))
                p.addLine(to: CGPoint(x: 20.7, y: 10.8))
                p.addLine(to: CGPoint(x: 22.5, y: 11.2))
                p.addLine(to: CGPoint(x: 22.5, y: 13.8))
                p.addLine(to: CGPoint(x: 20.7, y: 14.2))
                p.addLine(to: CGPoint(x: 20, y: 15.9))
                p.addLine(to: CGPoint(x: 21, y: 17.4))
                p.addLine(to: CGPoint(x: 19.2, y: 19.2))
                p.addLine(to: CGPoint(x: 17.8, y: 18.2))
                p.addLine(to: CGPoint(x: 16, y: 18.9))
                p.addLine(to: CGPoint(x: 15.6, y: 20.7))
                p.addLine(to: CGPoint(x: 13, y: 20.7))
                p.addLine(to: CGPoint(x: 12.6, y: 18.9))
                p.addLine(to: CGPoint(x: 10.8, y: 18.2))
                p.addLine(to: CGPoint(x: 9.4, y: 19.2))
                p.addLine(to: CGPoint(x: 7.6, y: 17.4))
                p.addLine(to: CGPoint(x: 8.6, y: 15.9))
                p.addLine(to: CGPoint(x: 7.9, y: 14.2))
                p.addLine(to: CGPoint(x: 6.1, y: 13.8))
                p.addLine(to: CGPoint(x: 6.1, y: 11.2))
                p.addLine(to: CGPoint(x: 7.9, y: 10.8))
                p.addLine(to: CGPoint(x: 8.6, y: 9.1))
                p.addLine(to: CGPoint(x: 7.6, y: 7.6))
                p.addLine(to: CGPoint(x: 9.4, y: 5.8))
                p.addLine(to: CGPoint(x: 10.8, y: 6.8))
                p.addLine(to: CGPoint(x: 12.6, y: 6.1))
                p.addLine(to: CGPoint(x: 13, y: 4.3))
                p.addLine(to: CGPoint(x: 12, y: 4.3))
                p.closeSubpath()
            }, stroke: .current, strokeWidth: 1.4),
        Element(path: Path { p in
                p.move(to: CGPoint(x: 9, y: 12))
                p.addCurve(to: CGPoint(x: 12, y: 15), control1: CGPoint(x: 9, y: 13.6569), control2: CGPoint(x: 10.3431, y: 15))
                p.addCurve(to: CGPoint(x: 15, y: 12), control1: CGPoint(x: 13.6569, y: 15), control2: CGPoint(x: 15, y: 13.6569))
                p.addCurve(to: CGPoint(x: 12, y: 9), control1: CGPoint(x: 15, y: 10.3431), control2: CGPoint(x: 13.6569, y: 9))
                p.addCurve(to: CGPoint(x: 9, y: 12), control1: CGPoint(x: 10.3431, y: 9), control2: CGPoint(x: 9, y: 10.3431))
                p.closeSubpath()
            }, stroke: .accent, strokeWidth: 1.8)
    ])

    static let all: [Icon] = [dashboard, health, visit, quick, results, medication, mind, messages, family, settings]

    static func icon(_ id: String) -> Icon? { all.first { $0.id == id } }
}

/// One icon of the family, at a size, stroked with round caps and joins, its signal dot pulsing only
/// when `animated` and only for a reader who has not asked for reduced motion.
struct MyThusoIcon: View {
    let icon: MyThusoIconsData.Icon
    var size: CGFloat = MyThusoIconsData.size
    var animated = false
    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @State private var pulsing = false

    private var scale: CGFloat { size / MyThusoIconsData.size }

    var body: some View {
        ZStack {
            ForEach(Array(icon.elements.enumerated()), id: \.offset) { _, element in
                element.path
                    .applying(CGAffineTransform(scaleX: scale, y: scale))
                    .stroke(element.stroke.color, style: StrokeStyle(lineWidth: element.strokeWidth * scale, lineCap: .round, lineJoin: .round))
            }
            signal
        }
        .frame(width: size, height: size)
        .accessibilityHidden(true)
    }

    private var signal: some View {
        let r = MyThusoIconsData.Signal.radius * scale
        let rect = CGRect(x: MyThusoIconsData.Signal.center.x * scale - r, y: MyThusoIconsData.Signal.center.y * scale - r, width: r * 2, height: r * 2)
        let live = animated && !reduceMotion
        return ZStack {
            Path(ellipseIn: rect).fill(MyThusoIconsData.Signal.fill.color)
            Path(ellipseIn: rect).stroke(MyThusoIconsData.Signal.stroke.color, lineWidth: MyThusoIconsData.Signal.strokeWidth * scale)
        }
        .scaleEffect(live && pulsing ? MyThusoIconsData.Signal.scaleTo : MyThusoIconsData.Signal.scaleFrom, anchor: UnitPoint(x: MyThusoIconsData.Signal.center.x / MyThusoIconsData.size, y: MyThusoIconsData.Signal.center.y / MyThusoIconsData.size))
        .onAppear {
            guard live else { return }
            withAnimation(ThusoMotion.soft(MyThusoIconsData.Signal.duration / 2).repeatForever(autoreverses: true)) { pulsing = true }
        }
        .onChange(of: live) { _, isLive in
            if isLive { withAnimation(ThusoMotion.soft(MyThusoIconsData.Signal.duration / 2).repeatForever(autoreverses: true)) { pulsing = true } }
            else { withAnimation(nil) { pulsing = false } }
        }
    }
}
