// Generated by scripts/emit-passport.mjs from packages/catalog/passport.json.
// Do not edit by hand — run `npm run passport`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// No reference range appears below, and none is coming from here. What a reading is judged against
// lives in packages/catalog/records.json and reaches this app as RecordsData; a copy beside the
// reading it flags is how a number that decides whether a doctor sees something comes to have two
// answers.
//
// Fictional patient, invented readings, nothing stored and nothing sent.

import Foundation

enum PassportData {
    struct Holder { let name: String; let passportId: String; let issuedBy: String }
    struct Reviewer { let name: String; let registration: String }
    struct Readings { let dayOffset: Int; let values: [String: Double]; let note: String? }
    struct Review { let assessment: String; let plan: String; let next: String; let reviewedDayOffset: Int }
    struct Document { let name: String; let kind: String; let dayOffset: Int; let reviewed: Bool; let opens: String? }
    struct Device: Identifiable { let id: String; let name: String; let offeredOn: [String]; let sheet: String; let withdraw: String }
    struct Refusal: Identifiable { let id: String; let sentence: String }

    static let holder = Holder(name: "Lerato Molefe", passportId: "TH-2048-3920",
                               issuedBy: "Akhanya IT Innovations")
    static let reviewer = Reviewer(name: "Dr Lerato Khumalo", registration: "HPCSA MP0612885")

    /* Four home visits over three months, oldest first. Every day is an offset from today rather
       than a date, because the charts these draw were once literal arrays labelled '12 Aug'
       through '4 Sep' — right the week somebody typed them and a year wrong by the next winter.
       The third set is the one worth opening: a systolic above its upper reference on the day a
       dose was missed, with the reason the person gave for it at the visit. */
    static let readingSets: [Readings] = [
        Readings(dayOffset: -87,
                 values: ["systolic": 128, "diastolic": 82, "pulse": 76, "respiratory": 16, "temperature": 36.7, "oxygen": 98, "glucose": 5.6],
                 note: nil),
        Readings(dayOffset: -59,
                 values: ["systolic": 134, "diastolic": 86, "pulse": 74, "respiratory": 16, "temperature": 36.6, "oxygen": 98, "glucose": 6.1],
                 note: nil),
        Readings(dayOffset: -31,
                 values: ["systolic": 141, "diastolic": 90, "pulse": 80, "respiratory": 18, "temperature": 37, "oxygen": 97, "glucose": 5.4],
                 note: "Missed medication"),
        Readings(dayOffset: -3,
                 values: ["systolic": 136, "diastolic": 85, "pulse": 72, "respiratory": 16, "temperature": 36.8, "oxygen": 98, "glucose": 5.2],
                 note: nil)
    ]

    /* The four the trends screen leads with. Seven charts on one phone screen is a wall; these are
       the four a person with a blood-pressure diagnosis actually watches, and the rest are one tap
       below in the same shape. The other three are not listed here — they are whatever the
       observation contract holds that is not one of these, so a reading added to records.json
       appears on the second screen without anybody editing this file. */
    static let headlineMeasures = ["systolic", "diastolic", "pulse", "glucose"]

    static let lastReview = Review(
        assessment: "Blood pressure is coming down again. The reading a month ago was above the reference range on the day a dose was missed; this one is inside it. Nothing here needs an urgent appointment.",
        plan: "Keep taking the medicine at the same time each morning. Bring the boxes to the next visit so the nurse can check what is left.",
        next: "A nurse visit in about four weeks, or sooner if you feel unwell.",
        reviewedDayOffset: -2)

    /* What the record holds, rather than what a screen offers to generate. None of these carries a
       date of its own: each is issued out of the visit the last reading set was taken at, so a
       document cannot claim a day on which no visit happened. Every one is marked reviewed by the
       doctor named above, because a clinical document nobody signed is not a document. */
    static let documents: [Document] = [
        Document(name: "Visit summary", kind: "Clinical summary", dayOffset: -3,
                 reviewed: true, opens: nil),
        Document(name: "Laboratory results", kind: "Pathology report", dayOffset: -3,
                 reviewed: true, opens: "Laboratory order LAB-0023"),
        Document(name: "Medical certificate", kind: "Certificate", dayOffset: -3,
                 reviewed: true, opens: nil)
    ]

    /* The integrations the passport offers and cannot open. Each owes the same three answers
       before a person could sensibly say yes: exactly what would be read, exactly what would not,
       and the fact that none of it is connected. The third is not written here — it is the devices
       capability's notice in packages/catalog/capabilities.json, rendered rather than restated.
       What is here is the part no other contract holds: how a particular operating system asks the
       question, and where a person goes to take the answer back. Apple Health is the iPhone's
       store and Health Connect is Android's, so each native app offers one of them; the web screen
       is read on both phones and offers all three. */
    static let devices: [Device] = [
        Device(id: "apple-health", name: "Apple Health", offeredOn: ["web", "ios"],
               sheet: "iOS asks you, on your own phone, one reading type at a time. MyThuso never sees the question and never sees a type you decline.",
               withdraw: "Health → Sharing → Apps, on your phone. Withdrawing it stops new readings; it does not remove what is already on your record."),
        Device(id: "health-connect", name: "Health Connect", offeredOn: ["web", "android"],
               sheet: "Health Connect asks you, on your own phone, one reading type at a time. MyThuso never sees the question and never sees a type you decline.",
               withdraw: "Health Connect → App permissions, on your phone. Withdrawing it stops new readings; it does not remove what is already on your record."),
        Device(id: "thuso-kit", name: "Thuso Kit", offeredOn: ["web", "ios", "android"],
               sheet: "The kit is paired at a visit, by the nurse, in front of you. Nothing pairs itself and nothing pairs while you are not there.",
               withdraw: "Ask the nurse to unpair it, or unpair it from this screen once the kit is connected. An unpaired instrument sends nothing.")
    ]
    static func devicesOn(_ platform: String) -> [Device] { devices.filter { $0.offeredOn.contains(platform) } }

    /* The sentences the passport says out loud rather than merely obeys. "Nothing on this screen
       interprets a reading for you" is the one that matters: a trends screen that says which way a
       line is going has almost interpreted it, and a screen that only *behaves* carefully still
       reads as a verdict. */
    static let refusals: [Refusal] = [
        Refusal(id: "no-interpretation", sentence: "Nothing on this screen interprets a reading for you. What a number means for a particular person is a clinical judgement, and MyThuso does not make one."),
        Refusal(id: "protected-not-by-permission", sentence: "These are released by you, entry by entry, and a permission sheet cannot hand one over on your behalf."),
        Refusal(id: "asks-for-nothing-else", sentence: "A permission it does not need is a permission it does not ask for."),
        Refusal(id: "nothing-goes-back", sentence: "Readings would come in. Your record would not go out to a store you did not choose to put it in."),
        Refusal(id: "reading-types-only", sentence: "MyThuso asks for reading types and nothing else.")
    ]
    static func refusal(_ id: String) -> String { refusals.first { $0.id == id }?.sentence ?? "" }
}
