// Generated by scripts/emit-passport-sharing.mjs from packages/catalog/passport-sharing.json, packages/catalog/passport-gateway.json,
// packages/catalog/consent.json and packages/catalog/records.json.
// Do not edit by hand — run `npm run passport-sharing`. The build fails if this file and its sources disagree.
//
// Nothing here is connected. A card drawn from this reaches no responder, and the log is synthetic.

import Foundation

enum PassportSharingData {
    struct LogEntry: Identifiable {
        let id: String; let dayOffset: Int; let time: String; let who: String; let requesterRole: String
        let action: String; let purpose: String?; let outcome: String; let outcomeLabel: String
        let reason: String; let breakGlass: Bool; let reviewDueInHours: Int?
    }
    struct Exclusion: Identifiable { let id: String; let sentence: String }

    /* The Record settings a card and a link are made with. A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here. */
    static let cardLifetimeDays = 30
    static let cardMaxUses = 10
    static let linkLifetimeDays = 7
    static let linkMaxUses = 5
    static let linkDefaultScope = "emergency-summary"
    static let settingsNote = "A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here."
    /* No card outlives the longest a consent grant may run, the founder's decision of 2026-09-14. */
    static let grantCeilingDays = 90

    /* What a card opens: the category that opens the emergency summary, and the summary's own categories. */
    static let emergencyScope = "emergency-card"
    static let emergencySummaryNames: [String] = ["Allergies", "Prescriptions"]
    static let qrPayload = "MYTHUSO PREVIEW. NOT CONNECTED TO ANY RESPONDER. NOTHING OPENS. CARD {code}"
    static let codeAlphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    static let codeGroups = 3
    static let codeGroupLength = 4

    /* The grant the preview card rides on. */
    static let cardRecipient = "Next of kin"
    static let cardGrantEndsInDays = 60

    enum Card {
        static let route = "Your emergency card"
        static let eyebrow = "Health Passport"
        static let title = "Your emergency card."
        static let intro = "A card you can show or print. It opens your emergency summary — allergies and the medicines you take — and nothing else."
        static let preview = "A preview. This card is not connected to any responder, ambulance or hospital. Nobody who scans it reaches your record, and no link was sent anywhere."
        static let ridesOn = "It rides on your grant to {recipient}, which ends {when}."
        static let noGrant = "An emergency card needs a grant whose scope includes the emergency card. You have none yet."
        static let make = "Make my card"
        static let code = "Card code"
        static let qrLabel = "A QR code for this preview card. It reads as a sentence saying the card is not connected to anything."
        static let ends = "Ends {when}"
        static let opens = "Opens {uses} times at most"
        static let print = "Print this card"
        static let opensOnly = "Opens only {categories}"
        static let sealedNever = "Nothing sealed is ever on this card."
    }
    enum Log {
        static let route = "Who opened your record"
        static let eyebrow = "Health Passport"
        static let title = "Who opened your record."
        static let intro = "Every access to your Health Passport, allowed or refused, including links you made being opened and anybody breaking the glass, with the reason the log carries."
        static let preview = "A preview. These entries are synthetic, and the ones you add here are kept in this tab's memory. The Passport service keeps the real log as a hash chain you can check."
        static let chain = "In the Passport service each entry is chained to the one before it, so an entry altered or removed breaks every one after it."
        static let empty = "Nothing has opened your record."
        static let newest = "Newest first"
        static let breakGlass = "Break-glass"
        static let reviewDue = "Reviewed by the governance board by {when}"
        static let purpose = "For {purpose}"
    }

    static let accessLog: [LogEntry] = [
        LogEntry(id: "preview-0", dayOffset: -25, time: "19:20", who: "You", requesterRole: "patient",
                 action: "Linked a hospital number to your record", purpose: nil, outcome: "granted", outcomeLabel: "Allowed",
                 reason: "Linked by the patient in their own session. A message carrying this number may now be matched to this record, and to no other.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-1", dayOffset: -21, time: "08:02", who: "You", requesterRole: "patient",
                 action: "Made a grant", purpose: nil, outcome: "granted", outcomeLabel: "Allowed",
                 reason: "Opened by the patient in their own session.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-2", dayOffset: -20, time: "10:41", who: "Next of kin", requesterRole: "next-of-kin",
                 action: "Opened the emergency summary", purpose: "emergency", outcome: "granted", outcomeLabel: "Allowed",
                 reason: "Opened under a consent grant, for the purpose it names.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-3", dayOffset: -14, time: "16:18", who: "Caregiver or delegate", requesterRole: "caregiver",
                 action: "Opened an entry", purpose: "treatment", outcome: "refused", outcomeLabel: "Refused",
                 reason: "Refused: this grant has expired. Grants expire by default, and a new one has to be asked for.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-4", dayOffset: -12, time: "22:14", who: "Synthetic General Hospital", requesterRole: "synthetic-general-hospital",
                 action: "A hospital said you were admitted", purpose: "treatment", outcome: "granted", outcomeLabel: "Allowed",
                 reason: "Sent by a registered development partner as an HL7 v2 message, and matched to this record by a hospital number the patient linked.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-5", dayOffset: -10, time: "11:02", who: "Synthetic General Hospital", requesterRole: "synthetic-general-hospital",
                 action: "A hospital said you were discharged", purpose: "treatment", outcome: "granted", outcomeLabel: "Allowed",
                 reason: "Sent by a registered development partner as an HL7 v2 message, and matched to this record by a hospital number the patient linked.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-6", dayOffset: -9, time: "02:37", who: "The dispatch desk", requesterRole: "dispatch-desk",
                 action: "Broke the glass", purpose: "emergency", outcome: "granted", outcomeLabel: "Allowed",
                 reason: "Break-glass: the patient is unresponsive and cannot consent.", breakGlass: true, reviewDueInHours: 24),
        LogEntry(id: "preview-7", dayOffset: -6, time: "09:12", who: "Assigned MyThuso doctor", requesterRole: "doctor-assigned",
                 action: "Looked through entries", purpose: "treatment", outcome: "granted", outcomeLabel: "Allowed",
                 reason: "Opened under a consent grant, for the purpose it names.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-8", dayOffset: -6, time: "09:13", who: "Assigned MyThuso doctor", requesterRole: "doctor-assigned",
                 action: "Opened an entry", purpose: "billing", outcome: "refused", outcomeLabel: "Refused",
                 reason: "Refused: the purpose of this request is not the purpose the patient granted.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-9", dayOffset: -4, time: "11:30", who: "You", requesterRole: "patient",
                 action: "Made a share link", purpose: nil, outcome: "granted", outcomeLabel: "Allowed",
                 reason: "Opened by the patient in their own session.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-10", dayOffset: -3, time: "14:05", who: "Assigned MyThuso doctor", requesterRole: "doctor-assigned",
                 action: "Opened a share link", purpose: "treatment", outcome: "granted", outcomeLabel: "Allowed",
                 reason: "Opened through a share link the patient made, for the purpose its grant names, and counted against its uses.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-11", dayOffset: -2, time: "09:40", who: "Synthetic Pathology Laboratory", requesterRole: "synthetic-pathology-laboratory",
                 action: "A laboratory sent a result", purpose: "diagnostics", outcome: "refused", outcomeLabel: "Refused",
                 reason: "Refused: the patient segment carries more than the patient's identifier — a name, a date of birth, an address, a phone number or another field the Passport has no consent basis to store. Nothing from this message was stored.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-12", dayOffset: -2, time: "10:05", who: "Synthetic Pathology Laboratory", requesterRole: "synthetic-pathology-laboratory",
                 action: "A laboratory sent a result", purpose: "diagnostics", outcome: "granted", outcomeLabel: "Allowed",
                 reason: "Sent by a registered development partner as an HL7 v2 message, and matched to this record by a hospital number the patient linked.", breakGlass: false, reviewDueInHours: nil),
        LogEntry(id: "preview-13", dayOffset: -1, time: "07:55", who: "Assigned MyThuso doctor", requesterRole: "doctor-assigned",
                 action: "Opened a share link", purpose: "treatment", outcome: "refused", outcomeLabel: "Refused",
                 reason: "Refused: this link has been opened as many times as it may be. A new one has to be asked for.", breakGlass: false, reviewDueInHours: nil)
    ]

    static let exportExclusions: [Exclusion] = [
        Exclusion(id: "sealed-unless-ticked", sentence: "Entries in a sealed category are left out unless you tick that category in by name."),
        Exclusion(id: "marked-private", sentence: "Entries you marked private are left out. You can read them in your own session."),
        Exclusion(id: "break-glass-notes", sentence: "The notes a clinician wrote when breaking the glass are left out. The reason they chose is already in your access log."),
        Exclusion(id: "access-log", sentence: "Your access log is left out. Read it where the chain can show whether it has been altered."),
        Exclusion(id: "keys-and-tags", sentence: "The keys your record is encrypted under, and the tags that hide which category an entry is filed in, are left out."),
        Exclusion(id: "grants-and-links", sentence: "The grants and links you made are left out. They are permissions over your record rather than your record."),
        Exclusion(id: "partner-messages", sentence: "Admissions, discharges and results a hospital or a laboratory sent by HL7 are left out of the export and out of any link. You can read them in your own session, and your access log shows each message.")
    ]
    static let exportStepUp = "The Health Passport has no second factor of its own, so this export is not stepped up. The identity service's step-up does not reach the Passport, and nothing here pretends it does."
}
