// Generated by scripts/emit-patient-pages.mjs from packages/catalog/patient-pages.json.
// Do not edit by hand — run `npm run patient-pages`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// The eight pages of the full Lovable export’s Gap 2 and their hub. General information, gated:
// the review notice is shown beside every screen until a clinician has signed, and the symptom
// checker and risk assessment inherit the screening capability’s block.

import SwiftUI

enum PatientPagesData {
    static let version = 1

    enum Review {
        /// Nil until a registered clinician has read and signed the pages' health material.
        static let reviewedBy: String? = nil
        static let notice = "This page carries general health information that no registered clinician has signed yet. Your nurse's advice comes first."
    }

    enum Hub {
        static let opens = "Your health"
        static let heading = "Your health, in one place."
        static let lead = "Eight pages the design asked for and the build did not have. Each says plainly what it holds today and what it is waiting for."
        static let shortcutTitles = [
            "Symptom checker",
            "Risk assessment",
            "Health library",
            "Health timeline",
            "Vaccinations",
            "Community support",
            "Nutrition",
            "Reminders"
        ]
    }

    enum Screen: String, CaseIterable {
        case symptomChecker = "Symptom checker"
        case riskAssessment = "Risk assessment"
        case healthLibrary = "Health library"
        case healthTimeline = "Health timeline"
        case vaccinations = "Vaccinations"
        case community = "Community support"
        case nutrition = "Nutrition"
        case reminders = "Reminders"

        var opening: String {
            switch self {
            case .symptomChecker: return "Opening the symptom checker."
            case .riskAssessment: return "Opening the risk assessment."
            case .healthLibrary: return "Opening the health library."
            case .healthTimeline: return "Opening your health timeline."
            case .vaccinations: return "Opening vaccinations."
            case .community: return "Opening community support."
            case .nutrition: return "Opening nutrition."
            case .reminders: return "Opening reminders."
            }
        }
    }

    static let refusals: [String] = [
        "Nothing here diagnoses, scores or triages you. A diagnosis is a clinician's, and screening stays blocked until a model, a vendor and a licence exist.",
        "No screen shows a number this tree's contracts do not hold. Where a figure would go, a written empty state says what is missing and why.",
        "The library, nutrition and vaccination material is general information with its source beside it — never advice about you. Your nurse's advice comes first.",
        "The emergency words are read before any of it. An emergency answer ends the screen and opens the emergency pathway with 10177 first."
    ]
}
