// Generated by scripts/emit-plans.mjs from packages/catalog/mom-plans.json, packages/catalog/business-model.json and Money's settings in packages/catalog/money.json.
// Do not edit by hand — run `npm run plans`. The build fails if this file and its sources disagree,
// so an edit here is lost rather than merely wrong.
//
// Every monthly price a plans screen shows is below, and none is typed in a screen. MyThuso for Mom
// has three, from the Master Blueprint v4, and its business-model row has none of its own. Each
// inclusion names the capability it depends on; the sentence shown beside it is read from the
// generated capabilities table, so it disappears when that capability is connected and not before.

import Foundation

extension Plans {
    /// The business model's subscriptions. A row with `tiered` set is priced by its tiers below.
    static let subscriptions: [PlanSubscription] = [
        .init(id: "chronic", name: "Chronic Routine", price: 199, phase: 2,
              includes: "Monthly visit, AI-screened vitals, doctor review, script collection, medicine delivery, adherence nudges", tiered: false),
        .init(id: "planning", name: "Family Planning Plan", price: 99, phase: 2,
              includes: "Injection every 2–3 months, reminders, discreet booking", tiered: false),
        .init(id: "mom", name: "MyThuso for Mom", price: nil, phase: 2,
              includes: "A nurse for a parent every month, fortnight or week, paid for by their children", tiered: true),
        .init(id: "senior", name: "Thuso Senior (Gogo)", price: 699, phase: 3,
              includes: "Weekly elderly visit, medication management, fall-risk check, family report", tiered: false),
        .init(id: "recover", name: "Thuso Recover", price: nil, phase: 3,
              includes: "Post-discharge visits for 2–6 weeks; sold to patients and hospitals", tiered: false),
        .init(id: "alert", name: "Thuso Alert", price: 79, phase: 4,
              includes: "Panic button dispatching nearest nurse and ambulance partner", tiered: false),
        .init(id: "cover", name: "Thuso Cover", price: 149, phase: 4,
              includes: "Insurer-backed visit allowance plus funeral cover", tiered: false)
    ]

    // MyThuso for Mom as Money's settings read it by default. Neither app has an admin surface:
    // plan-family-name: Decided by the Founder. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    // tiers-stack: A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    // plus-urgent-callouts: A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    // tier-name-essential: Decided by the Founder. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    // visit-reports-whatsapp: A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    // tier-name-plus: Decided by the Founder. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    // tier-name-premium: Decided by the Founder. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    // priority-sos-wording: A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    static let mom = MomPlan(
        id: "mom",
        name: "MyThuso for Mom",
        payerHeadline: "A nurse for your parent, paid for by you.",
        payerStatement: "The person who pays is usually not the patient. It is the son or daughter in the city, looking after a parent who cannot easily get to a clinic, with the same nurse every time and a report after every visit.",
        tiers: [
            .init(id: "essential", name: "Essential", price: 399, phase: 2, cadence: "A nurse every month",
                  inherits: nil, includes: [
                .init(id: "monthly-visit", text: "A nurse visit every month: blood pressure, glucose, weight, a medicine check and how they are doing", capability: "booking",
                      device: nil, detail: nil),
                .init(id: "medicine-collection", text: "Chronic medicine collected from the CCMDD pick-up point or the clinic, with their authorisation, and delivered", capability: "medicine-collection",
                      device: nil, detail: nil),
                .init(id: "visit-report", text: "A report and a photo after every visit, in the app", capability: "messaging",
                      device: nil, detail: nil)
            ]),
            .init(id: "plus", name: "Plus", price: 749, phase: 3, cadence: "A nurse every fortnight",
                  inherits: "Everything in Essential", includes: [
                .init(id: "fortnightly-visit", text: "A nurse visit every fortnight", capability: "booking",
                      device: nil, detail: nil),
                .init(id: "quarterly-screening", text: "A screening every quarter", capability: "booking",
                      device: nil, detail: nil),
                .init(id: "doctor-review", text: "A registered doctor reviews every visit", capability: "doctor-review",
                      device: nil, detail: nil),
                .init(id: "band", text: "A Thuso Band with an SOS button", capability: "thuso-devices",
                      device: "band", detail: nil),
                .init(id: "urgent-call-out", text: "One urgent nurse call-out a month", capability: "emergency",
                      device: nil, detail: nil)
            ]),
            .init(id: "premium", name: "Premium", price: 1299, phase: 3, cadence: "A nurse every week",
                  inherits: "Everything in Plus", includes: [
                .init(id: "weekly-visit", text: "A nurse visit every week", capability: "booking",
                      device: nil, detail: nil),
                .init(id: "home-station", text: "A Thuso Home station, for video calls with the doctor and the family", capability: "thuso-devices",
                      device: "home", detail: nil),
                .init(id: "pill-dispenser", text: "A pill dispenser", capability: "thuso-devices",
                      device: "home", detail: nil),
                .init(id: "carer-hours", text: "Carer hours for bathing and meals", capability: "carers",
                      device: nil, detail: nil),
                .init(id: "priority-sos", text: "Priority SOS", capability: "emergency",
                      device: nil, detail: "When you press SOS, a person at our desk picks up first among calls of the same urgency, and we tell your family straight away. It never means being seen ahead of someone more unwell."),
                .init(id: "family-dashboard", text: "A family dashboard", capability: "clinical-records",
                      device: nil, detail: nil)
            ])
        ],
        addOnsStatement: "These have been named and not priced, so none of them shows a price and none can be added.",
        addOns: [
            .init(id: "extra-carer-hours", name: "Extra carer hours"),
            .init(id: "physiotherapy", name: "Physiotherapy"),
            .init(id: "doctor-home-visit", name: "A doctor's home visit"),
            .init(id: "gift-a-visit", name: "Gift a visit"),
            .init(id: "second-parent", name: "A second parent, at a discount")
        ],
        splittingStatement: "Brothers and sisters would split the bill between them in the app. No share has been set, and nothing is split today.",
        splittingCapability: "payments",
        refusals: [
            .init(id: "a-device-that-does-not-exist-is-not-included", sentence: "No plan counts a device as included while the device does not exist. Thuso Band and Thuso Home have not been built, and every plan that names one says so beside it."),
            .init(id: "no-plan-buys-a-place-ahead", sentence: "No plan buys a place ahead of somebody else. When two people need a nurse urgently, the one who is more unwell is seen first, whatever either of them pays."),
            .init(id: "a-plan-is-not-medical-aid", sentence: "MyThuso for Mom is not medical aid, and no medical scheme pays for it. It pays for no hospital care, test or medicine beyond collecting what has already been prescribed."),
            .init(id: "paying-is-not-seeing", sentence: "Paying for your parent's plan does not let you see their health record. The report and the photo after a visit reach you only if your parent has agreed, and they can stop them.")
        ])
}
