// Generated by scripts/emit-teleconsult.mjs from packages/catalog/teleconsult.json.
// Do not edit by hand — run `npm run teleconsult`. The build fails if this file and the source
// disagree, so an edit here is lost rather than merely wrong.
//
// Nobody is named below. A participant carries a roleId into the vetting register and the screen
// resolves the party from it, so the name and the registration number the patient is shown are the
// ones the register holds rather than a second copy of them.
//
// The reasoning that uses this table — which limits a connection state permits, whether an outcome
// may be called a consultation, and which sections of the record it writes — is hand-written in
// Teleconsult.swift and Teleconsult.kt beside it.

import Foundation

extension Teleconsult {
    static let media = MediaPosture(declared: false, state: "never-asked", sentence: "This build has never asked this device for the camera or the microphone. Neither permission is declared, no media of any kind is captured, and no connection is opened. What follows is the design of a consultation, drawn at full size.",
                                    states: [
                                        .init(id: "never-asked", name: "Never asked", detail: "MyThuso has not requested the camera or the microphone on this device. There is nothing to allow and nothing to withdraw, because no question was put to you."),
                                        .init(id: "refused", name: "You said no", detail: "You were asked and you declined. The consultation is offered by voice on your phone line instead, and the refusal is remembered so you are not asked again every time."),
                                        .init(id: "granted", name: "Allowed", detail: "You allowed it for consultations. It is used only while a call is running, and you can take it back in your phone's settings without telling us first.")
                                    ],
                                    whyTheDistinctionMatters: "An app that shows the same screen for “we never asked” and “you refused” is telling you that your answer did not matter. They are different facts and they get different words.")

    static let identity = CallIdentity(patientSideDetail: "The person on the screen should be the doctor the booking named. Before the call opens, MyThuso shows you their name and their HPCSA registration number, read from the vetting record that was checked this morning — not typed into the booking by whoever made it. If the name on screen is not the name here, the call does not start.",
                                       doctorSideDetail: "The doctor asks for the six-digit visit code in the patient's own app — the same code a nurse is asked for at the door, for the same reason: a code the patient holds is a check the clinician cannot do without them. It changes for every visit and expires when the visit ends.",
                                       failure: "That code doesn’t match this visit. Call the Control Tower before continuing.",
                                       whyOneMechanism: "There is one identity check in MyThuso and this is it. A second mechanism invented for video would be a second thing to get wrong, and the one a patient had already learned would stop being the one that counts.")

    /* A participant is a role, not a person. The name on the screen comes from the vetting register
       through roleId, so the patient reads the registration the reviewer verified. */
    static let participants: [CallParticipant] = [
        .init(id: "patient", name: "The patient", roleId: nil, place: "At the address",
              sees: "The doctor, and anybody else on this list", hears: "Everyone on the call and everyone in the room", essential: true, mayBeAskedToLeave: false,
              consentQuestion: nil, ifDeclined: nil, note: "The consultation is theirs. Everything below is a question put to them, not a setting configured for them."),
        .init(id: "doctor", name: "The doctor", roleId: "doctor", place: "On video, from somewhere else",
              sees: "Whatever the patient's camera is pointed at, and nothing else in the house", hears: "Everything said in the room", essential: true, mayBeAskedToLeave: false,
              consentQuestion: "May this doctor see you and treat you on this call today?", ifDeclined: "There is no consultation. The call does not open, the booking is closed as declined, and the only thing written into your record is that you were asked and said no.", note: "The one person who cannot be asked to step out, because asking them to leave is the same as ending the call — and that is offered as its own button rather than dressed up as a roster change."),
        .init(id: "nurse", name: "The nurse", roleId: "nurse", place: "In the room with the patient",
              sees: "The patient, the room, and the doctor on the screen", hears: "Everything said in the room and on the call", essential: false, mayBeAskedToLeave: true,
              consentQuestion: "The nurse is in the room with you and will hear everything that is said. May she stay?", ifDeclined: "The nurse steps outside and waits. The consultation goes ahead without her, and the doctor is told plainly that there will be no examination and no readings taken during the call — because the only pair of hands in the room has just left it.", note: "This is the case a private doctor's appointment does not have, and the one most video-consultation products have no words for at all."),
        .init(id: "guardian", name: "A parent or guardian", roleId: "guardian", place: "In the room with the patient",
              sees: "The patient, the room, and the doctor on the screen", hears: "Everything said in the room and on the call", essential: false, mayBeAskedToLeave: true,
              consentQuestion: "Your guardian is in the room and will hear everything. May they stay?", ifDeclined: "Where the patient may consent to their own treatment, the guardian leaves the room and the consultation continues. Where they may not, the consultation is stopped and rebooked rather than held in private with a child who cannot consent to it.", note: "A guardian's authority to be present is verified in the vetting register, and it is still a question put to the patient rather than an answer given on their behalf."),
        .init(id: "interpreter", name: "An interpreter", roleId: nil, place: "On the call, from somewhere else",
              sees: "Whatever the doctor sees", hears: "Everything said in the room and on the call", essential: false, mayBeAskedToLeave: true,
              consentQuestion: "An interpreter is on this call and will hear everything you tell the doctor. May they stay?", ifDeclined: "The interpreter leaves the call. If you and the doctor do not share a language, the consultation is rebooked with a different interpreter — it is not continued in a language you did not choose, because a consultation you cannot follow is not consultation.", note: "An interpreter hears the whole consultation, including the parts a patient would not have said in front of a neighbour. They are named, they are bound by the same confidentiality as the clinicians, and they are consented to like anybody else.")
    ]

    /* Consent to each person's presence, separately, and every one of them revocable in the middle
       of the call — which is the only kind of consent worth asking for. */
    static let consent: [ConsentItem] = [
        .init(id: "consult", participant: "doctor", required: true, revocable: true,
              revokedMidCall: "The call ends at the moment it is said. It is not held open to finish the notes, and the notes are finished — if at all — from what was already said."),
        .init(id: "nurse-present", participant: "nurse", required: false, revocable: true,
              revokedMidCall: "The nurse steps out, and the doctor is told the room no longer has a clinician in it. Anything that needed hands is rebooked."),
        .init(id: "guardian-present", participant: "guardian", required: false, revocable: true,
              revokedMidCall: "The guardian leaves the room. Where the patient cannot consent for themselves, the call is stopped instead."),
        .init(id: "interpreter-present", participant: "interpreter", required: false, revocable: true,
              revokedMidCall: "The interpreter leaves the call. If the doctor and the patient cannot understand one another, the consultation is stopped and rebooked."),
        .init(id: "record-the-call", participant: nil, required: false, revocable: true,
              revokedMidCall: "Recording stops at the moment it is said, and what was captured before that moment is destroyed rather than kept for the part that was consented to. A recording that outlives its consent is a recording nobody gave.")
    ]

    static let recording = RecordingPolicy(offeredInPreview: false, decision: "This preview does not offer recording, and it does not offer a switch for it either.",
                                           why: "Consent to a consultation is not consent to a recording, and the honest way to hold that apart is to ask twice. But this build has no microphone permission, no camera permission and nowhere to put a recording, so a recording switch here would be a control that cannot do what it says — and a patient who is taught to tick it in a preview has been taught to tick it. A refusal is easier to design honestly than a promise: what the screen does instead is say what a recording would be for, who could open it, how long it would live and how it would be asked for, so that the design can be argued with before anything can be captured.",
                                           instead: [
                                            "The written consultation record is the record. It is the same structure a nurse's visit and a doctor's review write into, and it is what a later clinician actually reads.",
                                            "Who was in the room, and what each of them was consented to, is written into the record with the consultation — because “was anyone else listening” is a question a patient may ask a year later and deserve an answer to.",
                                            "A patient who wants a copy of what was decided is given the written record, which is legible, correctable and does not carry the sound of their own voice."
                                           ],
                                           whenItExists: .init(askedSeparately: "It is a second question, on its own screen, after consent to the consultation and before the call opens. It is never a checkbox underneath the first one, because a checkbox underneath the first one is answered by the momentum of the first one.",
                                                               refusingIsCostless: "Saying no changes nothing at all about the care you receive. The consultation goes ahead, with the same doctor, at the same time, for the same money, and nobody is told you refused.",
                                                               whileRecording: "A red bar across the top of the screen for the whole time it runs, on every participant's device, saying who started it and that it can be stopped. It cannot be minimised, dismissed or hidden behind anything.",
                                                               whoMayView: [
                                                                "You, from your own account, whenever you want",
                                                                "The doctor who held the consultation, under their own registration",
                                                                "Nobody else without a written request that appears in your access history before it is granted"
                                                               ],
                                                               keptForDays: 30,
                                                               afterwards: "Destroyed after 30 days, automatically, whether or not anybody has watched it. The written record is what is kept under the clinical retention schedule — a recording is evidence of a conversation, not the record of a decision, and keeping it for years would make every consultation a permanent tape of somebody's worst afternoon."))

    static let clinicalLimits: [ClinicalLimit] = [
        .init(id: "take-history", name: "Take a history", needs: "sound", detail: "What the patient reports, in their own words. This is most of a consultation and it survives a bad line."),
        .init(id: "see-the-patient", name: "See how the patient looks", needs: "video", detail: "Breathing, colour, distress, whether they can finish a sentence. A doctor who cannot see this says so rather than assuming it is fine."),
        .init(id: "assess-visible", name: "Assess something visible", needs: "video", detail: "A rash, a wound, swelling, a drooping face. On a poor picture this is refused rather than guessed at, because a wound seen through four frames a second is a wound not seen."),
        .init(id: "read-a-document", name: "Read a label or a document", needs: "video", detail: "A pill box, a clinic card, a discharge letter held up to the camera."),
        .init(id: "direct-the-nurse", name: "Ask the nurse to examine", needs: "nurse", detail: "The doctor asks; the nurse examines and reports. The finding is the nurse's, recorded under her name, and the doctor never writes it up as their own examination."),
        .init(id: "conclude", name: "Reach and sign a decision", needs: "sound", detail: "A decision needs enough of the above to stand behind, and the doctor says in the record which of it they had. A decision reached on sound alone is written as a decision reached on sound alone.")
    ]

    /* Ordered by fidelity, and what each one permits is a subset of the one above it. The build
       fails if that stops being true, because a degraded line that permits more than a good one is
       a screen telling a doctor they may conclude something they may not. */
    static let connection: [ConnectionState] = [
        .init(id: "video", name: "Video and sound", fidelity: 3, patientSees: "The doctor, and yourself in the corner. Everything is working.",
              doctorSees: "The patient, and the room behind them.", permits: ["take-history", "see-the-patient", "assess-visible", "read-a-document", "direct-the-nurse", "conclude"], note: "The state everything else is measured against, and the rarest of the four on a South African mobile network at five in the afternoon."),
        .init(id: "poor", name: "The connection is poor", fidelity: 2, patientSees: "The picture is breaking up. You can still be heard. The doctor knows.",
              doctorSees: "The picture is breaking up at the patient's end. Do not rely on what you can see.", permits: ["take-history", "see-the-patient", "direct-the-nurse", "conclude"], note: "A first-class state with its own screen, not a toast. Both ends are told the same thing at the same time, and the doctor is offered the drop to sound only rather than left to fight the picture. Something looked at through a breaking picture is not something examined, so assessing a wound and reading a label are withdrawn here — the doctor asks the nurse, or asks the patient to be seen."),
        .init(id: "audio", name: "Sound only", fidelity: 1, patientSees: "Sound only. This uses far less of your data and works on a weak signal. It is a normal way to hold a consultation.",
              doctorSees: "Sound only. You are not seeing this patient. Anything you record about how they look is the nurse's finding or the patient's own words.", permits: ["take-history", "direct-the-nurse", "conclude"], note: "Designed for, not fallen back to. Bandwidth in South Africa is a constraint on most of the country most of the time, and a product that treats sound as a failure state is a product that works in Sandton."),
        .init(id: "dropped", name: "The call dropped", fidelity: 0, patientSees: "The call has dropped. Stay where you are — the doctor is calling you back. You do not have to do anything.",
              doctorSees: "The line dropped at the patient's end. Do not close this encounter. Call back, then call the number on the booking.", permits: [], note: "A clinical event, not a network event. The encounter stays open, nothing about it is concluded, and the screen at both ends says the same thing about whose job it is to fix it.")
    ]

    static let reconnect = Reconnect(holdSeconds: 90, attempts: 3,
                                     whoCallsWhom: "The doctor calls back. The patient does nothing, and is told they do not have to — a person who has just lost signal is the person least able to re-establish it, and asking them to redial makes the failure their fault.",
                                     duringTheHold: "The encounter stays open on the doctor's screen for the whole hold, and cannot be closed as finished while it is running. The patient's screen counts the same seconds down, so neither of them is waiting on nothing.",
                                     afterTheHold: "A phone call to the number on the booking, on the ordinary telephone network, which works where data does not.",
                                     ifUnreachable: "The encounter is closed as interrupted and not resumed, the patient is offered the next available slot without losing their place, and nothing is charged. A note goes to the Control Tower, because three of these from one address in a week is a coverage problem rather than three unlucky patients.",
                                     nurseInTheRoom: "If a nurse is in the room she stays with the patient for the whole hold, tells them what is happening, and does not leave the house on the assumption that the call will come back. If the patient was unwell enough for the doctor to be worried before the line dropped, she escalates on the nurse's own pathway rather than waiting.",
                                     whyNotLonger: "Ninety seconds is long enough for a network to recover and short enough that nobody sits looking at a spinner wondering whether they have been forgotten. After it, a person tells them what is happening.")

    /* The 'writes' list names sections of the consultation record in packages/catalog/records.json. An
       outcome that is not a consultation cannot name the assessment or the plan, and the build
       fails if one does — that is the whole invariant of this feature, held as arithmetic rather
       than as a paragraph asking people to be careful. */
    static let outcomes: [EncounterOutcome] = [
        .init(id: "completed", name: "Consultation completed", reachedDecision: true, connectionLost: false,
              countsAsConsultation: true, charged: true, writes: ["reason", "history", "observations", "assessment", "plan", "followup", "notes", "clinician"],
              record: "A signed consultation in the standard structure, attributed to the doctor's HPCSA registration, carrying who was present and what each of them was consented to."),
        .init(id: "resumed", name: "Interrupted, then finished", reachedDecision: true, connectionLost: true,
              countsAsConsultation: true, charged: true, writes: ["reason", "history", "observations", "assessment", "plan", "followup", "notes", "clinician"],
              record: "A signed consultation, and the interruption on the face of it: when the line dropped, how long it was down, and that the doctor confirmed the visit code again before continuing. A break in a consultation is a clinical fact and it is not tidied away."),
        .init(id: "interrupted", name: "Interrupted and not resumed", reachedDecision: false, connectionLost: true,
              countsAsConsultation: false, charged: false, writes: ["reason", "history", "notes", "clinician"],
              record: "An interrupted encounter. It carries who was present, what was said before the line dropped, and the fact that no assessment and no plan were reached. There is no assessment field, no plan field and no signature block, because nobody may sign a decision they did not get to make — and an encounter with a signature on it reads, a year later, exactly like one that finished."),
        .init(id: "never-connected", name: "Never connected", reachedDecision: false, connectionLost: true,
              countsAsConsultation: false, charged: false, writes: ["reason", "clinician"],
              record: "That the appointment was attempted and no connection was ever made. Nothing clinical, because nothing clinical happened."),
        .init(id: "consent-declined", name: "Consent declined", reachedDecision: false, connectionLost: false,
              countsAsConsultation: false, charged: false, writes: ["reason", "clinician"],
              record: "That consent was asked for and not given. A declined consultation is a valid outcome, not a failed one, and the reason is not recorded unless the patient offers it."),
        .init(id: "identity-failed", name: "Identity not confirmed", reachedDecision: false, connectionLost: false,
              countsAsConsultation: false, charged: false, writes: ["reason", "clinician"],
              record: "That the visit code did not match and the consultation did not open. The same refusal as the nurse at the door: it stops, it does not warn and continue."),
        .init(id: "clinician-refused", name: "The clinician may not consult", reachedDecision: false, connectionLost: false,
              countsAsConsultation: false, charged: false, writes: ["reason", "clinician"],
              record: "That the call was not opened because the doctor's standing did not allow it, and the patient was rebooked with a doctor whose registration is current. The patient is told the appointment is moving, and is not told which check failed — a lapsed registration is the doctor's business with their council.")
    ]


    /* How a person reaches a doctor at all. The funding proposal sells no standalone video
       consultation — Thuso Doctor joins a visit, reads what was captured, or takes a booked
       counselling session — so none is invented here. A route names a service id rather than a
       price, because a price lives in packages/catalog/services.json and nowhere else. */
    static let routes: [CallRoute] = [
        .init(id: "joined-visit", name: "The doctor joins the visit", serviceId: nil,
              startedBy: "nurse", detail: "The nurse is at the house and wants a doctor. The call opens inside the visit that is already running, on the nurse's device, with the patient present.", patientWords: "The nurse is calling a doctor about what she has found. You do not pay again for this — it is part of the visit you booked.",
              live: true, phase: 1),
        .init(id: "results-review", name: "A doctor reviews what was captured", serviceId: "screening",
              startedBy: "system", detail: "Vitals, an ECG trace, a wound image or a rapid test were captured at a visit and screened. A doctor on the panel reads them and signs, or does not.", patientWords: "A doctor is reading what the nurse recorded. This is not a call — nobody will phone you unless the doctor wants to speak to you.",
              live: false, phase: 1),
        .init(id: "booked-session", name: "A booked counselling session", serviceId: "mental",
              startedBy: "patient", detail: "The only consultation in MyThuso a person books directly and attends alone. It runs to its full time or it does not run.", patientWords: "This is your session. Nobody else joins it and nothing about it goes to anybody without you saying so.",
              live: true, phase: 3)
    ]
    static let refusedRoute = CallRefusal(id: "doctor-on-demand", sentence: "You cannot call a doctor here. MyThuso sends a nurse to you, and the nurse calls the doctor.")

    /* The wait, said out loud. An app that shows "connecting…" for eleven minutes has lied for ten
       of them; these four states are the truth at each point, and the last one ends the wait with a
       different plan rather than a longer one. */
    static let waitingRoom: [WaitingState] = [
        .init(id: "asked", name: "The nurse has asked for a doctor", patientWords: "The nurse has asked the doctor panel to join. She will stay with you while you wait.", shows: "who-was-asked"),
        .init(id: "waiting", name: "Waiting for a doctor", patientWords: "No doctor is free at this moment. You are next, and the nurse is still here.", shows: "position-and-elapsed"),
        .init(id: "joining", name: "A doctor is joining", patientWords: "Dr {name} is joining now.", shows: "name-and-registration"),
        .init(id: "nobody-came", name: "No doctor was available", patientWords: "No doctor could join within the time this visit can wait. The nurse will finish what she can do and this goes to the panel as a review instead. You are not charged for the call that did not happen.", shows: "what-happens-instead")
    ]
    static let maximumWaitMinutes = 15
    static let whyFifteen = "Long enough for a doctor between consultations to finish one; short enough that a nurse standing in somebody's house is not waiting on a person who is never coming. It is a number in this file so that changing it is a decision, not a deployment."

    /* What may come out of a consultation held over a screen, and what may not. A prescription and
       a medical certificate are legal documents; a video call is not an examination. */
    static let issued: [IssuedDocument] = [
        .init(id: "prescription", name: "A prescription", mayIssue: true,
              condition: "Where the doctor has a record of the patient, and the medicine is one this consultation can responsibly reach.", goesTo: "packages/catalog/dispensing.json — the prescription is dispensed under the Medicines and Related Substances Act 101 of 1965 like any other, and the pharmacist's substitution rules are unchanged by how it was written.", limit: "Never a first prescription for a condition the doctor has not seen assessed. The nurse in the house is the examination; a description down a phone line is not."),
        .init(id: "repeat", name: "A repeat of a chronic authorisation", mayIssue: true,
              condition: "Where an authorisation exists and the review it ends with has actually happened.", goesTo: "The chronic authorisation in packages/catalog/dispensing.json, which ends in a review with the prescribing doctor, in person or by teleconsultation. This is that review.", limit: "A repeat renews what is already authorised. It does not start a medicine, change a dose or extend an authorisation that has run out."),
        .init(id: "referral", name: "A referral", mayIssue: true,
              condition: "Always. A doctor who thinks somebody needs more than MyThuso can give says so.", goesTo: "The patient, and the record.", limit: "A referral is not a booking. MyThuso does not hold an appointment at a hospital and must not imply that it does."),
        .init(id: "certificate", name: "A medical certificate", mayIssue: false,
              condition: "Not from a call. The sick-note visit in the service catalogue is a visit: a nurse examines the patient in person and a doctor reviews what she found.", goesTo: nil, limit: "A certificate says a doctor was satisfied the person could not work. Satisfying a doctor of that over a video call, with nobody in the room, is the thing the HPCSA's telemedicine guidance is most careful about — and it is a question for the HPCSA rather than for this repository. Until it is answered, the answer here is no."),
        .init(id: "sick-leave-extension", name: "An extension of sick leave already certified", mayIssue: false,
              condition: "Not from a call, for the same reason as the certificate it would extend.", goesTo: nil, limit: "Extending a certificate is issuing one.")
    ]

    /* Rendered word for word. A rule paraphrased on one platform is a different promise on that
       platform, which is the whole reason these live in one file. */
    static let rules: [CallRule] = [
        .init(id: "presence-is-consented", title: "Everyone who can hear you is on the list", sentence: "Everyone who can see or hear you is named on this screen, with their role and where they are, before the call opens. Nobody joins a MyThuso consultation without appearing here, and you can ask anyone except the doctor to leave at any moment, without giving a reason."),
        .init(id: "recording-is-separate", title: "Being seen is not being recorded", sentence: "Agreeing to a consultation is not agreeing to a recording. They are two questions asked at two different moments, and saying no to the second costs you nothing: the same doctor, the same appointment, the same price, and nobody is told you refused."),
        .init(id: "dropped-is-not-finished", title: "A dropped call is not a finished one", sentence: "A call that dropped is not a consultation that ended. Until a doctor has reached a decision and signed it, this is an interrupted encounter in your record — it says so in those words, it carries no diagnosis, and it is never charged for."),
        .init(id: "audio-is-not-lesser", title: "Sound only is a consultation", sentence: "Sound only is an ordinary way to be seen in South Africa, not a failure. What changes is not how seriously you are taken but what the doctor is allowed to conclude on their own, and this screen says which of those things they still can."),
        .init(id: "examination-is-attributed", title: "A doctor on a screen examines nothing", sentence: "On a call the doctor examines nobody. Anything felt, measured or looked at closely is the nurse's finding, recorded under her name and her SANC registration — never written up afterwards as the doctor's own examination."),
        .init(id: "no-media-in-this-build", title: "Nothing here is connected", sentence: "MyThuso has never asked this device for the camera or the microphone, and this build declares neither permission. That is not the same as you refusing: no question was put to you, so there is nothing to withdraw."),
        .init(id: "the-nurse-is-the-examination", title: "The nurse in the house is the examination", sentence: "Everything a doctor on a screen concludes rests on somebody who is physically present. That is why MyThuso does not sell a call on its own: the value is not the video, it is the person standing next to the patient with a stethoscope."),
        .init(id: "a-review-is-not-a-consultation", title: "Reading results is not a consultation", sentence: "A doctor reading vitals and signing them is doing a review. It is named a review, recorded as a review, and it becomes a consultation only when a doctor decides somebody should be spoken to — at which point it is charged and recorded as one."),
        .init(id: "a-wait-has-an-end", title: "A wait has an end, and the end is a different plan", sentence: "Fifteen minutes, and then the visit stops waiting. A queue a patient cannot leave is how somebody sits in a chair for an hour being told that a doctor is coming.")
    ]

    static let refusals: [CallRefusal] = [
        .init(id: "silent-observers", sentence: "Nobody sits in on a MyThuso consultation to learn. A student, a supervisor or a quality reviewer is a person in the room, and a person in the room is named, asked for and consented to — or they are not there."),
        .init(id: "covert-recording", sentence: "There is no way to record a consultation without the recording being visible on every participant's screen for the whole time it runs. An indicator that can be dismissed is a recording nobody consented to."),
        .init(id: "consent-outlives-withdrawal", sentence: "A consultation is not held open “just to finish the notes” after consent is withdrawn. Withdrawal ends the call at the moment it is said, and what is written afterwards is written only from what was already said."),
        .init(id: "diagnose-the-unseen", sentence: "A doctor does not record a finding about something they could not see or hear. On a poor line an uncertain answer is written down as an uncertain answer and the patient is seen again — a confident note is not a substitute for a working connection."),
        .init(id: "charge-for-a-failure", sentence: "An encounter that never reached a decision is not charged for, whoever's connection failed. Making a patient pay for their own bad signal puts the cost of South African bandwidth on the person least able to do anything about it."),
        .init(id: "half-a-consultation", sentence: "An interrupted encounter is never closed off as a completed consultation, and no clinician is offered a button that would do it. A record that cannot tell a finished consultation from an abandoned one is worse than no record, because it will be trusted."),
        .init(id: "certificate-from-a-call", sentence: "A doctor on this call cannot write you a medical certificate. A sick note needs somebody to examine you, and that is a visit — a nurse comes to the house and a doctor reviews what she finds."),
        .init(id: "doctor-on-demand", sentence: "You cannot call a doctor here. MyThuso sends a nurse to you, and the nurse calls the doctor."),
        .init(id: "waiting-without-an-end", sentence: "No doctor could join within the time this visit can wait. This goes to the panel as a review instead, and you are not charged for the call that did not happen."),
        .init(id: "first-prescription-unseen", sentence: "A medicine is not started on this call for something nobody has examined. The nurse with you is the examination; ask her to look, and the doctor will decide from what she finds.")
    ]
}
