// Generated by scripts/emit-verify-in-service.mjs from packages/catalog/verify-in-service.json, packages/catalog/apis/trust.json, packages/catalog/trust.json and packages/catalog/sos.json.
// Do not edit by hand — run `npm run verify-in-service`. The build fails if this file and its sources disagree,
// so an edit here is lost rather than merely wrong.
//
// The door code lifetime and tries, the complaint review window and the unmatched shift-start rule are PROPOSED
// defaults an admin changes on the web back office. This app reaches no settings route, so it uses them as
// written here, and they change in the contract, never in this file. Nothing here is a Trust Score or a face.

import Foundation

extension VerifyInService {
    /// A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    static let doorCodeMinutes = 5
    /// A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    static let doorCodeAttempts = 3
    /// A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    static let complaintReviewHours = 24
    /// A proposal nobody has decided. A default an admin may change on the web; this app has no admin surface and uses it as written here.
    static let unmatchedShiftStartDispatch = "withhold"
    /// How many digits a door code has. A design constant of the contract, not a policy.
    static let doorDigits = 6
    /// The longest complaint the form takes, in characters.
    static let complaintMaxCharacters = 1000
    /// What the face-match door answers. Never matched without a provider.
    static let matchOutcome = "not-integrated"

    enum ShiftText {
        static let door = "face-match-result"
        static let outcome = "not-integrated"
        static let heading = "Start your shift"
        static let intro = "Starting a shift tells the desk you are working. It is where a face match would happen, and none does."
        static let button = "Start my shift"
        static let started = "Shift started at {at}."
        static let noMatch = "No face match was performed. MyThuso has no identity provider to compare your face with, so nothing was compared, and nothing of your face was taken, kept or sent."
        static let whyNoMatch = "Whether matching a face is biometric information under POPIA section 26 is a decision the Information Officer has not taken (D-3), and no identity provider is contracted. Until both are settled, no image, template or embedding of anybody's face is held anywhere in MyThuso."
        static let dispatchRuleSetting = "unmatched-shift-start-dispatch"
        static let deskHeading = "Shift starts today"
        static let deskIntro = "Every shift started today, and what the rule in force did with it. No shift has been face matched, because nothing can match one."
        static let deskEmpty = "Nobody has started a shift today."
    }

    enum NurseDoorText {
        static let heading = "Your door code"
        static let intro = "Show these digits to the person who opens the door. They type them into their own MyThuso app, and it tells them the code is for their visit."
        static let button = "Show my door code"
        static let again = "Show a new code"
        static let expires = "This code stops working at {at}."
        static let tries = "They have {attempts} tries before the desk is told."
    }

    enum PatientDoorText {
        static let heading = "Check the nurse at your door"
        static let open = "Check the nurse at your door"
        static let intro = "Before you open the door, ask her for her door code and type it here. MyThuso checks it is the code for your visit."
        static let codeLabel = "Door code"
        static let check = "Check the code"
        static let wrong = "That code does not match your visit. You have {attempts} more tries before the desk is told."
        static let matched = "The code matches your visit."
        static let question = "Is this the person at your door?"
        static let name = "Name"
        static let badge = "Badge"
        static let noBadge = "She has no current verification, so there is no badge to show. Do not open the door."
        static let verified = "You checked the code and the name. The desk has been told she arrived."
        static let mismatch = "Do not open the door. The desk has been told, and a safety incident has been raised."
        static let anyTime = "If the person at the door is not who you expected, say so at any time, with or without a code."
        static let danger = "If you are in danger, call 10111 now."
        static let photo = "MyThuso holds no photograph of a nurse, so none is shown. Check the name and the badge, and ask to see her SANC card."
        static let badge = "You are shown her badge and never a number. A badge says her identity, registration and background are in order today."
        static let formWhy = "Digits, on every platform. A QR code is one more thing a patient's phone has to scan, which on the web and on Android needs a third-party library the open-source register has not procured (packages/catalog/open-source.json, section 15D). iOS could draw one with CoreImage, but no patient app could read it without a scanner, so a code only the nurse's phone can draw is decoration. Six digits are read aloud through a closed door as easily as they are typed."
    }

    enum ComplaintText {
        static let heading = "Make a complaint"
        static let open = "Make a complaint about this visit"
        static let intro = "Tell us what went wrong. A reviewer reads it within {hours} hours."
        static let category = "What is it about?"
        static let account = "What happened"
        static let accountHelp = "In your own words. Up to {characters} characters."
        static let nurseNotTold = "The nurse is told a complaint was made and what was decided. She is not told who made it or what you wrote."
        static let submit = "Send the complaint"
        static let sent = "Your complaint was received. A reviewer reads it by {at}."
        static let scoreRule = "A complaint never changes anybody's Trust Score by itself. A reviewer decides it, and anything that follows is a separate decision."
    }

    static let dispatchRules: [VerifyInServiceChoice] = [
        .init(id: "withhold", label: "Because no match was performed, you are not offered visits from this shift. The desk can see that, and why."),
        .init(id: "offer-with-desk-flag", label: "You may be offered visits from this shift, and the desk sees that no face match was performed.")
    ]
    static let answers: [VerifyInServiceChoice] = [
        .init(id: "she-is-my-nurse", label: "Yes, she is my nurse"),
        .init(id: "not-my-nurse", label: "This is not my nurse")
    ]
    static let categories: [VerifyInServiceChoice] = [
        .init(id: "late-or-missed", label: "The nurse was late, or did not come"),
        .init(id: "conduct", label: "How I was spoken to or treated"),
        .init(id: "care-given", label: "The care I was given"),
        .init(id: "privacy", label: "My information was not kept private"),
        .init(id: "identity-at-the-door", label: "I was not sure who was at my door"),
        .init(id: "payment", label: "What I was charged")
    ]
    static let tiers: [VerifyInServiceChoice] = [
        .init(id: "verified", label: "Verified"),
        .init(id: "trusted", label: "Trusted"),
        .init(id: "senior", label: "Senior")
    ]

    static let refusals: [VerifyInServiceRefusal] = [
        .init(id: "no-current-verification-to-start", status: 409, statement: "You have no current verification, so a shift cannot start. Your vetting status says why."),
        .init(id: "no-badge-to-show-at-a-door", status: 409, statement: "You have no current verification, so there is no door code to show. Speak to the desk."),
        .init(id: "no-door-code-for-this-visit", status: 404, statement: "No door code has been shown for this visit. Ask the person at the door to show one, or say they are not your nurse."),
        .init(id: "door-code-expired", status: 410, statement: "That code has expired. Ask her to show a new one."),
        .init(id: "door-check-closed", status: 409, statement: "This door check is finished. If you are worried about who is at your door, say they are not your nurse."),
        .init(id: "door-answer-before-code", status: 409, statement: "Type the code she shows before you say she is your nurse."),
        .init(id: "complaint-category-unknown", status: 422, statement: "Choose what the complaint is about from the list."),
        .init(id: "complaint-account-empty-or-long", status: 422, statement: "Say what happened in your own words, in no more than the space the form gives.")
    ]
}
