// Generated by scripts/emit-tokens.mjs from packages/design-tokens/tokens.json.
// Do not edit by hand — run `npm run tokens`. The build fails if this file and the token source
// disagree, so an edit here is lost rather than merely wrong.

package za.co.mythuso.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val Indigo = Color(0xFF1E3A8A)
val IndigoDeep = Color(0xFF172F6F)
val IndigoSoft = Color(0xFFEEF2FF)
val Teal = Color(0xFF14B8A6)
val TealInk = Color(0xFF0F766E)
val TealSoft = Color(0xFFE6FAF6)
val AccentSoft = Color(0xFFCCFBEF)
val TealLight = Color(0xFF99F6E4)
val TealMid = Color(0xFF5EEAD4)
val IndigoWash = Color(0xFF1E3A8A14)
val Mango = Color(0xFFFFB347)
val MangoInk = Color(0xFF92400E)
val MangoSoft = Color(0xFFFFF4E3)
val Ink = Color(0xFF0F172A)
val Slate = Color(0xFF1E293B)
val BodyText = Color(0xFF475569)
val Faint = Color(0xFF5D6B80)
val Line = Color(0xFFE2E8F0)
val Canvas = Color(0xFFF1F5F9)
val SurfaceWhite = Color(0xFFFFFFFF)
val Mist = Color(0xFFF0F0F0)
val Cloud = Color(0xFFE5E5E5)
val Stone = Color(0xFFDCDDDB)
val Charcoal = Color(0xFF1C1C1C)
val SageSlate = Color(0xFF8E9B92)
val MutedSage = Color(0xFF9EAC9B)
val SoftSage = Color(0xFFB2C0AA)
val PaleSage = Color(0xFFC8D5BB)
val Danger = Color(0xFFB42318)
val DangerSoft = Color(0xFFFEF3F2)
val Info = Color(0xFF175CD3)
val InfoSoft = Color(0xFFEFF4FF)
val Focus = Color(0xFFFFB347)
val FocusEdge = Color(0xFF0F172A)

object ThusoRadius {
    val card = 12.dp
    val control = 10.dp
    val tile = 10.dp
    val pill = 999.dp
}
object ThusoSpacing {
    val space4 = 4.dp
    val space8 = 8.dp
    val space12 = 12.dp
    val space16 = 16.dp
    val space20 = 20.dp
    val space24 = 24.dp
    val space32 = 32.dp
    val space40 = 40.dp
}
/** The type scale, in sp, so it scales with the reader's font size setting. */
object ThusoType {
    val screenTitle = 28.sp
    val sectionTitle = 18.sp
    val heading = 22.sp
    val cardTitle = 16.sp
    val body = 15.sp
    val caption = 13.sp
    val metric = 32.sp
    val minimumBody = 14.sp
    /** Nothing in any of the three apps renders text below this. */
    val minimumRendered = 13.sp
}
object ThusoMotion {
    const val durationMs = 180
    const val respectsReducedMotion = true
}
