import test from 'node:test';
import assert from 'node:assert/strict';
import { createThusoIQ, latestSample, sampleFreshness, type Actor, type Command } from './index.ts';
import { sandboxState } from './fixtures.ts';
const now='2026-09-13T08:00:00.000Z';
function fixture(){let actor:Actor={id:'D-401',role:'doctor',verified:true};let key=0;const port=createThusoIQ(sandboxState(now),()=>actor,()=>now);return {port,as:(next:Actor)=>{actor=next;},run:(c:Command)=>port.execute(c,{expectedRevision:port.snapshot().revision,idempotencyKey:`test-${++key}`})};}
const patientId='demo-lerato',consultationId='CO-DEMO-1';
const notes={subjective:'Fictional history reviewed',objective:'Fictional examination documented',assessment:'Clinician-authored test assessment',plan:'Clinician-authored test care plan'};
function signed(f:ReturnType<typeof fixture>){f.run({type:'consultation.save',patientId,consultationId,notes});f.run({type:'diagnosis.propose',patientId,consultationId,impression:'Test assessment',evidence:'Test record evidence'});f.run({type:'diagnosis.review',patientId,assessmentId:f.port.snapshot().assessments[0].id,decision:'confirmed',rationale:'Reviewed by the test doctor'});f.run({type:'consultation.sign',patientId,consultationId});}
test('a complete encounter progresses through doctor review and pharmacist handover exactly once',()=>{const f=fixture();signed(f);f.run({type:'dispensary.request',patientId,consultationId,item:'Fictional prescription item A',directions:'Fictional test directions',quantity:10});const requestId=f.port.snapshot().medicationRequests[0].id;f.as({id:'P-501',role:'pharmacist',verified:true});f.run({type:'dispensary.verify',patientId,requestId,batchId:'BATCH-DEMO-1',originalChecked:true,allergyChecked:true});f.run({type:'dispensary.release',patientId,requestId,recipientChecked:true});assert.equal(f.port.snapshot().stock[0].quantity,50);assert.throws(()=>f.run({type:'dispensary.release',patientId,requestId,recipientChecked:true}),/already been dispensed/);assert.equal(f.port.snapshot().stock[0].quantity,50);});
test('a nurse cannot confirm a diagnosis or sign a consultation',()=>{const f=fixture();f.run({type:'diagnosis.propose',patientId,consultationId,impression:'Test findings',evidence:'Test evidence'});f.as({id:'N-205',role:'nurse',verified:true});assert.throws(()=>f.run({type:'diagnosis.review',patientId,assessmentId:f.port.snapshot().assessments[0].id,decision:'confirmed',rationale:'Test'}),/required role/);assert.throws(()=>f.run({type:'consultation.sign',patientId,consultationId}),/required role/);});
test('signed notes cannot be overwritten',()=>{const f=fixture();signed(f);assert.throws(()=>f.run({type:'consultation.save',patientId,consultationId,notes:{...notes,plan:'overwrite'}}),/immutable/);assert.equal(f.port.snapshot().consultations[0].notes.plan,notes.plan);});
test('missing SOAP sections and consent prevent clinical completion',()=>{const f=fixture();assert.throws(()=>f.run({type:'consultation.submit',patientId,consultationId}),/four SOAP/);assert.throws(()=>f.run({type:'consultation.open',patientId:'demo-nomsa',appointmentId:'AP-DEMO-3'}),/consent/);});
test('patient context cannot be switched by substituting a record id',()=>{const f=fixture();assert.throws(()=>f.run({type:'consultation.save',patientId:'demo-thabo',consultationId,notes}),/selected patient/);assert.equal(f.port.snapshot().revision,0);});
test('overlapping appointments reject atomically, including patient overlap with another clinician',()=>{const f=fixture();const a=f.port.snapshot().appointments[0];assert.throws(()=>f.run({type:'appointment.schedule',patientId,clinicianId:'N-205',startsAt:a.startsAt,minutes:30,mode:'home'}),/overlapping/);assert.equal(f.port.snapshot().appointments.length,3);assert.equal(f.port.snapshot().events.length,0);});
test('rescheduling validates future slots, while cancellations require a reason',()=>{const f=fixture();assert.throws(()=>f.run({type:'appointment.reschedule',patientId:'demo-thabo',appointmentId:'AP-DEMO-2',startsAt:'2020-01-01',mode:'home'}),/future/);assert.throws(()=>f.run({type:'appointment.transition',patientId:'demo-thabo',appointmentId:'AP-DEMO-2',status:'cancelled'}),/reason/);f.run({type:'appointment.transition',patientId:'demo-thabo',appointmentId:'AP-DEMO-2',status:'cancelled',reason:'Patient requested another day'});assert.equal(f.port.snapshot().appointments[1].status,'cancelled');});
test('stale revisions and idempotency collisions are rejected',()=>{const f=fixture();const command:Command={type:'consultation.save',patientId,consultationId,notes};const options={expectedRevision:0,idempotencyKey:'same'};f.port.execute(command,options);assert.equal(f.port.execute(command,options).replayed,true);assert.equal(f.port.snapshot().revision,1);assert.throws(()=>f.port.execute({...command,notes:{...notes,plan:'different'}},options),/different command/);assert.throws(()=>f.port.execute(command,{...options,idempotencyKey:'other'}),/workspace changed/);});
test('invalid professional clearance blocks all commands',()=>{const f=fixture();f.as({id:'D-402',role:'doctor',verified:false});assert.throws(()=>f.run({type:'consultation.save',patientId,consultationId,notes}),/verification/);});
const sample={id:'s1',patientId,deviceId:'demo-watch',metric:'heart-rate' as const,value:72,unit:'bpm' as const,measuredAt:now,source:'simulator' as const,quality:'accepted' as const};
test('wearable samples require explicit consent and cannot arrive after revocation',()=>{const f=fixture();assert.throws(()=>f.run({type:'wearable.ingest',patientId,sample}),/paused/);f.run({type:'wearable.connection',patientId,enabled:true,consent:true});f.run({type:'wearable.ingest',patientId,sample});f.run({type:'wearable.connection',patientId,enabled:false,consent:false});assert.equal(f.port.snapshot().samples.length,0);assert.throws(()=>f.run({type:'wearable.ingest',patientId,sample:{...sample,id:'s2'}}),/paused/);});
test('wearable ingestion rejects duplicate, mismatched, future and nonfinite samples',()=>{const f=fixture();f.run({type:'wearable.connection',patientId,enabled:true,consent:true});f.run({type:'wearable.ingest',patientId,sample});for(const bad of [sample,{...sample,id:'s2',patientId:'demo-thabo'},{...sample,id:'s2',value:NaN},{...sample,id:'s2',measuredAt:'2099-01-01'}])assert.throws(()=>f.run({type:'wearable.ingest',patientId,sample:bad}));assert.equal(f.port.snapshot().samples.length,1);});
test('poor contact and delayed samples never replace the latest good measurement',()=>{const f=fixture();f.run({type:'wearable.connection',patientId,enabled:true,consent:true});f.run({type:'wearable.ingest',patientId,sample});f.run({type:'wearable.ingest',patientId,sample:{...sample,id:'old',measuredAt:'2026-09-13T07:30:00Z',value:64}});f.run({type:'wearable.ingest',patientId,sample:{...sample,id:'poor',quality:'poor-contact',value:100}});const latest=latestSample(f.port.snapshot().samples,patientId,'heart-rate');assert.equal(latest?.value,72);assert.equal(sampleFreshness(latest,'2026-09-13T08:10:00Z'),'stale');assert.equal(f.port.snapshot().assessments.length,0);});
test('returned snapshots and listener failures cannot corrupt committed data',()=>{const f=fixture();const snapshot=f.port.snapshot();snapshot.patients[0].consent=false;f.port.subscribe(()=>{throw Error('UI failure');});f.run({type:'consultation.save',patientId,consultationId,notes});assert.equal(f.port.snapshot().revision,1);assert.equal(f.port.snapshot().patients[0].consent,true);});
