// Generated by scripts/emit-care-tips.mjs from packages/catalog/care-tips.json.
// Do not edit by hand — run `npm run care-tips`. The build fails if this file and its source disagree,
// so an edit here is lost rather than merely wrong.
//
// Only the route: the name the router opens and what it says while the screen arrives. The door and the
// tips stay in the contract, read by apps/web/src/lib/care-tips.ts behind dynamic imports.

export const careTipsRoute = {
  opens: "Care tips",
  opening: "Opening the care tips.",
} as const;
