import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ShieldCheck, MapPin } from 'lucide-react';
import { type Service, money } from '../lib/catalog';
import { Pill, ServiceIcon } from '../components/UI';
export type DemoVisit = {service:Service;person:string;time:string;address:string};
export function Booking({service,onComplete}:{service:Service;onComplete:(visit:DemoVisit)=>void}) {
 const [step,setStep]=useState(0); const [person,setPerson]=useState('Lerato Molefe');const [time,setTime]=useState('Tomorrow, 09:00–10:00');const [address,setAddress]=useState('Rosebank, Johannesburg');const [consent,setConsent]=useState(false);const [payment,setPayment]=useState('Card after visit');
 return <><div className="stepper">{['Your visit','Review','All set'].map((s,i)=><span key={s} className={i<=step?'current':''}><b>{i<step?<Check size={12}/>:i+1}</b>{s}</span>)}</div>{step===2?<div className="success"><div className="success-icon"><Check size={32}/></div><h3>Your demo visit is booked.</h3><p>{service.name} for {person.split(' ')[0]}<br/>{time}</p><p className="muted">This is a preview. No nurse has been dispatched and no payment was taken.</p><button className="primary" onClick={()=>onComplete({service,person,time,address})}>View my visits<ArrowRight size={17}/></button></div>:<><div className="booking-summary"><span className="service-icon"><ServiceIcon name={service.icon}/></span><div><h3>{service.name}</h3><p>{service.duration} min · Registered nurse</p></div><strong>{money(service.price)}</strong></div>{step===0?<div className="form-stack"><label>Who is this visit for?<select value={person} onChange={e=>setPerson(e.target.value)}><option>Lerato Molefe</option><option>Nomsa Molefe</option><option>Thabo Molefe</option></select></label><label>Visit location<input value={address} onChange={e=>setAddress(e.target.value)} maxLength={160} required/></label><label>Choose a time<select value={time} onChange={e=>setTime(e.target.value)}><option>Tomorrow, 09:00–10:00</option><option>Tomorrow, 14:00–15:00</option><option>Friday, 10:00–11:00</option></select></label><label>Payment preference<select value={payment} onChange={e=>setPayment(e.target.value)}><option>Card after visit</option><option>Cash after visit</option><option>Thuso Wallet</option></select></label><p className="helper">Sample availability and proposal pricing. Tests, medicines and prescriptions may require separate arrangements.</p><button className="primary full" disabled={address.trim().length<5} onClick={()=>setStep(1)}>Review visit<ArrowRight size={17}/></button></div>:<div className="form-stack"><Pill>Demo booking · No charge</Pill><div className="review-line"><span>Patient</span><strong>{person}</strong></div><div className="review-line"><span>When</span><strong>{time}</strong></div><div className="review-line"><span><MapPin size={15}/> Location</span><strong>{address}</strong></div><div className="review-line"><span>Payment</span><strong>{payment}</strong></div><div className="review-line"><span>Visit total</span><strong>{money(service.price)}</strong></div><label className="checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I understand this is a UI preview using fictional information.</span></label><div className="privacy-note"><ShieldCheck size={19}/>Production visits will require appropriate patient or guardian consent.</div><div className="button-row"><button className="secondary" onClick={()=>setStep(0)}><ArrowLeft size={16}/>Back</button><button className="primary" disabled={!consent} onClick={()=>setStep(2)}>Confirm demo visit<ArrowRight size={16}/></button></div></div>}</> }</>;
}
