import { useEffect, useState, type FormEvent } from 'react';
import { Activity, ArrowUpRight, CalendarDays, Check, ClipboardList, Cpu, HeartPulse, PackageCheck, Radio, ShieldCheck, Stethoscope } from 'lucide-react';
import { useThusoIQ } from '../lib/thusoiq';
import { latestSample, sampleFreshness, type Command, type Notes } from '../../../../packages/thusoiq/index.ts';
import './clinical-workbench.css';

type Tool = 'Appointments' | 'Consultation' | 'Diagnostic review' | 'Dispensary' | 'Wearables';
const tools = [ ['Appointments', CalendarDays], ['Consultation', Stethoscope], ['Diagnostic review', ClipboardList], ['Dispensary', PackageCheck], ['Wearables', HeartPulse] ] as const;
const dateTime = (value: string) => new Date(value).toLocaleString('en-ZA', { month:'short',day:'numeric',hour:'2-digit',minute:'2-digit' });
const field = (event: FormEvent<HTMLFormElement>, name: string) => String(new FormData(event.currentTarget).get(name) ?? '').trim();
const sampleValues = [72,74,73,76,75,72,71,73];

export function ClinicalWorkbench({ role }: { role: 'Nurse' | 'Doctor' | 'Partner' }) {
 const { state, execute } = useThusoIQ();
 const [patientId, setPatient] = useState(state.patients[0].id);
 const [tool, setTool] = useState<Tool>(role === 'Partner' ? 'Dispensary' : 'Appointments');
 const [notice, setNotice] = useState('');
 const [error, setError] = useState('');
 const [streaming, setStreaming] = useState(false);
 const [now, setNow] = useState(new Date().toISOString());
 const patient = state.patients.find(p => p.id === patientId)!;
 const appointments = state.appointments.filter(a => a.patientId === patientId);
 const consultation = state.consultations.filter(c => c.patientId === patientId).at(-1);
 const assessment = state.assessments.filter(a => a.consultationId === consultation?.id).at(-1);
 const requests = state.medicationRequests.filter(r => r.patientId === patientId);
 const connection = state.wearableConnections.find(c => c.patientId === patientId)!;
 const samples = state.samples.filter(s => s.patientId === patientId && s.quality === 'accepted');
 const latest = latestSample(state.samples, patientId, 'heart-rate');
 const run = (command: Command, message: string) => {
  try { execute(command); setError(''); setNotice(message); return true; }
  catch (e) { setNotice(''); setError(e instanceof Error ? e.message : 'This action could not be completed.'); return false; }
 };
 useEffect(() => {
  if (!streaming || !connection.enabled || !connection.consent) return;
  const timer = window.setInterval(() => {
   if (document.hidden) return;
   const measuredAt = new Date().toISOString();
   setNow(measuredAt);
   run({type:'wearable.ingest',patientId,sample:{id:crypto.randomUUID(),patientId,deviceId:'DEMO-WATCH-01',metric:'heart-rate',value:sampleValues[state.samples.length % sampleValues.length],unit:'bpm',measuredAt,source:'simulator',quality:'accepted'}}, 'Simulator sample received.');
  }, 3000);
  return () => clearInterval(timer);
 }, [streaming, connection.enabled, connection.consent, patientId, state.revision]);
 useEffect(() => { const timer = window.setInterval(() => setNow(new Date().toISOString()), 15_000); return () => clearInterval(timer); }, []);
 const choosePatient = (id: string) => { setPatient(id); setStreaming(false); setError(''); setNotice(''); };
 const saved = (event: FormEvent<HTMLFormElement>) => {
  event.preventDefault(); if (!consultation) return;
  const notes = Object.fromEntries(['subjective','objective','assessment','plan'].map(key => [key,field(event,key)])) as Notes;
  run({type:'consultation.save',patientId,consultationId:consultation.id,notes}, 'Consultation draft saved in this sandbox session.');
 };
 const samplePath = samples.slice(-20).map((s,i,arr) => `${arr.length===1?50:i*100/(arr.length-1)},${85-(s.value-60)*2}`).join(' ');
 return <section className="iq-workbench" aria-label="ThusoIQ clinical workspace">
  <header className="iq-heading"><div><span className="iq-eyebrow"><Cpu size={16}/> THUSOIQ · CLINICAL WORKSPACE</span><h2>{role==='Doctor'?'From evidence to a care decision.':role==='Nurse'?'Your next visit, fully connected.':'From prescription to handover.'}</h2><p>One patient. Their appointments, clinical record and next action.</p></div><span className="iq-status"><span/>Fictional sandbox</span></header>
  <div className="iq-layout">
   <aside className="iq-patients" aria-label="Clinical patients"><p className="iq-eyebrow">CARE QUEUE</p>{state.patients.map(p=><button key={p.id} className={patientId===p.id?'selected':''} aria-pressed={patientId===p.id} onClick={()=>choosePatient(p.id)}><span className="avatar small">{p.name.split(' ').map(n=>n[0]).join('')}</span><span><strong>{p.name}</strong><small>{p.reason}</small><em>{p.consent?'Ready for review':'Consent outstanding'}</em></span><ArrowUpRight size={15}/></button>)}<p className="helper">These patients belong to a separate, in-memory workflow sandbox. No clinical service is delivered here.</p></aside>
   <div className="iq-patient-work">
    <div className="iq-patient-head"><div><span className="iq-eyebrow">PATIENT CONTEXT</span><h3>{patient.name}</h3><p>{patient.reason}</p></div><span className={`iq-chip ${patient.consent?'':'attention'}`}><ShieldCheck size={14}/>{patient.consent?'Care consent recorded':'Consent required'}</span></div>
    <div className="iq-allergy"><strong>Allergy record</strong><span>{patient.allergies}</span></div>
    <div className="iq-tools" role="group" aria-label="Clinical tools">{tools.map(([name,Icon])=><button key={name} aria-pressed={tool===name} onClick={()=>{setTool(name);setNotice('');setError('');setStreaming(false);}}><Icon size={17}/>{name}</button>)}</div>
    <div className="iq-tool-body" key={`${patientId}:${tool}`}>
     {tool==='Appointments' && <><div className="iq-section-head"><h3>Appointment engine</h3><span>Home visits & video</span></div><div className="iq-records">{appointments.map(a=><article key={a.id}><div><strong>{dateTime(a.startsAt)}</strong><p>{a.minutes} min · {a.mode==='home'?'Home visit':'Video consultation'} · {a.clinicianId}</p><span className="iq-chip">{a.status}</span></div><div className="button-row">{a.status==='scheduled'&&<button className="secondary" onClick={()=>run({type:'appointment.transition',patientId,appointmentId:a.id,status:'arrived'},'Patient checked in.')}>Check in</button>}{a.status==='arrived'&&!state.consultations.some(c=>c.appointmentId===a.id)&&<button className="primary" onClick={()=>{if(run({type:'consultation.open',patientId,appointmentId:a.id},'Consultation opened.'))setTool('Consultation');}}>Open consultation</button>}{a.status==='arrived'&&consultation?.status==='signed'&&<button className="secondary" onClick={()=>run({type:'appointment.transition',patientId,appointmentId:a.id,status:'completed'},'Appointment completed.')}>Complete visit</button>}</div></article>)}</div>
      {role!=='Partner'&&<form className="iq-form" onSubmit={e=>{e.preventDefault();const raw=field(e,'startsAt');if(!raw)return;run({type:'appointment.schedule',patientId,clinicianId:role==='Doctor'?'D-401':'N-205',startsAt:new Date(raw).toISOString(),minutes:Number(field(e,'minutes')),mode:field(e,'mode') as 'home'|'video'},'Appointment added to this care queue.');}}><h4>Arrange follow-up</h4><div className="iq-form-row"><label>Date and time<input type="datetime-local" name="startsAt" required/></label><label>Setting<select name="mode"><option value="home">Home visit</option><option value="video">Video consultation</option></select></label><label>Minutes<input type="number" name="minutes" min="10" max="180" defaultValue="30" required/></label></div><button className="primary" type="submit">Schedule appointment</button><p className="helper">Checks patient and clinician conflicts before accepting the slot.</p></form>}
     </>}
     {tool==='Consultation' && <><div className="iq-section-head"><h3>Consultation engine</h3><span>{consultation?.status??'No open encounter'}</span></div>{consultation?<><form className="iq-form" onSubmit={saved}><div className="iq-soap">{(['subjective','objective','assessment','plan'] as const).map(key=><label key={key}><span>{key[0].toUpperCase()} · {key[0].toUpperCase()+key.slice(1)}</span><textarea name={key} defaultValue={consultation.notes[key]} rows={3} maxLength={5000} disabled={consultation.status==='signed'||role==='Partner'}/></label>)}</div>{consultation.status!=='signed'&&role!=='Partner'&&<button type="submit" className="primary">Save clinical draft</button>}</form><div className="button-row">{consultation.status!=='signed'&&role!=='Partner'&&<button className="secondary" onClick={()=>run({type:'consultation.submit',patientId,consultationId:consultation.id},'Sent for doctor review in the sandbox.')}>Request doctor review</button>}{consultation.status!=='signed'&&role==='Doctor'&&<button className="primary" onClick={()=>run({type:'consultation.sign',patientId,consultationId:consultation.id},'Consultation signed. Its notes are now locked.')}>Sign consultation</button>}</div>{consultation.signedAt&&<p><Check size={15}/> Signed by {consultation.signedBy} · {dateTime(consultation.signedAt)}</p>}</>:<p>Check this patient in and open a consultation from Appointments.</p>}</>}
     {tool==='Diagnostic review' && <><div className="iq-section-head"><h3>Diagnosis review engine</h3><span>Clinician-led</span></div><p className="helper">Record findings and their evidence. A doctor reviews the assessment. No diagnostic model is connected and wearable samples never create a diagnosis.</p>{assessment&&<article className="iq-assessment"><span className="iq-chip">{assessment.status}</span><h4>{assessment.impression}</h4><p>{assessment.evidence}</p>{assessment.rationale&&<p><strong>Review:</strong> {assessment.rationale}</p>}</article>}{consultation&&consultation.status!=='signed'&&(!assessment||assessment.status==='rejected')&&role!=='Partner'&&<form className="iq-form" onSubmit={e=>{e.preventDefault();run({type:'diagnosis.propose',patientId,consultationId:consultation.id,impression:field(e,'impression'),evidence:field(e,'evidence')},'Assessment recorded for doctor review.');}}><label>{role==='Nurse'?'Recorded findings':'Clinical impression'}<textarea name="impression" required maxLength={5000}/></label><label>Evidence and uncertainties<textarea name="evidence" required maxLength={5000}/></label><button className="primary" type="submit">Submit assessment for review</button></form>}{assessment?.status==='proposed'&&role==='Doctor'&&<form className="iq-form" onSubmit={e=>{e.preventDefault();run({type:'diagnosis.review',patientId,assessmentId:assessment.id,decision:field(e,'decision') as 'confirmed'|'rejected',rationale:field(e,'rationale')},'Doctor review recorded.');}}><label>Review decision<select name="decision"><option value="confirmed">Confirm assessment</option><option value="rejected">Return for reassessment</option></select></label><label>Clinical rationale<textarea name="rationale" required maxLength={5000}/></label><button className="primary" type="submit">Record doctor decision</button></form>}{!consultation&&<p>Open a consultation before recording an assessment.</p>}</>}
     {tool==='Dispensary' && <><div className="iq-section-head"><h3>Dispensary engine</h3><span>Prescription → verification → handover</span></div>{requests.length===0&&<p>No medication requests for this patient.</p>}{requests.map(r=><article className="iq-assessment" key={r.id}><span className="iq-chip">{r.status}</span><h4>{r.item}</h4><p>{r.directions} · Quantity {r.quantity}</p>{r.reason&&<p>Hold reason: {r.reason}</p>}{role==='Partner'&&r.status!=='dispensed'&&<form className="iq-form" onSubmit={e=>{e.preventDefault();run({type:'dispensary.verify',patientId,requestId:r.id,batchId:field(e,'batch'),originalChecked:field(e,'original')==='on',allergyChecked:field(e,'allergies')==='on'},'Pharmacist verification recorded.');}}><label>Stock batch<select name="batch">{state.stock.filter(b=>b.item===r.item).map(b=><option key={b.id} value={b.id}>{b.id} · {b.quantity} available</option>)}</select></label><label className="iq-check"><input type="checkbox" name="original" required/>Original prescription checked</label><label className="iq-check"><input type="checkbox" name="allergies" required/>Allergy record reconciled</label><button className="secondary" type="submit">Verify prescription</button></form>}{role==='Partner'&&r.status==='verified'&&<form className="iq-form" onSubmit={e=>{e.preventDefault();run({type:'dispensary.release',patientId,requestId:r.id,recipientChecked:field(e,'recipient')==='on'},'Sandbox stock released once; handover recorded.');}}><label className="iq-check"><input type="checkbox" name="recipient" required/>Recipient identity checked</label><button className="primary" type="submit">Record handover</button></form>}</article>)}{role==='Doctor'&&<form className="iq-form" onSubmit={e=>{e.preventDefault();if(!consultation)return;run({type:'dispensary.request',patientId,consultationId:consultation.id,item:'Fictional prescription item A',directions:field(e,'directions'),quantity:Number(field(e,'quantity'))},'Medication request added for pharmacist verification.');}}><h4>Sandbox medication request</h4><p className="helper">Uses a fictional stock item to exercise the workflow. Requires a signed consultation; this does not issue a legal prescription.</p><label>Prescriber directions<textarea name="directions" required maxLength={5000}/></label><label>Quantity<input name="quantity" type="number" min="1" max="1000" defaultValue="10" required/></label><button className="primary" disabled={consultation?.status!=='signed'}>Send to dispensary</button></form>}{role!=='Partner'&&<p className="helper">A pharmacy partner verifies the prescription and records the handover.</p>}</>}
     {tool==='Wearables'&&<><div className="iq-section-head"><h3>Wearable ingestion engine</h3><span>{streaming?'Simulator running':'Stream paused'}</span></div><div className="iq-signal"><div><span>Heart rate · simulator</span><strong>{latest?.value??'—'}<small>bpm</small></strong><p>{sampleFreshness(latest,now)} · {latest?dateTime(latest.measuredAt):'No sample received'}</p></div><svg viewBox="0 0 100 100" role="img" aria-label="Recent fictional heart rate samples" preserveAspectRatio="none"><polyline points={samplePath} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg></div><p className="helper">DEMO-WATCH-01 · Samples every three seconds while this screen is active. No wearable is connected. Device/provider sync determines actual delivery frequency.</p>{role!=='Partner'&&<><label className="iq-check"><input type="checkbox" checked={connection.consent} onChange={e=>{setStreaming(false);run({type:'wearable.connection',patientId,enabled:e.target.checked,consent:e.target.checked},e.target.checked?'Fictional wearable sharing consent recorded.':'Sharing revoked and sandbox samples removed.');}}/>Preview patient consent to share wearable readings</label><div className="button-row"><button className="primary" disabled={!connection.consent||!patient.consent} onClick={()=>setStreaming(!streaming)}><Radio size={16}/>{streaming?'Pause simulator':'Start simulator'}</button></div></>}<details><summary>Readings and provenance</summary><div className="iq-table-wrap"><table><thead><tr><th>Measured</th><th>Received</th><th>Value</th><th>Source</th></tr></thead><tbody>{samples.slice(-20).reverse().map(s=><tr key={s.id}><td>{dateTime(s.measuredAt)}</td><td>{dateTime(s.receivedAt)}</td><td>{s.value} {s.unit}</td><td>{s.source} · {s.deviceId}</td></tr>)}</tbody></table></div></details></>}
    </div>
    {error&&<p className="iq-message error" role="alert">{error}</p>}{notice&&<p className="iq-message" role="status">{notice}</p>}
   </div>
  </div>
  <footer className="iq-audit"><span><Activity size={15}/> ThusoIQ connection: sandbox adapter</span><details><summary>Activity trail · {state.events.filter(e=>e.patientId===patientId).length} events</summary><ol>{state.events.filter(e=>e.patientId===patientId).slice(-12).reverse().map(e=><li key={e.sequence}>{e.action.replaceAll('.',' · ')} — {e.actorId} · {dateTime(e.at)}</li>)}</ol></details></footer>
 </section>;
}
