import { ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronRight, Clock3, Heart, MapPin, Plus, ShieldCheck, Sparkles, Video } from 'lucide-react';
import { SectionTitle, Pill, ServiceIcon } from '../components/UI';
import { CareIllustration } from '../components/CareIllustration';
import { services, money, type Service } from '../lib/catalog';
import { useT } from '../lib/i18n';
export function Dashboard({navigate,book,open}:{navigate:(s:string)=>void;book:(s:Service)=>void;open:(s:string)=>void}) {
 const t=useT();
 return <><div className="page-intro"><div><div className="eyebrow">A LITTLE CARE GOES A LONG WAY</div><h1>{t('shell.greeting')} <span className="wave">✳</span></h1><p>{t('shell.greetingSub')}</p></div><span className="date-label"><CalendarDays size={16}/> Thursday, 10 September</span></div>
 <div className="dashboard-grid"><div className="main-column"><section className="hero"><div className="hero-copy"><span className="hero-kicker"><span className="status-dot"/>CARE THAT COMES TO YOU</span><h2>{t('hero.title').split('|').map((line,i)=><span key={line}>{i?<br/>:null}{line}</span>)}</h2><p>{t('hero.body')}</p><button className="primary" onClick={()=>navigate('Book a nurse')}>{t('cta.book')}<ArrowRight size={17}/></button><div className="hero-foot"><ShieldCheck size={15}/>{t('hero.trust')}<span>•</span>{t('hero.price')}</div></div><CareIllustration/></section>
 <section><SectionTitle title="What can we help with?" action="Explore all services" onClick={()=>navigate('Book a nurse')}/><div className="service-grid">{services.slice(0,4).map((s,i)=><button key={s.id} className={`service-card tint-${i}`} onClick={()=>book(s)}><span className="service-icon"><ServiceIcon name={s.icon}/></span><h3>{s.name}</h3><p>{s.description}</p><div><strong>From {money(s.price)}</strong><ArrowUpRight size={17}/></div></button>)}</div></section>
 <section><SectionTitle title="Your next visit" action={t('cta.allVisits')} onClick={()=>navigate('My visits')}/><div className="visit-card"><div className="visit-top"><Pill><span className="status-dot"/>Confirmed · Demo</Pill><span className="muted">#TH-2048</span></div><div className="visit-main"><div className="calendar-tile"><span>SEP</span><strong>12</strong><span>SAT</span></div><div className="visit-description"><h3>Vitals & chronic check</h3><p><Clock3 size={14}/>09:00 – 09:30<span>•</span>For you</p><p><MapPin size={14}/>Home · Rosebank, Johannesburg</p></div><button className="secondary" onClick={()=>open('Visit details')}>View details<ChevronRight size={16}/></button></div><div className="nurse-row"><span className="avatar nurse-avatar">SN</span><div><strong>Sister Naledi Mokoena</strong><span>Registered nurse <ShieldCheck size={13}/></span></div><span className="rating">★ <strong>4.9</strong><span>(128 visits)</span></span></div></div></section>
 <section><SectionTitle title="Small steps. A healthier you."/><div className="wellness-card"><span className="wellness-icon"><Heart size={25}/></span><div><Pill tone="plain">THUSO ROUTINE</Pill><h3>Good health is a habit. We’ll help you keep it.</h3><p>Regular check-ins, thoughtful reminders and care that stays with you.</p><button className="text-button" onClick={()=>navigate('Care plans')}>Find your care plan<ArrowRight size={16}/></button></div><div className="wellness-art"><span>♥</span><i/><i/><i/></div></div></section>
 </div><aside className="right-column"><section className="passport-card"><div className="passport-heading"><span className="passport-symbol"><Heart size={19}/></span><span>THUSO PASS</span><ArrowUpRight size={18}/></div><h2>Your health.<br/>One safe place.</h2><p>Your history, results and care,<br/>always together.</p><div className="passport-owner"><span className="avatar">LM</span><div><strong>Lerato Molefe</strong><span>MY HEALTH PASSPORT</span></div><ShieldCheck size={23}/></div><button onClick={()=>navigate('Health Passport')}>{t('cta.passport')}<ArrowRight size={17}/></button></section>
 <section className="panel family-panel"><SectionTitle title="Your circle of care"/><p className="muted">Looking after your favourite people.</p>{[['NM','Mom','Nomsa Molefe','peach'],['TM','Thabo','Your son · 8 years','blue']].map(([initial,name,detail,color])=><button className="family-row" key={name} onClick={()=>navigate('My family')}><span className={`avatar ${color}`}>{initial}</span><span><strong>{name}</strong><small>{detail}</small></span><ChevronRight size={17}/></button>)}<button className="add-family" onClick={()=>open('Add a family member')}><Plus size={16}/>Add a family member</button></section>
 <section className="panel quick-links"><SectionTitle title="A little peace of mind"/>{[[Video,'Talk to a doctor','Doctor-reviewed care'],[ShieldCheck,'Your privacy matters','You’re in control of your data']].map(([Icon,title,sub])=>{const I=Icon as typeof Video;return <button className="quick-row" key={String(title)} onClick={()=>String(title).startsWith('Your')?navigate('Privacy & settings'):open('Talk to a doctor')}><I size={21}/><span><strong>{String(title)}</strong><small>{String(sub)}</small></span><ChevronRight size={16}/></button>;})}</section>
 <div className="community-note"><span><Sparkles size={18}/></span><p>Rooted in our communities.<br/><strong>Made for your everyday.</strong></p><div className="sa-dots"><i/><i/><i/><i/></div></div></aside></div><div className="trust-footer"><span><ShieldCheck size={14}/>Designed around your privacy</span><span><Check size={14}/>Doctor-reviewed care</span><span>Help. Health. Home.</span></div></>;
}
